### ISSUE TITLE
Set up travis-ci build (and tests)

### ISSUE THREAD

**Issue by tensafefrogs** [googleads/videojs-ima#10]
We should set up a travis-ci project to build this each time a pull request is created.

At a minimum we should build the project, but ideally we should run the unit tests.

There may be useful information in this post:
http://stackoverflow.com/questions/13412211/using-travis-ci-for-client-side-javascript-libraries

**Comment by watilde** [comment]
Do you have any updates on this? I can make a patch to add `.travis.yml`, but we need to turn on travis dashboard by admin.

**Comment by shawnbuso** [comment]
I tried briefly to add Travis tests a while back, but their video support wasn't great and the tests kept failing. If you've got something that works that's great and I can look into enabling travis in the dashboard.
