### ISSUE TITLE
How do we set custom headers on a non-streaming video request?

### ISSUE THREAD

**Issue by yogesh-r-kulkarni** [googleads/videojs-ima#1000]
### Description
- I wanted to set custom headers to the xhr request made by videojs-ima. Is there any method where I can add/modify the headers?
- I can't find a way to intercept, or otherwise add headers to the requests made by videojs-ima. Is there a method that I am missing?

**Comment by Kiro705** [comment]
Hello @yogesh-r-kulkarni ,

As far as I know, IMA does not request videos/ads via xhr request and there is not a way to enable that functionality. Based on that, there would not be a way to do this through the videojs-IMA plugin.

Can you point to any IMA specific documentation that calls for setting xhr headers?

Thank you,
Jackson
IMA SDK Team
