### ISSUE TITLE
How to use skip ads feature with videojs-ima?

### ISSUE THREAD

**Issue by arunk9034** [googleads/videojs-ima#1001]
Hi team,

Can you please guide me on how can I use the skip ads option on my videojs player? 
Here is my [XML file](https://video.unibots.in/clients/docbao.xml). 

Also, let me know that skip the ads feature can be work on this [simple linear ads](https://video.unibots.in/clients/docbao.xml) XML file. Or I need to use [this](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags#single-skippable-inline) kind of XML file specifically given for skippable ads by google.

**Comment by Kiro705** [comment]
Hello @arunk9034 ,

I see [your linear ad file](https://video.unibots.in/clients/docbao.xml) working in our [video.js-ima sample player](https://googleads.github.io/videojs-ima/examples/advanced/). The code for this sample player is apart of this github repo, which you can follow as a guide for a similar implementation.

Please let me know if you have any farther questions.

Thank you,
Jackson
IMA SDK Team
