### ISSUE TITLE
Responsive player renders ad in wrong position

### ISSUE THREAD

**Issue by stehag** [googleads/videojs-ima#1002]
Using the player with this: 

.video-js { padding-top: 56.25% }
player.fill(true);

to make it responsive, ads looks good  mobile, but on desktop itlooks like this:
![image](https://user-images.githubusercontent.com/4263261/120858964-d6333580-c583-11eb-85f6-6b1f01eac106.png)

Is there any way to make the ad "stick"  so i can debug css in browser? Or any other ideas how to resolve this?

**Comment by Kiro705** [comment]
Hello @stehag ,

In our [advanced sample](https://googleads.github.io/videojs-ima/examples/advanced/) it is possible to pause the player during linear ads, during which time the ad will always be visible. Would this solution work for you, to be able to style the page?

Thank you,
Jackson
IMA SDK Team
