### ISSUE TITLE
How to know why google not serving me ads?

### ISSUE THREAD

**Issue by arunk9034** [googleads/videojs-ima#1004]
Hi Team,

I'm facing an issue suddenly I'm getting stopped ads by google for days on my video player. And after some time on the diff, IPs and devices ads continue getting on the same player. Is there any way to track why google not giving me ads? I also tried with a low floor price but facing the same issue.

Please also suggest the best player sizes for diff devices & the best request patterns to be used in order to achieve better ad responses.

Here are my player configs 

`var vjsOptions = {autoplay: true,muted: true, width: isMobile() ? 344 : 400, height: isMobile() ? 258 : 225 }
       player = videojs('content_video', vjsOptions);
      player .src({ type: "video/mp4", src: "https://cdn.jsdelivr.net/gh/ubVids/video-library@latest/dist/top_indian_sweet.mp4"});
      var imaOptions = { id: "content_video", adTagUrl:"https://video.unibots.in/ads.xml",
        disableCustomPlaybackForIOS10Plus: true,
        contribAdsSettings: {
          debug: true,
          timeout: 8000,
          prerollTimeout: 12000,
        },
        adsRenderingSettings: { enablePreloading: true }
      };
      player .ima(imaOptions);`

**Comment by Kiro705** [comment]
Hi @arunk9034 ,

Thank you for reaching out. I think your questions may be best answered by reaching out through [Ad Manager help channels](https://support.google.com/admanager). This issue queue is specific to bugs/issues related to the videojs-IMA plugin.

I did test your ad tag in the [videojs-IMA plugin's advanced sample](https://googleads.github.io/videojs-ima/examples/advanced/) and saw ads play.

The Ad Manager help center would also be the best place to learn how different parameters (player size and request patterns) affect ad responses.

Please let me know if you have any other questions.

Thank you,
Jackson
IMA SDK Team
