### ISSUE TITLE
AdError 403: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

### ISSUE THREAD

**Issue by kh120** [googleads/videojs-ima#1005]
I am using demo [IMA Plugin Advanced Demo](https://googleads.github.io/videojs-ima/examples/advanced/) and passed VAST tag link to input box. When vast response's mediaFile tag is  streaming, ads error 403 will be occur 
![error](https://user-images.githubusercontent.com/10394697/126458077-e33498bd-d979-4ac2-864b-91d1c92e3884.png)

**Comment by Kiro705** [comment]
Hello @kh120 ,

Is this reproducible in the [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/)?

If so, I may recommend reaching out via the [IMA SDK forum](https://groups.google.com/g/ima-sdk) for general support for the IMA SDK.

Thank you,
Jackson
IMA SDK Team

**Comment by kh120** [comment]
Hi Jackson, Thanks for your reply.
