### ISSUE TITLE
Related to #98 and #100

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#101]
I am sorry that I am opening one issue after another, but github doesn't allow me to comment on any issue for videojs-ima, which is weird. Regarding issues #98 and #100 - I created two screencaptures to demonstrate the problem itself.

1. I am opening the Video JS IMA demo on github.io. I am choosing the sample ad tag. I am clicking play. No ads are displayed at all.
2. I am opening the IMA Stand Alone demo on github.io. I am choosing the sample ad tag. I am clicking play, the companion ad loads, but not the pre-roll.

Hope it helps.

Screencapture for VideoJS IMA:
https://www.youtube.com/watch?v=Wk8Jm0V4Y8w
Screencapture for IMA Stand Alone:
https://www.youtube.com/watch?v=5Jtc0r30FIo

This is IE11 on Windows 10. Same happens on Edge. There are no plugins, no adblockers etc. There are no errors in the console.

**Comment by shawnbuso** [comment]
This is definitely an odd GitHub issue - when you try to comment on an issue do you get an error, or is there just no comment box to begin with?

**Comment by kachnitel** [comment]
I know I'm probably a little late, but I just run into this issue and remembered reading this: The comment issue is likely related to adblock.
