### ISSUE TITLE
Why videojs-ima does not work on safari responsive design mode - iphone 8 

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#1011]
Tested advanced example on real iphone safari => works perfectly
Tested advanced example on safari responsive design mode - iphone 8 => player just bricks and ad is not played

https://googleads.github.io/videojs-ima/examples/advanced/
 
vast tag:  https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=
 
Test on safari => responsive design mode => iphone 8

Safari 14

**Comment by Kiro705** [comment]
Hello @damjan25 ,

When testing your ad tag in the advanced example, I see the following error:

```
videojs.ima.js:1521 Ad error: AdError 200: The provided ad type: skippablevideo is not supported.
video.min.js:12 VIDEOJS: adserror (Preroll)
```

Is this the same error you are seeing?

This [guide on skippable ads on mobile](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/skippable-ads) has more information. Using the following code, may be a solution for you.

```
google.ima.settings.setDisableCustomPlaybackForIOS10Plus(true);
```

Thank you,
Jackson
IMA SDK team

**Comment by damjan25** [comment]
Hey, thank you for checking this. 

Yes I am getting exactly the described error.

Will try with that solution, hope it solves the issue :)

**Comment by pkirk** [comment]
@damjan25 did that modify do the trick?
Because I'm seeing the exact error, but setDisableCustomPlaybackForIOS10Plus doesn't change.

Thanks for your time.

**Comment by damjan25** [comment]
unfortunately no :(

Safari response design mode is just acting weird.
