### ISSUE TITLE
Cors error with IMA sample tag

### ISSUE THREAD

**Issue by Anil-matcha** [googleads/videojs-ima#1013]
Hi @Kiro705 

I have been testing the plugin with sample tag from https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags and have observed the CORS error resulting in no playback of the ad

I am attaching a screenshot of the same
<img width="920" alt="sample" src="https://user-images.githubusercontent.com/4326215/134808512-2c35612b-fcd4-415b-9e20-0c194fff8a88.png">

Here is the link to the video with the issue https://api.vadoo.tv/landing_page?vid=WK1aotg5SFG0qJRUCwysEa01jdFOh0SI

Any help would be appreciated. Thanks a lot

**Comment by dioramayuanito** [comment]
in your video tag

<video id="player" class="video-js vjs-default-skin" style="width: 100%;
height: 100%" playsinline crossOrigin='anonymous'></video>

maybe you can delete 'crossOrigin' attribute and its value, and try again...

please cmiiw
🙏





Sent from Mobile Phone with Love, Flowers, and Gifts -
https://about.me/dioramayuanito

Pada tanggal Min, 26 Sep 2021 7.43 PM, Anil Chandra Naidu Matcha <
***@***.***> menulis:

**Comment by Anil-matcha** [comment]
@dioramayuanito 

Thanks for the suggestion. I removed it but it is causing no change https://api.vadoo.tv/landing_page?vid=WK1aotg5SFG0qJRUCwysEa01jdFOh0SI

**Comment by Anil-matcha** [comment]
@dioramayuanito @Kiro705 The issue was bad formatting of url due to the special characters inside the ad tag and is not related to this plugin, so I am closing the issue
