### ISSUE TITLE
Ad player controls overlapping

### ISSUE THREAD

**Issue by Anil-matcha** [googleads/videojs-ima#1014]
Hi @Kiro705 

I have tried the plugin and it works fine but the UI of ad player is distorted as can be seen in below image

<img width="939" alt="adplayer" src="https://user-images.githubusercontent.com/4326215/135132760-fe96173e-6a05-4dea-bb77-4db17b3dbac1.png">

Player controls like volume etc. are overlapping on playbar and resulting in bad experience.  Below is the link to the video, any help is appreciated

https://api.vadoo.tv/landing_page?vid=WK1aotg5SFG0qJRUCwysEa01jdFOh0SI

**Comment by Anil-matcha** [comment]
@Kiro705 Any help is appreciated as this is causing a poor user experience

**Comment by Kiro705** [comment]
Hello @Anil-matcha ,

Sorry for the delay in my response.

I was able to see the mis-styled ad controls on your test page. However, the styling looks correct in the [plugin's sample page](https://googleads.github.io/videojs-ima/examples/advanced/). The sample uses [this stylesheet](https://github.com/googleads/videojs-ima/blob/master/examples/style.css). I would recommend comparing your player with this example to see what style might be missing or being overwritten.

Thank you,
Jackson
IMA SDK team

**Comment by Anil-matcha** [comment]
Hi @Kiro705, I have imported the same scripts from the sample page but the styling is broken. The videojs skin I am using for the player is a custom made skin but it shouldn't impact the ad player as ad player is overlay on videojs player if I am not wrong. 

Is there any custom css for ad player which can be controlled to prevent this issue ?
