### ISSUE TITLE
Google urls in ad reporting instead of website URLs

### ISSUE THREAD

**Issue by amusakhan2016** [googleads/videojs-ima#1016]
Hello Support, 

We are embedding players through an iframe and some of the ad requests are taking google Ad URLs (safeframe.google.com) in the ad requests and showing these in the reports instead of the website page URL.  We checked the IMA documentation and there is a parameter to set Page URL for iframe video player to properly pass website page URLs but we didn't find a proper implementation guide for video players. 
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRequest#pageUrl

Can anyone help us how to set this value?

Thanks, 
Abdul

**Comment by Kiro705** [comment]
Hello @amusakhan2016 ,

Currently, there is not a way to set `AdsRequest.pageUrl()` through this plugin.

I can prioritize adding this feature in the plugin's next release.

Thank you,
Jackson
IMA SDK team

**Comment by amusakhan2016** [comment]
Hello @Kiro705 

Thank you for the update, we will be waiting for the release. 

We tested other video player providers too and that players are also not providing such parameter. We should contact that players teams or not?

Thanks,

**Comment by Kiro705** [comment]
Hi @amusakhan2016 ,

A quick update, it is possible to set the `pageUrl` currently. Sorry for the confusion. Please see the following example:

```
var imaOptions = {
  adTagUrl: 'YOUR_AD_TAG',
  adsRequest: {
    pageUrl: 'YOUR_PAGE_URL'
  }
};

player.ima(imaOptions);
```

You can also use the `adsRequest` setting to set or override any other ads request parameters.

I am unsure how other players/plugins handle the IMA ad requests, but if it is possible to set the ads request parameters prior to the request being made, that is how it should be done.

Please let me know if this works for you and if you have any other questions.
