### ISSUE TITLE
Content playback doesn't start after ad on Android LTE

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#103]
To repro:

1. Make sure 4G is on, and disable WiFi.
2. On Chrome on Android, navigate to https://googleads.github.io/videojs-ima/examples/simple or https://goo.gl/UkJ0QU for short.
3. Tap the play button to play the pre-roll.
4. After the pre-roll finishes, content does not start automatically unless tapped/clicked.

Expected behavior: content should start automatically without users having to tap or click on the play button again.

Order of events I see:
Desktop: ads-ready --> preroll --> ad-playback --> content-playback.
Android: ads-ready --> preroll --> content-playback --> ad-playback.

It looks like because content-playback has been fired already prior to ad-playback, the SDK doesn't fire it again unless the user manually hits Play again.  As to why content-playback is fired early before the ad, it can be seen when you first start playback, you will see a frame of content right before the ad begins.  

Having looked at Video.js documentation, it appears this is related to the prerollTimeout (https://github.com/videojs/videojs-contrib-ads#prerolltimeout).  It looks like the 4th scenario (startLinearAdMode() is called, but after the prerollTimeout expired — bad user experience; content video plays a bit, then preroll(s) cut in).  Not sure why this is happening only on 4G and not WiFi.

**Comment by shawnbuso** [comment]
Looked into this and it may be an IMA issue, not a vide.js plugin issue. Will keep this thread update as we investigate on the IMA side.

**Comment by nickcyang** [comment]
Hi Shawn,
Any update on this? :)

**Comment by shawnbuso** [comment]
Working with the rest of the IMA team, it looks like this is only an issue when custom playback is selected, which is the case for Android currently. We're deprecating this functionality soon (mid-month) so that we will *not* use custom playback on Android. When that changes goes live, this will be fixed automatically.

**Comment by nickcyang** [comment]
Sounds great. The issue seems gone after I loaded the pre-test IMA SDK https://imasdk.googleapis.com/js/sdkloader/ima3_test.js instead (which deprecates the custom playback function as I know). Thank you so much for the help.
