### ISSUE TITLE
Ad error: AdError 303: No Ads VAST response after one or more Wrappers

### ISSUE THREAD

**Issue by JulianNguyen1992** [googleads/videojs-ima#1032]
I think there was a problem when I implemented VAST on my Ad Manager.

When I test, a message returns that:
- Ad error: AdError 303: No Ads VAST response after one or more Wrappers

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector?tag=https%253A%252F%252Fpubads.g.doubleclick.net%252Fgampad%252Fads%253Fiu%253D%252F21899927763%252Fvast_test-video%2526description_url%253Dhttps%25253A%25252F%25252F24hexpress.net%2526tfcd%253D0%2526npa%253D0%2526sz%253D400x300%25257C640x480%2526ciu_szs%253Dfluid%2526gdfp_req%253D1%2526output%253Dvast%2526unviewed_position_start%253D1%2526env%253Dvp%2526impl%253Ds%2526correlator%253D

How can I fix them?

Thank   you so much

**Comment by Kiro705** [comment]
Hello @JulianNguyen1992 ,

This seems to be an issue with you VAST tag, and not the videoJS-IMA plugin. As you have shown, [the VSI player](https://googleads.github.io/googleads-ima-html5/vsi/), which does not use the plugin shows the error as well.

I would recommend checking your Ad Manager settings for the ad unit to ensure everything is set up correctly, and reaching out to Ad Manager support if the problem persists.

Thank you,
Jackson
IMA SDK team
