### ISSUE TITLE
How to detect VIDEOJS: WARN: Unexpected adsready event?

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#1036]
Does anyone maybe know how to detect this event ? 

Reason I need this is because some random vpaid-s sometimes cause this error/warning, and in some cases it bricks the player. That is why I just want to dispose the player when this event is fired. 

Event that player fires before this warning is ADSREADY event but in the object it returns I do not see any msg related to this warning.

player.on(EventType.ADSREADY, (e) => {});

![image](https://user-images.githubusercontent.com/60606529/160621423-4e328759-fa90-42b1-a059-bfe99c3ff0f7.png)

Events that are not fired when this happens: 

- .player.on(EventType.ADSLOADERERROR, error => {})
- .player.on(EventType.ADSERROR, error => {})
- .player.on(EventType.ERROR, error => {})

When this warning is fired I do not get vpaid 901 error 

Versions:
"videojs-ima": "^1.11.0"
"@types/video.js": "^7.3.31"

**Comment by Kiro705** [comment]
Hi @damjan25 ,

Thank you for sharing the VAST.

I captured the VAST, but when testing in the [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/) and the [videojs-ima advanced example](https://googleads.github.io/videojs-ima/examples/advanced/) I saw a 901 error 100% of the time (~20 tests).

Are there any other steps to reproduce the issue?

Based on [player_wrapper.js line 559](https://github.com/googleads/videojs-ima/blob/main/src/player-wrapper.js#L559), you could try to capture the event like this:

```
this.player.on('adsready', function() {
  // react to event
});
```

Please let me know if you have any questions.

**Comment by damjan25** [comment]
Thank you for checking this :)

Hmm but how can I differentiate between "adsready" normal event and "unexpected adsready event" ? 🤔

**Comment by Kiro705** [comment]
There may be some difference between the two events, or if you track the state of your player you may be able to determine when the event is unexpected.

Without being able to reproduce the issue on my end it will be difficult to offer any more concrete guidance.

That being said, it is most likely an issue with the VPAID tag, if you could reach out to the tag provider, that may be the best way to resolve the issue.

Thank you,
Jackson
IMA SDK team

**Comment by damjan25** [comment]
This strange issue with vpaid was solved by adding:
` if(this.player.ima.getAdsManager()) {  }`

Before calling this.player.play(); 

Hope it helps someone :) 

@Kiro705 Thanks for help, really appreciate it. Really strange bug :D
