### ISSUE TITLE
Unable to play M3U8 type Ad Creative

### ISSUE THREAD

**Issue by shyamvala** [googleads/videojs-ima#1037]
I integrated the VideoJS and IMA libraries and able to see the content playback working which is of type M3U8 but when I provided and Ad Tag that has a Creative with M3U8 type of ads, I am not seeing the AD playback. I tried in Advanced example and it fails there too saying something like `Missing Video Capabilities`. 

I am wondering if this isnt supported or am I missing setting up any configuration to make M3U8 type of ads to play.

**Comment by Kiro705** [comment]
Hi @shyamvala ,

Would you be able to share VAST or a vast URL that can reproduce the issue?

If you would like to share this privately, please email jsui@google.com

Thank you,
Jackson
IMA SDK team

**Comment by shyamvala** [comment]
Absolutely, sharing the URL to you on email. I just added mimeType to the options via adRenderingSettings and its launching in Safari but not in Chrome. Not sure why that is, i can see the content playing which is in m3u8 format but not the ad. Anyways I sent the email with subject same as this issues, appreciate your time on this. Thank you.

**Comment by shyamvala** [comment]
Hi @Kiro705 

Just wondering if you were able to  dig into this further. 

Thank you
Shyam

**Comment by shyamvala** [comment]
Oh no problem. Just sent it again.
