### ISSUE TITLE
VMAP tags not working

### ISSUE THREAD

**Issue by gcarrion-gfrmedia** [googleads/videojs-ima#1040]
We have integrated VideoJS 7.17.0 and videojs-ima plugin 1.11.0 into our player using AdManager.

We're trying to display VMAP creatives and we're doing tests with our player, but although the ad tag is called, the subsequent ad calls are not fired. With standard VAST tags, it works fine, it is just when the ad response is in VMAP format that it doesn't work.

Here is an example link: https://player-qa.videoplatform.tv/player/275676.html
Notice there that when the video is clicked, there's a wait time for the ad to load, then it times out and the main video starts to play, but the ad is never displayed. You can also see the ad request that is returned in VMAP format, but the <vmap:AdTagURI> in the main tag is never called by the player.

Here is also a screen recording of the process:
https://www.awesomescreenshot.com/video/8354504?key=67e899e7138c0eeb9ce5d7d451ef93f9

Here is another sample, but this one, the ad call returns a VAST instead o VMAP, notice this one works
https://player.videoplatform.tv/player/275676.html

Please let me know if additional details/samples are needed.

Thanks!

**Comment by Kiro705** [comment]
Hello @gcarrion-gfrmedia ,

When testing with the [IMA sample VMAP tag](https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/vmap_ad_samples&sz=640x480&cust_params=sample_ar%3Dpremidpost&ciu_szs=300x250&gdfp_req=1&ad_rule=1&output=vmap&unviewed_position_start=1&env=vp&impl=s&cmsid=496&vid=short_onecue&correlator=) in the [VideoJS-IMA advanced sample](https://googleads.github.io/videojs-ima/examples/advanced/) and saw the sample load as expected.

I would recommend testing your own VMAP tag in the advanced sample, and also the [VSI player](https://googleads.github.io/googleads-ima-html5/vsi/) to rule out the tag being the issue.

Thank you,
Jackson
IMA SDK team
