### ISSUE TITLE
Use lodash-es and not lodash

### ISSUE THREAD

**Issue by bjornharvold** [googleads/videojs-ima#1041]
Unless you are using the entire feature set of lodash, lodash-es ismore modular.

**Comment by Kiro705** [comment]
Hello @bjornharvold ,

I will look into minimizing the importing of lodash in the next release.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
This commit removes lodash, as it is not used directly by this repo's code.

https://github.com/googleads/videojs-ima/commit/4eab3cf825786cada4c5b091639ac128e9e9817b
