### ISSUE TITLE
Release 2.0.0 not documented in the changelog

### ISSUE THREAD

**Issue by cdhowie** [googleads/videojs-ima#1046]
The 2.0.0 release is absent from CHANGELOG.md, making it difficult to understand what breaking changes occurred.

**Comment by Kiro705** [comment]
Hi @cdhowie ,

Thanks for pointing this out. I will update CHANGELOG.md in the next release. For now please see [the release section](https://github.com/googleads/videojs-ima/releases) for information on new releases.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Changelog is now updated.
