### ISSUE TITLE
New Html5 Ima Sdk

### ISSUE THREAD

**Issue by aydinkn** [googleads/videojs-ima#106]
Hi,

I heard, Html5 Ima Sdk to be renewed / fixed in September. So new sdk, generate another video element for video adsense playback. Will you do a work about this issue, especially for mobile devices?

**Comment by shawnbuso** [comment]
Hi there,

I'm not 100% sure what fix you're referring to (I work on the IMA SDK as well) but IMA is designed so that all publishers pick up the latest changes as soon as they are released - so as soon as that goes out, video.js plugin implementations will be using it. I'm not sure what you're referring to with the AdSense change, because that's how AdSense ads are already handled today. You can see the current status of support for AdSense in our [compatibility matrix](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).

Thanks,
Shawn

**Comment by aydinkn** [comment]
Thanks for response.

I give up a test url: https://imasdk.googleapis.com/js/sdkloader/ima3_test.js

For example: My videojs ima implementation works well but when I change IMA SDK url to test url, video adsense not play on Android 4.3 device (and trigger adsense video timeout).
![2015-08-25 17 11 34](https://cloud.githubusercontent.com/assets/5111036/9468868/b278a31c-4b4c-11e5-8d0c-fd91fabd5dde.png)

**Comment by shawnbuso** [comment]
Could you share your ad tag so I can test this out on my end? Thanks!

**Comment by aydinkn** [comment]
My test video adsense url: http://pubads.g.doubleclick.net/gampad/ads?sz=640x360&iu=/6062/iab_vast_samples/skippable&ciu_szs=300x250,728x90&impl=s&gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]

This problem not happen when I test Google Chrome's device emulator.

**Comment by shawnbuso** [comment]
Hi there,

That's a Doubleclick tag, not an AdSense tag - the ad system is listed as "GDFP". Is that the right tag? If so then it doesn't look like an AdSense issue, but maybe a DFP issue.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Also, are you able to replicate this with our [samples](http://googleads.github.io/videojs-ima/)? I tested a few tags there with ima3_test.js on my Android device and all seem to be working fine for me.

**Comment by aydinkn** [comment]
Hi Shawn,

I tested samples ad tag but not working with my implementation. I suppose problem in my implementation. Because, these samples works fine with ima3_test.js just like you said.

Thanks.

**Comment by aydinkn** [comment]
I found this problem source.

When I request ads with first play event (my implementation just like this):
```javascript
player.one("play", function() {
   player.ima.initializeAdDisplayContainer();
   player.ima.requestAds();
   player.play(); // Or without this line
});
```
I've got this error on Android device. But when I request ads with click or tap event just like samples code:
```javascript
player.one("tap", function() { // or "click"
   player.ima.initializeAdDisplayContainer();
   player.ima.requestAds();
   player.play();
});
```
It works well.

Thanks.

**Comment by shawnbuso** [comment]
Thanks for the update, glad to hear you got it working! Yes initializing the ad display container as the result of a user action is a requirement for mobile implementations.
