### ISSUE TITLE
Property authKey of the streamRequest object should be authToken

### ISSUE THREAD

**Issue by ieyara** [googleads/videojs-ima#1060]
videojs.ima.js script is making use of streamRequest.authKey  property in https://github.com/googleads/videojs-ima/blob/main/dist/videojs.ima.js#L3060

According to StreamRequest class documentation (https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/reference/js/StreamRequest) the correct property name is authToken.

**Comment by Kiro705** [comment]
Hello @ieyara ,

Thank you for catching this, I will look to implement this fix.

Jackson
IMA SDK team

**Comment by Kiro705** [comment]
This bug is addressed in this commit:
https://github.com/googleads/videojs-ima/commit/a1cbb10bc43828dfee35a1d0f8696c631df230f9

It should go live in the next npm release.

**Comment by Kiro705** [comment]
This fix is available in [v2.1.0](https://github.com/googleads/videojs-ima/releases/tag/v2.1.0).
