### ISSUE TITLE
Improve documentation for omidVendorAccess

### ISSUE THREAD

**Issue by MarkusWollny** [googleads/videojs-ima#1063]
Our ad agency asked us to configure our video player to allow full Open Measurement access for Double Verify. The current documentation just references the official Google IMA SDK docs and doesn't give an example for setting omidVendorAccess, so I guessed that setting
```
ima.options = {
  ...
  omidVendorAccess: {
    DOUBLEVERIFY: 'FULL',
    OTHER: 'FULL'
  }
  ...
}
```
should do just that, but they tell me that they aren't seeing the expected incoming data. I am not sure if this is due to a misinterpretation of the omidVendorAccess setting on my part or if there is perhaps something wrong on their end. Would it be possible to include an example setting in the documentation? Is there some programmatic way to verify the OMID rules in effect during development on my side?

**Comment by Kiro705** [comment]
Hello @MarkusWollny ,

Please take a look at the [IMA guide for setting access move rules](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/omsdk#setting_access_mode_rules_for_a_request). The key and value pairs should use the IMA constants.

The updated code sample should be:
```
ima.options = {
  ...
  omidVendorAccess: {
    [google.ima.OmidVerificationVendor.DOUBLEVERIFY]: google.ima.OmidAccessMode.FULL,
    [google.ima.OmidVerificationVendor.OTHER]: google.ima.OmidAccessMode.FULL,
  }
  ...
}
```

Please let me know if you have any follow-up questions,
Jackson
IMA SDK team

**Comment by MarkusWollny** [comment]
Thank you! I wasn't aware that google.ima was actually directly available inside the plugin's configuration - I guess I just overcomplicated things and should have simply tried that :)
