### ISSUE TITLE
videojs-ima breaks other video players on website that use data-setup="{}" attribute

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#1064]
Videojs-ima package hooks onto any video player on the website that has attribute: data-setup="{}" which then breaks those players using that property.

Example: If I have videojs-ima + videojs player on the website (from publisher - not my website) for showing ads and there is another video player from publisher on page for just showing mp4 file for example `<video data-setup="{}"></video>` on the website. Videojs-ima will automatically hook onto that player with attribute `data-setup="{}"` and break it. 

![image](https://user-images.githubusercontent.com/60606529/189955421-a3c652d0-34b7-4de5-a1b2-7b0c5da002b3.png)

videojs-ima versions: "2.1.0" (also tried with version: "^1.11.0" )
browser: chrome
device: desktop and mobile

**Comment by damjan25** [comment]
Here is just html example what happens to the any random video html tag(with attribute: data-setup="{}") that is on website when videojs-ima is loaded
[videojsimaBugExample.csv](https://github.com/googleads/videojs-ima/files/9559005/videojsimaBugExample.csv)

**Comment by Kiro705** [comment]
Hello @damjan25 ,

Thank you for bringing this up. I am a little unclear on how this happens, I also do not see anywhere in the videojs-ima code that specifically targets `data-setup`.

Would you have any additional details on how a fix could be developed for this issue? My understanding is the videojs-ima plugin follows the standard for registering a videojs plugin. See code [here](https://github.com/googleads/videojs-ima/blob/main/src/ima-plugin.js#L353-L355).

Thanks you,
Jackson
IMA SDK team

**Comment by damjan25** [comment]
@Kiro705 I think that issue might be coming from videojs itself, from these lines:
https://github.com/videojs/video.js/blob/4e2f8add411d38549a39cf4e52172d9a01158da0/src/js/setup.js#L15

**Comment by Kiro705** [comment]
Would it be possible to raise the issue to the videojs player team? I won't be able to resolve it through this IMA plugin.
