### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by renebaudisch** [googleads/videojs-ima#1065]
Is this code still up to date?
https://github.com/googleads/videojs-ima/blob/main/src/client-side/controller.js#L116

The IMA docs do not say anything about deprecation:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRequest?hl=en

**Comment by Kiro705** [comment]
Hello @renebaudisch ,

This videojs-IMA plugin will detect if the player is muted or set to autoplay, and update the ad request. See [here](https://github.com/googleads/videojs-ima/blob/main/src/client-side/controller.js#L753).

The IMA parameters are not deprecated, as you pointed out.

Let me know if you have any follow-up questions.

**Comment by renebaudisch** [comment]
I didn't point that out, the plugin does. I just wondered why. And the detection happens if you don't set it manually, so...
