### ISSUE TITLE
Ad Events (Started, quartile, etc.) are not working on safari / IOS

### ISSUE THREAD

**Issue by vsawma** [googleads/videojs-ima#1067]
To reproduce the issue, try the Video.js IMA DAI Demo that you have.
If you try it on a Windows machine, all goes well. Events are triggered and appear logged.
If you do the same on an IPad using Safari browser, no events are there. The stream plays and shows the video but the events related to the Ads are not being fired / captured.

**Comment by Kiro705** [comment]
Hello @vsawma ,

Thank you for raising this issue. I was able to reproduce this using the Safari browser on a mac with the [DAI sample](https://googleads.github.io/videojs-ima/examples/dai/). Events did fire for the VOD stream, but not the live stream.

I will plan to investigate this, but may find it is a limitation of the modules being used for stream playback.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Update the plugin for a fix to this issue. It will be included in the next release of the videoJS-IMA plugin.

https://github.com/googleads/videojs-ima/commit/ed054306c90614db94a96a2e482d45c42493b59f
