### ISSUE TITLE
Progress bar has delay

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#1072]
- Currently there is a big delay between ad time and progress bar.
For example ad is already done playing and the progress bar is not even at full width yet. By the looks of if there is something like 1s delay without using any css transition. If you add css transitions to make the progress bar look smooth and not buggy then the delay is even bigger. 

- Is it possible to adjust this with any property ? 

- For example the ad is done playing and it closes and the progress bar is still not fully expanded like this:
![image](https://user-images.githubusercontent.com/60606529/209354218-6ce38308-4c6d-421d-b4d8-1fb9ee4a00ad.png)

- Simple example:
https://codepen.io/imasdk/pen/wpyQXP

- Why is this an issue? 
If someone is looking at the progress bar, they might think that you are closing the ad before the player even finishes playing the ad.

Browser: chrome 108.0.5359.125
"videojs-ima": "^2.1.0"

**Comment by damjan25** [comment]
Just an idea:
src\client-side\ad-ui.js

```js
  // Update UI
  //add configurable property so if user uses css like for ex. ".ima-progress-div { transition: width 1s ease; }"
  //so that he can add this 1s for the animation delay
  const userConfigurableDelay = 0; //default 0s and passed into the function as a parameter
  const animationDefaultDelay = 0.5; //by default there seems to be 0.5s animation delay

  currentTime += animationDefaultDelay + userConfigurableDelay;

  const playProgressRatio = currentTime / duration;
  const playProgressPercent = playProgressRatio * 100;
  this.progressDiv.style.width = playProgressPercent + '%';
```


Just for reference to see which lines are changed:
![image](https://user-images.githubusercontent.com/60606529/209378731-889ac684-73d0-4132-926f-dfc55108f43e.png)

**Comment by Kiro705** [comment]
Hello @damjan25 ,

Using your sample app, I see the progress bar nearly full right as the ad is nearly finished playing, see attached screenshot. Let me know if there is anything additional needed to be done to reproduce the issue.

<img width="1565" alt="Screenshot 2022-12-28 at 4 06 50 PM" src="https://user-images.githubusercontent.com/14110467/209872417-8b710f8a-6147-425b-97e2-b4da9df98f3b.png">

Jackson
IMA SDK team

**Comment by damjan25** [comment]
@Kiro705 This is the issue, that it does not go all the way. Looks like it just depends on player size.
On my laptop screen there seems to be much more space left (like on my 1st screenshot) but on my pc screen it looks the same as on your screenshot.

Would it be possible to add this so that the bar goes all the way ?

**Comment by Kiro705** [comment]
Hello @damjan25 ,

Would it be possible to share a screen-size I can emulate with Chrome inspector tools that can reproduce the issue?

Thank you,
Jackson
IMA SDK team

**Comment by damjan25** [comment]
24' 1080p 100% zoom  => looks like on my first screenshot 
27' 1440p 125% zoom => looks the same as on my first screenshot
16' 1200p 150% zoom (laptop) => looks the same as on your screenshot (progress bar does not go all the way but there is not that much space left)


Problem is that if you add any css animation/transition on progress bar to make it smoother it will add that delay :(

**Comment by Kiro705** [comment]
Hello @damjan25 ,

It is my understanding that the bar fills up at the same rate, and the last image of the progress bar will be roughly 95%-97% full. On larger players, the gap will appear larger, but will still be only 3-5% of the total length of the bar. 

As far as I can tell, the bar is accurately representing the remaining time of the ad. At 100% the player will have already transitioned back to content or gone to the next ad.

Right now, we are considering this as 'working as indented'.

Please let me know if you have any follow-up questions.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Here is where the css percentage is calculated:
https://github.com/googleads/videojs-ima/blob/main/src/client-side/ad-ui.js#L300

Either
```
// Update UI
  const playProgressRatio = currentTime / duration;
  const playProgressPercent = (playProgressRatio * 100) + 5;
  this.progressDiv.style.width = playProgressPercent + '%';
```

or

```
// Update UI
  const playProgressRatio = currentTime / duration;
  const playProgressPercent = (playProgressRatio * 100);
  if (playProgressPercent > 90) {
    playProgressPercent = 100;
  }
  this.progressDiv.style.width = playProgressPercent + '%';
```

would result in making sure the progress bar reaches 100% while the ad is still playing.
