### ISSUE TITLE
How to force video player to play ads even when it is out of the viewport?

### ISSUE THREAD

**Issue by yashraj-02** [googleads/videojs-ima#1075]
https://www.javatpoint.com/javascript-tutorial?forceOutstreamBid=true&forceApPlayer=true

Here ads only play when they come into the viewport.

**Comment by Kiro705** [comment]
Hello @yashraj-02 ,

This is not recommended behavior, ads should only be autoplayed if they are within the viewport. Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
