### ISSUE TITLE
Safari iPad: ads content stuck on the first frame, and switch back the video.

### ISSUE THREAD

**Issue by stavkamil** [googleads/videojs-ima#1076]
When I'm debugging it in our project (nextjs application), there's an error on preroll:
**Unhandled promise rejection. abortError: the operation was aborted**
The error occurs by the time the preroll should start. Then the adbreak freeze on the first frame and goes back to the video.

**I can also reproduce this bug in the simple/advanced examples** >> [https://googleads.github.io/videojs-ima/examples/simple/](https://googleads.github.io/videojs-ima/examples/simple/)
(There are no runtime errors, but still the ad content get stuck and goes back to the video).

Model Name: iPad(7th generation)
IOS Version: 15.4.1

our stack:
video.js: 7.19.2
videojs-ima: 2.1.0
videojs-contrib-ads: 6.9.0
next: 12.1.0
react: 17.0.2

**Comment by Kiro705** [comment]
Hello @stavkamil ,

I would recommend following the the [advanced example](https://github.com/googleads/videojs-ima/blob/main/examples/advanced/ads.js), specifically how certain steps are taken if an iPad is detected.

When testing on an iPad, with the [advanced example](https://googleads.github.io/videojs-ima/examples/advanced/), I was able to see pre-roll ads successfully play. Are you able to see successful playback in the advanced sample with your iPad.

Thank you,
Jackson
IMA SDK team
