### ISSUE TITLE
DAI with preroll example?

### ISSUE THREAD

**Issue by simplestream-adam** [googleads/videojs-ima#1080]
Hello

Is there a videojs-ima example of running an IMA preroll before a DAI stream?

Here is the Google example using hls.js:
https://github.com/googleads/googleads-ima-html5-dai/tree/main/hls_js/dai_preroll

**Comment by Kiro705** [comment]
Hello @simplestream-adam ,

Using both DAI and client-side SDKs, which is needed for DAI with preroll, has not been tested for the videojs-ima plugin, and is not explicitly supported.

The team may look into supporting this feature in the future, but it is not currently being planned for.

Thank you,
Jackson
IMA SDK team
