### ISSUE TITLE
Advertising does not work with the adding plugin method called "plugins option."

### ISSUE THREAD

**Issue by sanghavp** [googleads/videojs-ima#1082]
When I add the plugin as a plugin option, the advertisement does not work and this error is displayed on the console tab
![Screenshot_2](https://user-images.githubusercontent.com/89146529/216916391-8c568af1-99a5-43c8-b5ec-86fe1f13cc7d.png)
This could be due to the controlBar not being initialized by this method
![Screenshot_1](https://user-images.githubusercontent.com/89146529/216918655-c131c1eb-b064-4ae8-a2f5-bebc2e832a20.png)
![Screenshot_3](https://user-images.githubusercontent.com/89146529/216918854-c6f1b9ef-f754-41cc-be90-04d2f0bd20c9.png)

**Comment by sanghavp** [comment]
These are two ways to use the plugin on the videojs homepage, I used method 1 but the advertisement is not working: 
"Setting up a Plugin
There are two ways to set up (or initialize) a plugin on a player. Both ways work identically for both basic and advanced plugins.

The first way is during creation of the player. Using the plugins option, a plugin can be automatically set up on a player:

videojs('example-player', {
  plugins: {
    examplePlugin: {
      customClass: 'example-class'
    }
  }
});
Otherwise, a plugin can be manually set up:

var player = videojs('example-player');
player.examplePlugin({customClass: 'example-class'});
These two methods are functionally identical - use whichever you prefer!"

**Comment by Kiro705** [comment]
Hello @sanghavp ,

Would it be possible to share code snippet that reproduce the error you are seeing in the first comment?

We recommend following the [Get started](https://github.com/googleads/videojs-ima#get-started) section of our readme for instructions on setting up the videoJS-IMA plugin.

Please let me know if you have any questions.

Thank you,
Jackson
IMA SDK team

**Comment by sanghavp** [comment]
This is code snippet produce the error: 
![Screenshot_4](https://user-images.githubusercontent.com/89146529/218002368-afda9a8b-c194-43e9-812f-2e0b371c9519.png)
ControlBar not created when I using plugin option(I need to use this in my project): 
![Screenshot_5](https://user-images.githubusercontent.com/89146529/218002703-a4f3fc30-4dac-4384-8b84-5cd776de671f.png)

**Comment by sanghavp** [comment]
Thank you very much!!

**Comment by Kiro705** [comment]
Hello @sanghavp ,

This plugin is not designed to be included in the plugin option when initiating the videojs player. Instead please follow the initiation steps as detailed by the plugin readme. Otherwise you may see issue with certain plugin features not being properly initiated. 

Thank you,
Jackson
IMA SDK team

**Comment by sanghavp** [comment]
Thank you very much for support!
