### ISSUE TITLE
number of ads different in top bar V player

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1083]
I'm seeing a differnce in the number of ads being shown in the top bar and the player.  In top bar says Ad 1of 2: (TIME)  but it then shows Ad( 1 of 3) in the player,  any ideas whats wrong?

![Adysis_Video_Demo](https://user-images.githubusercontent.com/8503167/219784353-52811171-1b85-4720-a59a-0181fde4d4ea.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

Would it be possible to share a sample ad tag that can reproduce this issue? Feel free to share the ad tag privately by emailing jsui@google.com

Thank you,
Jackson
IMA SDK team
