### ISSUE TITLE
Non-linear ad (overlay) is at 50% opacity when re-opened

### ISSUE THREAD

**Issue by kchris78** [googleads/videojs-ima#1084]
Hi,

there is a bug, when re-opening a closed overlay on mobile/desktop.

1. Starting video (don't move the mouse cursor out of the player!)
2. Non-linear ad pops-up
3. Wait until the non-linear ad disappears
4. Re-open the overlay ad clicking on the little arrow in the middle of the player
5. The non-linear ad pops up - the only problem is that it has 50% opacity

Could you help fixing that bug? Thank you,
Christian

![letöltés](https://user-images.githubusercontent.com/15803452/222448351-2d1a1159-89d4-46da-bbaf-8630cd908f42.jpeg)

**Comment by Kiro705** [comment]
Hello @kchris78 ,

Thank you for sharing this issue. I am having some difficulty understanding how to reproduce the issue.

Is it reproducible with the [IMA sample non-linear ad](https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/nonlinear_ad_samples&sz=480x70&cust_params=sample_ct%3Dnonlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=)?

If not, you can privately share an ad tag by emailing me here (jsui@google.com)

Could you also share a screen recording of the issue, to help me understand how to reproduce it?

Thank you,
Jackson
IMA SDK team
