### ISSUE TITLE
add ability to send "secure signals"

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1085]
is there anyway that this can be used to send  "secure signals" as google video doesnt use GPT tags, so deploying the secure signals scripts automatically doesnt seem to work, but there seems to be a way to send custom according to this: https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/securesignals

**Comment by Kiro705** [comment]
Hello @spormeon ,

The sending secure signals with the guide you shared if currently in a closed beta. Please reach out to your account representative for more information on this.

I am going to remove this issue to limit exposing the above link. Please do not share it in a public forum moving forward.

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
whats wrong with it, its a public url?
