### ISSUE TITLE
videojs.ima is not a function

### ISSUE THREAD

**Issue by a0937027831** [googleads/videojs-ima#1086]
`###` Expected behaviour
play ads 

### Actual behaviour
this.player.ima is not a function

### Steps to reproduce
1.open cmd
2.npx nuxi init videojs_ima
3.npm i video.js、npm i videojs-contrib-ads、npm i videojs-ima

### Environment
-   Browser: chorme
-   Version: 110.0.5481.178
-   Operating System: nuxt
-   Version: 3.2.3

### Console errors (if any)
this.player.ima is not a function

### Link to where the bug is happening
[editor online](https://codesandbox.io/p/github/a0937027831/videojs_ima/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522clf23chlt0003g1h15ww37nqq%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clf23ckps000x356jbd6eykbr%2522%253A%257B%2522key%2522%253A%2522clf23ckps000x356jbd6eykbr%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clf23eutl0096356jyf9shvmw%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clf23eu0s006l356jy8djrrwj%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clf23ckps000x356jbd6eykbr%2522%252C%2522spacesOrder%2522%253A%255B%2522clf23ckps000x356jbd6eykbr%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

**Comment by netin1202** [comment]
Facing same issue in react js

**Comment by TodsapornSangpook** [comment]
I ran into the same problem as you in video.js 8.

**Comment by a0937027831** [comment]
video.js version 7.21.3 
videojs-ima version 2.1.0
=>can use

**Comment by Kiro705** [comment]
Hello @a0937027831 ,

In your sample I do not see a call loading in the IMA SDK:

```
<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
```

This is still required when using ES6 imports for the videoJS-IMA plugin.

In addition, I am not familiar with https://codesandbox.io/, but I did not see the various dependencies downloaded anywhere being used in the sample:

```
import videojs from 'video.js';
import 'videojs-contrib-ads';
import 'videojs-ima';
// Styles
import 'video.js/dist/video-js.min.css';
import 'videojs-contrib-ads/dist/videojs-contrib-ads.css';
import 'videojs-ima/src/css/videojs.ima.css';
```

Let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team

**Comment by a0937027831** [comment]
I add this script in head
 `<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>`
but also show videojs.ima is not a function

start point
`onMounted(() => {
  player = videojs("video", videoOptions, onReady);
});`

`function onReady() {
 var adsOptions = {
    debug: true,
    id: "video",
    adTagUrl:
      "http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator=",
  };
  player.ima(adsOptions);
}`

[this my example github](https://github.com/a0937027831/videojs_ima)
1.npm install
2.npm run dev
3.open chrome http://localhost:3000/

![loading_ima3](https://user-images.githubusercontent.com/27282377/225194372-5ab5d575-6121-4015-bf07-c2ab6967c785.png)
![not a function](https://user-images.githubusercontent.com/27282377/225194518-af2406e0-fc02-47c3-98e5-ce0861450ab4.png)

**Comment by Kiro705** [comment]
Hello @a0937027831 ,

Thank you for sharing the sample, I was able to reproduce the issue with the `Uncaught TypeError: player.ima is not a function` error.

I think this might be an issue with somehow Nuxt not supporting how the videojs-ima plugin is set up. When testing, I see a request to `http://localhost:63112/_nuxt/node_modules/.vite/deps/videojs-ima.js?t=1679412490332&v=3e4b2345` which seems to be a re-compiled version of the videojs-ima plugin files. This file is getting run, but does not seem to successfully register the plugin with video.js. I also do not see an explicit call to `import videojs from 'video.js';` in the file which might be the reason why.

I am not very familiar with Nuxt and cannot confirm if it supports this plugin. If you create a different sample that does not use Nuxt, does the issue still happen?

Thank you,
Jackson
IMA SDK team

**Comment by a0937027831** [comment]
Hi @Kiro705  ,Thanks for your reply
I can comprises this version to success play ads
"dependencies":{
  "video.js": "^7.21.3",
  "videojs-contrib-ads": "^6.9.0",
  "videojs-ima": "^2.1.0"
}
**I got the test result :**
1. if I use video.js 7+ version with videojs-contrib-ads 6.9.0 version can play
2. if you install video.js 8+ version , you need install **videojs-contrib-ads 7.1.0 version**，because videojs-contrib-ads 7.1.0 version not supper video.js 7+ !
3. So maybe videojs-contrib-ads 7.1.0 version there are changes something

this is my successed example project
[successed](https://github.com/a0937027831/videojs-ima-success)
[onlineEditor](https://codesandbox.io/p/github/a0937027831/videojs-ima-success/main?workspaceId=11f24b2d-04ff-40c1-9ed5-60ca74cc5cb4&file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A17%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A2%2C%22startLineNumber%22%3A13%7D%5D)

**Comment by adiffmike** [comment]
This is a peer dependencies issue. If you're installing and using this as a module.  The videojs version in peerDependencies is capped at 7    ``` "video.js": "^5.19.2 || ^6 || ^7"```  so  yarn/npm will install version 7 for the videojs-ima module.  That version is what will get the ima plugin attached but it won't be the version of videojs to create a player.  You can see this if you use version 8 and videojs-contrib-ads in your package.json and install videojs-ima yarn will install videojs and videojs-contrib-ads under node_modules/videojs-ima/node_modules

Until this package gets updated you can force it to use the locally installed versions by adding the following to your package.json:

```
  "resolutions": {
    "videojs-contrib-ads": "^7.1.0",
    "video.js": "^8.0.4"
  }
```

**Comment by a0937027831** [comment]
@adiffmike,Thanks for your reply
I succeeded to play ima,no error!
I add this:
`  "overrides": {
    "videojs-contrib-ads": "^7.1.0",
    "video.js": "^8.0.4"
  }`
@adiffmike @Kiro705 Thanks for your help!!
