### ISSUE TITLE
AdsRenderingSettings: { useStyledNonLinearAds: true} not setting close button?

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1087]
it seems that setting: AdsRenderingSettings: { useStyledNonLinearAds: true}  is not setting a close button on the ad, the ad is a direct ad being delivered from GAM

**Comment by Kiro705** [comment]
Hello @spormeon ,

This setting only applies to Non-Linear ads being served. It will not apply to other ad types.

You can test your implementation with this [non-linear sample tag](https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/nonlinear_ad_samples&sz=480x70&cust_params=sample_ct%3Dnonlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=). If `useStyledNonLinearAds: true`, there should be an 'X' button on the ad that can close it.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Hello @spormeon ,

Would you be able to share a sample that reproduces the issue?

When initiating IMA with the following settings, I am able to see the 'X' button.

```
const imaOptions = {
    adTagUrl: 'my-ad-tag',
    adsRenderingSettings: {
      useStyledNonLinearAds: true,
    },
};
  
  this.player.ima(imaOptions);
```
Make sure to use the correct case for `adsRenderingSettings` as seen in the [Additional settings section](https://github.com/googleads/videojs-ima#additional-settings).

Jackson
IMA SDK team

**Comment by spormeon** [comment]
capital A by the looks of it then, as that whats in the ima documentation, should bring that inline for consistancy?

**Comment by Kiro705** [comment]
Hello @spormeon ,

The capital `AdsRenderingSettings` is the IMA class name. The lower case `adsRenderingSettings` is the parameter used in this plugin's additional settings, and this is in line with how other settings parameters are set up.

Please feel free to reopen this issue if you have any additional concerns.

Jackson
IMA SDK team
