### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'registerPlugin')

### ISSUE THREAD

**Issue by sirsquall** [googleads/videojs-ima#1089]
Hi,

I just added the videojs.ima.min.js in my website, and I have this error:
videojs.ima.min.js?rs69ef:1 Uncaught TypeError: Cannot read properties of undefined (reading 'registerPlugin')
    at videojs.ima.min.js?rs69ef:1:46594
    at videojs.ima.min.js?rs69ef:1:171
    at videojs.ima.min.js?rs69ef:1:200

Is a standalone website, not vue or something, how can we make this work without configuration or something else?

**Comment by Kiro705** [comment]
Hello @sirsquall ,

Did you follow the [ES6 imports method](https://github.com/googleads/videojs-ima#es6-imports) or [Alternative setup](https://github.com/googleads/videojs-ima#es6-imports) to enable this plugin?

If you just add 'videojs.ima.min.js' to the page, things may not be properly configured.

Let me know if you have any additional questions.

**Comment by sirsquall** [comment]
Hello,

I'm probably missing something, but it's not super clear for me. I have a google admanager account up and running, when I setup a VAST (video) creative, google show a warning that we need to include the videojs ima in the website page, they didn't mention any configuration.

The video is added to the page by their scripts, I not adding the video or the player.js or anything else to the page.

have you already made those kind of setup? It's mandatory to do the palyerjs with the ad_tag? Where I can find it?

Thanks

**Comment by Kiro705** [comment]
Hello @sirsquall ,

Thank you for your reply. I am not familiar with the Google Ad Manager warning that says this plugin is required. Is there any additional Ad Manager documentation related to this warning? It may also be helpful to reach out to [Ad Manager support](https://support.google.com/admanager/?hl=en#topic=7505988).

It may also be helpful to share more details about your intended use for the IMA SDK. This could help me direct you to the correct support.

Thank you,
Jackson
IMA SDK team

**Comment by sirsquall** [comment]
ah find why, is not the same IMA script, see here:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side?hl=fr

Scripts is there:
https://imasdk.googleapis.com/js/sdkloader/ima3.js
