### ISSUE TITLE
Can I examine the ads in an AdPod / VAST response?

### ISSUE THREAD

**Issue by riksagar** [googleads/videojs-ima#1090]
From the logging in my app, I see that videojs-ima is only playing about half the ads returned in the adpods.  These are adpods returned from thirdparties, in real world content playback scenarios. 

I see this in our production app., based on logging of the `adPodInfo` when the adpod is loaded (`AdEvent.Type.LOADED` on the ad manager) versus the playback starts (`AdEvent.Type.STARTED` event).

I don't see a good way to get videojs-ima to report which ads are playable and which will be skipped.  Presumably the library is doing some browser capability checks and skipping ads it deems unplayback.

I do see an occasional _"There was an error playing the video ad"_ error logged (`adPlayError` events).  But not enough of those to account for the discrepency.

What events can I register for to catch all the skipped/invalid ads?  Alternatively, is there an event that dumps the contents of the `mediaFile` elements from the vast response, so I can log them?

Thanks,
Rik.

**Comment by Kiro705** [comment]
Hello @riksagar ,

Thank you for raising this issue. 

Would you be able to share an example ad VAST or VAST url that can reproduce this issue reliably? You can share it privately with jsui@google.com. This could help me determine if the ads being missed in the ad pods is in fact an error.

The videoJS-IMA plugin does not do any compatibility checks to disqualify certain ads. However, the IMA SDK itself does do this type of checks. Setting [AdsRenderingSettings.mimeTypes](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRenderingSettings#mimeTypes) can set what ad mimeTypes your player can play.

You can follow this step for listening for AdsLoader errors ([link](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side#7.-listen-for-adsloader-events))

And this step for AdsManager errors ([link](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side#handling-errors).

To get these IMA classes you can follow this videoJS-IMA plugin step ([link](https://github.com/googleads/videojs-ima#ima-plugin-ad-events)).

Let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
