### ISSUE TITLE
caught TypeError: Cannot read properties of undefined (reading 'onPlayerVolumeChanged')  

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1091]
I'm seeing this error randomly, its not constant.  When it happpens it stops the ds/player from working and throws me a "black" screen of doom:

source is this:
,
    a.prototype.onPlayerVolumeChanged = function(t) {
        this.adUi.onPlayerVolumeChanged(t),
        this.sdkImpl.onPlayerVolumeChanged(t)
    }

![Adysis_Video_Demo](https://user-images.githubusercontent.com/8503167/232051056-75a1043b-ae71-4d46-a67f-9cf48656b8b0.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

Possibly, do you have a test case that reproduces the issue 100% of the time? You can email more info to jsui@google.com.

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
emailed it to you

**Comment by Kiro705** [comment]
Hello @spormeon ,

Thank you for sharing the test page. Testing ~30 times, I did see the player stall with a black screen once. However, I did not see an error thrown related to:

```
a.prototype.onPlayerVolumeChanged = function(t) {
  this.adUi.onPlayerVolumeChanged(t),
  this.sdkImpl.onPlayerVolumeChanged(t)
}
```

If you could capture the VAST, or VAST url that triggers the error 100% of the time, that may be the best way to proceed.

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
i might of got rid of the volumechnage errors by some tweaks i pushed live the othe day,  I'll test it  and see if it come back

**Comment by dioramayuanito** [comment]
i don't know why, it only happens if we use video.js greater than v7.21.3

**Comment by Kiro705** [comment]
Hello @spormeon ,

Any updates on being able to reproduce this issue?

Thank you,
Jackson
IMA SDK team
