### ISSUE TITLE
unusal goings on/ senario with vidojs-ima and ima sdk maybe

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1095]
Hi  I think I have found a weird senario/ going on.  on 24th April there was a GAM issue causing "The affected users are able to access Google Ads, but are seeing error messages, high latency, and/or other unexpected behavior."   this was causing my player to not load and giving a "small black box".  I think this was because the sdk "couldnt work" due to the GAm issu and ima sdk.  Does this videojs-ima have any sort of "graceful fallover" for this sort of senario, so rather than "hanging" it timeouts/ skips etc, if something in the background ima sdk wise is going on?

no errors , nothing but i believe the sdk is hanging it, as there is no sign of the ima sdk iframe in console "warning" that is always there on load.  Its almost as if its say "there is an ad, but something gone bang in background, cant go any further"

![Phil_Hale_-_Video_js_-_Slack](https://user-images.githubusercontent.com/8503167/234229039-5f74f39d-455f-4235-9ab6-1a750514319c.png)

gam issue, if you have ability to dig into that more in background?
![Google Ads_Status_Dashboard_🔊](https://user-images.githubusercontent.com/8503167/234229838-cab34001-aeeb-4769-be5d-804f4af2b4af.png)

**Comment by dioramayuanito** [comment]
I have a feeling, that your case similar with our case in several months. It happens when VPAID make a lot of hops from one point into the last one.

Maybe you can set **numRedirects** in videojs-ima configuration value from 4 as a default into bigger number just like 10 or 12.

**Comment by spormeon** [comment]
@dioramayuanito thanks for the pointer but already got set at 15

**Comment by spormeon** [comment]
its on the test page i sent you on email the other day

**Comment by Kiro705** [comment]
Hello @spormeon ,

Thank you for confirming. I had thought that test page was related to issue #1091 , not this issue.

I just loaded the test page, and saw ads play. Are there any additional steps needed to reproduce this issue (black player, no errors)?

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
its random, when it happnens, which makes me think its related to gam issue maybe, as that in and out as well

**Comment by spormeon** [comment]
this resolution works out prefect as I have been seeing it work again from just after 5pm my time, im in uk, so my best guess is this issue is related to this, so a "no hang" allow content video to continue would be perfect, its far better than blocking everything out for a user:
![Google Ads_Status_Dashboard_🔊](https://user-images.githubusercontent.com/8503167/234353338-a1665b4a-8a36-4d65-80a9-269655ebf5ee.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

Based on your previous comment, is the black screen issue resolved?

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
its alot better now, more a 8/10 now
