### ISSUE TITLE
[Video] Plugin does not display ads if started in fullscreen

### ISSUE THREAD

**Issue by vhbramos** [googleads/videojs-ima#1097]
When video content playback starts in fullscreen, the plugin does not properly initialize IMA SDK and ads are not displayed.

[---Steps to Reproduce---]
 - Access the Plugin test page: [https://codepen.io/imasdk/pen/wpyQXP](https://www.google.com/url?q=https://codepen.io/imasdk/pen/wpyQXP&sa=D&source=buganizer&usg=AOvVaw3fvlHnPTUcBF9w3UwCiSRV)
 - Right-click on video player and select "Show Controls"
 - Put the video in full screen
 - Click on the video to trigger playback

**Comment by Kiro705** [comment]
Hello @vhbramos ,

After some experimenting, the following code captures the fullscreen event from the "Show Controls" option:

```
document.addEventListener('webkitfullscreenchange', () => {
    // response to event.
});
```

However, what is interesting, is this does not trigger the videoJS `fullscreenchange` event. If it did trigger the event, then things should work as expected. Without that event being triggered, it becomes somewhat messy to manage the fullscreen state for IMA. I would recommend raising an issue in the [video.js issues queue](https://github.com/videojs/video.js/issues) to better understand how it can be supported on their end.

In the current state, I do not think we can support this functionality in this plugin.

Let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
