### ISSUE TITLE
make videojs-ima use same controls style, colours etc as videojs

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1099]
Is there a quick and easy way to make videojs-ima use the same "controls" layout and colurs etc as videojs? Instead of having to pick my way through all the css etc.  If not, i think this would be a good addition to add to the plugin:   useVideoJsControls: true/ false

**Comment by Kiro705** [comment]
Hello @spormeon ,

The plugin does not have any APIs allowing for ad controls customization outside of the `disableAdControls` setting.

My recommendation would be to customize the css or layout directly in your app for now. But can keep this open if someone is interested in adding this feature.

Thank you,
Jackson
IMA SDK team
