### ISSUE TITLE
IMA fails on back/forward button

### ISSUE THREAD

**Issue by scothiam** [googleads/videojs-ima#110]
Hi, I've noticed that when I load a page, such as https://googleads.github.io/videojs-ima/examples/simple/ then hit the back button, then the forward to come back, the preroll will fail. Any ideas on how to get around that?

tested in Chrome 45, Safari 8, however works in Firefox 38 (with cache disabled...)

Thanks for a great plugin!

**Comment by shawnbuso** [comment]
I tested with the vanilla IMA sample and it looks like this happens in non-videojs implementations as well. I assume it has something to do with browser caching. We'll look into it further to see if there's anything we can do, though I don't know if we'll be able to change this behavior.

**Comment by scothiam** [comment]
Thanks shawn! I also notice that this example is oddly not affected https://googleads.github.io/videojs-ima/examples/iPhone/ ... I'm sifting through trying to find that one difference...

**Comment by shawnbuso** [comment]
If I had to guess I would say that everything in the iPhone example is created dynamically when you click on the video poster, whereas the other examples create the player and plugin at page load.

**Comment by shawnbuso** [comment]
I've opened an issue with the IMA engineering team for this - I'll keep this thread updated with their findings.

**Comment by nandy-andy** [comment]
this issue seem old and forgotten but just FYI @scothiam, you can find some ugly ideas in younger thread: https://groups.google.com/forum/#!topic/ima-sdk/Q6Y56CcXkpk

**Comment by shawnbuso** [comment]
FYI after discussing this with the IMA team we decided that this is a browser issue, not an IMA issue, and as such we will not be able to resolve this. If the underlying browser issue (which relates to how we load the SDK in pieces on the page) is resolved then this issue should resolve itself without any changes needed on our end.
