### ISSUE TITLE
Add Open Measurement APIs

### ISSUE THREAD

**Issue by moeednisardms** [googleads/videojs-ima#1101]
Hi Kiro,

I hope all is well.

We noticed that OMID implementation has been updated. could you please let us know how to pass the OMID now?
below is the previous implementation we had

featureFlags:{'enableOmidBeta': true},
omidMode:{
FULL: [ new RegExp('[.+\.]moatads\.com.$') ]
},

we updated the source files and passing the omidVendorAccess as below, however the access to MOAT is still limited.
omidVendorAccess: {"MOAT":'FULL'},

Test page URL: https://dmscg.com/tech/video/jsplayer/index.html
play the video, and search for OMSDK in the network tab. screenshot: https://prnt.sc/JUCRtJI9dRVY

Thanks

**Comment by Kiro705** [comment]
Hello @moeednisardms ,

I would recommend looking at this [issue thread](https://github.com/googleads/videojs-ima/issues/1063). The code snippet there should help you with your OMID implementation.

Please feel free to re-open that thread, if you have any questions on its contents.

Thank you,
Jackson
IMA SDK team

**Comment by moeednisardms** [comment]
Hi @Kiro705,

Thanks for sharing the issue thread. The issue has been resolved.
