### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by WesleyCarnicl** [googleads/videojs-ima#1103]
Is there a way I can integrate this with WordPress

**Comment by Kiro705** [comment]
Hello @WesleyCarnicl ,

We do not offer any guide specific to integrating this plugin with a WordPress site. However, it should be possible if you have access to the Wordpress template files.

Please let me know if you have any questions about specific aspects of the implementation, but it should be able to use a similar set up you are using to add a videoJS player to your site.

Thank you,
Jackson
IMA SDK team

**Comment by WesleyCarnicl** [comment]
Ok. I have a video player that supports vast but it seems my own ad tag doesn't work and i have in the ad unit the files and creatives

**Comment by WesleyCarnicl** [comment]
and what you mean wordpress template files i know one news site has it on their site and it's wordpress

**Comment by Kiro705** [comment]
Hello @WesleyCarnicl ,

I was looking at [this previous case](https://groups.google.com/g/ima-sdk/c/3hsnt8TmTLs) when asking about the Wordpress template files. I assume they are the files to manually edit code on a Wordpress site.

You can test your ad on the [IMA VSI player](https://googleads.github.io/googleads-ima-html5/vsi/) to determine if the ad tag is set up correctly.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team

**Comment by WesleyCarnicl** [comment]
I have the sdk in my footer.php file which they say put it but then it doesn't show any ads in my video player

**Comment by WesleyCarnicl** [comment]
Yes I was wondering if it was the functions.php file

**Comment by Kiro705** [comment]
Hello @WesleyCarnicl ,

I do not believe the videoJS-IMA plugin uses a functions.php file. Is this something specific to WordPress? Any more information you could share may be helpful.

Thank you,
Jackson
IMA SDK team

**Comment by WesleyCarnicl** [comment]
Yes I am wanting to get it done for my theme so I can run video ads on my site.

Sent from my iPhone

On Jun 27, 2023, at 3:52 PM, Jackson Sui ***@***.***> wrote:

﻿

Hello @WesleyCarnicl<https://github.com/WesleyCarnicl> ,

I do not believe the videoJS-IMA plugin uses a functions.php file. Is this something specific to WordPress? Any more information you could share may be helpful.

Thank you,
Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Hello @WesleyCarnicl ,

I closed this bug for being inactive for over 2 weeks. Was there any additional support you needed for this plugin, or were you able to address the WordPress issue separetly?
