### ISSUE TITLE
Support video.js-8.x ?

### ISSUE THREAD

**Issue by JonasWater** [googleads/videojs-ima#1108]
Hi, can you support video.js-8.x? Thx～

**Comment by Kiro705** [comment]
Hello @JonasWater ,

Thank you for sharing this issue. I will plan to look into this, and see if an update can be made to support video.js-8.x. Preliminary testing does show that this plugin does have issues with video.js v8.3.0.

If you can share an information on what needs to be updated for this support, that may expedite the update process.

Thank you,
Jackson
IMA SDK team

**Comment by JonasWater** [comment]
Okay, please note me when it support video.js-8.x.

Thx~

**Comment by Kiro705** [comment]
Hello @JonasWater ,

The new version (videoJS-IMA v2.2.0+) should now support video.js-8.x.

To do this, you will need to update to videojs-contrib-ads v7.x +.

Please let me know if you have any questions.

**Comment by marcellov7** [comment]
Hello @Kiro705 
I've tested every possible and imaginable version of videojs 8, even the ones you suggest, but from mobile the "skip ad" button can't be pressed, the click goes blank.
Thanks
