### ISSUE TITLE
How to import ima3.js instead of googleapis.com?

### ISSUE THREAD

**Issue by JonasWater** [googleads/videojs-ima#1109]
How to use a third-party CDN or local static to import https://imasdk.googleapis.com/js/sdkloader/ima3.js instead of googleapis.com?
Thx~

PS：When i try to use third-party CDN or local static to import that which will go wrong...

**Comment by Kiro705** [comment]
Hello @JonasWater ,

The IMA SDK requires the SDK be downloaded from the official Google URL (https://imasdk.googleapis.com/js/sdkloader/ima3.js). The SDK team does not offer a work around to avoid this requirement.

Please let me know if you have any additional questions. Another resource for information, general to the IMA SDK, is the [IMA SDK technical forum](https://groups.google.com/g/ima-sdk). This issues queue is specific to the videoJS-IMA plugin.

Thank you,
Jackson
IMA SDK team

**Comment by JonasWater** [comment]
The ima3.js will support with NPM install？

@Kiro705 Thx~

**Comment by Kiro705** [comment]
Hello @JonasWater,

The IMA SDK does not have an NPM module to install. We recommend including a script tag in your html to download the SDK. The this plugin's readme; the [Get started section]([go/ima-h5-audio-poster-doc](http://goto.google.com/ima-h5-audio-poster-doc)), for more details.

Thank you,
Jackson
IMA SDK team

**Comment by JonasWater** [comment]
OK, thx~
