### ISSUE TITLE
How to use videojs-ima with video.core?

### ISSUE THREAD

**Issue by JonasWater** [googleads/videojs-ima#1110]
I want to use videojs-ima in video.core, not in video.js. How to do?

Can you help me? thx

**Comment by Kiro705** [comment]
Hello @JonasWater ,

This plugin is intended to work with the [videoJS player](https://videojs.com/). Can you share any documentation on video.core, as I am not familiar with the player?

Thank you,
Jackson
IMA SDK team

**Comment by JonasWater** [comment]
Thank your reply. Do you have some idea just like this?

Link: 
https://github.com/videojs/videojs-contrib-ads/issues/480

ScreenPhoto:
<img width="882" alt="image" src="https://github.com/googleads/videojs-ima/assets/118031233/fb72468d-bb25-4eca-9c14-a35d05a3351f">

@Kiro705

**Comment by Kiro705** [comment]
Hello @JonasWater,

I do not believe this is supported, since it may break this plugin's stream playback functionality.

You may need to use the standard VideoJS player to use this plugin.

Jackson
IMA SDK team

**Comment by JonasWater** [comment]
OK, thx~
