### ISSUE TITLE
How to reset the binding of events and remove the adDisplayContainer clear、remove ima plugin clear?  

### ISSUE THREAD

**Issue by JonasWater** [googleads/videojs-ima#1112]
Sometimes, when i hit a unknown error, 
i want to reset the binding of events and remove the adDisplayContainer clear、 remove ima plugin clear that allows player events to control without being affected by videojs-ima plugin.

So how to make it? Thx~

**Comment by Kiro705** [comment]
Hello @JonasWater ,

I am a little unclear of what is being asked. If you can share a code sample that reproduces the issue, that may be helpful for finding a fix.

For resetting the IMA SDK, we recommend calling the destroy() methods for the [AdDisplayContainer](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdDisplayContainer#destroy), the [AdsLoader](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsLoader#destroy), and the [AdsManager](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsManager#destroy).

Let me know if you have any questions,

Thank you,
Jackson
IMA SDK team

**Comment by JonasWater** [comment]
Thank for your reply~ @Kiro705 

Okay, the scenario I encountered: When loading the ima plugin fails, I want to remove the ima plugin from the current environment, for example: deregister the plugin and remove all event bindings, because I found that after destroying AdDisplayContainer, AdsLoader, AdsManager, The player's play event is still affected by ima

So is there any way to clear the videojs-ima plugin or IMA SDK?


Thx~

**Comment by Kiro705** [comment]
Hello @JonasWater ,

Do you know if there is an API provided by videoJS to de-register the plugin? I do not think this plugin has a specific method to do so.

Also, do you know what causes the IMA plugin to fail? Fixing that could also resolve your issue.

Thank you,
Jackson
IMA SDK team
