### ISSUE TITLE
How to load ads again auto when change video source src?

### ISSUE THREAD

**Issue by JonasWater** [googleads/videojs-ima#1113]
I found that the ad appears only when the video is loaded for the first time, and when it appears once, if I change the video source src, the ad does not appear again (even though it does a pre-roll check every time).

**So, how to load ads again auto when change video source src?**

Thank for your help~

**Comment by Kiro705** [comment]
Hello @JonasWater ,

I think you will need to make another ad request to have ads load for a new content source. Although, I am not sure this use-case is specifically supported by the plugin, but should still be possible.

If you can share a code snippet to highlight your use-case, and I can help debug the issue from there.

Thank you,
Jackson
IMA SDK team
