### ISSUE TITLE
AdError 400: There was an error playing the video ad. Caused by: Error

### ISSUE THREAD

**Issue by Roz1c** [googleads/videojs-ima#1128]
Issue occurs randomly (~50/50) on Philips Android TV (Android 9, Chrome 119) where I'm running my web app in webview.
```log
[INFO:CONSOLE(1)] "Ad error: AdError 400: There was an error playing the video ad. Caused by: Error: Error: There was an error playing the video ad."
[INFO:CONSOLE(1)] "VIDEOJS: adserror (Preroll)"
[INFO:CONSOLE(1)] "VIDEOJS: ADS: resumeAfterNoPreroll: attempting to resume playback (Preroll)"
```

```js
player.src(source);

player.ready(function () {
    player.ima({
        adTagUrl: "https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_preroll_skippable&sz=640x480&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",
        disableAdControls: true,
        adLabel: "",
        showControlsForJSAds: false,
        contribAdsSettings: {
            debug: true,
        },
        debug: true
   });

   player.play();
}
```

"video.js": "^8.6.1",
"videojs-contrib-ads": "^7.3.2",
"videojs-ima": "^2.2.0",

**Comment by Kiro705** [comment]
Hello @Roz1c ,

Thank you for raising this issue. This plugin does not explicitly support connected TVs. Some features may work, but others may not. If you are able to reproduce the issue in a web environment, please add steps here, and I can take a look at a fix for the issue.

I would recommend not using this plugin, and following the [IMA HTML5 getting started guide](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side) for a IMA integration that is more customizable for your specific platforms.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
