### ISSUE TITLE
Setting currentTime before preroll completes causes to skip ad

### ISSUE THREAD

**Issue by Roz1c** [googleads/videojs-ima#1130]
I'm implementing continue watching feature along preroll. Problem that I'm facing with this library is that on some android TV devices, setting currentTime before preroll completes actually sets the time of ad player so the ad is skipped. But if I set currentTime after the ad completes, the player first shows the first frame of video, and then shifts to where I set currentTime. Is there any known ways around this?

**Comment by Kiro705** [comment]
Hello @Roz1c ,

Do you know if this is reproducible in a web environment? If so could you provide some steps to reproduce the issue?

Otherwise, if it is only reproducible on Android TVs, the plugin may be unable to support this specific feature.

Thank you,
Jackson
IMA SDK team
