### ISSUE TITLE
VAST wrapper / waterfalling issue: feeds in waterfall skipped

### ISSUE THREAD

**Issue by arifje** [googleads/videojs-ima#1132]
We're using a simple wrapper to create a waterfall with multiple VAST feeds of different suppliers. For unknown reasons some feeds are ignored (and skipped), giving the impression that there's no response or valid ad in this feed. But, there is. When we test the feeds outside of the wrapper, or using them directly on the player, they always return a valid response or ad.

Example of the wrapper:

```
<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
<Ad>
	<Wrapper fallbackOnNoAd="true">
		<AdSystem>1</AdSystem>
		<Error><![CDATA[https://error-pixel?[ERRORCODE] ]]></Error>
		<VASTAdTagURI>
			<![CDATA[ https://cdnzone.nuevodevel.com/pub/5.0/vast2.xml ]]>
		</VASTAdTagURI>
		<Extensions>
			<Extension type="waterfall" fallback_index="0"/>
		</Extensions>
	</Wrapper>
</Ad>
<Ad>
	<Wrapper fallbackOnNoAd="true">
		<AdSystem>2</AdSystem>
		<Error><![CDATA[ https://error-pixel?[ERRORCODE] ]]></Error>
		<VASTAdTagURI>
			<![CDATA[ https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator= ]]>
		</VASTAdTagURI>
		<Extensions>
			<Extension type="waterfall" fallback_index="1"/>
		</Extensions>
	</Wrapper>
</Ad>
</VAST>
```

Feed 1: https://cdnzone.nuevodevel.com/pub/5.0/vast2.xml (from Nuevo plugin)
Feed 2: https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

Both feeds work and return an ad when testing via: https://adplayer.pro/developer/vast_inspector or https://googleads.github.io/googleads-ima-html5/vsi/ 

When testing the wrapper feed, there's a difference: adplayer inspector works, shows the ad of the first feed in the wrapper. But the IMA HTML5 Video Suite Inspector alsways skips the first feed, showing only the second feed (Google test ad).

Have been testing it with latest release of video-js, videojs-ima and videojs-contrib-ads. Also tested on older versions, make no difference.

Edit: when I replace the first feed with another (random) test vast feed, this one seem to work: https://glomex.github.io/vast-ima-player/linear-ad.xml - the question is: why is this one working, but the other one isn't?

**Comment by Kiro705** [comment]
Hello @arifje ,

This issues queue is specific to the videoJS-IMA plugin. If the issue is reproducible in the IMA VSI player, it is likely an issue with the IMA SDK, and not specific to this plugin.

If possible could you raise this issue to the [IMA SDK technical forum](https://groups.google.com/g/ima-sdk). That will be the best way to get fixes for the IMA SDK.

Thank you,
Jackson
IMA SDK team
