### ISSUE TITLE
access to the iframe for HAI reporting?

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#1134]
is there anyway to get acces to the iframe that is created so as we can get/ send reports for any HAI triggers.  I can see a div with id="adysisPlayer_ima-ad-container"  which is "constant" but the ima iframe sends a "random" variable/ id on the end on each load

**Comment by Kiro705** [comment]
Hello @spormeon ,

As far as I know, IMA does not provide any APIs for accessing the iframe, which I think is by design. Can you share any documentation on HAI triggers, since there may be other ways to support this?

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
hi @Kiro705 
these are a couple of "docs" 
https://developer.chrome.com/blog/heavy-ad-interventions
https://github.com/johnivdel/heavy-ad-intervention

we have already tried the methods mentioned for the "Reporting API", and you just cant seem to "pick anything up" as everything seems to be happening inside the https://imasdk.googleapis.com/js/core/bridge3.613.0_en.html#goog_367038471 iframe, so no "report" is ever fired in console "Application" > background services> Reporting API tab window

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/googleads/videojs-ima/assets/8503167/6afdfaa3-9388-42eb-b3ed-850893447407)

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/googleads/videojs-ima/assets/8503167/39fa04a1-76fd-4aaa-bf1d-9c62bec5f471)


we have also tried to "sniff/ look out for" for the "heavy ad intervention" element, which appears when its "triggered" but can't get to that because its in the iframe ( at least with the methods we are trying)

![DevTools_-_cdn_adysis_com_VideoDemo_DemoSite_pages_playlistUIverticalAmazonParallelReBid_html](https://github.com/googleads/videojs-ima/assets/8503167/c78036df-2840-4de6-9151-40fd2e3a5804)


so , we are stumped as these reports are ment to be availabe to send , but just cant get to them

**Comment by Kiro705** [comment]
Hello @spormeon ,

It is my understanding that the IMA SDK handles its own heavy ads detection, and will error out for ads the are detected this way. Publishers should not need to take additional steps to support this.

The iframe architecture is not specific to the videoJS-IMA plugin, but part of the IMA HTML5 SDK. If you have more questions about the functionality of the IMA SDK, I would recommend reaching out on the [IMA HTML5 technical forum](https://groups.google.com/g/ima-sdk).

Thank you,
Jackson
IMA SDK team

**Comment by spormeon** [comment]
ok, will do
