### ISSUE TITLE
use fluid and aspectRatio option with videojs-ima it is display wrong position

### ISSUE THREAD

**Issue by OSS98** [googleads/videojs-ima#1135]
when i use fluid option with videojs-ima it is display wrong position

this fluid and aspectRatio option that i set up
<img width="329" alt="image" src="https://github.com/googleads/videojs-ima/assets/53668180/fe22dd55-0f3c-460b-b227-b4897e1262ce">

the ima ads is on under of my video component  
<img width="649" alt="image" src="https://github.com/googleads/videojs-ima/assets/53668180/b0fafc3a-dc23-4440-a0c2-e1bfda1d1239">

how can i fix this issue?

**Comment by Kiro705** [comment]
Hello @OSS98 ,

Thank you for raising this issue. Would you be able to share more details on exactly how to reproduce the issue? I tried adding the highlighted options, but did not see the same behavior:

```
fluid: true,
aspectRatio: '16:9',
```

I would recommend taking one of the [demo apps](https://github.com/googleads/videojs-ima/tree/main/examples), then listing all changes needed to reproduce the issue.

Thank you,
Jackson
IMA SDK team
