### ISSUE TITLE
Skippable Ad is not clickable on IOS with custom control bar height

### ISSUE THREAD

**Issue by nochev** [googleads/videojs-ima#1144]
Hello all,

I have player with custom control bar height and noticed that on IOS it overlaps `Skip Ad` button. Is there any way to control the position of that button or whole ad container? Here is how it looks like
![image](https://github.com/googleads/videojs-ima/assets/1902089/fd17105a-5933-4be8-a088-c877ba516a42)

Any help is appreciated.

Thanks in advance

**Comment by Kiro705** [comment]
Hello @nochev ,

I think the Ad UI is set to fit within the adDisplayContainer which is created to match the size of the video player. You may need to set the disableCustomPlaybackForIOS10Plus [additional setting](https://github.com/googleads/videojs-ima?tab=readme-ov-file#additional-settings) on iOS. A custom control bar should not overlay the skip button or ad choices icon to remain Google Ad Manager policy compliant.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
