### ISSUE TITLE
Videojs IMA SDK mute icon not updating when  videojs.ima.getAdsManager().setVolume(1)

### ISSUE THREAD

**Issue by sunilstg** [googleads/videojs-ima#1145]
Hi Everyone, I have added taptounmute on overlay of videojs ima sdk and when user click on it, I am changing the volume using below methods then ima sdk ads controlbar mute icon not updating to volume icon and volume slider baar is also not updating. Can you please check below comnmand and advise how to change the mute icon to volume icon when set volume to 1 in below process - 

myvideoplayer.ima.getAdsManager().setVolume(1);
myvideoplayer.muted(false);
myvideoplayer.volume(1); (edited) 

Best regards,
Sunil Kumar

**Comment by Kiro705** [comment]
Hello @sunilstg ,

I don't think there was a simple function built into this plugin to allow updating the volume with a button press. However, it should be able to work if your button calls the following:

```
myvideoplayer.ima.controller.setVolume(1);
myvideoplayer.ima.controller.onPlayerVolumeChanged(1);
```

This should unmute both content and ads, and update the UI accordingly.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
