### ISSUE TITLE
I want to show m3u8 file as a VAST tag media source.

### ISSUE THREAD

**Issue by pavelsust** [googleads/videojs-ima#1154]
I want to play m3u8 media file as a VAST ads source. But When I want to play it shows a error that is Non-fatal error occurred: Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

Playing mp4 file is so costly for me. So I want to show m3u8 url for media source can you help me? I am using video.js as a player.

**Comment by Kiro705** [comment]
Hello @pavelsust ,

You should use [AdsRenderingSettings.mimeTypes](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRenderingSettings#mimeTypes) to set the media types your player supports.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
