### ISSUE TITLE
How can I play content with DAI and preroll Content in Video JS and React JS

### ISSUE THREAD

**Issue by ashishdiwedi7600** [googleads/videojs-ima#1155]
I have content, in which I have to play pre-roll ads first and then I have to play the DAI content, But I am not sure how to achieve this, this is working using HLS but not working with video.js.

**I am using video js and Google IMA SDK for this task**
`"video.js": "^7.20.1"
"videojs-ima": "^2.1.0",
"videojs-contrib-ads": "^6.9.0",`

I  would be grateful if any suggestions can be provided on this

I have tried adding both with the video js player object but am getting an error as added in the attachment.

Sample Data used :-
daiKey: "c-rArva4ShKVIAkNfy6HUQ",
adTagUrl: "https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=",

<img width="953" alt="jtBHQxwF" src="https://github.com/user-attachments/assets/89919d07-ee2c-431e-b9f8-9a3665a0f78e">

**Comment by Kiro705** [comment]
Hello @ashishdiwedi7600 ,

The IMA SDK supports this by using both the client-side and DAI HTML5 SDKs. You can see more info in the [IMA Live stream pre-fetch guide](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/live-stream). Using both client-side and DAI SDKs simultaneously is not currently supported by this videoJS-IMA plugin. The work-around for this would be to not use the plugin, and implement a [typical DAI integration](https://developers.google.com/ad-manager/dynamic-ad-insertion/sdk/html5?service=full), with [Live stream pre-fetch](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/live-stream).

Please let me know if you have any questions.

Thank you,
Jackson
IMA SDK team
