### ISSUE TITLE
Multiple VideoJS Instances on One Page

### ISSUE THREAD

**Issue by kjanoudi** [googleads/videojs-ima#116]
Hello,

My usage of videojs involves having multiple instances of a videojs player on a single page. When I use videojs-ima, it generates one container as a child of each videojs player's parent div element. The issue is that all the containers and elements generated by videojs-ima are using the same id, causing problems with CSS selectors and errors in the DOM. 

Would you be open to a pull request that includes the id of the videojs player element as a postfix/prefix of the id of the ad containers? Or perhaps a PR that uses classnames rather than IDs for the elements created by videojs-ima?

Any other solutions?

Thanks

**Comment by shawnbuso** [comment]
Hi there,

I think your first solution would be the best - we'd definitely be open to pull requests to solve this issue. When you have something ready, be sure to look through our [Contributing doc](https://github.com/googleads/videojs-ima/blob/master/CONTRIBUTING.md) to make sure you have the required agreements signed.

Thanks,
Shawn

**Comment by kjanoudi** [comment]
@shawnbuso I have submitted the paperwork for the contributing doc. 

Related to this issue - I failed to account for styling when suggesting that we use solely unique id's on the elements. There needs to be a combination of both (adding classnames to the elements, as well as using unique ids) in order for the IMA plugin to function as expected. Currently if we simply change to using unique IDs, the styling from the css will no longer be valid.

I'll attempt to account for these issues and submit a pull request

**Comment by mimse** [comment]
Hi @kjanoudi, any updates on your PR ?

**Comment by kjanoudi** [comment]
@mimse I actually no longed needed to use several instances on one page, sorry, so i never finished off the PR work.

**Comment by jamesgorrie** [comment]
@kjanoudi Did you make any headway on it that you could share?

**Comment by kjanoudi** [comment]
@jamesgorrie see my last comment, sorry!

**Comment by jamesgorrie** [comment]
> so i never __finished__ off the PR work

I was wondering if you had any of the progress that you made to share - that could be super useful.

**Comment by mimse** [comment]
@jamesgorrie 

You can have a look this branch

https://github.com/tv2/videojs-ima/tree/fix_for_multiple_instances

We are using it in production, and I have made a pull request, but it still missing a bit to get accepted. I have not had the time to correct the changes needed.

**Comment by ehoch** [comment]
@jamesgorrie @mimse @shawnbuso 

Has there been any progress on getting this PR merged in? We definitely need this resolved ASAP and would be willing to help fund the work to fix this even.

**Comment by shawnbuso** [comment]
I think my last comment on the PR is still accurate - the way the changes were made makes the diff tool think *everything* has been changed, so I can't really do a review.

**Comment by Cosrnos** [comment]
Fixed in #253. Let me know if you're still having trouble!

**Comment by shawnbuso** [comment]
Do you have a test page set up to verify 2 player support? I tried testing it out by modifying our simple sample to add another player, but initializing a second player breaks the first player for me - it looks like the ad request times out and I just go straight to content.

**Comment by Cosrnos** [comment]
@shawnbuso The issue in the example you highlighted is actually related to a different problem with the library in relation to using the same adTagUrl for two instances of the adsLoader. In order to use the same URL twice you need to destroy the first adsLoader instance and initialize another. This could be solved by dynamically generating the adsLoader and destroying the instance once the preroll is done, but I believe the recommended setup is to have another adTagUrl for the second player.

**Comment by shawnbuso** [comment]
@Cosrnos I'm testing with 2 different ad tags already and seeing the same issue :/ Also that issue should only occur if you *request* the same ad twice - I'm seeing issue without even trying to request the second ad, just initializing the player.

**Comment by ehoch** [comment]
@shawnbuso Are you using two different ids for the VideoJS players? I'm actually using this code right now (I actually put @Cosrnos up to this) and it's working for me.

**Comment by shawnbuso** [comment]
Yea I pushed my test code [here](https://github.com/shawnbuso/videojs-ima/tree/2player/examples/simple). Using 2 different player IDs and 2 different test tags. When I have two players on the page I'm able to play the second one but the first times out. The code for each player works on its own, they just don't work together.

**Comment by Cosrnos** [comment]
@shawnbuso I'll dig into this a bit later this evening and let you know what I find!

**Comment by mimse** [comment]
@shawnbuso @cosrnos @ehoch

I have a new merge request i´ll submit tomorrow. It has fewer changes and @shawnbuso should be able to merge it.

**Comment by mimse** [comment]
@shawnbuso @Cosrnos @ehoch 

Please take a look at #255
