### ISSUE TITLE
ClearInterval Should be Called When Player is Disposed

### ISSUE THREAD

**Issue by kjanoudi** [googleads/videojs-ima#118]
Intervals are currently only cleared on 'ended', per https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L988

```player.on('ended', localContentEndedListener);```

https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L953

I believe it would be best if they were also cleared when a player is disposed. If they are not cleared, the result is javascript errors regarding null or undefined elements attempting to be accessed. I will be submitting a pull request with this patch shortly.

**Comment by shawnbuso** [comment]
Do we have a concrete way to determine when the player is "disposed"? I noticed in your (now closed) pull request that you were trying to listen to a "dispose" event but I'm not seeing that in the video.js API docs. Clearing the intervals is trivial if we can reliably determine when the player has been disposed of.

**Comment by jgubman** [comment]
It's in the Player documentation:
http://docs.videojs.com/docs/api/player.html#Methodsdispose

I'd like this feature too, our site's content is ajax loaded -- clicking on a link just replaces everything inside the body tag, so the listener events don't get cleared out on new requests.

**Comment by kjanoudi** [comment]
@jgubman @shawnbuso while it isn't actually seen in the API for videojs, the player does in fact call a 'dispose' event when it is disposed. The relevant lines are here: https://github.com/videojs/video.js/blob/master/src/js/player.js#L236

**Comment by kjanoudi** [comment]
I've reopened my PR here: https://github.com/googleads/videojs-ima/pull/119/files

Please note this is untested with videojs 5, as we have not integrated ads into our videojs 5 version.
