### ISSUE TITLE
Support for Video.js 5

### ISSUE THREAD

**Issue by dguiley** [googleads/videojs-ima#122]
Is there an ETA for videojs 5 support?

Thanks.

**Comment by shawnbuso** [comment]
No ETA yet but we'll be testing to see if everything works as expected. It looks like the plugin we use, videojs-contrib-ads, still only supports up to 4.12.4.

**Comment by dguiley** [comment]
Thanks Shawn.

**Comment by TixxyTAM** [comment]
Hey Shawn videojs-contrib-ads has an upgrade for vjs 5...
I'v tested vjs ima with that... but it's not working...
I want to know whether you are willing to add support for vjs5

**Comment by dguiley** [comment]
Very interested in this, as we are working on bugs that may go away with vjs5. 

Best. 
-- Dathan

**Comment by TixxyTAM** [comment]
It just have some css issues when using with vjs5 and videojs-contrib-ads vjs5 upgrade.  I'v managed to fix them manually... now it works fine ... I don't see any other issues...

**Comment by shawnbuso** [comment]
Did a quick test and the ads plugin we use is erroring with VJS 5. This is a KI on their end, will hopefully be resolved once https://github.com/videojs/videojs-contrib-ads/pull/121 is finalized.

**Comment by shawnbuso** [comment]
Blocked by https://github.com/videojs/videojs-contrib-ads/pull/121

**Comment by dacast** [comment]
any update with videojs-contrib-ads 3.1 ?
It still does not seems to work.

**Comment by akestner** [comment]
+1 on an update as well.  Seems that https://github.com/videojs/videojs-contrib-ads/pull/121 has been merged.

**Comment by shawnbuso** [comment]
Still working on this one but seeing errors from the latest contrib ads plugin. Blocked on videojs/videojs-contrib-ads/issues/139

**Comment by jmccraw** [comment]
I had that issue, too. I think I solved by upgrading to a more recent version of Videojs (I used 5.4.4). The version in the example didn't have the `$` method for query selectors.
