### ISSUE TITLE
VPAID 2.0 built with IMA fails to load in IMA Plugin based player in Android Chrome

### ISSUE THREAD

**Issue by zrehmani** [googleads/videojs-ima#123]
I have built a VPAID 2.0 that uses IMA SDK to play an ad.  When this VPAID is loaded inside a player built with VJS + IMA Plugin - it fails to load the video on Android 4.4.2 / Chrome 40.0.2214.109 and Android 4.2.2 / Chrome 34.0.1847.114.  It works everywhere else - tested on iOS 9.02 and iOS 8.3 and all desktop browser tests are successful.  It fails to load the ad media file in two Android devices mentioned.  It used to work even on these devices - something happened this month and it has stopped working now.

Here is a link that is using the iPhone example from the example set of this project to load the VPAID JS.  
http://dev.testing.optimatic.com/tests/optivpaid/gima-fix/

The link has detail console output.  Screenshot of error attached.  I have tried a few things but nothing is working.  I hope you can look at it and see what's going on and guide me in the right direction.  Not sure if its a bug in IMA SDK or IMA Plugin for VJS or bug in my VPAID set up.  Thanks!

![screen shot 2015-10-13 at 3 45 40 pm](https://cloud.githubusercontent.com/assets/266330/10466299/9ce76452-71c1-11e5-8d38-b1ce1f3537e9.png)

**Comment by shawnbuso** [comment]
Which version of our sample is your implementation based on? I'm seeing the issue you described on your page, but when I tested your tag with our [latest sample](http://googleads.github.io/videojs-ima/examples/advanced/) it did work for me.

**Comment by zrehmani** [comment]
Thanks Shawn for your help.  Unfortunately I am not seeing it play even when I plug in the tag in the latest sample url you have given.  On Android 4.4.2 / Chrome 40.0.2214 - even the sample tag does not load.  They both give the ad timedout error.  On Android 4.2.2/Chrome 34.0.1847 - sample tag works and my vpaid tag simply hangs at onContentPauseRequested handler.  Media file is added to the video element but it doesn't play it and then times out (I have added a very long timeout to IMA to help troubleshoot).  One thing I did notice is that on iOS devices - IMA SDK uses the content video element to play the ad (unlike on desktop) but on Android - it still tries to play the ad in its own video element (like desktop).  Any help is much appreciated!

**Comment by zrehmani** [comment]
This is the console log showing where its hanging...

![screen shot 2015-11-12 at 11 30 49 am](https://cloud.githubusercontent.com/assets/266330/11124045/df9c9e08-8930-11e5-8632-1d86497efd8a.png)

Here you can see that the vpaidjs is loaded and the IMA SDK has plugged in the media file in its own video player on Android... rather than the content video element passed by the user and custom playback is false even though its turned on.  It works as expected on iOS devices.

![screen shot 2015-11-12 at 11 32 31 am](https://cloud.githubusercontent.com/assets/266330/11124114/48da0ce8-8931-11e5-96d3-f9d3289f48e2.png)

**Comment by zrehmani** [comment]
This is my vpaid tag: http://dev.testing.optimatic.com/optivpaid/examples/vpaid/outputXML.ashx?f=optimatic-vpaid.xml

**Comment by shawnbuso** [comment]
The differences in playback you're seeing are expected (content video element on iPhone but dedicated ad player on Android). Are you still seeing this same issue? I'm now seeing the ad load but it never gets around to playing, and I get "Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture." in the console.

I'm also a bit confused by your use case - you said you have a VPAID ad that uses IMA to play an ad, but you're then putting that into the video.js player with the IMA plugin. So you're using IMA to request an ad that in turn uses IMA to request another ad?

**Comment by shawnbuso** [comment]
Closing for lack of response. If this is still an issue please feel free to re-open.
