### ISSUE TITLE
VPAID not working

### ISSUE THREAD

**Issue by tcctmw** [googleads/videojs-ima#128]
I'm trying to use the plugin with this valid adTagUrl:

https://ima3vpaid.appspot.com/?adTagUrl=https%3A%2F%2Fgoogleads.g.doubleclick.net%2Fpagead%2Fads%3Fclient%3Dca-video-pub-9154529747663279%26slotname%3D9817278932%26ad_type%3Dvideo%26description_url%3Dhttp%3A%2F%2Fgoogleads.github.io%2Fvideojs-ima%2Fexamples%2Fadvanced%2F%26max_ad_duration%3D15000%26sdmax%3D30000%26videoad_start_delay%3D0&type=js

On the Advanced Demo page:
http://googleads.github.io/videojs-ima/examples/advanced/

When the tag doesn't erogate nothing the player keeps stuck in a black screen and doesn't reproduce the content video

In a test page, I'm trying to catch the "adserror" event but it doesn't seem to be launched in this scenario

**Comment by shawnbuso** [comment]
Is there a particular browser and/or operating system on which you're seeing this error? I'm seeing the ad  play fine on my end. Using Chrome on Ubuntu.

**Comment by tcctmw** [comment]
Chrome and Firefox on Windows

Try viewing the ad at least 10 times. After some erogation anything is displayed

**Comment by shawnbuso** [comment]
I was able to view the ad 15 times without error. I noticed I'm getting a different ad almost every time. My guess is that one of the ads being returned to your VPAID has an error, and if that happens to serve it causes the problem. Do you have a more reliable way to repro the error?

**Comment by tcctmw** [comment]
In the Javascript console, when the problem occurs, I'm able to get this GET request:

https://googleads.g.doubleclick.net/pagead/ads?sdkv=h.3.112.0&sdki=5&video_product_type=0&correlator=1329278984283619&client=ca-video-pub-9154529747663279&url=http%3A%2F%2Fimasdk.googleapis.com%2Fjs%2Fcore%2Fbridge3.112.0_en.html&adk=2064120704&num_ads=1&channel=vpaidadp_html5&ad_type=video&output=xml_vast3&flash=19.0.0&sz=640x360&adsafe=high&hl=it&slotname=9817278932&u_tz=60&u_his=1&u_java=true&u_h=1080&u_w=1920&u_ah=1040&u_aw=1920&u_cd=24&u_nplug=11&u_nmime=65&dt=1447343691839&unviewed_position_start=1&videoad_start_delay=0&osd=2&frm=2&video_format=43&t_pyv=exclude&min_ad_duration=0&max_ad_duration=16500&sdmax=33000&ca_type=flash&description_url=http%3A%2F%2Fgoogleads.github.io%2Fvideojs-ima%2Fexamples%2Fadvanced%2F&ref=http%3A%2F%2Fimasdk.googleapis.com%2Fjs%2Fcore%2Fbridge3.112.0_en.html&ged=ta1_ve3_pt0.0.u_td0_tt0_pd0_bs10_tv1_is2_er0.0.155.300_sv2_sp1_vi0.0.360.640_vp100_ct1_vb1_vl1_vr1_eb24171

With this simple response:
<?xml version="1.0" encoding="UTF-8"?>
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0"/>

When something similar occurs shouldn't be triggered the "adserror" event?
![screenshot-1](https://cloud.githubusercontent.com/assets/15816987/11123209/f5c762de-895e-11e5-9b14-aba925e4c6cc.png)

**Comment by shawnbuso** [comment]
It looks like the VPAID ad is requesting another ad to play, and in some cases that ad request comes back empty. When it comes back empty, the ad should fire an error so the SDK knows to play content, but I don't think it's doing that. Do you have a support contact for that particular VPAID ad to whom you could reach out to get debugging help?

**Comment by tcctmw** [comment]
The tag is the one provided by AdExchange.

**Comment by shawnbuso** [comment]
OK so it looks like what you're running into may be a bug, and we're working on that, but we can also avoid this scenario altogether. The tag you're using is for something called the "VPAID adapter", which is intended to be used in video players that support VPAID ads but *do not have an IMA SDK implementation*. The video.js plugin for IMA gives you an IMA implementation, so you should be able to use the tag directly instead of through the VPAID adapter. When you get your tag from AdExchange, you should see an option under Technology for "Direct SDK" instead of "IMA Adapter". Try using the tag you get by selecting "Direct SDK" - that should work.

**Comment by tcctmw** [comment]
It seems to work with this tag:
https://googleads.g.doubleclick.net/pagead/ads?client=ca-video-pub-9154529747663279&slotname=9817278932&ad_type=video&description_url=http%3A%2F%2Fgoogleads.github.io%2Fvideojs-ima%2Fexamples%2Fadvanced%2F

I'll test it more to be sure.

BUT
After the ad loading, the video content is started in any case ( ad started or ad error ).
How can I set the autoplay only if the ad is really erogated?

**Comment by shawnbuso** [comment]
Are you seeing this on our [official sample](http://googleads.github.io/videojs-ima/examples/advanced/)? If so, which browser and OS are you using? My tests show the ad play and the content start *after* the ad, not right away.

**Comment by tcctmw** [comment]
Yes, I said that badly.. The player behave exactly like you describe

The behavior I'd like to create is to pause (or better reset) the player if there isn't any ads or the ads throw an error

The player should be autostart only in case everything is ok

**Comment by shawnbuso** [comment]
Ah ok I see what you're saying. This behavior is somewhat baked into the contrib-ads plugin that we use as it's standard practice to let a user watch your video even if the ad fails. When the ads error, we fire the 'aderror' event, which tells the plugin to resume content. If we just skip firing that event, that will trigger a timeout on the contrib-ads plugin, which will also lead to content playing. [I've followed up with the contrib-ads folks to see if there's a way around this.](https://github.com/videojs/videojs-contrib-ads/issues/130)

**Comment by tcctmw** [comment]
Thank you very much

**Comment by shawnbuso** [comment]
Closing since the blocking contrib-ads issue was closed.
