### ISSUE TITLE
VAST 2 Aderror 303 and 403

### ISSUE THREAD

**Issue by riccardobevilacqua** [googleads/videojs-ima#129]
Scenario:
- Vast 2
- No VPAID
- VideoJS 4.7.1
- VideoJS ads 2.2.1

I get Aderror 303, ad skipped and content reproduced.

Scenario:
- Vast 2
- No VPAID
- VideoJS 5+ (5.2.4)
- VideoJS ads 3.1.0

I get Aderror 303 with some sources, Aderror 403 with other sources, ad skipped and content reproduced.

Any hints, please?

**Comment by shawnbuso** [comment]
Hi there,

Could you try reproducing with your tags in our [sample page](http://googleads.github.io/videojs-ima/examples/advanced/) and let us know if you see the same issue there? If so, could you share your tags with us? If not, do you have a page we can look at to see your implementation?

Thanks,
Shawn

**Comment by riccardobevilacqua** [comment]
This turned out to be a provider issue, not a plugin issue.
