### ISSUE TITLE
Click through not working on iPhone example

### ISSUE THREAD

**Issue by Avien** [googleads/videojs-ima#131]
Am I not suppose to redirect to an advertiser URL once pressing the "Done" button on the full screen video?
Nothing happens, in fact the video even resumes automatically if I touch it again
Is it an iOS 9 issue? 
or maybe I am misunderstanding how it works?

Thanks

**Comment by shawnbuso** [comment]
Clicking "Done" should just take the user back to your page, not to the ad's clickthrough URL. Right now our recommended solution for clickthrough is to traffic a companion that users can click on to get to the landing page (see the iPhone example). We're also working on supporting custom click tracking, but that's a bigger investment.

**Comment by Avien** [comment]
Got it, thanks!

Any idea on how to show a poster image of the 1st second of the pre roll video retrieved from the VAST?

**Comment by shawnbuso** [comment]
Currently I don't think that's possible - we only load the pre-roll once you tell us to play it, and we don't expose the URL for you to fetch yourself.

**Comment by Avien** [comment]
If I had that URL I could load it in the content video dynamically and then set its current time to 1 second, save the original video and replace it back once played
Are you sure there is no way to get the MediaFile from the VAST xml schema somehow?

**Comment by shawnbuso** [comment]
Is this specific to iPhone? If so there's no way to do what you're asking because iPhone requires all video to be loaded as the result of a user action (like a click or a tap) - if you just put the video in the player and tell it to load without the user doing something to make that happen, it will fail to load. On top of that, iPhone plays all video in it's fullscreen player, so when you try to start the video to get the poster image your users will see the full screen player launch.

**Comment by Avien** [comment]
iPhone is exactly my problem:
I need to show some poster image of an unknown advertiser video and this is why I am looking for a workaround
I am using the touch event to bind a loadedmetadata event called on player.load() to play the ad and its working (assuming the video is placed somewhere in the middle of the page)

So I have the event, I have the initializeAdDisplayContainer() and requestAds() already called
I dont need to play the video, but only to set its current time once I load it in the src of the content video
The only question is: how do I get the VASt media files? 
Cant I get a callback from the ads manager with any resources loaded?
Maybe I will load it via xhr seperatly and use xml parser...yuck! reminds me old times (10 years ago)

**Comment by shawnbuso** [comment]
Ah ok I see what you are asking. So the short answer is no, we will not give you a direct URL to the ad asset. That's currently not supported by the IMA SDK, which our plugin uses under the hood.

**Comment by Avien** [comment]
Thanks for you time!
