### ISSUE TITLE
Width 100%

### ISSUE THREAD

**Issue by riccardobevilacqua** [googleads/videojs-ima#132]
Is there a way to set width 100%?
Tuning CSS I'm able to achieve this for videojs (v5.4.4), but it doesn't look to be possible for ads reproduction through videojs ima.

**Comment by shawnbuso** [comment]
Currently the ad plugin just grabs the video player width and height at initialization and uses that. If you want to change the ad size after initialization, you can use getAdsManager to get a handle to the AdsManager, then [resize](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManager.resize) to set the size. IMA doesn't support percentage dimensions, though, only pixel values.

**Comment by riccardobevilacqua** [comment]
I solve this way:
```
.video-wrapper #video #ima-ad-container,
.video-wrapper #video #ima-ad-container > div:first-child,
.video-wrapper #video #ima-ad-container iframe {
position: absolute !important;
width:100% !important;
top: 0 !important;
left: 0 !important;
}
```
It's far from being optimal, but it works so far.
