### ISSUE TITLE
iOS Blocked a frame with origin

### ISSUE THREAD

**Issue by riccardobevilacqua** [googleads/videojs-ima#134]
I suddenly got this error message on Safari Mobile (iOS 8.3):
Blocked a frame with origin "http://imasdk.googleapis.com" from accessing a frame [...]

The player is completely unable to play neither adv nor video content.

I tried to load ima3.js from my domain, but I got another error message alerting I'm not allowed to load ima3.js outside a google domain.

Any hint, please?

Edit: I checked out my adv source, it is a regular VAST, not some random html, and it works on Chrome.

**Comment by shawnbuso** [comment]
Are you seeing this with our [sample](http://googleads.github.io/videojs-ima/examples/iPhone/) as well? If not can you provide a link to a test page that we could use to replicate the issue?

**Comment by riccardobevilacqua** [comment]
I can't provide a test page.

I tried using this additional settings with no luck:
```
adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
        'iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&' +
        'gdfp_req=1&env=vp&output=xml_vast2&unviewed_position_start=1&' +
        'cust_params=sample_ct%3Dlinear%26deployment%3Dgmf-js&correlator=',
nativeControlsForTouch: false
```

I provided dimensions through js for some reasons, I tried providing them as html attributes just like any other setting, but it didn't work.

**Comment by riccardobevilacqua** [comment]
It works using videojs 4.12 and videojs.ads version used in the google sample.
The error keeps popping in the console, but adv reproduction and video content reproduction work anyway.

**Comment by tuancn** [comment]
Hi @shawnbuso 
I've encountered the error same as @riccardobevilacqua when I've updating to videojs-ima (0.3.0). So I played the link: https://googleads.github.io/videojs-ima/examples/advanced/ on Safari Mobile (iOS 9.2) then I got this error message: Blocked a frame with origin "http://imasdk.googleapis.com" from accessing a frame with origin "http://googleads.github.io". Protocols, domains, and ports must match.

Please check it, thank you very much.

TuanCN

**Comment by shawnbuso** [comment]
We've been having problems with the non-iPhone samples on mobile since the most recent video.js update. Are you seeing the same issue with the iPhone sample?

**Comment by tuancn** [comment]
No, iPhone sample is ok on Safari (iOS 9.2).

TuanCN

**Comment by shawnbuso** [comment]
Closing since this looks to be an issue with the non-iPhone samples on mobile (#142). If the problem persists on the iPhone sample feel free to re-open.

**Comment by amatigianc** [comment]
Hi @shawnbuso, 

I have tested your sample page on iOS 9.2 iPhone 6 simulator and I see the same  error message: 
Blocked a frame with origin "http://imasdk.googleapis.com" from accessing a frame with origin "http://googleads.github.io". Protocols, domains, and ports must match.

I cannot see the advert, but I can see the video playback. This is my sample page where I used a very basic adTag url from Google website.

http://cs1.brightcodes.net/gamati/test/RingierAG/testRingierAG_iOS.html

Would you be able to look into it?

Best, 
GC

**Comment by shawnbuso** [comment]
Hi there,

Are you using the iPhone sample to test? We're still seeing the same issue as above on all the non-iPhone samples.

Thanks,
Shawn
