### ISSUE TITLE
AdError 402: VAST media file loading reached a timeout

### ISSUE THREAD

**Issue by riccardobevilacqua** [googleads/videojs-ima#136]
With VideoJS 4.12 and latest version of videojs-ima on Android Chrome mobile I get this error:
```
Ad error: AdError 402: VAST media file loading reached a timeout of 15 seconds.
```

Adv can't be played, video content is available only when timeout expires, and it requires another tap to play.

I tried extending the timeout but this bug still occurs.

Same configuration works on iOS.

Any hints, please?

**Comment by aydinkn** [comment]
Hi,
You must initialize videojs-ima with user action (e.g click or tab events) on mobile. If you don't, Android browsers not play video adsense and fired timeout event.

For example:
```
        var initEvent = 'click';

        if (vjs.IS_IPHONE || vjs.IS_IPAD || vjs.IS_ANDROID) {

          initEvent = 'tap';
          
        }

        player.one(initEvent, function () {

            // Initialize videojs-ima

        });
```

**Comment by riccardobevilacqua** [comment]
Thanks, it worked.
Apparently initializing ima on play is mandatory on Android, while it works anyway on iOS.
