### ISSUE TITLE
overlay google ads

### ISSUE THREAD

**Issue by mhndm** [googleads/videojs-ima#138]
how I can add overlay google ads ?

**Comment by shawnbuso** [comment]
The video.js IMA plugin is already set up to handle overlay ads, you'll just need an ad tag that returns them. Are you currently set up with an ad server? If so, you'll need to get an ad tag from them for overlay ads. If not, I'd suggest taking a look at [AdSense for Video](https://support.google.com/adsense/answer/1705822?hl=en).

**Comment by mhndm** [comment]
Thanks for your support
I want to display google ad when the player play the original video , I don't want to display video ad
like those pictures :
![unnamed 1](https://cloud.githubusercontent.com/assets/484366/12022821/36e92c6e-ad9c-11e5-89f0-659e0eb8d11c.png)
![unnamed](https://cloud.githubusercontent.com/assets/484366/12022820/36e2ea98-ad9c-11e5-8e28-c46b4e09523c.png)

**Comment by shawnbuso** [comment]
Hmm I'm a bit confused - that first picture is an overlay ad, which I thought you were looking for. Could you give me an example of what you want to see?

**Comment by mhndm** [comment]
like this :
http://cdn00.vidyomani.com/c/6/9/8/gx8yfgclwcvm/index.html

can you provide me an example code?

**Comment by shawnbuso** [comment]
Hmm when I visit that website I see the same thing that's in your second image - are you seeing something different? You won't need any additional code to get this to work, you should be able to just follow along with our simple sample. You just need to get an ad tag that will return that kind of ad.

**Comment by mhndm** [comment]
the simple example play and ad video before the original one.
Can you give me an example to show picture ad ( like the  first picture ) in the middle of the original video ?

adTagUrl: 'http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on'

Thanks for your time

**Comment by shawnbuso** [comment]
Unfortunately I don't have a test tag that will only serve those ads, because our ad network doesn't allow you to only request those ads. You can request overlay ads, which will sometimes return a full slot ad, but the overwhelming majority of ads you get back will be bottom-third overlay and not full slot. You can turn the tag you provided into an overlay tag by changing "ad_type=video" to "ad_type=image"

**Comment by mhndm** [comment]
Thanks a lot for this note

**Comment by mkhatib214** [comment]
I want to display google ad for three times when the player play the original video, 
 - before the video play 
 - when the video are played 
 - and after the video finishes

**Comment by shawnbuso** [comment]
We support that functionality via either ad rules (DFP proprietary) or VMAP (industry standard). You can set up VMAP to play a video before the ad starts, at some timestamp (or multiple timestamps) during the video, and again after the video ends. I've included a sample tag below that shows an ad before the video, at the 15 second mark of the video, and again after the video finishes. You can plug that into our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/) to see it in action. You can read more about using VMAP on the [IAB site](http://www.iab.com/guidelines/digital-video-multiple-ad-playlist-vmap-1-0-1/). If you have any other questions let me know!

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=
