### ISSUE TITLE
Non-iPhone samples don't work on Android

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#142]
For the moment this appears to be a regression with video.js no longer firing the tap event on Android. See https://github.com/videojs/video.js/issues/2958

**Comment by shawnbuso** [comment]
This is apparently not a regression but rather just a change to video.js.

**Comment by famthangbk** [comment]
Hi #shawnbuso
please help me
my player not show ads when i used ads tag on iphone sample
`adTagUrl: 'http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on'
`
i want use adsense for video
if i use simple or advance sample for my web, in ads.js file,although i have changed 'tab' to 'touchend', but can't play video when i touch
if i use iphone sample and sample ads tag every thing ok, but when i change ads

`http://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on`
no ads show on both desktop and moblie (android and ios)

**Comment by shawnbuso** [comment]
Hi there - this doesn't appear related to this issue - could you open a new issue for this? Thanks!

**Comment by famthangbk** [comment]
thank you so much!
