### ISSUE TITLE
Support for VideoJS 5 Responsive / Fluid Classes

### ISSUE THREAD

**Issue by ehoch** [googleads/videojs-ima#143]
Thank you guys for bringing 5.x support to this plugin!

Any chance we can bring in support for the new responsive options (http://blog.videojs.com/post/130143694631/video-js-5)?

e.g. vjs-16-9, vjs-4-3 classes or setting fluid = true?

Currently, the plugin requires that you hard-code the player size and if you add in those classes, the ads appear below the player.

**Comment by shawnbuso** [comment]
I'll consider this a feature request and we'll definitely look into it. The IMA SDK that we use under the hood ultimately requires pixel dimensions to initialize and resize ads, so we'll need to see how we can get that info from the video player when it's using responsive CSS classes rather than hard coded pixel dimensions.

**Comment by shawnbuso** [comment]
Do you have a specific device and browser where you saw this problem? I did a quick test in Chrome on Linux and I do see the ads where they're supposed to be with the responsive classes, so it may be platform-specific.

**Comment by hc2p** [comment]
I face the same problem. Latest videojs' `player.width()` and `player.height()` are returning 0 if player is not hardcoded with a specific size. 

I am thinking about circumventing the issue until videojs fixes this with following code: 

```
player.ima.width = function() {
  return player.el().offsetWidth
}
player.ima.height = function() {
  return player.el().offsetHeight
}
```

```
adContainerDiv.style.width = player.ima.width() + 'px';
adContainerDiv.style.height = player.ima.height() + 'px';
```

Could wrap this in a PR if you like.

**Comment by ehoch** [comment]
@shawnbuso I am using Chrome (latest version) on a Mac. VideoJS 5.3 and using your code from the sample. Do you need me to put up a Fiddle?

**Comment by ehoch** [comment]
Even better, here it's live on our staging site on a sample video happening. It looks like the ad is now appearing behind the video instead of below...

http://staging.foodfanatic.com/videos/how-to-make-truffles/iframe/

**Comment by ehoch** [comment]
@hc2p While we're waiting for this feature to be release, would you mind sharing a gist with me so I can see where that code goes for a workaround? 

Should we try and make an issue / PR at videojs?

**Comment by hc2p** [comment]
i created a PR for this issue https://github.com/googleads/videojs-ima/pull/161 sorry for the delay, got sidetracked.
@ehoch PR on videojs is not needed. read https://github.com/videojs/video.js/issues/2974 and https://github.com/videojs/video.js/issues/2282

**Comment by shawnbuso** [comment]
Can you folks confirm that the issues you were seeing are resolved with #161? If so we can go ahead and close this issue. Thanks!

**Comment by ehoch** [comment]
@shawnbuso @hc2p Unfortunately for me, when running things in fluid or with the vjs-16-9, the ad appears in the correct resolution, but below the player:

<img width="473" alt="screen shot 2016-02-01 at 10 07 52 pm" src="https://cloud.githubusercontent.com/assets/852746/12738659/bb6b7708-c930-11e5-800f-ee811fad8329.png">

**Comment by hc2p** [comment]
i have the same issue. Totally forgot that i worked around it with this css: 
`  #ima-ad-container {
    position: absolute;  
    top: 0;  
  }
`

**Comment by ehoch** [comment]
@hc2p That mostly solves the issue, however, if a user resizes the fluid player, the player will adjust but the ad does not leading to this:

![screen shot 2016-02-02 at 10 48 53 am](https://cloud.githubusercontent.com/assets/852746/12754801/b7099e1e-c99a-11e5-9ca3-a93a38397118.png)

**Comment by hc2p** [comment]
yes, that's a problem with the ima-plugin which hardcodes the width/height
of the ad-player.

**Comment by ehoch** [comment]
@shawnbuso Is this a fixable problem ever with the way Google IMA handles ads?

**Comment by shawnbuso** [comment]
Does the player fire any kind of event to let you know that it's resizing / has resized? If so we can respond to that event with a call to adsManager.resize() with the new player dimensions.

**Comment by shawnbuso** [comment]
FYI it looks like the issue with the ad being bumped below the player is that playerStyles.height is being set to 0, so there's no space for the ad inside the ad container. We might have to somehow delay ad display container creation until the video player is initialized - it looks like right now we're creating it before the video player exists and the height is being reported as 0. The width is being accurately reported for some reason though...

**Comment by shawnbuso** [comment]
Looking into this more, the height of 0 is breaking the controls as well. We'll only be able to make this work if we can get the actual DOM height and width of the video player when we initialize the ad container and ads manager. The code from pull request #161 is returning a height of 0 when we create the ad display container. Setting position:absolute and top:0 fixes the ad video rendering, but all the controls rendering is still broken.

**Comment by shawnbuso** [comment]
I think I might have something here - take a look at https://github.com/shawnbuso/videojs-ima/tree/fluid_support and let me know what you think.

**Comment by jgubman** [comment]
This mostly works for me (noted a few typos in the checkin comments), but for the life of me I can't get the player.one('play', setUpPlayerIntervals_) callback to fire. The fix works if I just do that setInterval outside of the player.one('play') callback though...

**Comment by jgubman** [comment]
Think I narrowed it down to us calling the ima plugin via a play handler on our player. 

Moved the setUpPlayerIntervals_ logic to player.on('loadedmetadata') callback and moved all the callbacks into the player.ready block and all's well.

:+1: for the fix

**Comment by ehoch** [comment]
This works for me in terms of solving the fluid issue, but I'm running into a different problem with this branch (that might be related to what @jgubman is seeing).

We use this for a click-to-play player so I don't directly call player.play(), I let VideoJS handle that when a user clicks (except on mobile where we follow your iPhone example). The regular branch works, but the fluid branch does not do anything when you click the player, only when you call player.play().

**Comment by hc2p** [comment]
@shawnbuso are you sure you want to read out width/height in an interval?https://github.com/googleads/videojs-ima/commit/5106b675aa3066f6949c945d53fa974d8c63d42d#diff-56b40006e5136dbf9868a615013d9e03R773 It looks like it would force a lot of additional layouts (see https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getcomputedstyle). 

What about exposing an resize() method on the plugin (`videojs.ima.resize()`). It would be up to the integration code to call it on the right time. One could listen on specific player-size affecting media-query changes (see https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList) and call it only when needed.

**Comment by hc2p** [comment]
There is also this library https://github.com/marcj/css-element-queries. Which easily could be done by the user and doesn't need to be part of the plugin.

**Comment by shawnbuso** [comment]
@ehoch How does your click to play player work outside of this branch? Looking at the workflow for the [contrib-ads](https://github.com/videojs/videojs-contrib-ads) plugin that we use, I can't find a path that ets you to ad playback without calling player.play()

@hc2p I could expose just a resize method, but that would leave more for the integrator to do and potentially do incorrectly, which would lead to more support cases for us. (Not that you would do it incorrectly, but potentially the hundreds of other people that use the plugin). Currently I only actually resize the adsmanager if the numbers I get back are different than the current size, so we shouldn't have extraneous calls to adsManager.resize.

I do like the look of that library, but I'd want to thoroughly test it with video.js to make sure it responds the way we think.

**Comment by ehoch** [comment]
@shawnbuso In the main branch, on desktop it works by simply calling:

```
player.ima(options);
player.ima.requestAds();
```

Then when the user was clicking play on the player it just seemed to be working on desktop. Was I supposed to be hijacking their click and calling player.play() myself?

I thought that iPhone thumbnail hack was just because VideoJS broke the tap event and wasn't needed for desktop..

**Comment by shawnbuso** [comment]
Hmm interesting, I wonder if there is an internal call to play() that triggers ad playback. In all of our examples we are calling player.play() after requesting ads. See [https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js#L84](here in the advanced sample).

**Comment by ehoch** [comment]
Thanks @shawnbuso. I'll update my code to do exactly that. Any idea when VideoJS will be fixing that regression with the tap event so we can go back to using the simple code rather than the thumbnail hack?

**Comment by shawnbuso** [comment]
I've filed an issue for it here: https://github.com/videojs/video.js/issues/2958. It looks like it *might* be fixed with a more recent version of video.js but I haven't had a chance to test yet.

**Comment by ehoch** [comment]
@shawnbuso Well for now, using the thumbnail hack for mobile devices and tracking the click on desktop and the fluid branch works beautifully. Thank you for this. Can we get it merged?

**Comment by shawnbuso** [comment]
Sure thing, just opened a pull request.
