### ISSUE TITLE
Ads playlist like VMAP

### ISSUE THREAD

**Issue by aydinkn** [googleads/videojs-ima#146]
Hi,
I want to make a ads playlist like this:
1 preroll linear
1 midroll nonlinear (10 sec. on content video)
1 midroll linear (60 sec. on content video)
1 postroll linear

Normally, html5 ima sdk handle this with VMAP, but it is not support overlays in VMAP yet. So, how can I handle ads playlist with videojs-ima?

**Comment by shawnbuso** [comment]
Hi there,

The videojs-ima plugin uses the IMA SDK under the hood, so we won't have support for this until the IMA SDK does.

Thanks,
Shawn
