### ISSUE TITLE
setContent adsManager null

### ISSUE THREAD

**Issue by mimse** [googleads/videojs-ima#151]
Hi, im trying to use setContent to start playback of a new clip. But because setContent calls the private function resetIMA_ which does this
```javascript
adsManager.destroy();
adsManager = null;
```
Now I get this error in console

Uncaught TypeError: Cannot read property 'getRemainingTime' of null

From this call
```javascript
 player.ima.onAdPlayheadTrackerInterval_ = function() {
      var remainingTime = adsManager.getRemainingTime();
}
```

Am I using this function wrong or this there a bug here?

**Comment by shawnbuso** [comment]
Are you changing the content while an ad is playing? I think that's the only way this should happen. We should probably be clearing that interval in resetIMA_ just to be safe anyway. I can add that.

**Comment by mimse** [comment]
Thanks for look into this. Just testet the code you put up. Did not work as I was had expected.

This is what I think it was suppose to do

1. Start playback
2. Ad is requested and shown
3. While ad is showing, user request new video clip
4. Ad stops
5. Ad is requested and shown
6. After ad new video clip is shown

What is happening right now is this

1. Start playback
2. Ad is requested and shown
3. While ad is showing, user request new video clip
4. new video clip is shown, but the controls have not reset to videojs controls and if you use them you get this error

````javascript
Uncaught TypeError: Cannot read property 'pause' of null
````

in this function

```javascript
player.ima.onAdPlayPauseClick_ = function() {
      if (adPlaying) {
        playPauseDiv.className = 'ima-paused';
        adsManager.pause();
        adPlaying = false;
      } else {
        playPauseDiv.className = 'ima-playing';
        adsManager.resume();
        adPlaying = true;
      }
    };
``` 
Again maybe the function is not suppose to work like this

**Comment by shawnbuso** [comment]
Ah yes that is a bug - tested with #155, that should take care of it.

**Comment by mimse** [comment]
Hi again,

Sorry for the delay just tested the new code. Its almost working. Last thing we need is to request an ad again

I fixed with this

https://github.com/tv2/videojs-ima/commit/11e3983508791bbb194994661dcd6f5bc4be2cc8
