### ISSUE TITLE
unable to control two instances of videojs-ima

### ISSUE THREAD

**Issue by aronallen** [googleads/videojs-ima#158]
If I have two instances on the same page of the videojs-ima plugin, I am can only control the one that was initialized as the last.

```js
player[0].ima.pauseAd();
player[1].ima.pauseAd();
```

in the above example both calls will pause the ad container in player[1], assuming player[1] was the initialized as the last.

**Comment by shawnbuso** [comment]
Thanks for the info - this is a KI, currently tracked as a feature request in #116.
