### ISSUE TITLE
Android Ad error: AdError 402: VAST media file loading reached a timeout of 15 seconds.

### ISSUE THREAD

**Issue by phommata** [googleads/videojs-ima#160]
I am using video-js-5.4.6, videojs-ima-master-5.3, and videojs-contrib-ads-master-3.1.2. I'm having a problem on Sony Xperia Z2 (D6503) Android 5.1 and the Chrome 47.0.2526.83 and the adTagUrl: 'http://scads.starsite.com/www/delivery/fc.php?script=apVideo:vast2&zoneid=4' and I am getting the following error: Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture. Ad error: AdError 402: VAST media file loading reached a timeout of 15 seconds. The ad window will appear with the ad text, but there will be no video or audio. 

The video ads will play in Safari, Chrome, Firefox, and iPhone. The problem is when I am attempting to run this on Android.

Note: The advanced example will not work for me on the same device. I cannot play the video.

<img width="479" alt="screen shot 2016-01-27 at 11 27 24 am" src="https://cloud.githubusercontent.com/assets/7331396/12625506/fd69a82e-c4e8-11e5-8e32-433de93009c2.png">

**Comment by shawnbuso** [comment]
We've been having trouble lately with the standard samples on Android - can you try your tag in the iPhone sample? That works for me testing on a Nexus 5x. Thanks!

**Comment by phommata** [comment]
My video advertisements work under the iPhone example. I think I'm getting somewhere now. Thank you!

**Comment by phommata** [comment]
Was able to correct the video advertisements not loading, due to the first Android tap event not being captured. Implemented the jQuery mobile library to capture the tap event, and then called the initializeAdDisplayContainer function.
