### ISSUE TITLE
Overlay overlaps / blocks controls after pause

### ISSUE THREAD

**Issue by ehoch** [googleads/videojs-ima#169]
Should be pretty easy to replicate... if you get an overlay on our site:

http://www.foodfanatic.com/videos/how-to-make-truffles/

We're running AdX for video through DFP. The steps on Google Chrome on a desktop browser:

1) Play Video.
2) Pause
3) Overlay shifts down over the controls
4) You can no longer resume the video. You can close the overlay and it won't matter. Its div is still absolute positioned over the controls

Caveat: I am running the fluid branch.

![screen shot 2016-02-10 at 12 06 53 pm](https://cloud.githubusercontent.com/assets/852746/12955224/153ad9fc-cff0-11e5-8153-8c51c9dd1c61.png)

**Comment by shawnbuso** [comment]
Thanks for the report! We were relying on the vjs-active class to bump the overlay, which was being removed from the player when it was paused. I added another line to our CSS to also bump the overlay whenever the player is paused. Opened #172 to fix
