### ISSUE TITLE
VideoJS blocks controls after an ad error

### ISSUE THREAD

**Issue by JasterTDC** [googleads/videojs-ima#170]
I have the next html code on my test directory, I have *videojs-ima*, *videojs-contrib-ads*, and *videojs* updated to latest version. When I load the page on my browser, I got the next mensaje through console:

Error: `AdsLoader error: AdError 1009: The VAST response document is empty.`

Once the error appears on my browser console, I cannot pause the video, change volume,... etc

¿What can I do to fix that? 

Thanks, Jaster.

```html
<!doctype html>
<html>
  <head>
    <title> VideoJS v5.6 - Test </title>

    <!-- Stylesheet -->
    <link href="./styles/video-js.css" rel="stylesheet" >
    <link href="./styles/videojs.ads.css" rel="stylesheet">
    <link href="./styles/videojs.ima.css" rel="stylesheet">
    <link href="./styles/style.css" >
  </head>
  <body>

    <!--
    <video id="content_video" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360">
      <source src="http://rmcdn.2mdn.net/Demo/vast_inspector/android.mp4" type="video/mp4" ></source>
    </video>
    -->

    <video id="example_video" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360">
      <source src="http://rmcdn.2mdn.net/Demo/vast_inspector/android.mp4" type="video/mp4" ></source>
    </video>

    <!-- Javascript -->
    <script src="./js/video.js" type="text/javascript" ></script>
    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script src="./js/videojs.ads.js" type="text/javascript" ></script>
    <script src="./js/videojs.ima.js" type="text/javascript" ></script>

    <script src="./js/ads-2.js" type="text/javascript" ></script>
  </body>
</html>

```

**Comment by shawnbuso** [comment]
Hi Jaster,

That error means we're reaching out the the ad server for ads, but it's not giving us any ads back. We should be playing your content automatically when that error happens - the line of code to do that is [here](http://googleads.github.io/videojs-ima/examples/advanced/). I was also able to verify that we properly handle a bad ad tag in our [sample player](http://googleads.github.io/videojs-ima/examples/advanced/) by filling in a bonus tag (I just used www.google.com). Are you seeing the same issue in that sample player?

Thanks,
Shawn

**Comment by ehoch** [comment]
I actually have the same error. @shawnbuso What happens is the content does automatically play, but the #ima-ad-container is positioned over the player so you can't press the buttons behind it. To patch, I did the following in my code:

```
  // On ad error, hide ima container
  this.player.on('adserror', this.bind(this, function() {
    document.getElementById('ima-ad-container').style.visibility = 'hidden';
  }));
```

**Comment by shawnbuso** [comment]
Interesting, is this only on certain platforms? I don't see that problem on our [advanced example](http://googleads.github.io/videojs-ima/examples/advanced/)

**Comment by moabdelhadi** [comment]
The problem appears if you use the sample Ad Tag but change the ui value to invalid one. 
The Solution of ehoch solve the problem, but you cannot use multiple videos in the same page.

**Comment by shawnbuso** [comment]
Is this a specific browser or OS? I'm still not seeing it in Chrome on Linux.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing the issue please feel free to re-open.

**Comment by jdp** [comment]
I'm seeing this happen as well. The error I see is:

> AdsLoader error: AdError 1012: Unable to request ads from server due to network error.

Then the `#ima-ad-container` remains, blocking the controls.

**Comment by shawnbuso** [comment]
@jdp are you seeing this with the most recent version of our player? You can test easily with your tag in our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/).

**Comment by jamesgorrie** [comment]
I also have this issue:
[Here's an example](https://jsfiddle.net/jamesgorrie/aofw550k/). Strangely - this also seems to recreate [this issue](https://github.com/googleads/videojs-ima/issues/167) too (not to conflate it though).

**Comment by shawnbuso** [comment]
It looks like you're using multiple instances of the plugin on the same page, which we currently don't support (see #116). Are you seeing this issue with only one player on the page?

**Comment by jamesgorrie** [comment]
@shawnbuso Nope - I didn't realise this was in feature request as opposed to bug, thanks for letting me know.
