### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by wmcmurray** [googleads/videojs-ima#173]
First of all, thanks a lot for this plugin !! It saved me a lot of time on a project that have an almost impossible to meet deadline.

Just one thing : I firstly installed the plugin via NPM and noticed some bugs using the latest VideoJS version (5.6.0), after fixing some I was ready for a pull request but realized that all of them were already fixed in the repo but not released yet... So it would be nice if you could release a new version soon, because things has evolved a lot since the last release, thank you :)

**Comment by shawnbuso** [comment]
Sure thing - I just need to get the license added to the package file (#166) and I'll be good to go.
