### ISSUE TITLE
Player keeps loading playlist even if player is in paused state.

### ISSUE THREAD

**Issue by erarjit** [googleads/videojs-ima#174]
We are using m3u8 playlist for playing live video on video.js and on other devices. Our playlist doesn't contain #EXT-X-ENDLIST (which marks playlist end). This had to be done to support live video for other devices.

The issue is- Even after clicking pause button the playlist keeps loading. video segments don't download anymore but playlist does.

seems like a bug to me. 

Edit: we are using Video.js v4.12.7

**Comment by shawnbuso** [comment]
This sounds like an issue with video.js to me, not the IMA plugin. I'd recommend filing an issue on [their issue tracker](https://github.com/videojs/video.js/issues).
