### ISSUE TITLE
Overlay/AdRules

### ISSUE THREAD

**Issue by hakanguner** [googleads/videojs-ima#175]
Hello,

I'm quite new at this. Maybe there is no support or there is a mistake on my example code but I am not able to show overlay ads. I created a manuel tag that has 4 element. First one is preroll, others are one overlay midroll, one linear midroll and a postroll video. But SDK skips the overlay one and plays other linear ads. Can we show overlay ads like this? When I use the overlay tag directly(on the adTagUrl), it shows at the beginning of the video like a preroll.

Example: http://www.sporx.com/tv/_videojs/test_ima_adrules.php
TAG: http://adm3.sporx.com/_banner/adrules2.php
Overlay TAG: http://tester.advertserve.com/servlet/vast2/media?mid=125&pid=0&random=8670

Thank you.

**Comment by shawnbuso** [comment]
The IMA SDK doesn't support overlay ads in a VMAP response, so that's why this isn't working here. See  footnote 3 in the HTML5 column of the VMAP 1.0.1 row [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).

**Comment by hakanguner** [comment]
Thank you for the very fast response. Just out of curiousity :) Do you know if this support is in the roadmap?

Thanks again.

**Comment by shawnbuso** [comment]
I know we're looking into options for supporting it, but we don't have any release timeline info yet.

**Comment by hakanguner** [comment]
OK. Thanks for the support.
