### ISSUE TITLE
Shows first frame of content before playing ad

### ISSUE THREAD

**Issue by mimse** [googleads/videojs-ima#178]
Hi,

We are seeing an issue with the first frame of the video content being shown before the ad starts. We would like to see the ad start before any content is being shown. 
The way it works now leads to a lot of flickering between states.

I have tried playing around with preload option, but it does change the behaviour.

Our quick fix has been to hide the video element like this, but we would like to see a more smooth solution :-)

```language-css
.vjs-ad-loading > video {
  opacity: 0;
}
```

[Video of the issue](https://youtu.be/_BMbP_DndVY)

**Comment by shawnbuso** [comment]
Hi there,

I'm not sure that this is possible today unfortunately. The way the video.js plugin is set up requires that we call play on the video player before requesting ads. So what's happening is that the player starts loading the content, then the ads play. [I've followed up with the contrib-ads folks to see if there's a way around this](https://github.com/videojs/videojs-contrib-ads/issues/145).

**Comment by mimse** [comment]
Hi again,

Thank you for looking into this issue.

I have been doing some testing with the videojs-contrib-ads plugin as well to see if I could locate the issue.

I modified their example to call the DPF and as you can see on the video no content is shown before the ad starts.

[Test of videojs-contrib-ads](https://youtu.be/8cMM722yhkw)

**Comment by shawnbuso** [comment]
Is this the opacity CSS fix you mentioned earlier or is this something else? Could you share the details of the fix?

**Comment by mimse** [comment]
I modified this example 

[Videojs-contrib-ads example](https://github.com/videojs/videojs-contrib-ads/tree/master/example)

To work with DFP, to test if the issue had to with videojs-ima or videojs-contrib-ads

I added an adServerUrl to app.js

```
player.exampleAds({
      debug: true,
      adServerUrl:'http://pubads.g.doubleclick.net/gampad/ads?adk=831413252&ancr=http%3A%2F%2Fsport.tv2.dk&ciu_szs=300x250%2C930x180&correlator=3374934648684544&cust_params=site%3Dsport%26sport%3Dformel%2B1%26node_type%3Darticle%26url%3Dhttp%3A%2F%2Fsport.tv2.dk%2Fformel-1%2F2016-02-23-kevin-magnussen-det-er-ligesom-at-vinde-i-lotto%26is_video_node%3D1%26page_type%3Dcontent%26CxSegments%3D8ka9i4jn8z6z%7C8kaarmsyvdqa%7C8kafxepvjt82%7C8kldv66rxucp%7C8kljo1cpvcov%7C8klkj0h176ir%7C8kwio2e8fryc%7C8kwmtsqt17yr%7C8kwmtsqt17ys%7C8l7i5bq95el5%7C8l7id2tlnufd%7C8l7jnaiz0hji%7C8m52toqzepq2%7C8mg5x81qxdhu%7C8nd2ye5sunwq%7C8noc9ibd680r%7C8noc9ibd680u%7C8noc9ibd680w%7C8noc9ibd680x%7C8noc9ibd6810%7C8noc9ibd6811%7C8noc9ibd6812%7C8olfcjflimg9%7C8olfcjflimga%7C8owuyzqhzqcb%7C8p7ztd8gynbr%7C8p7ztd8gynbs%7C8p8190y9vkar%7C8pj3gr2qi6gp%7C8pj4ck96cf70%7C8pj4dnfezgmg&description_url=&dt=1456236522135&eid=41351096&env=vp&flash=20.0.0.306&frm=2&frmd=1&gdfp_req=1&ged=ta1_ve3_pt4.3.u_td4_tt0_pd0_bs10_la11000_tv1_is2_er0.0.349.620_sv2_sp1_vi0.0.349.620_vp100_ct1_vb1_vl1_vr1_eb24171&hl=da&impl=s&iu=%2F19784602%2Ftv2dk-web%2FSport%2FSport_Underside%2FSport_Underside_Video_1&mpt=theplatform%2Fpdk&mpv=5.6.2&osd=6&output=xml_vast3&scor=49256129888256&sdkv=3.226.0&sdr=1&spotlength=65&sz=640x360&u_ah=1053&u_asa=1&u_aw=1920&u_cd=24&u_h=1080&u_his=3&u_java=false&u_nmime=7&u_nplug=5&u_tz=60&u_w=1920&unviewed_position_start=1&url=http%3A%2F%2Fsport.tv2.dk%2Fformel-1%2F2016-02-23-kevin-magnussen-det-er-ligesom-at-vinde-i-lotto&video_id=614916163922&vpos=preroll'
    });
```

and changed example-integration.js to parse the VAST fil from DPF like this

```
/**
 * Example ad integration using the videojs-ads plugin.
 *
 * For each content video, this plugin plays one preroll and one midroll.
 * Ad content is chosen randomly from the URLs listed in inventory.json.
 */
(function(window, document, vjs, undefined) {
"use strict";

  /**
   * Register the ad integration plugin.
   * To initialize for a player, call player.exampleAds().
   *
   * @param {mixed} options Hash of obtions for the exampleAds plugin.
   */
  vjs.plugin('exampleAds', function(options){

    var

      player = this,

      // example plugin state, may have any of these properties:
      //  - inventory - hypothetical ad inventory, list of URLs to ads
      //  - lastTime - the last time observed during content playback
      //  - adPlaying - whether a linear ad is currently playing
      //  - prerollPlayed - whether we've played a preroll
      //  - midrollPlayed - whether we've played a midroll
      //  - postrollPlayed - whether we've played a postroll
      state = {},

      // just like any other video.js plugin, ad integrations can
      // accept initialization options
      adServerUrl = (options && options.adServerUrl) || "inventory.json",
      midrollPoint = (options && options.midrollPoint) || 15,

      // asynchronous method for requesting ad inventory
      requestAds = function() {

        // reset plugin state
        state = {};
        
        // fetch ad inventory
        // the 'src' parameter is ignored by the example inventory.json flat file,
        // but this shows how you might send player information along to the ad server.
        var xhr = new XMLHttpRequest();
        xhr.open("GET", adServerUrl);
        xhr.onreadystatechange = function() {
          if (xhr.readyState === 4) {
            try {
              state.inventory = xhr.responseXML;
              player.trigger('adsready');
            } catch (err) {
              throw new Error('Couldn\'t parse inventory response as JSON');
            }
          }
        };
        xhr.send(null);

      },

      // play an ad, given an opportunity
      playAd = function() {

        // short-circuit if we don't have any ad inventory to play
        if (!state.inventory) {
          return;
        }
        
        var srcFile = document.evaluate('//MediaFile', state.inventory, null, XPathResult.STRING_TYPE, null);

        console.log(srcFile.stringValue);
        
        // tell ads plugin we're ready to play our ad
        player.ads.startLinearAdMode();
        state.adPlaying = true;

        player.src(srcFile.stringValue);

        // when it's finished
        player.one('adended', function() {
          // play your linear ad content, then when it's finished ...
          player.ads.endLinearAdMode();
          state.adPlaying = false;
        });

      };

    // initialize the ads plugin, passing in any relevant options
    player.ads(options);

    // request ad inventory whenever the player gets new content to play
    player.on('contentupdate', requestAds);
    // if there's already content loaded, request an add immediately
    if (player.currentSrc()) {
      requestAds();
    }

    player.on('contentended', function() {
      if (!state.postrollPlayed && player.ads.state === 'postroll?') {
        state.postrollPlayed = true;
        playAd();
      }
    });

    // play an ad the first time there's a preroll opportunity
    player.on('readyforpreroll', function() {
      if (!state.prerollPlayed) {
        state.prerollPlayed = true;
        playAd();
      }
    });

    // watch for time to pass 15 seconds, then play an ad
    // if we haven't played a midroll already
    player.on('timeupdate', function(event) {

      if (state.midrollPlayed) {
        return;
      }

      var currentTime = player.currentTime(), opportunity;

      if ('lastTime' in state) {
        opportunity = currentTime > midrollPoint && state.lastTime < midrollPoint;
      }

      state.lastTime = currentTime;
      if (opportunity) {
        state.midrollPlayed = true;
        playAd();
      }

    });

  });

})(window, document, videojs);
```

So to me it looks like an issue in the videojs-ima plugin

**Comment by mimse** [comment]
Any news on this issue? :-)

**Comment by shawnbuso** [comment]
Hi there,

I'm still working on this one. The sample is interesting, because in the state diagram in their README it looks like you should never arrive at "preroll?" or "adstart" without calling play on the player. That sample never calls play at all though. I'll need to look into this more to see if we can modify our code to behave more like their sample code.

**Comment by mimse** [comment]
#167 Guess they could be related

**Comment by phommata** [comment]
I had to pause the player and allow the preroll to start.

`player.play();  // Call play on the videojs player to arrive at "preroll" or "adstart"
player.pause(); // Pause videojs player before preroll`

**Comment by mimse** [comment]
Playing around with timeouts looks to have fixed the issue more or less, set both to 5000

**Comment by ehoch** [comment]
@mimse Would mind sharing what timeouts you set to 5000 to fix this?

**Comment by mimse** [comment]
@ehoch 

`prerollTimeout: 5000,
 timeout: 5000`

**Comment by spodlecki** [comment]
Adding *both* timeouts seem to have solved this... I don't see either of these options in the documentation though. What exactly is the difference? Should there just be a single option?

**Comment by shawnbuso** [comment]
Those timeouts are actually options on the contrib-ads plugin that this plugin uses - you can find documentation on them [here](https://github.com/videojs/videojs-contrib-ads#plugin-options).

**Comment by spodlecki** [comment]
Understood -- are there only certain options you auto-pass to the `contrib-ads` plugin? I wouldn't have even guessed to go there because of the attribute `contribAdsSettings`

Thanks for the prompt response

**Comment by shawnbuso** [comment]
I think we surfaced them because we expected them to be used often, but in retrospect it would have been better to have one and only one place to specify this, which would be contribAdsSettings. 
Whatever you provide to the contribAdsSettings param will override what you provide in the top-level IMA plugin settings, so you can provide them in either place.

**Comment by oldmtn** [comment]
Is this issue fixed now?

**Comment by shawnbuso** [comment]
This issue is fixed now, except for one edge case - if you're on a very slow connection, you could see content before ads. This is because the contrib-ads preroll timeout is a soft timeout - if we hit that timeout, we will start content, but if the pre-roll loads after that we will interrupt content to play it. More info in #571, which we're still deciding if we want to merge or not.

**Comment by Slind14** [comment]
> This issue is fixed now, except for one edge case - if you're on a very slow connection, you could see content before ads.

Or one is using a vast/vmap waterfall, since these requests are queued and not concurrent. Any chance this soft timeout could be made configurable?

**Comment by shawnbuso** [comment]
This is configurable in the contrib-ads settings. You can set it like this in your IMA plugin options:

```
{
  ...
  contribAdsSettings: {
    prerollTimeout: XXX
  }
}
```

A complete list of available settings for contrib-ads can be found [here](http://videojs.github.io/videojs-contrib-ads/integrator/options.html).

**Comment by Slind14** [comment]
Thank you.
