### ISSUE TITLE
VPAID/VMAP Issue

### ISSUE THREAD

**Issue by hakanguner** [googleads/videojs-ima#179]
Hello,

We are using a VMAP setup in our player. A Preroll, a midroll (an overlay on 10th second) and a postroll.

We got a VPAID tag recently. When we use this tag as a preroll in our VMAP tag, it skips and won't show it. But aside from VMAP setup, when we try to use this VPAID tag directly, we can see the ad. 

I tested this on the demo page (http://googleads.github.io/videojs-ima/examples/advanced/). It behaves    the same way. Do you have an idea what might be the problem?

VPAID tag: http://adm3.sporx.com/_tmp/vmap_getvpaid.php
VMAP URL: http://adm3.sporx.com/_tmp/vmap.php

Thanks.

**Comment by shawnbuso** [comment]
The IMA SDK currently has an issue where VPAID ads do not work in VMAP, but that should be fixed shortly. However, they don't currently support overlay ads in VMAP, so when the VPAID issue is resolved I think you'll see that ad work fine but not your overlay.

**Comment by hakanguner** [comment]
Thanks for the answer.
