### ISSUE TITLE
requestAds() events 

### ISSUE THREAD

**Issue by ksheurs** [googleads/videojs-ima#181]
Question - If `requestAds()` returns no ads for some reason will the `CONTENT_RESUME_REQUESTED` event still be fired? If not, is there a better event to listen to in this case? Thanks.

**Comment by shawnbuso** [comment]
That will not fire - the SDK fires an ads loader error instead and the plugin triggers adserror, which results in content playing. you can see that here: https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L247
