### ISSUE TITLE
Will it work with Dash & version 5.8.0

### ISSUE THREAD

**Issue by baqarrivi** [googleads/videojs-ima#182]
I am using creating wordpress plugin what i want ot know is that will it work with dash and with latest version 5.8.0

**Comment by shawnbuso** [comment]
We're blocked by the contrib-ads plugin, which look like it currently supports up to 5.3. As far as content goes, we should support anything video.js supports out of the box. Ad formats are limited to what the vanilla HTML5 <video> tag can play.

**Comment by baqarrivi** [comment]
IT is working fine with version 5.7.1 With dash but i am having a problem to play ads in mobile it only supporting i phone i think . here is the codepen. 
http://codepen.io/baqarrizvi/pen/ZQgboZ?editors=1000

**Comment by baqarrivi** [comment]
1) I am using Mpeg dash 
2) My video.js version is 5.7.1 
3) sometimes its showing ads sometimes its not and its not working in mobile.!

**Comment by baqarrivi** [comment]
here is the link . http://bestsongs.pk/zoobi-doobi-3-idiots/

**Comment by baqarrivi** [comment]
Hi shawnbuso,
it works thanks , the problem was with the javascript
