### ISSUE TITLE
videojs ima | Liverail error.

### ISSUE THREAD

**Issue by kellogx** [googleads/videojs-ima#185]
Hi Team,

If you wait until ad finish we are getting a  see the link =>http://imgur.com/8JNwruk error.
I couldn't locate if the problem is from IMA or Liverail.

Would it be possible to check this link below ?
test page => http://www.sporx.com/tv/_iframe/embed_video_ysx.php?frm_vId=70009&ck_html5=1

**Comment by shawnbuso** [comment]
It looks like this issue is coming from the liverail ad itself, not the IMA SDK or plugin. Have you reached out to LiveRail to see if anyone there is able to take a look?

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need assistance feel free to re-open :)
