### ISSUE TITLE
Not initiating

### ISSUE THREAD

**Issue by jlieb10** [googleads/videojs-ima#186]
I am trying to use this plugin (installed via npm) alongside the contrib-ads plugin but am getting an initialization error on it: `Uncaught ReferenceError: videojs is not defined` - this is coming from the last two lines of videojs.ima.js:

```
  videojs.plugin('ima', imaPlugin);
}(window.videojs));
```

I am trying to use this in an ES module, importing as:
```
import videojs from 'video.js';
import ads from 'videojs-contrib-ads';
import ima from 'videojs-ima';
```

videojs and ads both load properly (I am getting expected behavior from them) but this plugin errors out. That is, when I comment out the import on videojs-ima, I do not get the error.

By comparison, the last two ads of videojs.ads.js (from contrib-ads) looks like this
```
  videojs.plugin('ads', adFramework);
})(window, videojs);
```

so I can tell `videojs` is available to contrib script, but for some reason, not this one

I hope that this bug report is clear enough to be actionable. If you need more information, please ask. Thanks for your help!

**Comment by shawnbuso** [comment]
If you change the videojs-ima source final line from `}(window.videojs));` to `}(window, videojs));` does it work? That's the only difference I'm seeing between the ads contrib code and ours.

**Comment by jlieb10** [comment]
I ended up just binding videojs to the window rather than importing it to the module and it was fine-- thanks @shawnbuso

**Comment by jimjkelly** [comment]
@jlieb10 - can you expand a bit on how you got this to work?  I'm facing the same issue and can't seem to get things going.  Using browserify, it seems it pushes the imports above my code, so doing something like the following doesn't work:

```
import videojs from 'video.js';
window.videojs = videojs;
import ads from 'videojs-contrib-ads';
import ima from 'videojs-ima';
```

Also, simply changing the final line to `}(window, videojs));` doesn't seem to work either.  I'll keep poking but I'd be curious to hear how @jlieb10 got things going.

**Comment by jimjkelly** [comment]
So, I was never really able to get this running completely when importing it, but I did code up something to show one way the library could be made compatible for importation.  This method is similar but not exactly the same as what videojs.ads.js uses.  The difference is they seem to run the process before a release, where as this runs as a postinstall script.

https://github.com/vusemedia/videojs-ima/tree/fix/missing-video-js
