### ISSUE TITLE
Full screen button not working when ads are playing "player.isFullScreen is not a function"

### ISSUE THREAD

**Issue by mirageisme** [googleads/videojs-ima#189]
When clicking full screen button while ads are playing I get this error

> `videojs.ima.js:411 Uncaught TypeError: player.isFullScreen is not a function`

The methods are case sensitive it actually ` player.isFullscreen()` please can you look at it.

Here is where the error shows:
```
    /**
     * Listener for clicks on the fullscreen button durin ad playback.
     * @ignore
     */
    player.ima.onAdFullscreenClick_ = function() {
      if (player.isFullScreen()) {
        player.cancelFullScreen();
      } else {
        player.requestFullScreen();
      }
    };
```

**Comment by shawnbuso** [comment]
I think you may just need to grab the latest release - this was fixed a bit back :)

https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L552
