### ISSUE TITLE
Not working in UC Browser. Any Solution

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/videojs-ima#191]
Hello,
    ima ads not working in uc browser as well as some other browsers. UC Browser add it's default videoplayer on top of it please any solution. thanx

**Comment by shawnbuso** [comment]
Currently the IMA SDK only supports Chrome and the default Android browser on Android devices. For more info you can see the IMA SDK support matrix [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).
