### ISSUE TITLE
VPAIDjs not displaying video

### ISSUE THREAD

**Issue by FlashbackDavid** [googleads/videojs-ima#192]
SpotX test tag: http://search.spotxchange.com/vast/2.00/79391?VPAID=JS&player_width=640&player_height=360&content_page_url=http%3A%2F%2Fexample.org&cb=14580139120

note: in both cases below, INSECURE vpaidmode needs to be set

Using the SpotX test tag on the [videojs-ima advanced test page](http://googleads.github.io/videojs-ima/examples/advanced/), the ad appears to be playing, but the video is black.

Using the same test tag on the [ima html5 advanced test page](http://googleads.github.io/googleads-ima-html5/advanced/), the ad plays and is visible.

**Comment by shawnbuso** [comment]
It looks like the issue is that the VPAID is displaying under the content video player, because the content video player is being rendered later. #193 should fix this.
