### ISSUE TITLE
When an ad errors out, the player controls seem to get hosed

### ISSUE THREAD

**Issue by vineet** [googleads/videojs-ima#194]
it seems when there is a bad ad -- the video goes on to play, but the player controls do not respond to clicks.  videojs 5x

**Comment by shawnbuso** [comment]
Are you able to reproduce this in our [sample](http://googleads.github.io/videojs-ima/examples/advanced/)? We've fixed similar issues in the past - are you using the latest version of the plugin?

**Comment by vineet** [comment]
Sample looks good.  I'm using VideoJS 5.7.1 and plugin 6603dee0a3bbcd0ccd0a5a49656947bd75dc1ff5  (because we needed fluid support)-- I will try latest versions, but I see the last "release" version of the plugin is still 0.3.0

Is the sample using the head version of the plugin?

**Comment by shawnbuso** [comment]
It is, but we currently only support upto video.js 5.3, which may be your issue. Are you able to use that to test? Fluid support was introduced in 5.0, so you should be good to go with 5.3 if that's what you need.

**Comment by vineet** [comment]
Ahh okay, we'll try 5.3.  Thanks!

**Comment by vineet** [comment]
Hi, I wanted to revisit this again -- as it's creeped back.  And it seems to be the case for VJS 5.3 as well as the latest versions.  I tried the sample page again -- and the problem is there as well.   

It seems if there is a bad VAST response, i.e.: failed ad attempt, the player does go on to play content.   But the pause button or volume control cannot be clicked on -- you can however use the scrub bar.

For example -- I just tried a blank XML file to see how the player handles it:  http://www.detat-cg.net/clients/dummy_vast.xml  -- and you'll see what I mean with the hosed player control.

After we spoke about it in March, the problem seemed to have gone away.  Somehow, now it's crept back in...

**Comment by shawnbuso** [comment]
Sorry about that - this should be fixed by #216, which should be merged soon

**Comment by vineet** [comment]
Thanks, I'll keep an eye out for the merge..!

**Comment by shawnbuso** [comment]
Just merged and tested and I'm no longer seeing the issue on our samples. Let me know if you still see it :)

**Comment by vineet** [comment]
Looks good, thanks a lot!
