### ISSUE TITLE
Midroll Question/Request for Docs

### ISSUE THREAD

**Issue by jlieb10** [googleads/videojs-ima#195]
I've read through the code in examples/playlist/ several times and believe I understand it for the most part, but I'm not sure how or where the midroll ads are being initiated. Is this being somehow controlled by the ad tag response? Documentation would be really helpful- thank you!

**Comment by shawnbuso** [comment]
For mid-rolls you can use VMAP, which is an industry standard for ad playlists. The ad response itself tells the SDK when to play ads. You can see an example VMAP response [here](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=).

**Comment by jlieb10** [comment]
Thanks again, @shawnbuso
