### ISSUE TITLE
Flash VPAID Ads?

### ISSUE THREAD

**Issue by ehoch** [googleads/videojs-ima#196]
In the past I saw on comments this plugin did not support Flash VPAID creatives due to the lack of support in Google IMA. Does this update:

http://googleadsdeveloper.blogspot.com/2016/03/ima-sdk-for-html5-now-supports-vpaid.html

Mean we can now use this plugin to run Flash VPAID ads or does a change need to be made? Sorry for using a Github issue for this..

**Comment by shawnbuso** [comment]
Yes, Flash VPAIDs will work with the video.js plugin as well. Note that your users will still need to be in an environment that supports Flash.

**Comment by DrLightman** [comment]
Test

**Comment by shawnbuso** [comment]
You shouldn't have to make any changes to the code, unless your VPAID ad requires access to the parent frame. In that case you'll need to use INSECURE mode, which can be enabled with the vpaidMode setting in the plugin settings.

**Comment by DrLightman** [comment]
Thank you. Just to be sure, since I'm totally newbie on ima sdk, is this the proper way to do that?

```javascript
var options = {
    id: 'video',
    adTagUrl: adTag,
    VpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE
};
```

**Comment by shawnbuso** [comment]
I think you'll need to lower-case the "v", but that should work:

vpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE

**Comment by DrLightman** [comment]
Thanks man.
