### ISSUE TITLE
Flash VPAID Ads? (Part 2)

### ISSUE THREAD

**Issue by DrLightman** [googleads/videojs-ima#198]
I'm sorry to open another issue, I was trying to reply to this one:
https://github.com/googleads/videojs-ima/issues/196

But it didn't let me: http://m67.imgup.net/errbc32.jpg

--

I wanted to ask:

What changes should we do to the code to be able to support VPAID? Or are these upgrades "for free" and we don't have to change anything?

Thank you and I'm sorry to have posted this here, maybe is not the right place.

**Comment by shawnbuso** [comment]
That's odd that you can't respond - I've seen that a few times before on here. Do you get a specific error? I can close that issue and we can run with this one, but I feel like once I reply here you may not be able to reply again :-/

You shouldn't have to make any changes to the code, unless your VPAID ad requires access to the parent frame. In that case you'll need to use INSECURE mode, which can be enabled as shown [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vpaid2js#iframe-security).

**Comment by DrLightman** [comment]
Okay I found why I couldn't respond, there was an ad blocking plugin that for sure was messing with some script with "ads" name in it. You can erase this thread and transfer your reply over there if you want :)

**Comment by shawnbuso** [comment]
Sounds good, back on the first thread :)
