### ISSUE TITLE
The label in the countdown is not multilingual nor customizable.

### ISSUE THREAD

**Issue by LRancez** [googleads/videojs-ima#200]
Hi there,
I'm having some problems trying to make the countdown label different than english. Although the plugin has a locale setting, the word "Advertisement" is a constant string inside the code and it doesn't variate with the locale option.
I'd made a small change to the plugin so the label can be passed as a setting, but it seems that the sdk (ima3.js) still forces the word "Advertisement" in the countdown.
https://github.com/FOXITES/videojs-ima/commit/8c8cef8386da3e3a3fa692374f04c9951d0930ac

Is there any way to put a custom label in the countdown? or at least that it uses the correct word from the chosen locale setting?

**Comment by shawnbuso** [comment]
Definitely agree that we should make the plugin's text customizable - I'll take a look at the pull request.

As for IMA still using English - could you send me the tag you're using to test the locale you're trying to use? If IMA is putting up its own UI it should be respecting your locale setting.
