### ISSUE TITLE
Youtube api ( Advertisement is not working in youtube blocked country ) 

### ISSUE THREAD

**Issue by baqarrivi** [googleads/videojs-ima#203]
Dear shawnbuso 

Advertisement is not working In YouTube ban countries is there is any way to bypass it ? in some of the countries youtube is accessible but it is keep fluctuate according to gov order . so plugin stop working and because of that i am having Unfilled impressions in my DFP . hope you have great idea to bypass it like before .

Many Thanks 
baqarrizvi

**Comment by shawnbuso** [comment]
Hi there,

Our plugin should work in countries that block YouTube. We do use some YouTube resources, but if those requests fail we fall back to alternate resources that are non-YouTube. For example, on my test page redirected youtube.com to a non-existant website and the plugin still worked. Are you getting any errors other than YouTube being blocked?

**Comment by baqarrivi** [comment]
Dear shawnbuso,

Thanks For your immediate response in this issue . I am using IMA SDK PLAYER In my mobile app also. will it also call alternate option when youtube got blocked like website . I am talking about google media Framework right now . Hope you will respond .

Many Thanks 
baqarrizvi

**Comment by shawnbuso** [comment]
I'm a bit confused - which product are you using? If you're using the Video.js plugin, you're in the right place, and as I stated above it should be working even if YouTube is blocked. If you're using our [Android](https://github.com/googleads/google-media-framework-android) or [iOS](https://github.com/googleads/google-media-framework-ios) Google Media Framework, could you follow up on the issue tracker for the one you're using?

**Comment by baqarrivi** [comment]
Dear shawnbuso,

You always comes with great idea actually we have tried you example as well after blocking youtube in our router but its not responding also have try all of your example non of them are working. can you please try same at your side .

Many Thanks
Baqarrizvi

**Comment by shawnbuso** [comment]
Hmm that's odd - what network requests are you seeing fail? I tried it again and it's still working for me - I see a request to https://www.youtube.com/iframe_api fail but yhe ad still plays (see attached screenshot).
![screenshot from 2016-04-04 09 52 50](https://cloud.githubusercontent.com/assets/1238504/14250154/2098a204-fa4b-11e5-8e37-8dcb8121f5d4.png)

**Comment by baqarrivi** [comment]
Dear shawnbuso,
Thanks for your Response from your important time. we have tried any other software K9 . but if its working fine at your side it should be. you are awesome like always.
Many Thanks
Baqarrizvi
