### ISSUE TITLE
Play event doesn't go to preroll on Android

### ISSUE THREAD

**Issue by jgubman** [googleads/videojs-ima#205]
Given a plain vanilla videojs 5.3 player and a basic ima set up (using the config in the simple example), when the video has a preroll Android rejects playback of the preroll with an error:

Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

You can see an example here:
https://jsfiddle.net/q5onb63p/2/
we set up a basic videojs player. When the user clicks the videojs big play button the request to  ima.initializeAdDisplay() and requestAds() is called, but Chrome on Android fires back with that "Failed to execute 'play'...." error.

Any advice? 

I noticed the iPhone sample DOES play the preroll, but that's kind of a bunk example, since it's not using videojs at all, but rather creating a vanilla video tag that plays a preroll on click.

**Comment by shawnbuso** [comment]
Hi there,

There's currently a known issue with the non-iPhone samples and Android devices (see #142). The iPhone sample is still using a full video.js player - we go through the same workflow as the other samples (create a video tag and then pass its ID to the video.js constructor) so it's using a video.js player, not just a vanilla video tag.

**Comment by jgubman** [comment]
Hmmm, I'm still looking into is, but it *seems* to me the issue boils down to if you create the videojs player based on a click/tap event and then request the ima stuff the preroll works. 

If the videojs player is created BEFORE a user taps a button, the ima play call throws the error above and times out. 

I'll let you know if I find any other details.

Note that we had our QA dept. report this behavior also happened in videojs 4.12.* (I've yet to confirm that).

**Comment by shawnbuso** [comment]
That specific error is caused when you call initializeAdDisplayContainer but not as the result of a user action. Is that expected behavior with your current code?

**Comment by jgubman** [comment]
We call initializeAdDisplayContainer in the videojs play handler. So the expectation is the user comes in, clicks the big play button and then the on('play') event fires and initializes the ima stuff.

**Comment by shawnbuso** [comment]
OK that is the issue then - "play" is not fired as the result of a user action. You need to listen for the "click" or "tap" event itself.

**Comment by jgubman** [comment]
Ok, so the user has to touch an element that directly creates the ima object? The intention gets lost somewhere in the callbacks that the big play button makes?

**Comment by shawnbuso** [comment]
The only thing that must be done as the result of a user action is the call to initializeAdDisplayContainer - you can create the IMA object any time you want before that. You can do this as the result of a click or tap on the play button, but it must be in an event listener for "click" or "tap" - the "play" event doesn't count.

**Comment by jgubman** [comment]
Gotcha, thanks.

**Comment by jgubman** [comment]
Just wanted to confirm, in android I added a div over the player and button that calls the same function that's called by the videojs player.on('play') (so essentially covered the poster image and play button with a transparent div that calls the same handler).

Works great, thank you for your help!
