### ISSUE TITLE
ima must be instantiated before play is called or setUpIntervals won't be triggered

### ISSUE THREAD

**Issue by jgubman** [googleads/videojs-ima#209]
Not sure if this is a bone fide bug or just a documentation tweak, but the setUpPlayerIntervals_ function is called on Player.play here:
https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L1095

If you create the plugin inside a player's play handle that line will never get triggered.

**Comment by shawnbuso** [comment]
Thanks for spotting this - I would consider this a documentation issue. We need the plugin created and initialized before play is called. I'll get that added to the docs somewhere.
