### ISSUE TITLE
VAST 2 non linear not working

### ISSUE THREAD

**Issue by aldfeu** [googleads/videojs-ima#22]
On latest videojs 4.9 and latest ima and contrib-ads, I cannot use vast2 non linear.

Everytime I see the following error:
AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area.

you can ty with the follwing parameters on any videojs player:

```
        var opt = {};
        opt['debug'] = true;
        opt['id'] = player.id();
        opt['adTagUrl'] = 'http://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=228&LR_SCHEMA=vast2#sthash.aZO6xZYl.dpuf';
        opt['nonLinearWidth'] = player.width();
        opt['nonLinearHeight'] = player.height();
```

Do you know how I can fix it?

this ad works fine here:
https://developers.google.com/interactive-media-ads/docs/vastinspector_dual

Preroll and postroll work.

**Comment by shawnbuso** [comment]
Moderately good news - it looks like this is possible with the current version of IMA and video.js. There is a property on adsRenderingSettings called [useStyledNonLinearAds](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRenderingSettings.useStyledNonLinearAds) that renders the nonLinear with close and recall buttons. You can pass this to the plugin as follows:
`
var opt = {};
...
opt.adsRenderingSettings = {useStyledNonLinearAds: true};
`
I tested with your tag and I do see the close button. The only issue is that once the ad is minimized, the recall button is blocked by the controls. I'm going to see if it's possible to move that button above the controls when they show up, but I think it will be fairly non-trivial, so it might take some time.

**Comment by dacast** [comment]
perfect it works... thanks.
