### ISSUE TITLE
"google is undefined" error in Windows 10 UWP project 

### ISSUE THREAD

**Issue by rs-sean** [googleads/videojs-ima#224]
We slightly modified the [simple example](https://github.com/googleads/videojs-ima/tree/master/examples/simple), with IMA plugin and videojs-contrib-ads plugin included, and we were able to get it work fine in a browser (we can see video playing with pre-roll and mid-rolls). 

But once ported into a Windows 10 UWP project (Javascript-based), we're getting the following error: 

> Unhandled exception at line 1219, column 5 in ms-appx://e815aafe-3034-4f1f-b1de-fbf96af3e701/pages/playback/js/videojs.ima.js
> 
> 0x800a1391 - JavaScript runtime error: 'google' is undefined

It seems to indicate that Google API script is not available, but we do have the following reference in place: 
`<script src="http://imasdk.googleapis.com/js/sdkloader/ima3.js"></script>`

Any idea what could have caused this?

**Comment by shawnbuso** [comment]
Hi there,

Unfortunately, the IMA SDK doesn't support JavaScript-in-an-app implementations - we only currently support browsers (Chrome, Firefox, etc.).

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Hi there,

Unfortunately the IMA SDK doesn't support JavaScript-in-an-app implementations - we currently only support web browsers (Chrome, Firefox, etc.). We've found JavaScript performance in these kind of apps to be unpredictable at best, so it's not surprising to me that the SDK isn't behaving as expected there.

Thanks,
Shawn
