### ISSUE TITLE
Does videojs-ima work with youtube video?

### ISSUE THREAD

**Issue by coneits** [googleads/videojs-ima#235]
Hello.

This videojs-ima is nice plugin. It works well when I don't use youtube video.
But is that impossible to advertise some ads before playing youtube video?
Is that violet from IMA sdk policy or youtube policy?

Please let me know if you could help me on my issue. I'm in a bit urgent case.
Thanks.

**Comment by shawnbuso** [comment]
The IMA SDK does not support monetizing YouTube videos - for that you should use the built-in YouTube monetization as described [here](https://support.google.com/youtube/answer/72857?hl=en).
