### ISSUE TITLE
SWF ad not clicking through

### ISSUE THREAD

**Issue by anthonyadvertdigital** [googleads/videojs-ima#238]
I've setup everything correctly as far as I can tell, except when you click on the ad the ad stops and plays the video, instead of going to the click through for the ad.

I even setup an exact match of the advanced sample page so that I could test one of the tags. The sample tag works correctly.

The error coming up in firebug:
_Error: Permission denied to access property "toString"
http://imasdk.googleapis.com/js/core/bridge3.133.0_en.html#goog_1830347736
Line 564_

Test Page: _http://www.burst.co/test-page/_

Tag testing:
_http://pubads.g.doubleclick.net/gampad/ads?sz=800x450&iu=/179376284/burst_tier_1&cust_params=Adslot%3De&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=http://www.burst.co&correlator=[timestamp]_

**Comment by shawnbuso** [comment]
Hi there,

Have you made any changes to our advanced sample in your sample page? When I test in our advanced sample, modified to allow insecure VPAID ads, it's working fine, but I do see the issue on your page. If you've made changes to the example we can try to figure out which one is causing the issue.

Thanks,
Shawn

**Comment by anthonyadvertdigital** [comment]
The only changes made were locally hosting the css and js files (except for the videojs files).

**Comment by shawnbuso** [comment]
Hi there,

Sorry for the delayed response - the original advanced example does *not* allow insecure VPAID by default. If you make that change on your end, do you see the ad working? You'll need to add the following to the options you're passing to the plugin:

    {
      ...
      vpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE
    }

**Comment by shawnbuso** [comment]
Did this fix your issue? Let me know so I can close it out - thanks!

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still having a problem feel free to re-open. Thanks!
