### ISSUE TITLE
Hi!, need help for implement ima plugin for clappr player

### ISSUE THREAD

**Issue by sportexholdings** [googleads/videojs-ima#239]
Hello!, I need help for implement this plugin with clappr video player.I tried many times.but not succeed.
player link: https://github.com/clappr/clappr

Test link:  http://xaphanentertainment.com/clappr-ads-final/

**at this moment - ads are not loading with video player..can you help me for solved this issue...
is something i missed.**

Best,
Anuj

**Comment by shawnbuso** [comment]
Hi there,

This plugin is specifically for the video.js player, and it looks like you're not using that. For help with other players check out our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk), where you can get help for the IMA SDK in general.

Thanks,
Shawn
