### ISSUE TITLE
Autoplay not working When there is no ad.

### ISSUE THREAD

**Issue by TheRealKev1n** [googleads/videojs-ima#24]
Hello,

When there is an empty VAST response The autoplay doesn't work. It has something to do with the ad timeout. because when i set the timeout lower the autoplay works fine but then it doesn't have enough time to get the ads so there will never be a ad.

Kind regards,
Kevin

**Comment by shawnbuso** [comment]
Closing for lack of response. If you're still seeing the issue please let us know and we'll look into it.
