### ISSUE TITLE
Hi!, how do i run vpaid & vmap ads using your plugin 

### ISSUE THREAD

**Issue by sportexholdings** [googleads/videojs-ima#242]
Hi!, I have tried to run vpaid and vmap ads using your plugin.but it's not work.can you help me.what code do i need to used.also how do i insert mid roll ads.

sample vpaid tag:

http://vpc.altitude-arena.com/vpc.xml?uid=IBSLQII4VD1QDEQ6QJ0S6H4NU4&page_url=[REPLACE]&cb=[REPLACE]&ref_page_url=[REPLACE]&player_width=[REPLACE]&player_height=[REPLACE]&video_duration=[REPLACE]&media_file_url=[REPLACE]&media_file_title=[REPLACE]&media_description=[REPLACE]&media_file_id=[REPLACE]

Thanks
shawan

**Comment by shawnbuso** [comment]
Our plugin works with VPAID and VMAP out of the box, so you should be able to just provide the tag, but it looks like your tag has some issues - I'm seeing lots of errors in the console about the tag having trouble finding a compatible ad. You'll need to work with the folks who set up your ad tag (or if you set it up, the ad server that you got the tag from ) to troubleshoot and see why you're not getting any compatible ads back from your request.

**Comment by sportexholdings** [comment]
Hi!,
Thanks for your response..
Can you  tell me is this tag also work with your plugin.

1st vpaid tag
http://vast.ssp.optimatic.com/vast/getVast.aspx?id=lUsbpbQtY6JC&zone=default&pageURL=[referrer_url]&pageTitle=[PAGE_TITLE]&cb=[timestamp]


3rd tag
http://ads.adaptv.advertising.com/a/h/3Hqvk5ktAHMnxQN+jlYW9O1L9cVhyf71gPqMKkt8c9w=?cb=[CACHE_BREAKER]&pageUrl=EMBEDDING_PAGE_URL&description=VIDEO_DESCRIPTION&duration=VIDEO_DURATION&id=VIDEO_ID&keywords=VIDEO_KEYWORDS&title=VIDEO_TITLE&url=VIDEO_URL&eov=eov

4th tag
http://vast.videe.tv/vast-proxy/?aid=20606&content_page_url={content_page}&player_width={player_width}&player_height={player_height}&vid_duration=300&cb={cb}

5th tag
http://vast.yashi.com/11176&vid_id=[video_id]&vid_title=[video_title]&vid_url=[referrer_url]&player_width=[player_width]&player_height=[player_height]&page_url=[referrer_url]

How do you replace the value..

Kindly regards!,
shawan

**Comment by shawnbuso** [comment]
All of your tags look VAST compliant, so they should work. You can test them out in our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/). I'm not sure what you mean by "how do you replace the value" - to which value are you referring?

**Comment by sportexholdings** [comment]
I mean macros player hight,width,page url etc... as this link:  https://support.jwplayer.com/customer/portal/articles/1434340-ad-tag-variables

Like jw player does?

**Comment by shawnbuso** [comment]
The plugin doesn't support that out of the box, so you would need to set that on the tag programmatically before you provide it to the plugin

**Comment by sportexholdings** [comment]
Ok!,Thanks
