### ISSUE TITLE
Liverail VPAID is not working with setVpaidAllowed(true)

### ISSUE THREAD

**Issue by mente** [googleads/videojs-ima#25]
Here's an [example](http://jsfiddle.net/mente/odac8awe/1/). I have VPAID enabled using global shortcut:

``` javascript
google.ima.settings.setVpaidAllowed(true); 
```

Looks like due to VPAID caveats in IMA sdk it just does not work. . Error says `Uncaught Error: Invalid JSON string: lrHandshakeResponse=ÚÈîv`

Error comes from [this source](http://tpc.googlesyndication.com/pagead/js/loader7.html?http://cdn-static.liverail.com/js/LiveRail.AdManager-1.0.js%3fLR_PUBLISHER_ID=1331&LR_FORMAT=application/javascript&LR_AUTOPLAY=0&LR_CONTENT=1&LR_VERTICALS=international_news&LR_TAGS=vpaid). IMHO IMA sdk tries to load video file as json but I can be wrong.

**Comment by ocundale** [comment]
I hit this exact same issue and did some investigation- You will get this same problem using the Google IMA SDK whether on the Video Suite Inspector or via the video-js IMA plugin.
I think the problem is lies with a postMessage that the Liverail Ad Manager posts from the script within handshake.html. 
Has anyone got in touch with Google about this issue? I expect it might be something they want to fix...
Cheers :)

**Comment by mente** [comment]
I did. They said is issue in liverail said so there's nothing they can do
6 лют. 2015 19:15, користувач "Oli Cundale" <notifications@github.com>
написав:

**Comment by ocundale** [comment]
@mente - I think they are working on it, after contacting them I was told "we have reached out to Liverail and we are working on solving the issue together."

**Comment by mente** [comment]
Sounds great. I hope they notify on results in this issue

**Comment by shawnbuso** [comment]
Hi all,

Are you still seeing this issue? I tried testing with the original example but I'm getting an ad server config error.

Shawn

**Comment by ocundale** [comment]
I am not seeing this specific error anymore and I see a preroll ad, but there are still console errors... I assume these are being worked on after they were highlighted in the thread on the Support Forum:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/community?place=topic%2Fima-sdk%2FixIIbrVHv2A%2Fdiscussion

If you need any further info, I am happy to help.

**Comment by shawnbuso** [comment]
The only remaining errors I'm seeing are CORS errors, which we can't fix - you need to change the configuration of your ad server to allow tpc.googlesyndication.com to request data:

"XMLHttpRequest cannot load http://cdn.innovid.com/iroll/vast/1hk265. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://tpc.googlesyndication.com' is therefore not allowed access."

For more info you can see our [documentation on CORS](https://developers.google.com/interactive-media-ads/docs/sdks/html5/ads#cors).

**Comment by ocundale** [comment]
I am not seeing any CORS errors Shawn, but I believe the IMA is still not fully compatible with VPAID 2 JavaScript Creatives. The problems I mentioned in Support Forum are still present:
- Preroll ad is not clickable
- Ad time doesn't seem to be detected correctly

(https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector?player=h5&tag=%2F%2Fad4.liverail.com%2F%3FLR_PUBLISHER_ID%3D1331%26LR_SCHEMA%3Dvast2-vpaid%26LR_FORMAT%3Dapplication%2Fx-shockwave-flash%3Bapplication%2Fjavascript)

**Comment by shawnbuso** [comment]
Hi all - I'm cleaning up old issues tagged as "IMA issue" - is this still an issue / are you still looking for a resolution here? I tried requesting your sample VAST tag above but it's not returning anymore. Let me know - thanks!

**Comment by mente** [comment]
I, as original creator, not working on it anymore for over 2 years. Maybe someone else has something to add.
