### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'vdata1470922997360' of nullgetElData

### ISSUE THREAD

**Issue by raasumy** [googleads/videojs-ima#261]
I got videojs player with ima plugin.
After player is disposed and then created again I get this error after trying to start preroll. It's being traced continiously.
		 * video.js:20179 Uncaught TypeError: Cannot read property 'vdata1470922997360' of nullgetElData
		 * @ video.js:20179on
		 * @ video.js:20735on
		 * @ video.js:3878player.ima.resetIMA_
		 * @ videojs.ima.js:647player.ima.setContent
		 * @ videojs.ima.js:703parseVAST
		 * @ player.js:945onTagReady
Any ideas on how this can be treated properly?

**Comment by shawnbuso** [comment]
Do you have a sample page I can take a look at? It looks like an error within the video.js player when you try to change the content.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing issues please feel free to re-open. Thanks!
