### ISSUE TITLE
iOS Safari: postroll freeze

### ISSUE THREAD

**Issue by mkhazov** [googleads/videojs-ima#265]
iOS 9.3, Safari

**Steps to reproduce:**
- Use [Post-roll tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=)
- Watch or rewind the video to the end.

**Actual results:**
- Only the first frame of post-roll is displayed, playback stucks. Player controls are not displayed.
  or
- Post-roll is playing, but when it ends - Player controls are not displayed. Can not replay the video.

This can be reproduced using our videojs bundle:
- `git clone -b ads_ios https://github.com/Go-Promo/wjplayer.git`
- `cd wjplayer && npm i && npm start`
- Open Ads sample
- above steps

**Comment by shawnbuso** [comment]
Are you seeing this with iPhone or iPad? Which example are you using to test? Thanks!

**Comment by mkhazov** [comment]
iPad
I use https://codepen.io/mkhazov/pen/akANNq

Can't test it using https://googleads.github.io/videojs-ima/examples/advanced/ because it's not working on iPad (touchend event seems to be not working)

**Comment by shawnbuso** [comment]
I'm seeing the advanced example working on my iPad - what is wjlpayer? Is that something you wrote or a different library? My guess is that something is going wrong somewhere in there.

**Comment by mkhazov** [comment]
Hmm, I checked the advanced example again on my iPad - now it's working but postroll freezes on its last frame (the one with text "Postroll 1 Second") and ima-container is not being removed.

**Comment by shawnbuso** [comment]
Ah ok - I think this is expected but we can consider it as an FR. When the post-roll finishes we don't have anything else to put in the player, so we just leave it in there and you see the last frame.

**Comment by shawnbuso** [comment]
FR: Remove the ad container after a post-roll so the user isn't stuck staring at the last frame of the ad.

**Comment by mkhazov** [comment]
Any update on this issue?

**Comment by shawnbuso** [comment]
I just sent PR #313 to fix the issue of the last frame sticking around - are you still seeing a freeze at the beginning of the post-roll? I wasn't able to repro that on my end.

**Comment by mkhazov** [comment]
Yes, the problem still persists.

When post-roll starts playing, adtimeout gets triggered (although I set timeout to 10000):
```
"ads"
"adtimeout triggered: ads-ready? -> content-playback"
```
Post-roll is playing, but when it ends - I can replay post-roll, but not the original video. It happens because post-roll video is set as the player source.

![2016-12-02 12 22 26](https://cloud.githubusercontent.com/assets/3628510/20828772/2896b3a8-b88a-11e6-8411-92d08c0aa116.png)

**Comment by shawnbuso** [comment]
Ah ok it looks like we're confusing the video.js player by re-using it to play our post-roll. I should be able to get this fixed but it will take a bit longer than the previous fix. Are you still seeing issues with the post-roll freezing at the *beginning* of its playback? It looks like now the only issue is that it hangs around when it's done playing, but I want to make sure.

**Comment by mkhazov** [comment]
Only when it's done playing. Thanks

2 дек 2016 г. 6:13 PM пользователь "Shawn Busolits" <
notifications@github.com> написал:

**Comment by shawnbuso** [comment]
OK I just submitted a PR that should resolve this - let me know if that works for you.

**Comment by mkhazov** [comment]
Thanks. Now the postroll kind of begins its playback for a moment and then the player src gets replaced with the original source, and the original video continues its playback.
If you can't reproduce this, I will try to debug and fix this when I have time.

**Comment by shawnbuso** [comment]
Hmm that's odd - that would suggest that the SDK is firing all ads complete before the post-roll actually completes. Are you seeing this with our hosted sample on googleads.github.io/videojs-ima?

**Comment by mkhazov** [comment]
I'm sorry, I was seeing the last mentioned problem on my side because of wrong configuration. Thank you for help
