### ISSUE TITLE
Simple example doesn't work on FF (Private mode)

### ISSUE THREAD

**Issue by svitlanaAntoniuk** [googleads/videojs-ima#267]
https://googleads.github.io/videojs-ima/examples/simple/
example does not work on FF (Private mode).

Errors in console:
AdsLoader error: AdError 1012: Unable to request ads from server due to network error.videojs.ima.js:323:7
The resource at "https://pagead2.googlesyndication.com/pagead/gen_204?error=1012&lid=7&sdkv=h.&e=420706010&id=ima_html5&c=2682089557129327&domain=googleads.github.io" was blocked because tracking protection is enabled.[Learn More]

**Comment by shawnbuso** [comment]
It looks like Firefox is blocking our ad server in Private mode. I'm not sure that there's anything we can do about that - the content video plays as expected, we just don't get an ad.

See https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection

**Comment by svitlanaAntoniuk** [comment]
I tried with another VAST document and other adverts urls. Got the same.

**Comment by shawnbuso** [comment]
That link says Mozilla "will block content loaded from domains that track users across sites" in private mode, so if you're using any major ad server odds are it falls under that categorization.
