### ISSUE TITLE
VAST event is tracked only once during ad play

### ISSUE THREAD

**Issue by svitlanaAntoniuk** [googleads/videojs-ima#268]
I'm testing sample https://googleads.github.io/videojs-ima/examples/simple/
and found that VAST events are tracked only once. 
That's ok for events such 'start', 'firstQuartile' and so on. 
But there are events which can be fired more than once during ad: 'play', 'pause', 'mute', 
and I believe requests should be sent to server every time these events are fired.

**Comment by shawnbuso** [comment]
This is working as intended according to the IMA SDK - the JavaScript events should be fired every time for those events you mentioned, but the tracking URLs will only be pinged the first time the event happens.

**Comment by svitlanaAntoniuk** [comment]
Can't find any information in IMA SDK why URLs only pinged the first time the event happens.
Found  in VAST v3_0 (http://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf): 
• mute: the user activated the mute control and muted the creative.
• unmute: the user activated the mute control and unmuted the creative.
• pause: the user clicked the pause control and stopped the creative. 

There is no any info about first time event also.

**Comment by shawnbuso** [comment]
IIRC the VAST spec doesn't specify either way - we wanted to prevent polluting ad server logs with a ton of pause/mute/etc. requests, so we elected to only report them the first time they happen.

**Comment by svitlanaAntoniuk** [comment]
I see. Thanks for explanation.
