### ISSUE TITLE
Compatibility with VMAP timeOffset (percentages)

### ISSUE THREAD

**Issue by theighost** [googleads/videojs-ima#269]
Hello guys,

I'm trying to deliver a mid-roll that would appear in the middle of the content video no matter the length of that video. The VMAP standard provides support for a percentage to be added as a value to the **timeOffset** attribute, but it doesn't seem to work with this plugin.

Example of the XML:
`<vmap:AdBreak timeOffset="50%" breakType="linear" breakId="block_2">
<vmap:AdSource id="source_2" allowMultipleAds="false" followRedirects="true">
<vmap:VASTAdData>
</vmap:VASTAdData>
</vmap:AdSource>
</vmap:AdBreak>`

I tried to use "50%", or "50", nothing like that seems to work, in the console I see the following error:

> AdsLoader error: AdError 900: Cannot parse the timeOffset value for the adslist response: 50.

Check page 16 in the standard (can't search for it by ctrl+f):

http://www.iab.com/wp-content/uploads/2015/06/VMAP.pdf

Thanks a bunch

**Comment by shawnbuso** [comment]
Hey there - unfortunately that use case is not yet supported by the IMA SDK. See the [Video Features & SDK Compatibility page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility#vmap-footnote), footnote 4:

"The following VMAP features are not yet supported: ... Time offsets other than hh:mm:ss or "start" and "end""

**Comment by theighost** [comment]
Thanks a lot Shawn for clearing it up, sorry about the confusion.

**Comment by adamellsworth** [comment]
Is this still the case? I can't find reference to this on the current docs.

**Comment by shawnbuso** [comment]
This is still the case - IMA does not yet support percentage time offsets for VMAP.

**Comment by jnthnclrk** [comment]
Can we get a mid/ 50%?

**Comment by shawnbuso** [comment]
The IMA SDK is still working on support for percentage time offsets. Once they add it to the SDK, we'll pick it up here automatically.

**Comment by jnthnclrk** [comment]
Great!

**Comment by Vladislavik** [comment]
any news about %?

**Comment by adamellsworth** [comment]
Wanted to check in on this as well and ping the devs. Docs still state `Time offsets other than hh:mm:ss or "start" and "end"` so i'm guessing it was never implemented.
