### ISSUE TITLE
Ads fullscreen icon broken

### ISSUE THREAD

**Issue by yshterev** [googleads/videojs-ima#273]
Bug can be observed in the [simple demo](https://googleads.github.io/videojs-ima/examples/simple/).

1. When the ad starts click on the fullscreen icon - **RESULT:** The icon disappears, but the button is still there
2. Click again on the empty button to turn off ad fullscreen - **RESULT:** Button goes to the left with wrong icon character with messed up classes.

Something is probably wrong with adding/removing classes to the fullscreen button, because after **Step 2** one of the classes is just `-div` instead of `ima-fullscreen-div`

**Comment by kachnitel** [comment]
I believe the issue is in the regex function (`getClassRegexp_`) that removes the `ima-fullscreen` class capturing the `ima-fullscreen-div` in the match. 
`\bima-fullscreen\b` regex does actually match the part of `ima-fullscreen-div` as `-` is considered a word boundary (`\b`)
