### ISSUE TITLE
libpepflashplayer.so: 0x42742D89 is not a valid instance ID.

### ISSUE THREAD

**Issue by arpu** [googleads/videojs-ima#276]
libpepflashplayer.so: 0x42742D89 is not a valid instance ID

any idea how i can fix this problem?

.

**Comment by shawnbuso** [comment]
I haven't seen anything like this before - do you have a test page where I can replicate?

**Comment by shawnbuso** [comment]
Closing for lack of response - if you're still seeing this issue please feel free to re-open. Thanks!
