### ISSUE TITLE
iPhone sample ads click doesn't work when in "touch" mode

### ISSUE THREAD

**Issue by maxim-novikov** [googleads/videojs-ima#277]
Hello,

When I use your sample for iPhone - https://googleads.github.io/videojs-ima/examples/iPhone/ - it works flawlessly in browser, but as soon as I switch to test in chrome's phone emulation, the problems start to appear, the biggest one being ads click not being registered. Instead of taking me to the Video Suite Inspector page, the click just pauses the video and the console throws the following error messages:

```
ima3.js:275 Uncaught TypeError: document.createTouch is not a function
ima3.js:275 Uncaught TypeError: Cannot read property 'apply' of undefined

```
I've tried applying startEvent switching from "click" to "touchend" in case that's a related issue, as in your simple example, but that doesn't change anything for me. Am I doing something wrong or is that a known bug with some kind of workaround I cannot find?

**Comment by shawnbuso** [comment]
We do have a few known issues using the iPhone sample on anything but iPhone, including Chrome emulating iPhone. If you can I recommend testing on either a physical iPhone or the iPhone emulator built into OSX.
