### ISSUE TITLE
VPAID/VAST Waterfalling

### ISSUE THREAD

**Issue by shogemuk** [googleads/videojs-ima#278]
Hi Guys,
I would like to be able to detect if an ad is not returned in VAST tag, and then be able to cascade to another tag and attempt to play a different ad.  Is this possible? If yes does anyone have any examples of how to do this?

Thanks in advanced

**Comment by shawnbuso** [comment]
Hi there,

I don't think there's a good way to do this in code - I think the better way would be to do this via VAST redirects. You could set up a tag that returns multiple ads, where each one redirects to the tag you want to request. If the first fails, the SDK will try the second, and so on and so on until it runs out of ads. A sample response would look something like this:

    <VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
    <Ad id="1">
    <Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
    <![CDATA[ TAG_ONE ]]>
    </VASTAdTagURI>
    <Error>
    <![CDATA[https://www.error_tracker.com]]>
    </Error>
    </Wrapper>
    </Ad>
    <Ad id="2">
    <Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
    <![CDATA[ TAG_TWO]]>
    </VASTAdTagURI>
    <Error>
    <![CDATA[https://www.error_tracker.com]]>
    </Error>
    </Wrapper>
    </Ad>
    </VAST>

If you have any questions let me know!

Thanks,
Shawn

**Comment by shogemuk** [comment]
Hi Sean, Thanks so much for the reply.  I tried your suggestion by creating a vast.xml file and linking to it via adTagUrl but I keep receiving the following error

`XMLHttpRequest cannot load http://localhost/videojs/assets/js/vast.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://imasdk.googleapis.com' is therefore not allowed access`

I've done some research and I found out that I need to enable CORS in order for this to work but I am not sure exactly where or how to enable it.  Can anyone help please?

Thanks again

Here is my xml 
`<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="2.0"/>
<Ad id="1">
<Wrapper>
<AdSystem>AD_SYSTEM</AdSystem>
<VASTAdTagURI>
<![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=]]>
</VASTAdTagURI>
<Error>
<![CDATA[https://www.error_tracker.com]]>
</Error>
</Wrapper>
</Ad>
<Ad id="2">
<Wrapper>
<AdSystem>AD_SYSTEM</AdSystem>
<VASTAdTagURI>
<![CDATA[https://pubads.g.doubleclick.net/gampad1/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=]]>
</VASTAdTagURI>
<Error>
<![CDATA[https://www.error_tracker.com]]>
</Error>
</Wrapper>
</Ad>
</VAST>`

**Comment by shawnbuso** [comment]
CORS settings will depend on your particular server and configuration. I'm assuming you won't be loading the VAST from localhost when you push to production, so I would try again with the ad server you plan on using to see if they're already configured for CORS. If not you can reach out to them with this error info and they should be able to update the configuration for you.

**Comment by shogemuk** [comment]
Hi Shawn, Thanks again for the feedback.  I've noticed that there is one flaw with this method and that is if both feeds work then it will play two adverts.
Is there a way to break out if the first feed works or to tell videojs to only play one ad at most?

Thanks again

**Comment by shawnbuso** [comment]
Sorry about that - I completely forgot one part of the response. What you're trying to do is called waterfall, so we can add the waterfall extension so it will only request one ad. I've modified the response below to include that. The important bit is in the `<Extensions>` tags for each ad.

<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
    <Ad id="1">
    <Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
    <![CDATA[ TAG_ONE ]]>
    </VASTAdTagURI>
    <Error>
    <![CDATA[https://www.error_tracker.com]]>
    </Error>
    <Extensions>
    <Extension type="waterfall" fallback_index="0"/>
    </Extensions>
    </Wrapper>
    </Ad>
    <Ad id="2">
    <Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
    <![CDATA[ TAG_TWO]]>
    </VASTAdTagURI>
    <Error>
    <![CDATA[https://www.error_tracker.com]]>
    </Error>
    <Extensions>
    <Extension type="waterfall" fallback_index="1"/>
    </Extensions>
    </Wrapper>
    </Ad>
    </VAST>

**Comment by peterrei** [comment]
maybe you can develop an ads plugin and configure it with a tag array as follow:
ads: {
    schedule: [
        {
            position: 'pre-roll',
            server: {
                tags: [
                    'https: //adserver1.com/pathto/vast.xml',
                    'https: //adserver2.com/pathto/vast.xml',
                    'https: //adserver3.com/pathto/vast.xml',
                    'https: //adserver4.com/pathto/vast.xml'
                ]
            }
        }
    ]
}

you can change the position in mi-roll or post-roll if you need.

When you receive an AdError event (you receive an AdError also when vast is "empty") from the player you should proceed with the next tag of array.

**Comment by shawnbuso** [comment]
We try not to replicate anything that's already possible in VAST itself - since it's supported in VAST with waterfalling, I don't think we'll be adding it to the plugin itself.

**Comment by codepreneur** [comment]
@shawnbuso what you suggested works perfectly however, most tags require dynamic parts like so: `http://some.vast-tag.com/whatever?pid=14409&subid=3&ad_type=in&player_width=[REPLACE_ME]&player_height=[REPLACE_ME]&timestamp=[REPLACE_ME]&page_url=[REPLACE_ME]`

How can I provide those parameters at a time of firing ?

**Comment by shawnbuso** [comment]
How are you getting this response to the SDK? Are you getting this returned as a request to an ad tag URL, or are you setting the VAST response directly? If the former, you'll need to work with your ad server to see if you can put those parameters on the initial request and have them propagated to the nested tags that get returned in the response. If the former, you should be able to just do a find and replace on the string that you're giving to the SDK to set those parameters.

**Comment by tonykor** [comment]
Hello Shawn, where can we find the specification for waterfall extension. Thanks.

**Comment by shawnbuso** [comment]
The waterfall extension is something specific to the IMA SDK and we unfortunately don't have an external spec. It works as I showed in the example above:

```
<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
<Ad id="1">
<Wrapper>
<AdSystem>AD_SYSTEM</AdSystem>
<VASTAdTagURI>
<![CDATA[ TAG_ONE ]]>
</VASTAdTagURI>
<Error>
<![CDATA[https://www.error_tracker.com]]>
</Error>
<Extensions>
<Extension type="waterfall" fallback_index="0"/>
</Extensions>
</Wrapper>
</Ad>
<Ad id="2">
<Wrapper>
<AdSystem>AD_SYSTEM</AdSystem>
<VASTAdTagURI>
<![CDATA[ TAG_TWO]]>
</VASTAdTagURI>
<Error>
<![CDATA[https://www.error_tracker.com]]>
</Error>
<Extensions>
<Extension type="waterfall" fallback_index="1"/>
</Extensions>
</Wrapper>
</Ad>
</VAST>
```

You can return multiple ads in one response (these are wrappers, but they don't have to be) and put the waterfall extension with increasing indexes in each ad. It will try the first, and if that fails move onto the second, etc.
