### ISSUE TITLE
Ads hang until timeout on Android Chrome 53

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#281]
Test page: https://dev.player.dotstudiopro.com/share/57be8615d66da81809a33855?targetelm=.player&companykey=57bdf792d66da8b744a33855&autostart=false

Ads play perfectly fine on iOS, including when autoplay is set to true (as long as it starts off muted).  On Android Chrome 53, the first frame of the ad shows up and the ad player acts like it's going to do something.  It does not.

If you press the pause button (on the ad player), then press play, the ad plays.  If you have autoplay set, even those actions don't cause the ad to do anything.

Tested with Android Chrome 53 and iOS 10 with whatever version of Safari that entails.

**Comment by shawnbuso** [comment]
The IMA SDK is still working on supporting auto-play on mobile. Until then, you'll still need to call initializeAdDisplayContainer as the result of a user action to initialize the ad player.

**Comment by stoicbuddha** [comment]
Is there an ETA on when that will be completed?  Are there any workarounds?

**Comment by shawnbuso** [comment]
I don't have any timelines to share as of now, and there aren't any workarounds that I now of. The issue is that the IMA SDK isn't using your player to play ads, it's using a different player layered on top of yours, and that player also needs to be set up for inline playback. That player isn't exposed outside of the SDK, so you don't have access to it to set it up for inline playback.

**Comment by stoicbuddha** [comment]
Are there any updates on this issue?  The closest thing to a workaround I've found for it is loading the ad and binding the actual playing of the ad to a 'touchend' on the window and/or player so that no matter where they touch on the screen, it'll play.  I'd love a more elegant solution though.

What's kind of weird is that it works perfectly fine in iOS 10.  Is it possibly inheriting something in Safari that it's not in Android Chrome?

**Comment by shawnbuso** [comment]
Still no ETA unfortunately - we did add support for inline playback on Safari in the IMA SDK, and we're working on Chrome now.

**Comment by stoicbuddha** [comment]
Understandable.  For anybody who runs across this prior to the Chrome support being added, what I did was:

1. `player.ima.setContentWithAdTag()` first, then `player.ima.initializeAdDisplayContainer()`. I have some other processes that I do after those, but I get it right up to the point where the ad is supposed to play (this is in Android Chrome *only*).

2. Bound `player.ima.startFromReadyCallback();` to `$(window).one("touchend")` and drew an overlay over the player (because loading the ad overlays the ad player on top of the player, making it impossible to press play) and bound a `touchend` event to that overlay, removing it after it is touched (and when the window is touched too).

I don't know if it's the *proper* way to do it, but it works for me, for the moment.

**Comment by sonicsoul** [comment]
I have the same problem here... 

Before I used the IMA SDK, I first checked if I could create a video element programmatically and autoplay it. That worked perfectly with the onion´s vast-plugin but does not with the IMA SDK.  

```
var video = document.createElement('video');
video.play();
return video.paused;

```
If this returned "true" I would know I could start with autoplay. 

If false, I added an eventlistener to check if the page was scrolled. 

The scroll handler then first loads the player via myPlayer.load() and sets its source after a timeout of 1000ms. So in my opinion the play() method is bound to a user gesture then.. isn´t it? 

When I debug my Samsung S4 with Chrome, the script already breaks at the first "video.play();"
while other browsers just ignore it and the function returns "true" because the play() method did not work at all. On Android the function instantly throws an error instead of just returning something. 
Do you see a way to get this approach back working again? 

This is the script I use (out of context now but should explain what I do)

```
videojs('im_video').ready(function(){
if (mediaPlaybackRequiresUserGesture()) {
console.log('user gesture REQUIRED'); 
                window.addEventListener('touchenter', removeBehaviorsRestrictions);
                window.addEventListener('touchmove', removeBehaviorsRestrictions);
                window.addEventListener('scroll', removeBehaviorsRestrictions);
                window.addEventListener('keydown', removeBehaviorsRestrictions);
                window.addEventListener('mousedown', removeBehaviorsRestrictions);
                window.addEventListener('touchstart', removeBehaviorsRestrictions);
            } else {
                setSource();
            }
});
// try to create and play a video via script, return value will tell you if autoplay is possible or not
    function mediaPlaybackRequiresUserGesture() {
        var video = document.createElement('video');
        video.play(); // -----> here is where Android breaks and all the others don´t. 
        return video.paused;
    }

//set the source 
function setSource(){
           myPlayer.src("miniblack.webm");
           myPlayer.play();   
    }

//after interaction event was detected, first load() the videoplayer, then set its source after some timeout
    function removeBehaviorsRestrictions() {
        myPlayer.load();
        window.removeEventListener('touchenter', removeBehaviorsRestrictions);
        window.removeEventListener('touchmove', removeBehaviorsRestrictions);
        window.removeEventListener('scroll', removeBehaviorsRestrictions);
        window.removeEventListener('keydown', removeBehaviorsRestrictions);
        window.removeEventListener('mousedown', removeBehaviorsRestrictions);
        window.removeEventListener('touchstart', removeBehaviorsRestrictions);
        setTimeout(setSource, 1000);
    }     
```

**Comment by sonicsoul** [comment]
I see this is because of the SDK using its own player on top of the content player. 
How could I tell the SDK that a user gesture happened before I try to start the ad? I am developing a special ad banner that opens a video player when the user scrolls into view. I want to request the ad after the banner has opened to avoid making a request in case the user does not scroll enough or leaves the page before the banner opens up.

**Comment by sonicsoul** [comment]
Any news on this topic?

**Comment by shawnbuso** [comment]
There's still no progress on this on our end - does @stoicbuddha's solution work for you in the interim?

**Comment by sonicsoul** [comment]
Yes, it does, I had to change a little bit more of my code but in the end it is what @stoicbuddha suggested. The main thing was initializing the AdDisplayContainer as a result of "touchstart" and startFromReadyCallback() as a result of "touchend". I am building a banner that opens up when the user scrolls into view, so its a bit tricky and different to the usual case of just opening a website with a player. For example, firing requestAds() must not happen if the user does not scroll enough. etc..  anyway, thank you for that great plugin! Would love to hear a solution from your side soon ;-)

**Comment by stoicbuddha** [comment]
@shawnbuso I ended up not being able to go that direction because it only works for preroll ads, and is not really good for midrolls or postrolls, or even multiple preroll ads.

Is there somebody further up the chain that can be bugged about this?  Ads not playing in Android is kind of a *very large issue* and we haven't seen movement on it in 4 months.

**Comment by shawnbuso** [comment]
If I recall correctly the issue is not that ads don't play at all, just that they don't auto-play. Is that still correct? We are actively working on adding auto-play support for mobile platforms to the SDK.

**Comment by stoicbuddha** [comment]
Yes, it's just autoplay, as far as I'm aware.  And awesome, thanks for the update!

**Comment by stoicbuddha** [comment]
@shawnbuso I'm actually having issues with non-autoplay ads as well.  It's possible that my implementation is wonky, but I have a couple of times where I have to call `player.play()` and of course, the browser won't have any of it.  It all works fine in iOS, since we set up iOS as autoplay. Should I open another issue for this?

**Comment by shawnbuso** [comment]
Yea let's open a new issue since this one seems to be autoplay-centric. Thanks!

**Comment by Sivitas** [comment]
Has there been any updates to this or roadmap for when it will be resolved? Autoplay isn't working for me on both ios and android. Looking at the inspector on mobile, I see the playinline attribute on the video elements, but no autoplay nor muted attributes set.

**Comment by shawnbuso** [comment]
Hi all - I'm cleaning up old issues marked as "IMA issue" - is this still an issue for you / are you still looking for a resolution here? I tried the original test page but it looks like it's no longer loading. Let me know!

**Comment by stoicbuddha** [comment]
No, this is no longer an issue due to an update to the IMA SDK a month or two ago.
