### ISSUE TITLE
Ads player ignoring any ads after 2nd play

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#285]
Video player: http://video.bossip.com/

I have a player instance that utilizes a recommendation engine to feed videos to the player constantly.  At the start of each video, there is an ad.  The first two videos have an ad play just fine (there is one that is missing an ad tag, so sometimes it just skips and the third one plays). But regardless, I get 2 ads max.  I need as many ads to play as I throw at the plugin.  I'm doing plenty of logging, so I know the process to get the ad is working fine.  It just seems to completely ignore it.

**Comment by shawnbuso** [comment]
Do you have instructions to replicate this behavior on your page? I tried watching a few videos in a row, but after the first video I get "Video tag undefined for  moreblah blah" in the console, which to mean sounds like you don't have an ad tag associated with the upcoming video.

**Comment by stoicbuddha** [comment]
That was the one that has an issue with the ad tag.  That one video *should* be the only one that has the issue (every other one comes up properly, as far as I'm aware.)

**Comment by shawnbuso** [comment]
OK I am seeing that behavior now - I'm not sure why it was different the first time I tested.  I've got a few questions to help troubleshoot:

Are you requesting the same tag repeatedly?
If so, are you using setContentWithAdTag like we do in our playlist example? That will ensure the IMA SDK is reset properly for another ad request.
Can you show me where the code is responsible for setting your ad tag after the first video?

Lastly, would you be able to modify that page to load ima3_debug.js and to set the debug flag for the video.js IMA plugin to true? I'm seeing the third and all following ads fail. I can tell you that ads 4 and beyond are failing because once ad 3 fails, the SDK stops trying to request ads. I'm not sure, however, why the third ad is failing. Hopefully the debugging output will give us a clue.

**Comment by stoicbuddha** [comment]
*Are you requesting the same tag repeatedly?*
The initial wrapper is slightly different each time, as we include keywords and title to pass on to the unwrapped tag.  So, for example, one might by "site.com/someadtag.php?title=CoolVideo" while another might be "site.com/someadtag.php?title=AdequateVideo".

*If so, are you using setContentWithAdTag like we do in our playlist example? That will ensure the IMA SDK is reset properly for another ad request.*  
As I mentioned, we aren't, but could this possibly help?  I basically call the same code each time to set up an ad, excluding the initial setting of player.ima after it's already created.

*Can you show me where the code is responsible for setting your ad tag after the first video?*
In our ad script in that frame (videojs-ima-ads.js), the setupAds() function loops through all of the ad breaks we have set for a video, then creates a new Ads() with the appropriate variables needed.  I then attach a .one('play') event to call adPlay(), which sets up player.ima if it's not already set up, displays the ads container, and then sets up various events and controls for the ad, along with hiding other control bars, etc.

*Lastly, would you be able to modify that page to load ima3_debug.js and to set the debug flag for the video.js IMA plugin to true?*
Done.

**Comment by shawnbuso** [comment]
Ah ok so there are a few points - first, the way you're handling mid-rolls isn't really supported by the plugin - you should have one and only one ad tag per video source. If you want to show mid-rolls, you need to use [VMAP](https://www.iab.com/guidelines/digital-video-multiple-ad-playlist-vmap-1-0-1/).

I think it would be a good idea to use setContentWithAdTag before we debug further - that will ensure that, among other things, the current AdsManager gets destroyed so the IMA SDK doesn't get confused with multiple AdsManagers hanging around. I think a combination of multiple tags per video and not properly resetting the SDK between videos is causing the issues. If you structure your page more like our [playlist example](https://github.com/googleads/videojs-ima/tree/master/examples/playlist) you should see better results.

**Comment by stoicbuddha** [comment]
*If you want to show mid-rolls, you need to use VMAP.*
I will do some looking into going that direction.  If I have any questions on it, I'll let you know.  The mid-rolls do work (there aren't any midrolls involving this particular page, though), although I'd rather just throw some XML in somewhere and have that part dealt with, honestly.

*I think it would be a good idea to use setContentWithAdTag before we debug further*
I have this working on my local and will be pushing up in an hour or so.  If I have further issues once I have this bit dealt with, I'll let you know.

**Comment by stoicbuddha** [comment]
Ok, so between my own experimentation and the use of `setContentWithAdTag`, I managed to get it working the way I needed it to.  I ended up setting up ads with the aforementioned function, then telling the player to change the source.  If I did it the other way around, there was an odd fight the player had with itself where it tried to play a new ad every 5 seconds.  I appreciate the help!
