### ISSUE TITLE
Player.js Issues - Preroll not working

### ISSUE THREAD

**Issue by jrglass** [googleads/videojs-ima#289]
Video is loading but I can't seem to get the preroll to work.
Works great on the test page: https://goo.gl/VL5SP4

All files are loaded according to the documentation but I'm confused on the player.js file. Is this a file I need to create or does it exist somewhere and I just need to update it with my ad code and video id?

Currently, I'm just creating a new file called player.js and loading it below the <video> tag along with the other js files.

**Comment by shawnbuso** [comment]
Yes, player.js is a file you would need to create. I'd recommend taking a look at our [simple sample](https://github.com/googleads/videojs-ima/tree/master/examples/simple). There "player.js" has been renamed to "ads.js," but everything else is more or less the same. Let us know if you have any more questions!

**Comment by jrglass** [comment]
Yup, I ended up using that example to get mine working.
Thanks for the help. She's working great!
