### ISSUE TITLE
Source not found issue

### ISSUE THREAD

**Issue by jrglass** [googleads/videojs-ima#290]
Randomly getting a "no compatible source found for this video issue" and on refresh the DFP ad and video plays fine. Any ideas why this might be happening or if this is a IMA issue or not? 

We are using the youtube plugin along with video.js.

![unnamed](https://cloud.githubusercontent.com/assets/5082721/19242025/a733ad28-8ece-11e6-989c-047c0959c86c.png)

Example: http://freeskier.com/videos/ski-season-just-unnofficially-started-jackson-hole

**Comment by shawnbuso** [comment]
Hi there,

You shouldn't be using IMA to monetize YouTube videos - for that you should be using [YouTube's monetization options](https://support.google.com/youtube/answer/72857?hl=en).

Thanks,
Shawn Busolits
IMA SDK Team

**Comment by bamboocreative** [comment]
@shawnbuso just want to be clear on this, videojs-ima does not support [videojs-youtube](https://github.com/videojs/videojs-youtube). Is that correct?

Thanks

**Comment by shawnbuso** [comment]
The IMA SDK in general does not support monetizing YouTube videos, so by extension the videojs-ima extension does not support it either. If you want to monetize YouTube videos I recommend this YouTube help center article - [How to earn money from your videos](https://support.google.com/youtube/answer/72857?hl=en).
