### ISSUE TITLE
Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities.

### ISSUE THREAD

**Issue by jgainfort** [googleads/videojs-ima#292]
Im using the following setup and receiving the error in from the title. The player is strictly HTML5 and playing back a HLS manifest.

```
player.ima({ id: <player_id>, adTagUrl: 'http://29773.v.fwmrm.net/ad/g/1?flag=+sltp-slcb+qtcb+aeti+exvt+emcr&nw=169843&mode=live&prof=169843:nbcu_allisports_mobile_linear&csid=allisports_motocross_html5_embed_live_tab_WNBC&caid=nbcs_97243&vdur=600&resp=vast3&metr=7;;slid=mid1&tpcl=MIDROLL&tpos=0&maxd=30&ptgt=a&cpsq=234&mind=30;', debug: true, adsRenderingSettings: { mimeTypes: ['application/x-mpegURL'] } });

player.ima.requestAds();
```

Now in the vast response there are 2 MediaFile objects

```
<MediaFiles>
<MediaFile delivery="streaming" height="0" type="application/f4m+xml" width="0">
<![CDATA[
http://olyhdliveextra-vh.akamaihd.net/z/NBCU_Sports_Group_-_Ads/985/883/NFL_PopularityContestMICROSOFTXBOX-NBCSports_US_30_ISV_01147465540797,9_3,8_70,8_40,8_22,8_14,9_9,9_6,00k.mp4.csmil/manifest.f4m?hdcore=3.1.0
]]>
</MediaFile>
<MediaFile delivery="streaming" height="0" type="application/x-mpegURL" width="0">
<![CDATA[
http://olyhdliveextra-vh.akamaihd.net/i/NBCU_Sports_Group_-_Ads/985/883/NFL_PopularityContestMICROSOFTXBOX-NBCSports_US_30_ISV_01147465540797,9_3,8_70,8_40,8_22,8_14,9_9,9_6,00k.mp4.csmil/master.m3u8
]]>
</MediaFile>
</MediaFiles>
```

Now I would understand this error if there wasn't an HLS manifest returned by the vast response. Am I missing a setting in the adsRenderingSettings property other than what Im currently using?

`adsRenderingSettings: { mimeTypes: ['application/x-mpegURL'] }`

**Comment by shawnbuso** [comment]
Hi there,

Are you able to repro with your tag in our [test player](http://googleads.github.io/videojs-ima/examples/advanced/)? It works there for me, so it might be an issue with your implementation.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Closing for lack of response -  if you still need help let us know!

**Comment by polyglot1** [comment]
facing the same problem

**Comment by Kiro705** [comment]
Hello @polyglot1 ,

Since this issue is ~6 years old, please explain the behavior you are seeing and how to reproduce it in a sample.

Thank you,
Jackson
IMA SDK team

**Comment by laty96** [comment]
To reproduce this with [test player](http://googleads.github.io/videojs-ima/examples/advanced/) I use this [xml](https://static.nanda.vn/tag/corejs/testhls/assets/adpod.xml) 
It the same as iab adpod example except the <Mediafile> path:
`<MediaFile id="222" delivery="streaming"  type="application/vnd.apple.mpegurl">
                <![CDATA[https://f12.admicro.vn/public/test_perormance_v2/11.m3u8]]>
              </MediaFile>`

**Comment by Kiro705** [comment]
Hello @laty96 ,

I do not think the "application/vnd.apple.mpegurl" mimetype is supported by the IMA SDK (not specifically an issue with this plugin). You may need to raise this issue on the [IMA technical forum](https://groups.google.com/g/ima-sdk), if you think it is a lack of support from the IMA side.

Please let me know if you have additional questions, and feel free to reopen the issue, if this issue is specific to the videoJS-IMA plugin.

Thank you,
Jackson
IMA SDK team

**Comment by geethu-rajasekharan** [comment]
I have the same issue. Here's my Mediafile:
<MediaFile id="GDFP" delivery="streaming" width="426" height="240" type="application/x-mpegURL" minBitrate="49" maxBitrate="8129" scalable="true" maintainAspectRatio="true">
<![CDATA[ https://redirector.gvt1.com/api/manifest/hls_variant/requiressl/yes/source/dclk_video_ads/id/de1df9ef46b9c301/itag/0/playlist_type/LIVE/acao/yes/mime/application%2Fx-mpegURL/ctier/L/ip/0.0.0.0/ipbits/0/expire/1754723455/sparams/ip,ipbits,expire,requiressl,source,id,itag,playlist_type,acao,mime,ctier/signature/3AB5A1E1B7E1E803B74566F9D03517F29B914FB6.0812F227CD8B461FAF1DBA5F792522A9E12DCF66/key/ck2/file/index.m3u8 ]]>
</MediaFile>
