### ISSUE TITLE
player button is not synchronize with audio

### ISSUE THREAD

**Issue by NatalieGabel** [googleads/videojs-ima#293]
Hi,

I am running instream ad inside google IMA player and It seems that there are few problems:
1.  the properties of the video like muted and volume are defined. How can  I know the initial state of the video? How can I know these values while the video is playing?
2. When the sound button of the player starts with no sound when the insecure option is chosen the video starts with sound
3.  When the sound button of the player starts with no sound  and we change the volume to 1 (and dispatch ad volume change event) the video starts unmuted (as it should) but the button of the player is not synchronized - it is still muted (secure and insecure mode)

ad tag for example: https://bs.serving-sys.com/Serving/adServer.bs?c=23&cn=display&pli=1073953433&ord=12121212

If you need additional please let me know

Thanks

**Comment by NatalieGabel** [comment]
remark regarding point 1: values are undefined of volume and muted in secure mode

**Comment by shawnbuso** [comment]
1 is a known issue, and we're working on fixing it in the IMA SDK itself.

Can you clarify points 2 and 3 for me? When you talk about the "player", are you talking about the content player or the player for the video portion of your VPAID? Could you give me steps to repro the issue? e.g. load this tag, click play, click mute, see X but expect Y. Thanks!

**Comment by NatalieGabel** [comment]
Hi, thanks for the reply. 
Regarding point  1 - Do you have estimation when it will be fixed?
The other points I'll detail the phases:
Problem -> the state of the mute button of the player is not synchronized with the audio

Scenario 1
a. Open the following URL - https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector?hl=iw&tag=https%253A%252F%252Fbs.serving-sys.com%252FServing%252FadServer.bs%253Fc%253D23%2526cn%253Ddisplay%2526pli%253D1073982496%2526ord%253D12345%2526cim%253D1
b. click on Test ad (relevant for both secure and insecure mode)
c. Click on Audio off -> behave as it should: video is muted and mute button of the player is in state mute (UI: X is displayed)
d. Click on Audio on -> video is unmuted but state of the mute button of the player is not changed

Scenario 2
in our code we check if we have value of volume from video. if not (like in IMA secure case) our default is 1 and we dispatch AdVolumeChange event to the player.
Therefore, I expect the video to start unmuted and that the mute button of the player will be in unmute state, even if user set it before to muted (unless setAdVolume is sent which is not the case)
Steps to reproduce:
a. Open the following URL - https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector?hl=iw&tag=https%253A%252F%252Fbs.serving-sys.com%252FServing%252FadServer.bs%253Fc%253D23%2526cn%253Ddisplay%2526pli%253D1073982496%2526ord%253D12345%2526cim%253D1
b. choose secure mode
c. mute the player button (so in UI will be X)
d. click on Test Ad
e. expected result: video unmuted + mute btn in state unmuted. Actual result: video unmuted + mute btn is state mute

Scenario 3
Getting wrong values in insecure mode when state of the mute button of the player is muted.
In insecure mode when setting the mute button of the player to muted I expect to get in the video slot muted true and instead I get videoSlot.volume - 1 and videoSlot.muted - false.
As a result the video starts unmuted even though I expect it to start muted

I think that as result of these issues when toggling the mute button of the player I get wrong behavior.
If you need more information please let me know

**Comment by shawnbuso** [comment]
Hi there,

Is this an issue with the IMA SDK in general or the video.js plugin (which uses the IMA SDK)? The samples you linked are using the Video Suite Inspector, which does not use the video.js plugin. If you are using the video.js plugin (the project hosted in this repo) the you're in the right place, but if you're using the IMA SDK without the video.js plugin you'll get better support at our [IMA SDK forum](https://groups.google.com/forum/#!forum/ima-sdk). If you're using the video.js plugin, can you replicate your issues in [our samples](http://googleads.github.io/videojs-ima/examples/advanced/)?

Thanks!
Shawn

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need help let us know!
