### ISSUE TITLE
Overlapping controls in ad iframe and own controls

### ISSUE THREAD

**Issue by kachnitel** [googleads/videojs-ima#295]
I've built a player based on the iPhone example, but no matter what I do, I cannot get rid of the "small" countdown behind the play/pause button, and the player seems to be controlled by both the iframe's standard mobile behavior, as in pausing upon tapping the video, but that doesn't change the play/pause button. Touching the button specifically does. 

I put it up here to test: https://rburkat.github.io/pbvideo/commits/54_master_384fae6/test/video-ima-ios-full.html

![screenshot_20161021_171627](https://cloud.githubusercontent.com/assets/4067705/19615524/43773c42-97b5-11e6-90f9-0192ebba906f.png)
So is there a way to control what's in the iframe?
I also seem to have an issue which I believe is closely related, that is on iPad, when I pause the ad, sometimes it starts playing again after a second at first, and then apparently at some weird occasions, such as when the tablet's screen goes off. I'm not entirely sure it's related and I have to look deeper into that, but it might very well be so I thought I'd mention it.

Thanks for any suggestions, I'm probably just missing something simple, but I can't narrow it down :(

**Comment by kachnitel** [comment]
So is there a way to control what's in the iframe?
I also seem to have an issue which I believe is closely related, that is on iPad, when I pause the ad, sometimes it starts playing again after a second at first, and then apparently at some weird occasions, such as when the tablet's screen goes off. I'm not entirely sure it's related and I have to look deeper into that, but it might very well be so I thought I'd mention it.

Thanks for any suggestions, I'm probably just missing something simple, but I can't narrow it down :(

**Comment by shawnbuso** [comment]
Hey there,

We do have 'showCountdown' as an [option](https://github.com/googleads/videojs-ima#user-content-additional-settings), which you could use to disable the countdown timer entirely - does that work for you? Your iPad issue does seem strange - if you're able to repro in any of our [samples](http://googleads.github.io/videojs-ima/) let me know and we can take a look.

Thanks,
Shawn

**Comment by kachnitel** [comment]
Thanks for the reply! Sorry I should have mentioned that, I did try using the showCountdown flag, but they turns off the 'overlaying'  countdown, added within the page and which I can control with cos, but the countdown in the I frame stays there behind the play / pause button. That I can see even in the iPhone example at https://googleads.github.io/videojs-ima/examples/iPhone/

The ad playback resuming after pause doesn't happen there though so that doesn't seem to be related, I'll look deeper into it. 

Still would love to know if there's a way to control the ui within the iframe. Thanks!

**Comment by shawnbuso** [comment]
Ah ok I see what you're saying - that UI is put there by the IMA SDK, not the plugin, so you would have to try to turn it off from the SDK. The countdown timer is required for AdSense and AdX ads, and it looks like that's what you have here, so I don't think you can turn it off. You can try though with the adsRenderingSettings option we provide. I've provided a snippet for that below. If you are using AdSense or AdX which can't be modified, this will just be ignored by the SDK.

    var options = {
      ...
      adsRenderingSettings = {
        uiElements: []
      }
      ...
    }

**Comment by kachnitel** [comment]
Oh that explains why it wouldn't hide anyhing. This setting indeed does hide the countdown when I need, thanks!

I'm still struggling with the automatic resume, but I have absolutely no information to provide related to that so I'll keep digging until I see where the problem even is and go from there.

Thanks!
