### ISSUE TITLE
Which combination is best

### ISSUE THREAD

**Issue by sonicsoul** [googleads/videojs-ima#298]
Hi there, 

I am wondering which combination of versions is best regarding Videojs / Ima Sdk / Contrib-ads? 
What would you prefer right now? 

Btw. I had to add the event "adplaying" in the videojs.ima.js after updating contrib-ads to the latest version (4.0) 

Cheers & Thank you!
Steve

**Comment by shawnbuso** [comment]
Hi there - you can find this info in our [package.json](https://github.com/googleads/videojs-ima/blob/master/package.json). Currently we recommend video.js ~5.3 and contrib-ads ~3.1.2. The IMA SDK only allows you to work with its latest version (it downloads the latest version at runtime), so you don't need to worry about versioning there.
