### ISSUE TITLE
pause ads start to play content in background 

### ISSUE THREAD

**Issue by adim** [googleads/videojs-ima#300]
I test it in platlist demo page:
https://googleads.github.io/videojs-ima/examples/playlist/

steps to reproduce :
1. click on video1
2. pause ad 
3. hear sound of video 1 content.

I hope it's not duplicate issue

**Comment by tehnuty** [comment]
Any updates on this one?

**Comment by shawnbuso** [comment]
Yea it looks like this is an issue with the way the playlist sample is set up and not an issue with the plugin - should be fixed by #310
