### ISSUE TITLE
Uncaught TypeError: this.onAdError_ is not a function

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#301]
Page to see error: http://video.bossip.com/channel/nimble-slider

Seems to fire whenever an ad starts.  You can press the 'next' button on a video to see it happen on subsequent videos.

**Comment by mimse** [comment]
It seems like you are calling startFromReadyCallback before adsready event has been triggered.
Regarding the this.onAdError_  is not a function. I will have a merge request for it later today.

**Comment by stoicbuddha** [comment]
It is being called after the `adsready` event is fired.

**Comment by shawnbuso** [comment]
I'm seeing the same issue on my end - when you call startFromReadyCallback, this.adsManager isn't defined. Can you point me to your video.js plugin implementation code?
