### ISSUE TITLE
Impression pixel not firing for an ad tag

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#303]
The impression pixel does not fire for the following ad tag (seen here: `http://video.madamenoire.com/`): 

VAST Ad Wrapper: `http://adserver.dotstudiopro.com/adserver/www/delivery/fc.php?script=apVideo:vast2&zoneid=1128&cb=1478205118&vid_duration=&content_type=video&id=57f7c71199f8153a6b7b23c6&keywords=&title=Nate%20Parker%20Not%20Sorry%20&%20Viral%20Booty%20Grab%20Wedding%20Pic%20|%20Did%20Y%27all%20See?&url=http://cdn.dotstudiopro.com/files/company/56798e9197f815d36f339ee4/assets/videos/57f7c71199f8153a6b7b23c6/vod/57f7c71199f8153a6b7b23c6.m3u8&pageUrl=www.dotstudiopro-56798e9197f815d36f339ee4.com&eov=eov`

It fires everything through start and complete (quartiles, etc) but no impression.

**Comment by sonicsoul** [comment]
Does the first pixel get fired but the pixel from the vastAdTagURI does not? Or none of them?

**Comment by shawnbuso** [comment]
Which impression URL are you missing? I tested in Chrome and I'm seeing all 3 - one to adserver.dotstudiopro.com, one to securepubads.g.doubleclick.net, and one to s.innovid.com.

**Comment by stoicbuddha** [comment]
Maybe I misstated the problem:

When an ad is playing, there are calls to URLs for ad start, the 3 ad quartiles, and ad complete.  There should be a call to an ad impression URL, but it's not firing.

**Comment by shawnbuso** [comment]
When I tested on my end I was seeing the impression URLs pinged along with all the other tracking URLs you mentioned - which specific impression URL(s) from the response are you missing? Would you be able to capture a [Charles](https://www.charlesproxy.com/) session for the problem ad and include that as well?

**Comment by stoicbuddha** [comment]
I'm verifying something with a client of mine right now, but as of this morning, I believe it's pinging everything properly.  I'm not sure if I just missed this on Friday or was misinformed of what it was supposed to be pinging by the client, so I'll be getting in touch with them and letting you know if this is still an issue by EOD today.

**Comment by stoicbuddha** [comment]
Ok, so I clarified some things with the client.  There is a url within an `<impression>` tag that is getting pinged, but it is not the right one.  

The video tag being used on http://video.madamnoire.com/channel/nimble-slider is not firing the `measureable_view`:  `https://adserver.dotstudiopro.com/adserver/www/delivery/fc.php?script=apVideo:vast2&zoneid=1128&cb=1478633121&vid_duration=&content_type=video&id=5800583f97f815ad101dfb4d&keywords=&title=Gabrielle%20Union%20Suing%20BET%20&%20Black%20Feminism%20To%20Blame%20For%20Birth%20Of%20A%20Nation%20Fail?%20|%20Did%20Y%27all%20See?&url=http://cdn.dotstudiopro.com/files/company/56798e9197f815d36f339ee4/assets/videos/5800583f97f815ad101dfb4d/vod/5800583f97f815ad101dfb4d.m3u8&pageUrl=www.dotstudiopro-56798e9197f815d36f339ee4.com&eov=eov&mp4=1&content_page_url=http%3A%2F%2Fvideo.madamenoire.com%2Fchannel%2Fnimble-slider&mediaId=5800583f97f815ad101dfb4d&srcPageUrl=http%3A%2F%2Fvideo.madamenoire.com%2Fchannel%2Fnimble-slider&mediaTitle=Gabrielle%20Union%20Suing%20BET%20%26amp%3B%20Black%20Feminism%20To%20Blame%20For%20Birth%20Of%20A%20Nation%20Fail%3F%20%7C%20Did%20Y%27all%20See%3F&mediaDesc=In%20this%20week%27s%20episode%20of%20Did%20Y%27all%20See%2C%20the%20ladies%20discuss%20Gabrielle%20Union%27s%20lawsuit%20against%20BET%2C%20%27Birth%20Of%20A%20Nation%27%20flop%2C%20banking%20while%20black%20and%20so%20much%20more!%20Tune%20in%20and%20be%20sure%20to%20share%20your%20thoughts%20below.&mediaUrl=https%3A%2F%2Fk7q5a5e5.ssl.hwcdn.net%2Ffiles%2Fcompany%2F56798e9197f815d36f339ee4%2Fassets%2Fvideos%2F5800583f97f815ad101dfb4d%2Fvod%2F5800583f97f815ad101dfb4d.m3u8&player_width=1057.40625&player_height=594.78125&cust_params=channel_id=5800583f97f815ad101dfb4d&video_id=5800583f97f815ad101dfb4d&rand=9710`

**Comment by stoicbuddha** [comment]
If you use that ad tag in the video suite inspector (`https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector`), it fires the `measureable_view`.

**Comment by stoicbuddha** [comment]
Is there an update for this?  I have a client that's waiting for an answer/update/etc.

**Comment by shawnbuso** [comment]
It looks like your site may have gone down - I'm seeing a GoDaddy placeholder page. I took a look at the initial tag that you sent me but I'm not seeing any measurable_view URLs in that response - could you send the tag again?

**Comment by stoicbuddha** [comment]
They're back up now.  Must've been a weird issue.

**Comment by shawnbuso** [comment]
Hmm I'm still seeing the same thing - video.madamnoire.com is parked on a godaddy landing page, and when I reques tthe ad tag from the first message in the VSI I get nothing in the network tab that contains "measureable_view". The closest thing I get is "active_view_video_measureable_impression."

**Comment by stoicbuddha** [comment]
The link was missing a letter. I edited it, it works now.  And yes, that's the event.  They'd given me some info and I'd read something wrong.

But, anyway, to summarize, that's the impression I'm talking about and the link is fixed.  My bad.

**Comment by shawnbuso** [comment]
Ah ok I'm able to see this now - I'll take a look and let you know what I find.

**Comment by stoicbuddha** [comment]
Hey @shawnbuso do you have any updates?

**Comment by shawnbuso** [comment]
Sorry, I'm just getting back to this now. Are you still seeing the issue? Did the ad server settings change again? I took another look at the tag from your opening comment but I'm not seeing any thing for "measureable_view" in the to-level tag or the tag that it wraps.

**Comment by shawnbuso** [comment]
I'm going to close this out since it's been ~2 weeks since my last response, but if you still need help feel free to re-open. Thanks!
