### ISSUE TITLE
iphone sample

### ISSUE THREAD

**Issue by eXistenZ** [googleads/videojs-ima#304]
What does the iphone sample do? Does that mean the other samples do not work on iphone and I need a separate version for it?

I tried using the advanced sample to my page, it works perfect on android on firefox and chrome, but on iphone it looks messed up, seems that the ad sound plays in the background but with my main video.

**Comment by shawnbuso** [comment]
Yes, the non-iPhone samples won't necessarily work on iPhones. We've had trouble detecting clicks on the video player on iPhone, so the iPhone sample instead shows a placeholder image, detects a click on that, and then programmatically creates the video player.
