### ISSUE TITLE
HLS and videojs-ima on IOS

### ISSUE THREAD

**Issue by AlexMurm** [googleads/videojs-ima#314]
Hi!

I want to use videojs-ima and HLS plugin (https://github.com/videojs/videojs-contrib-hls) together. But collided with an issue on IOS. A screen freezes and nothing happens.  

How to reproduce:
http://origin.platformcraft.ru/alexmurm/mirtv_hls/black3/hls.html

IOS version: 8.0.2
Browser: Safari 

How to avoid this issue? Thanks in advance!

**Comment by campones** [comment]
yours is working pretty good, i m trying using hls.js  library and player won't autoplay after the video-ads end.

**Comment by shawnbuso** [comment]
Is this working for you *without* the IMA plugin on iOS? iOS requires video playback to be started as the result of a user action, so if you're trying to auto-play the video on iOS that is not expected to work.

**Comment by AlexMurm** [comment]
Without IMA plugin this is working:
http://origin.platformcraft.ru/alexmurm/mirtv_hls/black3/hls_without_ads.html

**Comment by shawnbuso** [comment]
OK I think we may need to turn this into an FR to get these two plugins working together - I'll need to first check if videojs-contrib-hls and videojs-contrib-ads are compatible, then potentially make some adjustments to videojs-ima to get it working with HLS.

**Comment by jonigl** [comment]
Hi, any updates about this?

**Comment by shawnbuso** [comment]
I have this on my list of things to investigate this quarter - I don't have a tight timeline, but I should have more info on this in the coming weeks.

**Comment by shawnbuso** [comment]
This appears to be resolved with the latest version of the plugin. Can you let me know if you're still seeing the issue? Thanks!

**Comment by jonigl** [comment]
@shawnbuso I just tested the last version 1.0.4 of the plugin and unfortunately i'm still seeing this issue.

**Comment by shawnbuso** [comment]
Hrm ok, do you have an updated test page where I can replicate? Thanks!

**Comment by shawnbuso** [comment]
Heyo, just checking in to see if you have somewhere I can replicate this. I'd like to get it resolved since I think this could be a big use case for the plugin. Thanks!

**Comment by shawnbuso** [comment]
Closing out since I haven't had a response in ~1 month. If you're still seeing this issue feel free to respond with a test page I can use to repro and I'll look into it :)

**Comment by edilashimov** [comment]
@shawnbuso Hello I am having an issue with iOS mobile/iPad devices fail to play the content after the preroll has been completed. Happens only with the hls live content not the mp4. Please help. I am trying to cast the content using Chromecast and google IMA Ads.
