### ISSUE TITLE
Linear preroll + nonlinear overlay + linear postroll, example.

### ISSUE THREAD

**Issue by tonykor** [googleads/videojs-ima#315]
Hello,

Does this combination supported with this plugin. I want to play a preroll and after that when the video starts to show user a nonlinear overlay, and a linear postroll at the end. I can't make it to work together. Does anyone have any examples.  

Thanks.

**Comment by tonykor** [comment]
possible duplicate of https://github.com/googleads/videojs-ima/issues/99, can i know does this feature currently supported?

**Comment by tonykor** [comment]
Seems like not supported yet, https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility#vmap-footnote

How does you are solving the problem with showing overlay ads with preroll and postrolls ?

**Comment by shawnbuso** [comment]
Hi there,

You are correct that we don't currently support mixing linear and non-linear. We don't have a workaround at the moment but we are working on adding support for this to the IMA SDK in the future.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Tested and confirmed that this is working as of 1.0.0.
