### ISSUE TITLE
Ad playing on IE 11 with audio but no video

### ISSUE THREAD

**Issue by grantfeldman** [googleads/videojs-ima#319]
Hi, i am seeing ads working fine accross all browsers and devices except for IE which plays audio but no video. Is there anything obvious that could be wrong here?

**Comment by shawnbuso** [comment]
Is this with the sample ads or your own ad tag? If it's your own ads, my guess is that the ad you're serving is using an encoding that IE isn't compatible with. If you're using your own ads, could you send me your tag? Thanks!

**Comment by ConceitedCode** [comment]
My team ran into this a couple months ago. The issue was resolved by setting the height attribute on the video tag. The ad was playing with a height of 0px, which is why we could hear the ad, but couldn't see the ad.

**Comment by grantfeldman** [comment]
Yes that was the problem for us as well. thanks!
