### ISSUE TITLE
Midroll ad problem

### ISSUE THREAD

**Issue by taliptako** [googleads/videojs-ima#321]
I'm using google dfp for small business i dont have this feature https://support.google.com/dfp_premium/answer/1406418?hl=en -> its dfp premium feature which you should have millions ad impressions to have it.
So how can i add midroll or postroll ads with the vast ad tag?

**Comment by shawnbuso** [comment]
There is now an industry standard called VMAP which works the same way as ad rules, so we recommend using that. You can see sample VMAP tags in our [list of sample tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags). Though those tags point to DFP, you should be able to use the VMAP standard on any VMAP-compliant ad server.

**Comment by taliptako** [comment]
I should create them manually  ? As a small business user i cant create those tags from my dfp panel isnt it ?
Thank you for your support

**Comment by shawnbuso** [comment]
I don't believe DFP SB can use ad rules or VMAP, but you can take your DFP tags an manually create a VMAP response for them, and then use that with the plugin.

**Comment by taliptako** [comment]
Actually i tried something like that here is my vmap response: [](https://detayhosting.com/player/asd.xml)
I manually create this xml and put my dfp tags in it.I'm trying this from https://googleads.github.io/videojs-ima/examples/advanced/ here i dont get any ads its showing only the video.

**Comment by shawnbuso** [comment]
Can you send me the VMAP that you're creating so I can test with it?

**Comment by taliptako** [comment]
Sorry i update the link now

**Comment by shawnbuso** [comment]
Ok it looks like detayhosting.com doesn't have the proper CORS settings to serve ads to the SDK: "XMLHttpRequest cannot load https://detayhosting.com/player/asd.xml. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://imasdk.googleapis.com' is therefore not allowed access." It might me easier for you to inject the VMAP directly as a string using adResponse instead of adTagUrl.

**Comment by taliptako** [comment]
Actually now i'm getting error like this AdsLoader error: AdError 1010: The ad response was not understood and cannot be parsed.
I'm trying this on this url https://detayhosting.com/player/player.html you can check the page source 
By the way in this example i'm trying to use this plugin with dash.js

**Comment by taliptako** [comment]
Thank you so much for your support. https://detayhosting.com/player2/ in this url i make it work.
I just wonder google dfp does not provide vmap for us i'm doing manually its legal isnt it ?
