### ISSUE TITLE
Player crashing on iPhone

### ISSUE THREAD

**Issue by mexxy** [googleads/videojs-ima#324]
Hi, i have a serious issue:

I was integrated this plugin to php vibe script, but when i try to open with my iphone, the player crash sometimes, and whole screen seems to be blocked.
My site is: http://somemovies.xyz and here you can see little video about issue: http://tinypic.com/r/34470vk/9

Thank you!

**Comment by shawnbuso** [comment]
It looks like video.js is having an issue with your framework - instead of creating a video player for itself as expected, it creates a div and then tries to use it like a video player. Are you able to get your site working with video.js but without the IMA plugin? If so can you send me an example of that? That will at least confirm that it is the IMA plugin that's causing the issue.

**Comment by mexxy** [comment]
Here we have fresh instalation without IMA plugin: http://www.bizfeed.online/video/2/videoplayback-mp4/

**Comment by shawnbuso** [comment]
Do you have a setup identical to the one you sent originally? That looks like a different site altogether, and I think the issue might be with how the player is interacting with the site.

**Comment by mexxy** [comment]
Its the same script, but without any customization. I can remove from first site temporarly the ima plugin, or i can add to this script all customizations without ima plugin.

**Comment by shawnbuso** [comment]
If it's not too much trouble could you remove the IMA plugin from the first site and try using video.js without it? I want to make sure that we don't have the same issue in that exact set-up without the IMA plugin. Thanks!

**Comment by mexxy** [comment]
I removed the plugin i think. You can try now http://www.somemovies.xyz/video/4/video-test-53/

**Comment by shawnbuso** [comment]
Hmm ok it looks like it is definitely working without the IMA plugin - could you put it back in so I can continue to test? Thanks!

**Comment by mexxy** [comment]
Now its back with the ima plugin http://www.somemovies.xyz/video/4/video-test-53/

**Comment by mexxy** [comment]
Also here we have fresh instalation without customizations, but with IMA plugin integrated. You can check if here its working on iphone : http://www.bizfeed.online/video/2/videoplayback-mp4/ ?

**Comment by shawnbuso** [comment]
It looks like both of the links you posted are now working - are you still seeing issues on your end?

**Comment by mexxy** [comment]
Now its ok. I have removed some js error from my script and that was the solution. Thank you for your help. Just to inform others with this issue, the problem is from phpvibe script.

**Comment by shawnbuso** [comment]
Glad you got it working, thanks for the info!
