### ISSUE TITLE
On Firefox Mobile Browser, ad plays in full screen(overlay) while content played in Background

### ISSUE THREAD

**Issue by A-Hadi786** [googleads/videojs-ima#327]
I am facing the issue in Firefox mobile browser , the ad video goes to full screen and screen hangs when the ad is ended, while video content played in background.
In android default browsers play button on ad container does not respond on Tap or touchend.

You had provided the Vast adTag (http://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&url=&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0)
for iphone works for me in both Iphone and firefox,but when i change the adUnit id it does not work in firefox .

My Tag is(this tag is working fine in Iphone, while Firefox not working for me) :
http://pubads.g.doubleclick.net/gampad/ads?slotname=/39243592/413851632/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&url=&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0 

Any solution ?

**Comment by shawnbuso** [comment]
I tested this with our simple example (using your tag) on an iPod touch (iPhone equivalent) in Firefox and I'm not able to repro - I see the ad play full screen, and the content plays full screen in the same player immediately after. Are you still seeing the issue?

**Comment by A-Hadi786** [comment]
Thanks @shawnbuso 
Yup still i am facing the issue ..
on both Android and IOs in firefox .
www.thescriptowls.com/player
this is my test page please check it on Firefox .
thanks

**Comment by shawnbuso** [comment]
OK I do see the issue on that page - can you point me to your implementation code so I can see what's going on? I'm mostly curious about your fullscreen implementation for the ad - our sample players don't play the ad in fullscreen, so it looks like there's something in your implementation doing that, and it's not playing nice with either the IMA plugin or the IMA SDK.

**Comment by A-Hadi786** [comment]
Thanks for quick response !!
This is my page where I implemented the code..
http://www.thescriptowls.com/player/js/ads.js

------------------------------------------------------------------
var player = videojs('content_video');

var options = {
  id: 'content_video',
  adTagUrl : 'http://thescriptowls.com/player/ads1.xml'
};

player.ima(options);
player.ima.initializeAdDisplayContainer();
player.ima.requestAds();
player.play();

// Remove controls from the player on iPad to stop native controls from stealing
// our click
var contentPlayer =  document.getElementById('content_video_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
  contentPlayer.removeAttribute('controls');
}

// Initialize the ad container when the video player is clicked, but only the
// first time its clicked.

var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
  startEvent = 'touchend';
}

player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
    player.play();
});
---------------------------------------------------
thats my code..

**Comment by shawnbuso** [comment]
It looks like you have the following code block twice, which might be messing with things:

```
player.ima(options);
player.ima.initializeAdDisplayContainer();
player.ima.requestAds();
player.play();
```

If you remove the first instance of that do you still see the issue?

**Comment by shawnbuso** [comment]
I'm going to close this out since it's been a week, but if you still need help feel free to re-open. Thanks!
