### ISSUE TITLE
It doesn't call twice

### ISSUE THREAD

**Issue by ye0jun** [googleads/videojs-ima#329]
I can see ad through player.ima.requestAds(); 
but I want see ad again when I need
what can I do ?

**Comment by shawnbuso** [comment]
We don't have a feature to replay ads on-demand, but you can set up [VMAP](https://www.iab.com/guidelines/digital-video-multiple-ad-playlist-vmap-1-0-1/) to schedule ad breaks throughout your content. you can check out our [sample tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags) to see some VMAP examples. Let me know if that helps.

**Comment by shawnbuso** [comment]
Closing this issue since it's been a week since my last response - if you need any more help from us feel free to re-open!
