### ISSUE TITLE
Ads are not auto play?

### ISSUE THREAD

**Issue by Night-Crawle** [googleads/videojs-ima#331]
Hi!,
I have tried to run ads automatically when page load..But it not succeed yet..I have checked all support tickets,couldn't find anything useful..So,I am still,looking for   right solution.. Solution -(autoplay) ,I am looking for this solution for  both mobile and desktop..Thanks!..

Link: http://tronevr.esy.es/fixed-version/test.html

Kindly regards!,
Dj

**Comment by shawnbuso** [comment]
For desktop all you'll need to do is remove the event handler for startEvent in our sample and instead run that code on page load. Using the simple sample as an example, just change this:

`player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
    player.play();
});`

to this:

`player.ima.initializeAdDisplayContainer();
player.ima.requestAds();
player.play();;`

For mobile it's a bit more complicated. Currently IMA does not support autoplay on Android. For iOS it should work as long as you can get content to auto-play, because we re-use the same player for content and ads. Let me know if you run into any specific issues getting it working on iOS and if you have a sample page I can use to repro those issues.

**Comment by Night-Crawle** [comment]
Hi!,Thanks!..
I have made test page here: http://tronevr.esy.es/fixed-version/complete-test.html
in here autoplay works.both android and ios devices..but not ads load..
Note never android devices...that used android 6 and 7  and ios -10

**Comment by shawnbuso** [comment]
IMA does not support autoplay on Android, so that's why no ads are loading on Android.

Could you point me to your unobfuscated implementation code so I can take a look at how you have autoplay set up? Thanks

**Comment by Night-Crawle** [comment]
Thanks! for your quick response....   I used autoplay muted loop playsinline controls >
for get auto play work and i used,web gl(three.js) support for autoplay run...I used:
 
videojs panorama viewer sorce code for improve mobile experience.

view-source:https://yanwsh.github.io/videojs-panorama/

used necessary implement

**Comment by Night-Crawle** [comment]
seems ok! with chrome in ios 10, but for older version of ios android...is there is solution with webgl or using canvas for enable auto play with ads.. autoplay is possible in mobile device using inline stream... and also using `autoplay muted  controls >` or `autoplay muted loop playsinline controls >`
as i know,most of them used `autoplay muted loop playsinline controls >` or autoplay muted  controls > for auto start..

i am not sure..100%,But i hope you have better solutions for this..
Thanks!,
Dj

**Comment by shawnbuso** [comment]
Ah ok, no that's not possible - Apple only introduced support for auto-play on mobile as of iOS 10. See https://webkit.org/blog/6784/new-video-policies-for-ios/

For Android it's not yet supported by the IMA SDK, so we can't support it in the plugin until they support it in the SDK.

**Comment by Night-Crawle** [comment]
Thank you, thank you for your great support..

**Comment by Night-Crawle** [comment]
BTW,I still have a doubt...How do enable vpaid mode/enable vpaid?
Can you tell me the code?

**Comment by shawnbuso** [comment]
You can specify that in your plugin options, the same place that you provide 'id' and 'adTagUrl':

`
var options = {
  id: 'content_video',
  adTagUrl: 'YOUR_AD_TAG',
  vpaidMode: google.ima.ImaSdkSettings.VpaidMode.<MODE>
};`

Accepted values for <MODE> are DISABLED, ENABLED, and INSECURE and you can see more info about them here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.ImaSdkSettings.VpaidMode

**Comment by Night-Crawle** [comment]
OK!…...thanks...

**Comment by Night-Crawle** [comment]
Hi!,
I have issue with my vpaid tag..
It's not showing well  on my player..can you checked and tell what the issue is?
Link: http://tronevr.esy.es/vpaid-final-test/vpaid.php
Thanks!,
Dj
