### ISSUE TITLE
Loading spinner does not disappear when preroll ends

### ISSUE THREAD

**Issue by bcharna** [googleads/videojs-ima#332]
The videojs loading spinner remains stuck during the preroll (using a DFP ad tag URL) using video.js 5.16.0 and videojs-contrib-ads 4.2.3. The loading spinner has the class "vjs-loading-spinner". My solution was to modify the following function of this library to trigger an "ads-ad-started" event which causes videojs-contrib-ads to remove the spinner:

```
    var onAdStarted_ = function(adEvent) {
      this.currentAd = adEvent.getAd();
      if (this.currentAd.isLinear()) {
        this.adTrackingTimer = setInterval(
            onAdPlayheadTrackerInterval_, 250);
        // Don't bump container when controls are shown
        removeClass_(this.adContainerDiv, 'bumpable-ima-ad-container');
      } else {
        // Bump container when controls are shown
       addClass_(this.adContainerDiv, 'bumpable-ima-ad-container');
       this.player.trigger('ads-ad-started'); // *********** my patch
      }
    }.bind(this);

```

See the screenshot for an example of the issue.
<img width="664" alt="screen shot 2017-02-13 at 5 20 02 pm" src="https://cloud.githubusercontent.com/assets/1569074/22910735/c0d2771e-f210-11e6-846a-204a4d1feb79.png">

**Comment by shawnbuso** [comment]
Do you have a sample where I can repro this? I'm not seeing it with our sample player and sample tag. Thanks!

**Comment by bcharna** [comment]
Hey yep, check this out: https://jsfiddle.net/s4thz185/3/. Use iPhone device agent in safari or chrome. Thank you for looking!

**Comment by shawnbuso** [comment]
Hmm weird, it's not actually being hidden on desktop either - the ad just covers it. For some reason in iOS the spinner gets pushed above the ad on the view stack. Can I use your JSFiddle to talk to the video.js folks to try to figure out what's going on here?

**Comment by bcharna** [comment]
Sure, definitely feel free to. One other note related to z-index. I had the following code in place before I was starting to upgrade libraries as well:

```    videojsObject.ima(options, => @initVideoAdLifecycleListeners(videojsObject))
    # The ad container must be temporarily moved back in the stack (it's set to a very high z-index by the google videojs.ima plugin)
    # because it intercepts user clicks for a portion of the video element which means video won't play on iOS (user interaction required to play video):
    $(".ima-ad-container").css("z-index", -1)
```

And then to fix the z-index after user pressed the video poster:
```    videojsObject.one("firstplay", =>
      $(".ima-ad-container").css("z-index", 1) # move it back to front of the stack now that the user initiated click happened.
```

That hack was all I needed regarding this bug. Now, I still need this hack and the additional "ads-ad-started" event triggering mentioned before for it to work properly on an actual iPhone.

**Comment by m-spyratos** [comment]
Had the same issue.  
Solved it by using the `ima` callback method:

````
 player.ima({
    id: 'my_video',
    adTagUrl: 'TAG_URL'
}, function () {
    player.ima.addEventListener(google.ima.AdEvent.Type.STARTED, function () {
        player.removeClass('vjs-ad-loading');
    });
    player.ima.start();
});
````

**Comment by shawnbuso** [comment]
Aha ok - I think the z-index thing is the issue here. Have you taken a look at our iPhone sample? That should give you some tips on implementing for iPhone without having to mess with z-index.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need assistance let us know!
