### ISSUE TITLE
adaptv  No ad could be found matching this request.

### ISSUE THREAD

**Issue by arputcu** [googleads/videojs-ima#334]
<?xml version="1.0" encoding="UTF-8"?>
<VAST version="2.0">
	<Error>	</Error>

	<Extensions>
		<Extension type="adaptv_error">
			<Error code="2"><![CDATA[No ad could be found matching this request.]]></Error>
		</Extension>
	</Extensions>
</VAST>

http://lpaste.net/352755

log:
VIDEOJS: ads play triggered: content-set -> ads-ready?
Ad error: AdError 402: VAST media file loading reached a timeout of 15 seconds.
 VIDEOJS: ads adserror triggered: ad-playback -> content-resuming

and video does not start

**Comment by shawnbuso** [comment]
Could you send your ad tag so I can test on my end? Thanks!

**Comment by arputcu** [comment]
https://ads.adaptv.advertising.com/a/h/A+w6aPAjEmDSRqtHWwnT6eQAJ__dNdyTyRIIvtN6rX5d4Qo3+_N2QQ==?cb=[CACHE_BREAKER]

i think you can test with this or i can send it in private?

**Comment by arputcu** [comment]
any response on this?

**Comment by shawnbuso** [comment]
Hey there,

It looks like this is an issue with your ad server - you're requesting ads from the player, and it's telling you it has no ads to give you. You can reach out to adap.tv and they should be able to help you figure out why you're not getting any ads back.

Thanks,
Shawn Busolits
IMA SDK Team

**Comment by arputcu** [comment]
hey 
yes but this was the test on no ads found 
i think videojs ima should start the playback on no ads found

**Comment by shawnbuso** [comment]
I am seeing it play after the 15 second timeout - are you seeing something different? I think the reason it hits the timeout instead of playing right away is because your ad does load OK, it loads a JS VPAID ad, but *that* ad then tries to load another ad which ends up being empty. So to the SDK the ad loads fine, but after 15 seconds it hasn't fired the START event so it considers it to be a timeout.

**Comment by arputcu** [comment]
yes it starts playing after the 15s timeout , is it possible to start on no ads found ?

**Comment by shawnbuso** [comment]
This is an issue with the VPAID ad that you're loading. There are 2 ad loads happening - the SDK is loading a VPAID, then that VPAID is trying to load another ad. That second request is the one that times out. The request comes back empty, but the VPAID never sends an error or anything to the SDK - it just sits there and does nothing, so the SDK eventually fires a timeout. In order for the content to start when that second request comes back empty, the VPAID ad needs to surface an error to the SDK.
