### ISSUE TITLE
On mobile unable to scroll when touch event starts from over the video

### ISSUE THREAD

**Issue by lucascharrierpulpix** [googleads/videojs-ima#335]
I can't scroll my page when I start scrolling from the ad playing on my video. It seems it is due to preventDefault on touchstart and touchend event. I get the following warning when trying to scroll:

> Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080.

I know I could add an overlay, but I'll prefer no too.

**Comment by shawnbuso** [comment]
I believe this is an issue with the IMA SDK, not just this plugin, but will have to investigate further. Thanks for the report!

**Comment by dtapuska** [comment]
Unable to scroll seems odd due to this intervention. Is there a URI that reproduces this? (I'm not familiar with videojs-ima at all but am looking at it from Chrome's touch handling perspective as I'm a chromium author)

**Comment by shawnbuso** [comment]
You can repro with vanilla IMA SDK (no video.js pluign) here: http://googleads.github.io/googleads-ima-html5. If you zoom in a bit you can scroll vertically - it works when you tap outside the ad, but not when you start your tap inside the ad.

**Comment by shawnbuso** [comment]
Testing with 1.0, this appears to be resolved. If you're still seeing the issue with the updated plugin let me know.
