### ISSUE TITLE
Errors when calling videojs' dispose() method

### ISSUE THREAD

**Issue by m-spyratos** [googleads/videojs-ima#337]
## Versions
- `videojs`: __5.16.0__
- `videojs ads`: __4.1.3__
- `videojs ima`: __0.4.0__

## Use Case
Usage of videojs and videojs-ima in an angular application, where DOM is dynamically changing.

## Cause
Calling `player.dispose()` destroys the player, but videojs-ima still runs an interval for checking the player's size.

## Error
Infinitely getting the following error:
````
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
````

## Reproduce
Here's a [jsFiddle of the issue](https://jsfiddle.net/tsnLbgb4/) mentioned above.

1. Click on the player to play.
2. When the ad starts playing and the "dispose" button appears, click the button.
3. Check the console log for the errors.

## Possible Solutions
1. Check for element's existence inside of `checkForResize_` and catch any errors. If element does not exist, clear the intervals.
2. Either automatically clear all intervals on player disposal, or provide a method to do so manually.

**Comment by shawnbuso** [comment]
Are you on the latest version of the plugin? We have a [playerDisposeListener](https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L1297) method that should be getting called when the player gets disposed which clears all of our intervals. I'm seeing this working properly in my local tests, so maybe you're on a version from before this listener was added?

**Comment by m-spyratos** [comment]
@shawnbuso I can see this method in the master branch, but it hasn't made it in any of the releases yet. In my example I was using the [latest 0.4.0 release](https://github.com/googleads/videojs-ima/releases/tag/0.4.0). I tested again with the master branch and I can confirm that it worked fine!

Thanks!

**Comment by shawnbuso** [comment]
Thanks for the update - we'll work on a new release so this is included.
