### ISSUE TITLE
Controls not accessable with NonLinear VPAID Ads

### ISSUE THREAD

**Issue by ocundale** [googleads/videojs-ima#346]
I have setup a very basic demo using the Google IMA with VideoJs to demonstrate an issue I am seeing- After a nonlinear VPAID overlay ad is loaded into the player, the user no longer has access to the player controls.
This can be seen on the page I have made here:
http://coullwebsdk.herokuapp.com/nonlinearvpaid/examples/simple/

On display of the overlay ad, I would expect the controls to still be accessible to the user.

**Comment by ocundale** [comment]
I have looked further into this issue and have some more information regarding the problem.

I have tested with multiple non-linear creatives and it seems like the onAdStarted_ function is never called from **videojs.ima.js** despite the VPAID 'AdStarted' event being fired from the creative.

There is a line within the onAdStarted_ function which seems like it needs to run so that the ad container can move up and allow space for the controls:
`addClass_(this.adContainerDiv, 'bumpable-ima-ad-container');`
I think this may be part of the problem, if anybody can confirm this function should run, that would be great! Thanks.

**Comment by shawnbuso** [comment]
Hmm this is interesting - it looks like my [sample image non-linear](https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=&debug_experiment_id=1269069638) and your VPAID non-linear both have divs that take up the entire video display, but mine is allowing mouse events through and yours is not, and I'm not sure why :/ I'll need to look into this a bit more, but just wanted to let you know that it's on my radar.

**Comment by hrehman200** [comment]
My issue (https://github.com/googleads/videojs-ima/issues/353) may also be related to this issue.

**Comment by ocundale** [comment]
Thanks Shawn, appreciate the response- I did notice that it works with the sample non-linear response you used, though that is just a standard VAST overlay ad, not a VPAID creative.  

I tried a few different non-linear VPAID creatives whilst testing and saw the same issue every time. The demo page I created uses the following nonlinear vpaid creative: https://github.com/ryanthompson591/vpaidExamples

But I have hosted my own simple version via the following tag, which is perfect for testing:
`adTagUrl: '//coullwebsdk.herokuapp.com/nonlinearvpaid/test-creative.php'`

**Comment by shawnbuso** [comment]
Thanks for the update - I'm working with the rest of the IMA team now to see how we can resolve this one.

**Comment by ocundale** [comment]
Thanks Shawn- let me know if you need any further info, the ad tag I provided is a good example of a non-linear VPAID creative, so feel free to use that for testing. Cheers :)

**Comment by ocundale** [comment]
Any progress on this Shawn? Let me know if there's anything I can do to assist. Thanks.

**Comment by shawnbuso** [comment]
Still looking into this one with the rest of the IMA team - we need to figure out how to provide access to the controls where desired while not breaking other VPAID ads, so it's going to require a lot of testing. I'll let you know when we have an update.

**Comment by shawnbuso** [comment]
Hi all - I tested in [our sample](http://googleads.github.io/videojs-ima/examples/advanced/) with the [sample tag](http://coullwebsdk.herokuapp.com/nonlinearvpaid/test-creative.php) provided and it looks like this issue has been resolved - can you confirm?

**Comment by shawnbuso** [comment]
Closing this out since it appears to be resolved from my end. If you're still seeing the issue, feel free to re-open or start a new issue. Thanks!

**Comment by ocundale** [comment]
Hi Shawn, I can confirm this issue was resolved. Thanks!
