### ISSUE TITLE
v0.5.0 of videojs-ima

### ISSUE THREAD

**Issue by extend1994** [googleads/videojs-ima#347]
Hi
I am a member of CDNJS and the one who is in charge of adding videojs-ima to CDNJS according to the request cdnjs/cdnjs#10491.
I found that there is v0.5.0 on npm, could you please also release/tag it on GitHub?
It will help me use GitHub as the source to let videojs-ima be more compete on CDNJS :smile: 
Thank you!

**Comment by shawnbuso** [comment]
Sorry about that! It should be added now. I'll also be creating 0.6.0 once I work through the existing PRs to get some bug fixes added, since 0.5.0 is a few months old now.

**Comment by extend1994** [comment]
@shawnbuso No problem :+1: I will add it to CDNJS ASAP, thanks for your help!
