### ISSUE TITLE
skip ads button gone

### ISSUE THREAD

**Issue by vanthai79** [googleads/videojs-ima#349]
Dear friends,
I run sample code from https://github.com/googleads/videojs-ima/tree/master/examples/simple/index.html

But i can not see skip ads button. I change video ads file wich has duration > 4 minutes but still not see skip ads button.
Can you help me to to show skip ads button?
Thank you very much for support!

**Comment by shawnbuso** [comment]
Could you share your ad tag with us so we can debug on our end? You should be getting a skippable ad automatically if the ad's VAST indicates that it's skippable. Thanks!

**Comment by vanthai79** [comment]
Dear Shawnbuso,
Base on your guid i added this property <Linear skipoffset='00:00:05' > then can see skippable ads button.
Thank you very much for help !

**Comment by Wesley-Carnicle** [comment]
Can you guys make a Wordpress plugin
