### ISSUE TITLE
Big Play Button not working

### ISSUE THREAD

**Issue by hrehman200** [googleads/videojs-ima#353]
Following code works, i.e. it plays the ad, plays my video. However, if I turn off autoPlay, I see the Big Play Button over my video, but it doesn't work. Only case when that button works is when i comment out ---> player.ima(options);

```
    var player = videojs("my-player", {
        controls: true,
        autoplay: false,
        preload: 'auto'
    });

    var options = {
        id: 'my-player',
        adTagUrl: 'my-adtag-url'
    };
    google.ima.settings.setVpaidAllowed(true);
    player.ima(options);
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
```

I guess ima plugin is messing up with Big Play Button. I tested it on Firefox, Chrome, Safari. 

Also, when i run following code in browser console, it worked:
`$('.vjs-big-play-button').trigger('click');`

So it looks like some sort of overlay problem.

**Comment by shawnbuso** [comment]
Are you seeing this issue with our sample tag? I modified the simple sample as follows and it's working for me:

```
var player = videojs('content_video', {
  controls: true,
  autoplay: true,
  preload: 'auto'
});

var options = {
  id: 'content_video',
  adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
      'iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&' +
      'impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&' +
      'cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&' +
      'vid=short_onecue&correlator='
};

player.ima(options);                                                                                                                 
player.ima.initializeAdDisplayContainer();
player.ima.requestAds();
player.play();
```

**Comment by hrehman200** [comment]
No it doesn't work with sample tag as well. Also I think you need to set autoPlay:false, so that big play buttons is visible from start.

**Comment by okeanos2** [comment]
I am having the same issue, when autoplay is set to false the play button doesn't work.

**Comment by thiagonzalez** [comment]
Me too! There are some CSS declared for google-ima container: `position: absolute; z-index: 1111;` that put this in front of the big play button.

**Comment by shawnbuso** [comment]
Is there a specific platform on which you're seeing this issue? I updated my simple sample to set the following:

```
var player = videojs('content_video', {
  controls: true,
  autoplay: false,
  preload: 'auto'
});

var options = {
  id: 'content_video',
  adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
      'iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&' +
      'impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&' +
      'cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&' +
      'vid=short_onecue&correlator='
};

player.ima(options);

// Remove controls from the player on iPad to stop native controls from stealing
// our click
var contentPlayer =  document.getElementById('content_video_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
  contentPlayer.removeAttribute('controls');
}

// Initialize the ad container when the video player is clicked, but only the
// first time it's clicked.
var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
  startEvent = 'touchend';
}
                                                                                                                                                                                     
player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
    player.play();
});
```

And the big play button is still working for me on Mac Chrome. Could you paste your full code as it is when you're seeing the issue? Thanks!

**Comment by thiagonzalez** [comment]
This example works fine if you don't use autoplay. I'm using both autoplay and not autoplay.
I fixed this issue calling the ads only when the player starts to play. But before the ad starts I can see the first frame of the video. So it is not 100% solved 👎 

```
  // Play event
  player.one('play', function() {
    player.ima(ads);
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
```

There's another problem that I found here. I can't pause/play the ads just using `videojs(id).pause()` or `videojs(id).play()`. We have multiple videos on our homepage and I need to pause all the other videos when one is playing. Even if the player is playing the ad.

**Comment by shawnbuso** [comment]
We do have an open issue to try to fix the first-frame showing problem - that's #167. For your second issue, you should be able to use player.ima.pauseAd() and player.ima.resumeAd() - let me know if that works for you.

**Comment by shawnbuso** [comment]
I just noticed something re: big play button not working - are you on a supported version of the video.js player? Currently we only support up to and including 5.3. I noticed this issue when I was testing compatibility with 5.10.

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you're still seeing  an issue feel free to re-open!

**Comment by ocundale** [comment]
Hi Shawn, I can confirm this issue was resolved. Thanks!
