### ISSUE TITLE
VPAID AD Not showing correctly on the Player

### ISSUE THREAD

**Issue by Night-Crawle** [googleads/videojs-ima#356]
Hi!,
I have a issue with showing my vpaid tag on videojs player..
It's not showing well on my player..can you checked and tell what the issue is?
Link: http://tronevr.esy.es/vpaid-final-test/vpaid.php
Thanks!,
Dj

**Comment by shawnbuso** [comment]
Hey there,

I think this might be an IMA SDK issue we need to look into - in INSECURE mode your ad is being rendered on top of our controls, but it should be beneath them. I'll let you know what we find when we look into it.

Thanks,
Shawn

**Comment by Night-Crawle** [comment]
Hi!, Also, want to how do i used java script for auto fire clicks without user interaction?
Do you know,any codes?
Thanks!

**Comment by shawnbuso** [comment]
Unfortunately I do not - as far as I know it's not possible to fake a user interaction in a way that will let you play video on mobile (if that's what you're looking to do).

**Comment by shawnbuso** [comment]
Hi there - looking into this today, it looks like your tag has stopped working (I get a NO_ADS error). Do you have another test tag I can use to replicate this?

**Comment by shawnbuso** [comment]
Closing this out since it's been a month with no response, but if you're still seeing this issue please feel free to re-open and we can continue to investigate :)

**Comment by awongops** [comment]
Hey @shawnbuso - we're having a similar issue with an iAS VPAID tag on our player - we're in INSECURE mode and the VPAID ad is rendering on top of our player but an unwrapped tag doesn't (and obeys player commands accordingly) Any idea on what could be causing the issue? We have a Google Dev session showing "Uncaught ReferenceError: manager is not defined...at HTMLIFrameElement.AdVolumeChange..." etc. Did your team have any findings regarding ads rendering on top of the player? I can open a separate project as well.

**Comment by iflixweb** [comment]
@awongops ,
we already fixed this.
if you are interesting.please!,get back to me via e-mail
e-mail: iflixweb@outlook.com
