### ISSUE TITLE
Disable Flash Ads

### ISSUE THREAD

**Issue by StaymanHou** [googleads/videojs-ima#358]
Hi, we want to disable Flash ads. I found that there's an interface to disable it in the ima sdk documentation, but how do I invoke that interface from this plugin?

**Comment by shawnbuso** [comment]
It looks like that's not yet exposed, so I'll take that as an FR. In the meantime you can add that API call to your copy of the source - after we create the adsLoader, call `adsLoader.getSettings().setDisableFlashAds(true);`.

**Comment by StaymanHou** [comment]
Great. Thank you very much!
