### ISSUE TITLE
dynamic change of the adTagUrl

### ISSUE THREAD

**Issue by andreoman** [googleads/videojs-ima#359]
Hello, is it possible dynamically to change the atTagIrl value on the VAST xml-link and reload video ? 
According to the simple examples I created the `var player = videojs('content_video');`, but I have several xml-links on the page and I want to change the atTagIrl when click on the xml-link and start video playing again.

**Comment by shawnbuso** [comment]
Have you tried calling `changeAdTag` followed by another call to `requestAds`? This should get you what you're looking for. Let me know if that works!

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you have any further questions let me know :)
