### ISSUE TITLE
What if I do not need to play any videos after Google Advertisement?

### ISSUE THREAD

**Issue by bichikim** [googleads/videojs-ima#360]
Hello~
I'd like to make my page do something after the advertisement without playing source of videos.
When I remove all sources in a video element, it is not working .
Please help me.
I want to know some way to do. should I add a short video in the video element for it?

**Comment by stoicbuddha** [comment]
If you have it set up properly, you can keep a source there (just have it be a completely black 5 second video or something) and do `playerObj.one('play', function(){ WHATEVER YOU NEED TO DO HERE });`

**Comment by shawnbuso** [comment]
Hey there,

This SDK is really overkill if you just want to show video ads - it's loading an entire video player that you're never going to use. What you want to do is called "outstream video ads," where you play ads without playing a content stream. Have you looked into any outstream video solutions?

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you have any further questions let me know :)
