### ISSUE TITLE
I get "Uncaught TypeError: player.ima is not a function"

### ISSUE THREAD

**Issue by programfight** [googleads/videojs-ima#361]
Hi,

I always get this error "Uncaught TypeError: player.ima is not a function" but I don't know why.
Anyone can help me ?

**ads.js** code
```js
var player = videojs('content_video');

var options = {
  id: 'content_video',
  adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
      'iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&' +
      'impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&' +
      'cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&' +
      'vid=short_onecue&correlator='
};

player.ima(options);

// Remove controls from the player on iPad to stop native controls from stealing
// our click
var contentPlayer =  document.getElementById('content_video_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
  contentPlayer.removeAttribute('controls');
}

// Initialize the ad container when the video player is clicked, but only the
// first time it's clicked.
var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
  startEvent = 'touchend';
}

player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
    player.play();
});
```
my php code
```php
<link href="//vjs.zencdn.net/5.3/video-js.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/4.2.6/videojs.ads.css" />
<link rel="stylesheet" href="css/videojs.ima.css" />

<video id="content_video" class="video-js vjs-default-skin" controls autoplay preload="auto" height="400"
                  poster="img/<?php echo $element['img_normal']; ?>" data-setup="{}">
                    <source src="video/<?php echo $element['video']; ?>" type='video/mp4'>
                  </video>
    <script src="https://s0.2mdn.net/instream/video/client.js" async="" type="text/javascript"></script>
    <script src="//vjs.zencdn.net/5.10.7/video.js"></script>
    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/4.2.6/videojs.ads.min.js"></script>
    <script type="text/javascript" src="script/videojs.ima.js"></script>
    <script type="text/javascript" src="script/ads.js"></script>
```

Sorry for my bad english.

**Comment by Cosrnos** [comment]
Hey @programfight,

Can you provide the full error log you're receiving? It's kind of tough to track down issues without having a stack trace. Thanks!

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you have more info or further questions feel free to re-open :)

**Comment by jackson-sandland** [comment]
Having the same issue....there should be one npm install that gets you everything you need. 
Obviously, the ima library cannot be found.

**Comment by shawnbuso** [comment]
Do you have a sample page where I can take a look? player.ima is created by videojs.ima.js (or player.ima.min.js), so make sure that's being loaded on your page.

**Comment by MrWiLofDoom** [comment]
Same problem.

`const videojs = global.videojs = window.videojs;

import * as videojsContribAds from 'videojs-contrib-ads';
window.videojsContribAds = videojsContribAds;
import * as ima from 'videojs-ima';`
...
let options = {
                id: this.playlist[0].ad.id,
                adTagUrl: this.playlist[0].ad.tag
            }
            this.player = window.videojs('video-js-player', {
                controls: true,
                autoplay: false,
                preload: 'auto'
            });
            this.player.ima(options);

it is importing the library, but not attaching itself to the main videojs object it seems. I'm running into the same problems with playlist too. Are these plugins at all compatible with es6 code?

**Comment by shawnbuso** [comment]
Do you have a live page where I can take a look? It should be compatible with ES6.

**Comment by MrWiLofDoom** [comment]
I sorted it out. Spent a lot of time on the blogs, tried a  inch of
solutions  and then everything and tried again. Last attempt got it all
working.

**Comment by prrenish** [comment]
> this.handlePlayAdTimer = setTimeout(() => {
            try {
                if (typeof this.player.ima === 'function') {
                    this.player.ima(options);
                    this.player.ima.requestAds();
                } else {
                    this.player.ima.setContentWithAdTag(null, updatedAdTagUrl, true);
                    this.player.ima.requestAds();
                    this.player.ima.initializeAdDisplayContainer();
                }
            } catch (err) {
                console.log(err); // eslint-disable-line
            }
        }, 3000);
try with a set timeout
