### ISSUE TITLE
After ads ended, ad controller at the bottom doesn't hide 

### ISSUE THREAD

**Issue by umutg4d** [googleads/videojs-ima#363]
Hello, I am using Angular2/Ionic2 project. After ads show up succesfully, the controller which informs users about how many minutes left to skip to ads stays the same and it doesn't hide. It only happens for live streaming video. It works as expected on other video types.Here are the codes:

This is the default html design. liveStreamLink in here is in m3u8 format.
 `<video id="vid1" playsinline class="video-js vjs-default-skin vjs-16-9"  controls preload="auto" autoplay
        muted
        poster=""
        src="{{liveStreamLink}}"
        type="application/x-mpegURL"
        >
      </video>`
And this is the script part 

`
       this.vid1.ima(options);

       var contentPlayer =  document.getElementById('content_video_html5_api');
        if ((navigator.userAgent.match(/iPad/i) ||
             navigator.userAgent.match(/Android/i)) &&
             contentPlayer.hasAttribute('controls')) {
                 contentPlayer.removeAttribute('controls');
       }
      this.vid1.one('ready', function() {
        this.vid1.ima.initializeAdDisplayContainer();
        this.vid1.ima.requestAds();
      }.bind(this));`

**Comment by shawnbuso** [comment]
Hey there,

Do you have a sample page where I can take a look? If not, could you share your ad tag and content URL so I can test on my end?

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you have any additional info or more questions feel free to re-open :)
