### ISSUE TITLE
VIDEOJS: ERROR: TypeError: this.contentEndedListeners[index] is not a function

### ISSUE THREAD

**Issue by joshuairl** [googleads/videojs-ima#364]
It should be known, I'm using the videojs-playlist plugin.
The preroll plays for my first video in the playlist.  Once the first item ends, that error is thrown... then the timeouts hit and the next video in the playlist queues up.

Just figured I'd send this here if needed.

![image](https://cloud.githubusercontent.com/assets/171077/25539216/243e8aa8-2c14-11e7-8f00-c0a60c653920.png)

```javascript
// ...
     /**
     * Local content ended listener for contentComplete.
     */
    this.localContentEndedListener = function() {
      if (this.adsLoader && !this.contentComplete) {
        this.adsLoader.contentComplete();
        this.contentComplete = true;
      }
      for (var index in this.contentEndedListeners) {
        this.contentEndedListeners[index]();
      }
      if (this.allAdsCompleted) {
        for (var index in this.contentAndAdsEndedListeners) {
          this.contentAndAdsEndedListeners[index]();
        }
      }
      clearInterval(this.updateTimeIntervalHandle);
      clearInterval(this.seekCheckIntervalHandle);
      clearInterval(this.resizeCheckIntervalHandle);
      if(this.player.el()) {
        this.player.one('play', setUpPlayerIntervals_);
      }
    }.bind(this);
// ...
```

**Comment by shawnbuso** [comment]
Are you calling addContentEndedListener() in your implementation? If so make sure that what you're passing there is a function. That array (contentEndedListeners) is only populated by calls to that method, so whatever it's trying to access would have been added via a call to that method.

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you still have questions feel free to re-open :)
