### ISSUE TITLE
Certain ad not muting or reporting the time left correctly

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#365]
On the following link: http://noseyshows.com/new-on-nosey/sally-new

There is a preroll ad for Glade.  The ad will pause/play just fine, but mute doesn't work.  It also doesn't report the time left in the ad.  This is the only ad we've ever tested that has these issues, as the rest perform properly with those controls.

In order to access the player object via the console for testing, you can use `dotstudiozPlayer.player`.

**Comment by shawnbuso** [comment]
I took a look at that page but I'm not seeing any ads, I just go straight to the content video. Are you still seeing the problem ad on your end?

**Comment by shawnbuso** [comment]
Closing for lack of response, but if you have any further information or additional questions feel free to re-open :)
