### ISSUE TITLE
Do not want video to autoplay

### ISSUE THREAD

**Issue by JoshWobbles** [googleads/videojs-ima#366]
Whenever I include the player.js it autoplays the ads and my video, I do not want this especially on a page that lists several videos and they all start playing at once....

**Comment by Cosrnos** [comment]
Hey @JoshWobbles !

Can you link me to a sample page this is happening on or a place I can see the code that's causing videos to autoplay? Any extra information would help with tracking down the source of this bug

**Comment by JoshWobbles** [comment]
sorry but I have since removed the script from my site. I could either get it to not autoplay (and no ads would play) or autoplay with ads.

**Comment by shawnbuso** [comment]
Hey Josh,

Sorry to hear you couldn't get it working. All of our samples are non-autoplay, except for the autoplay sample of course, so feel free to take a look at those for reference if you try to get this working again.

Thanks,
Shawn
