### ISSUE TITLE
So which version of video-contrib-ads is this library using?

### ISSUE THREAD

**Issue by joshuairl** [googleads/videojs-ima#367]
Is the dependency correct?

**Comment by Cosrnos** [comment]
We're using 3.1.8. IIRC, @shawnbuso has plans to update to 4.2.6 after some key issues are addressed

**Comment by shawnbuso** [comment]
Yes the package.json is correct - we're using ~3.1.2, so anything above or equal to 3.1.2 but less than 3.2.0. As soon as I find time I'll be updating to the latest, but I need to do a lot of testing along with that update to make sure everything still works as expected.
