### ISSUE TITLE
videojs-ima

### ISSUE THREAD

**Issue by arslanarsi** [googleads/videojs-ima#373]
I want to use multiple ads, like first on video start 2nd after 30 secs and 3rd after 1 mint. currently, it displays only preroll, no mid-roll and pos-troll

**Comment by shawnbuso** [comment]
Are you using a VMAP tag? That's the quickest and easiest way to implement what you're looking for. You can see a sample [here](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=&debug_experiment_id=1269069638).

**Comment by arslanarsi** [comment]
thank you VMAP worked
