### ISSUE TITLE
[iOS Safari] 400 Error on tag with MP4

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#375]
On the following link in Safari on iOS, we get a 400 for the ad: https://staging.player.dotstudiopro.com/share/5888d0ef99f815122efb077d?targetelm=.player&companykey=56798cd097f8156c6a339ee4&loopplayback=false&autostart=true&muteonstart=false&enablesharing=true&skin=0000ff&channelid=56b8eabd97f815600d5209a6&pagetype=channel

The video will autostart, and the ad tries to play (preroll), but errors out. I've set up the ima3_debug.js file so you can take a look.  This *only* happens on iOS Safari.  

Please note: you may sometimes get a working ad that starts out with a guy walking toward the camera; this ad is fine.  It's the other ad (GUHH) that is the issue.  You can test the link on desktop to see what I mean.

**Comment by stoicbuddha** [comment]
The ad is a preroll, by the way.

**Comment by shawnbuso** [comment]
I looked into this, and it looks like the IMA SDK is selected an m3u8 format for the ad, but the video.js player doesn't support m3u8, so it errors out. I'm going to work with the IMA and video.js folks to see if this is an error on the IMA side or the video.js side. I'll let you know what I find.

**Comment by stoicbuddha** [comment]
Hey Shawn, in my tests, it grabbed an MP4.  I utilized Charles to test.  Here is the session: https://drive.google.com/file/d/0BxUTz9Xb3eLjRExFNmNCLVR0QkE/view?usp=sharing

I have the mimeTypes set to video/mp4 because it was trying to grab an m3u8 at one point.

The client has asked DFP to look into it on their side (the creative is a direct upload to DFP from my understanding) and they said something about the player being unable to play any of the formats, but that's not true.

I did discover that on iOS, the ad will play perfectly fine if I call `player.play()` after the ad loads.  However, if I do `player.ima.startFromReadyCallback()`, these creatives specifically error out (I discovered today that was indeed the reason for the 400s).  Other creatives play just fine when calling this though.

**Comment by shawnbuso** [comment]
Hey there, are you calling initializeAdDisplayContainer() anywhere in your code? That could be the issue here - I searched for that in the sources for your sight but it only turned up in the video.js.ima library, I didn't see it in any of your implementation code.

**Comment by stoicbuddha** [comment]
@shawnbuso Here is the iOS implementation script we're using: http://dyuajcdhq9jhp.cloudfront.net/js/videojs-ima-ads/videojs-ima-ads-vmap-ios.js?bust=1496766558258

I'm not calling `initializeAdDisplayContainer()` anywhere in my code.  Should I be? I haven't had to call that for any other implementation (desktop, Android).

**Comment by shawnbuso** [comment]
Yes you'll need to call that for mobile Safari - mobile Safari requires that we initialize the ad display container as the result of a user action, so you should call that as a response to the user clicking on the play button or something similar on your page.

**Comment by stoicbuddha** [comment]
So can I not implement autoplay via the `player.ima.startFromReadyCallback()` method, then, since `initializeAdDisplayContainer()` needs to be the result of a user action?

**Comment by shawnbuso** [comment]
Specifically for mobile, yes that's correct.

**Comment by stoicbuddha** [comment]
That seems really bizarre considering you can get it to work if you autoplay normally by just playing the video.  The SDK will apparently do whatever it needs to do to play the ad.  The issue is that you can see up to 5 seconds of video before it does its thing.

So the choices are "no autoplay" or "wonky autoplay", then?

**Comment by shawnbuso** [comment]
Sorry about that - we recently made a change to the IMA SDK to support autoplay, so this should in fact work. What I'm seeing now is that for some reason as soon as your ad starts, your code is firing a custom ad timeout which is killing the ad. Are you familiar with that code? This is something happening outside of the IMA plugin - in my log I see "Ad Timeout from Plugin Fired." from videojs-ima-ad-events.min.js:1:3052. I'm not sure where that code is from, but I think you need to talk to the authors of that code to see why it's firing the timeout prematurely.

**Comment by stoicbuddha** [comment]
I am familiar with that code, as I wrote all of our ad implementation code.  We've had issues in the past where ads timed out and the SDK didn't catch it because the ads threw uncaught errors or what have you, so we set up a custom ad timeout.  If I remove that on iOS, would the ads work the way I'm trying to get them to?

The timeout is currently set to 5 seconds.  It only triggers if the videojs.ads.js plugin fires an adtimeout on the player object.  It then waits 5 seconds and checks to see if the ad has any time remaining and that said time remaining is greater than 0 (this seems to be the best way to check, but if I'm wrong, let me know).  If it has more than 0 seconds of time remaining, then we assume the ad didn't actually timeout and don't try to stop anything.  If it did, we run our cleanup functions to kill the ad and put everything we need to back in place.

**Comment by shawnbuso** [comment]
I can't see your implementation because it's minified, but I think your issue lies somewhere in the logic you just explained - I'm seeing that ad timeout fire as soon as the ad starts, so I think your way of checking if an ad is playing or not is falsely thinking that an ad is not playing.

**Comment by stoicbuddha** [comment]
If you remove the ".min" you'll get the regular version.

In our staging environment, I have increased the timeout to 30 on iOS but seem to run into the same problem. It now just takes longer to correct.

**Comment by stoicbuddha** [comment]
Do you have any follow up on this?

**Comment by shawnbuso** [comment]
Sorry for the delay - do you have a version of your page from your first comment that loads that non-minified script? It'll be a lot easier to debug if I can break on the executing script on the page. Thanks!

**Comment by shawnbuso** [comment]
Closing this for lack of response, but if you still need me to look into it please re-open. Thanks!
