### ISSUE TITLE
techName_ Flash - Cannot read property 'hasAttribute' of null at new ImaPlugin

### ISSUE THREAD

**Issue by samueleastdev** [googleads/videojs-ima#378]
Hi,

When I try and use vpaid ads with flash tech I get this error.

~~~
TypeError: Cannot read property 'hasAttribute' of null at new ImaPlugin
~~~

My setup is.
~~~
videoPlayer.ima({
    id: "video-player",
    adTagUrl: "https://googleads.g.doubleclick.net/pagead/ads?ad_type=video&client=ca-video-pub-4968145218643279&videoad_start_delay=0&description_url=http%3A%2F%2Fwww.google.com&max_ad_duration=40000&adtest=on"
});

// Remove controls from the player on iPad to stop native controls from stealing
var contentPlayer = document.getElementById("video-player_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
        navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
    contentPlayer.removeAttribute('controls');
}

var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
    startEvent = 'touchend';
}

// Initialize the ad container when the video player is clicked, but only the
videoPlayer.one(startEvent, function() {

    videoPlayer.ima.initializeAdDisplayContainer();
    videoPlayer.ima.requestAds();
    videoPlayer.play();

});
~~~

Any suggests? 

I have the following setup.
~~~
"video.js": "^5.19.1",
"videojs-contrib-hls": "5.5.3",
"videojs-contrib-ads": "~3.1.2",
"videojs-ima": "0.6.0",
~~~

Just as a update i am using this with live streaming hls works fine but if i have rtmp set it wont work.

Thanks

**Comment by shawnbuso** [comment]
Hi there - are you still seeing this issue? If I test your tag in our [advanced example](http://googleads.github.io/googleads-ima-html5/advanced/) it works fine and I don't see the error. If you still have an issue, do you have a sample page I can take a look at? 

Also this may be unrelated but [we don't yet have support for the HLS plugin alongside the IMA plugin](https://github.com/googleads/videojs-ima/issues/314).

**Comment by maddhacker24** [comment]
I'm having the same issue with that exact error. I'm using the "simple example". The only difference is that I'm using "techOrder": ["flash", "html5"]

**Comment by shawnbuso** [comment]
Ah ok is that tech order for the video.js player? The IMA plugin only supports the HTML5 video.js player - we don't have support for the Flash player.

**Comment by shawnbuso** [comment]
Closing this out since it's been a month with no response, but if you're still seeing this issue please feel free to re-open and we can continue to investigate :)
