### ISSUE TITLE
VPAID Ads plays audio, but with a black screen in front of the video ad, making the video visualization impossible. 

### ISSUE THREAD

**Issue by willhessel** [googleads/videojs-ima#385]
Similar to https://github.com/googleads/videojs-ima/issues/356 
and https://github.com/googleads/videojs-ima/issues/128
It's not the first time we face it, and it's not aways it happens.
We've received from an advertiser the screenshot confirming the problem we've faced as well:

VPAID Ads plays audio, but with a black screen in front of the video, making the video visualization impossible. 
![gp_black_screen](https://cloud.githubusercontent.com/assets/12644691/26701136/4d572e34-46f6-11e7-9893-7745bd1c5787.jpg)

Is it a known bug?
Where is the problem? IMA or Player?

Thanks

**Comment by shawnbuso** [comment]
We had this issue in the IMA SDK a few months back but it was resolved there - do you have a sample page where I can see this issue live?

**Comment by willhessel** [comment]
Hi Shawn, thanks for your response.
Here is an exemple that we face in the preview of a VPAID tag:
http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=PwOSVGgU0GYY353cyQUw37mR0QWIAYCAgKDL39jS4AE&op=set&redirect=https://globoplay.globo.com/v/5548871/programa/&redirect_hash=AJlzBa0POFWYHJ1uUyVLWYU18l9ayeOhJA&lineItemId=763598533&creativeId=113378901133

Now we have an open issue with the Google (BR) support team, but as you asked an exemple, here it goes. Seems it has something to do with preload (combined with VPAID enabled and adrules) feature, and the IMA team will work on it.

**Comment by shawnbuso** [comment]
Thanks for the update - is that page using the video.js plugin? I saw the issue with the Google support team (I work on those as well) but I didn't realize that it was using this plugin.

**Comment by shawnbuso** [comment]
Closing this out since it's been a month without a response, but if you're still seeing the issue please feel free to re-open and we can continue to investigate :)

**Comment by willhessel** [comment]
@shawnbuso thanks!
They've confirmed an issue with IMA SDK. The problem is when you have a combination os pre-load + adRule + tags VPAID. Then the black layer may appear, not always. To force this issue I recommend to make a DFP creative preview...in this condition (pre-load + adRule + VPAID) the black layer will aways appears. 
Thanks anyway for your response and we'll be waiting for the bug fix from IMA SDK team. Until there we've disabled the pre-load impacting only the midrolls. 

Cheers
