### ISSUE TITLE
iOS: Specific ads break seeking in main video's

### ISSUE THREAD

**Issue by nickygerritsen** [googleads/videojs-ima#386]
If I use the following adtag:

```
https://search.spotxchange.com/vast/2.0/85394?VPAID=js
```

something goes wrong when the ad finishes playing on iOS. I can not seek ahead in the video, until the video has actually played to that point (i.e. I can not seek from 10s to 20s if the video has only played until 10s). I can however seek back.

This seems to be the case for all ads from SpotXchange, but I can find no reason why this happens. Even setting the `currentTime` on `player.tech_.el_` does not work...

Things I have found:

* It does not go wrong with the IMA SDK itself, i.e. it seems to be tied to either this plugin or video.js
* It does not happen with other adtags
* It only happens on iOS (both iPad and iPhone)

I hope anyone has any clue what is happening, because I am stuck here 😢

**Comment by shawnbuso** [comment]
It looks like that tag is returning empty VAST now - are you still seeing an ad on your end?

**Comment by nickygerritsen** [comment]
Ah you need to add a param to the tag, my bad. This should return a response: https://search.spotxchange.com/vast/2.0/85394?VPAID=js&content_page_url=https://google.nl

**Comment by shawnbuso** [comment]
Thanks for the update - it looks like this is an SDK issue - I'm able to repro on an SDK sample page without the video.js plugin. We have some logic that prevents users from seeking through an ad, and I think for some reason this logic is not being killed when this particular ad completes. I've opened an issue with the IMA SDK team and I'll update here when that gets resolved.

**Comment by shawnbuso** [comment]
Hi there - are you still seeing this issue? I tested on my end and it appears to be resolved, so let me know if you're still seeing it on your end. Thanks!

**Comment by shawnbuso** [comment]
Closing this out since it's resolved from my end - if you're still seeing the issue feel free to re-open or start a new issue. Thanks!
