### ISSUE TITLE
How to control fallbacks order?

### ISSUE THREAD

**Issue by vrnezhdanov** [googleads/videojs-ima#387]
Hello guys, –

I'm trying to setup fallbacks functionality (or waterfalling) using VAST and IMA SDK (using Extensions). I've checked this question: https://github.com/googleads/videojs-ima/issues/278 and clarification answers.

So here is the VAST XML I have:
```<VAST version="3.0">
<Ad id="1">
<Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
                <![CDATA[AD TAG ONE]>
    </VASTAdTagURI>
    <Error>
        <![CDATA[https://www.error_tracker.com]]>
    </Error>
    <Extensions>
        <Extension type="waterfall" fallback_index="0"/>
    </Extensions>
</Wrapper>
</Ad>
<Ad id="1">
<Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
        <![CDATA[AD TAG TWO]>
    </VASTAdTagURI>
    <Error>
        <![CDATA[https://www.error_tracker.com]]>
    </Error>
    <Extensions>
        <Extension type="waterfall" fallback_index="1"/>
    </Extensions>
</Wrapper>
</Ad>
<Ad id="2">
<Wrapper>
    <AdSystem>AD_SYSTEM</AdSystem>
    <VASTAdTagURI>
        <![CDATA[AD TAG THREE]>
    </VASTAdTagURI>
    <Error>
        <![CDATA[https://www.error_tracker.com]]>
    </Error>
    <Extensions>
        <Extension type="waterfall" fallback_index="2"/>
    </Extensions>
</Wrapper>
</Ad>
</VAST>
```

I was testing in google vast inspector and in JWPlayer test tool. In both these tests ads are played in order of appearance of the corresponding <Ad> tags in XML. So, the first one plays AD TAG ONE.In case i break the AD TAG ONE, than AD TAG TWO is being played. However, when all tags are in place and working, changing of 'fallback_index' does not change anything. Say, if i give a fallback_index of "1" to AD TAG ONE and fallback_index of "0" to AD TAG TWO, but the order of <Ad> tags in XML is the same, the AD TAG ONE will be played. Is that expected? I assumed that setting the fallback_index is a way to order the priority of AD TAGS. Am i getting it wrong?

Thank you.

**Comment by shawnbuso** [comment]
Yes this is expected behavior - the fallback_index is only considered once we have to fall back. If your first ad succeeds, we won't look at its fallback index. If you want the ads to play in a different order, you'll have to rearrange the XML to have them ordered the way you want them to play.

**Comment by vrnezhdanov** [comment]
Hi Shawn, –

thank you. 

When the AD TAG ONE is broken and AD TAG TWO and AD TAG THREE are alive, changing fallback_index for AD TAG ONE and AD TAG TWO (making one greater then another and vice versa) does not make AD TAG ONE and AD TAG TWO to play in different order. Actual fallback is happening, but it is not controlled by fallback_index.

Can't get why..

**Comment by shawnbuso** [comment]
Correct - we always try to play the first ad in the response first, regardless of the fallback index. If that fails, we look for the lowest fallback index of the remaining ads. In this case that would be ad 2, so we go ahead and play ad 2.
