### ISSUE TITLE
Google IMA sdk throw erorr when vast document return no ads on Mobile Devices

### ISSUE THREAD

**Issue by omeryounus** [googleads/videojs-ima#388]
## Description
Briefly describe the issue.
Google imaSDK ima3.js throw exceptions when there is no ads return from the vast xml. 

## Steps to reproduce

1. Set the ima-container on the videojs player
2. Let the vast xml return no ads or empty vast xml document

var videoPlayer = videojs("video");
videoPlayer.ima({
    id: "video",
    adTagUrl: "https://pubads.g.doubleclick.net/gampad/ads?"ADS_URL"
});
videoPlayer.ima.initializeAdDisplayContainer();
videoPlayer.ima.requestAds();

videoPlayer.one("click", function() {
    videoPlayer.play();
});

### Expected
It should be able to click on the video to play it on the mobile devices browsers. On desktop it works fine.
### Actual
Please describe what actually happened.
It throws error and you cannot able to play the video 
### Error output
ima3.js
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Jq (ima3.js:303)
    at Hq.K (ima3.js:304)
    at Zg (ima3.js:82)
    at tq.h.dispatchEvent (ima3.js:80)
    at tq.w (ima3.js:294)
    at Wg (ima3.js:77)
    at Sg (ima3.js:78)
    at ima3.js:76

Using ima3_debug.js
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Xq (ima3_debug.js:321)
    at Vq.R (ima3_debug.js:322)
    at sh (ima3_debug.js:93)
    at R (ima3_debug.js:91)
    at wq.B (ima3_debug.js:306)
    at oh (ima3_debug.js:88)
    at kh (ima3_debug.js:89)
    at ima3_debug.js:87

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
videojs version = 5.19.2

#### browsers
what browser are affected?
Chrome, safari on Mobile devices
#### OSes
what platforms (operating systems and devices) are affected?
IOS, Android
### plugins
are any videojs plugins being used on the page? If so, please list them below.
Google IMASDK platform 
ima3.js

**Comment by omeryounus** [comment]
Yes, updated to latest videojs-ads, and videojs-ima but still getting the same error. 
For short turn around I have used the following code for touch Listener for mobile 

this.posterImage.el().style.zIndex = 1400
this.bigPlayButton.el().style.zIndex = 1410
this.loadingSpinner.el().style.zIndex = 1420

This has temporarily fix the issue but not the solution. 

Can anyone please advise for a better fix?

**Comment by omeryounus** [comment]
for a example...
https://codepen.io/JoshHubi/pen/MejZZQ?editors=1010

**Comment by omeryounus** [comment]
similar issue

[https://github.com/googleads/videojs-ima/issues/339](url)

**Comment by omeryounus** [comment]
Hey @shawnbuso is there any update?

**Comment by renewj** [comment]
https://github.com/googleads/videojs-ima/issues/339
