### ISSUE TITLE
Preroll and Postroll with different calls

### ISSUE THREAD

**Issue by thiagonzalez** [googleads/videojs-ima#389]
Hello guys
We work with VAST here and I have one URL for preroll and another one for postroll.
I want to call preroll when the video starts and postroll when the video finishes.
When the video starts I declare adTagUrl and id on player.ima(). When I tried to declare player.ima() again with the postroll URL on player.ended() I got some errors.

ERROR: `VIDEOJS: ERROR: TypeError: player.ima is not a function`

Is that possible to do?

--- 
UPDATE:
I tried to execute `player.ima.resetIMA_();` on player.ended() but I got the same error.

**Comment by shawnbuso** [comment]
Currently it's not possible to do this with 2 separate requests, however you can build a VMAP doc that contains those 2 requests and use that to accomplish the same thing. Take a look at [this sample tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=&debug_experiment_id=1269069638) - you can remove the mid-roll node in the middle, then replace the ad tag URIs for preroll and postroll with the tags that you want to use.
