### ISSUE TITLE
DFP SB and most other ad networks don't support VMAP

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#39]
Hi,

The current structure of the VideoJS and IMA integration, supposed that the ad network supports VMAP and/or AdRules. However, it appears that most of the ad serving platforms, including DFP SB, do not offer this.
This by itself, makes it impossible to serve anything different than preroll with the current IMA integration.

**Comment by shawnbuso** [comment]
This doesn't sound like an issue with the video.js plugin to me, so I'm closing it. If there's something we can do to help let me know. We do test with VMAP/ad rules responses and they do work.
