### ISSUE TITLE
Once Ads are Played, Video Stream (.m3u8) Doesn't Resume on Mobile (Chrome)!

### ISSUE THREAD

**Issue by maryam-abdullah** [googleads/videojs-ima#390]
Hello,
The code below has prevented the video from resuming after an ad ends on mobile (Chome).
Any thoughts, please?

My complete code:
```
<script src="~/Content/VideoJS/js/videojs.js"></script>
<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
<script src="~/Content/VideoJS/js/videojs-contrib-hls.js"></script>
<script src="~/Content/VideoJS/js/videojs.ads.js"></script>
<script src="~/Content/VideoJS/js/videojs.ima.js"></script>

<video id="content_video" class="video-js vjs-default-skin" controls width="640"
       height="360">
    <source src="https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"
            type="application/x-mpegURL">
</video>

<script>
    var player = videojs('content_video');
    var options = {
        id: 'content_video',
        adTagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?' +
            'sz=640x480&iu=/37592844/5flix-vast&impl=s&gdfp_req=1' +
            '&env=vp&output=vast&unviewed_position_start=1&url=' +
            '[referrer_url]&description_url=[description_url]&correlator=[timestamp]'
    };
    player.ima(options);
    player.ima.requestAds();
    player.ima.initializeAdDisplayContainer();
    player.play();
</script>

```
The weird thing I tested it in Firefox (PC with mobile emulator) and it worked perfectly well, but in Chrome, it doesn't work. Is it supported on those browsers?
**On Chrome (PC with mobile emulator), after the ad ends, the player stays in a loading state infinitely.**
**PS:** Once I replaced the m3u8 with an mp4 video, it works fine.
Thanks.

**Comment by maryam-abdullah** [comment]
The issue was solved after I added:

```
var startEvent = 'ready';
if (navigator.userAgent.match(/iPhone/i) ||
   navigator.userAgent.match(/iPad/i) ||
   navigator.userAgent.match(/Android/i)) {
   startEvent = 'touchend';
}
player.one(startEvent, function () {
   player.ima.initializeAdDisplayContainer();
   player.ima.requestAds();
   player.play();
});
```
I also added "autoplay" to the video tag.

**Comment by shawnbuso** [comment]
Yep that makes sense - on mobile you need to call `initializeAdDisplayContainer` as the result of a user action. We did have an issue in the past as well with resuming m3u8s in the IMA SDK, so your addition of `autoplay` probably helped resolve that.

**Comment by fahadpk01** [comment]
Hello I am also trying to play play m3u8 streaming files with IMA DAI SDK for HTML5 with its not working.

i used the above code but its not working. Please help me in this regard
