### ISSUE TITLE
Preroll plays several seconds after content starts (Firefox/Safari/Mac)

### ISSUE THREAD

**Issue by skmelendez** [googleads/videojs-ima#392]
Link to view: https://googleads.github.io/videojs-ima/examples/advanced/
Use the sample and hit play. Make sure you are not cached. On play you will see the preroll play a second or more after the content starts.

**Comment by shawnbuso** [comment]
This looks like a buplicate of #167 - does that sound right?

**Comment by skmelendez** [comment]
That sounds about right. I have tried to see about changing the timers for timeout settings and it had no effect on some of the lower bandwidth stuff. Also, I have pages which may take 'x' amount of time to fully load and this affects them there. 

Is there a fix in the works for this already? I know its marked as a bug, but if there is something in the works, would you have a rough ETA of when it would be available?

**Comment by shawnbuso** [comment]
We're still looking into this one - it looks like it will require a small re-write of the plugin to work with the latest version of the contrib-ads plugin, so we're hoping to do that some time in Q4. I'm going to close this issue out and we can use #167 for updates.
