### ISSUE TITLE
[iOS] Ads pausing when loaded and not playing again

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#393]
Our player is here: player.dotstudiopro.com/share/5888d0ef99f815122efb077d?targetelm=.player&companykey=56798cd097f8156c6a339ee4&loopplayback=false&autostart=true&muteonstart=false&enablesharing=true&skin=0000ff&channelid=56b8eabd97f815600d5209a6&pagetype=channel

On iOS, when a video plays and the ad gets fill, you'll see that the ad loads, then fires a pause (it's logged in the console), then will not start again.  There is a Toyota ad that's currently in the mix that has a black bar overlay on top of the iOS controls, but the iOS controls don't really work anyway for ads, as they just trigger an ad click if you tap them.

Once you tap the Toyota ad, and it opens the url in another screen, if you go back to the player, you'll see a big white play button.  If you click it, the ad plays.

If it's not the Toyota ad, it just simply will not play. It pauses, and goes nowhere and does nothing.  There is one ad we've seen come from the tag attached to the player above that sometimes plays in iOS, but it's rare to see and in several hours of testing, I think we saw it twice.

In our staging environment (add `staging.` to the url above) I've removed every player pause I could find related to iOS, in case it was doing something funky.  No dice.

The ads we get from that tag are VPAID, so it may be related to that.  We've only experienced these issues on iOS, and only within the last couple of weeks.

We've tested with SpotX test ads and they work: http://player.dotstudiopro.com/share/57be6f6697f815f57ed5784d?targetelm=.player&companykey=5429b21c97f8153f257b23c6&skin=228b22&autostart=true

I tested with the IMA Linear sample, and it worked great.

I've also tested the following VPAID tag and it works great: https://rtr.innovid.com/r1.5554946ab01d97.36996823;cb=567468746468476464

So at this point, I don't know if it's the particular ads, or if it's something weird with DFP, or what.

**Comment by shawnbuso** [comment]
Hey there,

I think the issue lies somewhere in your implementation - I was able to extract the problem Toyota ad, and when I test it on our [advanced example](http://googleads.github.io/videojs-ima/examples/advanced/) it plays fine. I'm wondering if the issue has something to do with your autoplay implementation - are you able to get this to work with click-to-play? If so then we know the problem lies there and we can dig deeper.

Thanks,
Shawn

**Comment by stoicbuddha** [comment]
I havent tried click-to-play yet. You can set autostart=false in the url to stop it from autoplaying. 

That particular ad seems to start and immediately pause on iOS and Android. I can start it again on Android though. Much more of a pain on iOS. Did you test it with the player expanded?

**Comment by stoicbuddha** [comment]
Do you have any follow up for this?

**Comment by hyurtseven81** [comment]
Same issue occurs for me too, i tried click-to-play autoplay
before last autoplay update i was initialising ima when user touched but after autoplay update i changed that behaviour and i initialise ima when player loaded but there is an interesting issue,

Autoplay or click-to-play the behaviour is same

ad starts pauses but the interval still runs and 10 seconds later ad changes even it still paused.

The behaviour does not happen on desktop mode.

Thanks

**Comment by shawnbuso** [comment]
@hyurtseven81 do you have a sample page I can take a look at to debug? Thanks!

**Comment by KevinBrogan** [comment]
If you "autoplay" a video by using element.play() instead of using the autoplay attribute, then mobile on ios and chrome will both pause the video instead of giving you a permission denied message. This will trigger a pause event. Make sure you always start muted with autoplay on mobile.

On Android, note that the ad plays with no audio. Something in the code is turning the audio off and then attempting to play again.

**Comment by shawnbuso** [comment]
Thanks @KevinBrogan.

+1 to what Kevin said. For those of you having trouble with autoplay, take a look at our [autoplay sample](https://github.com/googleads/videojs-ima/tree/master/examples/autoplay), which is working for me across all mobile platforms.

**Comment by shawnbuso** [comment]
Closing because I think following the autoplay sample is the way to go. If anyone is still having issues feel free to re-open. Thanks!
