### ISSUE TITLE
IMA sdk issue with Vidoejs on Mobile Device

### ISSUE THREAD

**Issue by omeryounus** [googleads/videojs-ima#396]
## Description
Briefly describe the issue.
Google imaSDK ima3.js throw exceptions when there is no ads return from the vast xml. 

## Steps to reproduce

1. Set the ima-container on the videojs player
2. Let the vast xml return no ads or empty vast xml document

var videoPlayer = videojs("video");
videoPlayer.ima({
    id: "video",
    adTagUrl: "https://pubads.g.doubleclick.net/gampad/ads?"ADS_URL"
});

var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
navigator.userAgent.match(/iPad/i) ||
navigator.userAgent.match(/Android/i)) {
startEvent = 'touchend';
}

videoPlayer.ima.initializeAdDisplayContainer();
videoPlayer.ima.requestAds();

videoPlayer.one(startEvent , function() {
    videoPlayer.play();
});

### Expected
It should be able to click on the video to play it on the mobile devices. On desktop it works fine.
### Actual
Please describe what actually happened.
It throws error and you cannot able to play the video 
### Error output
ima3.js
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Jq (ima3.js:303)
    at Hq.K (ima3.js:304)
    at Zg (ima3.js:82)
    at tq.h.dispatchEvent (ima3.js:80)
    at tq.w (ima3.js:294)

Basically, this error happened on the function 'createTouchlist()' and it's not able to handle the touch type. 

for example: 
touchend, click or tap etc. 

Using ima3_debug.js
Uncaught TypeError: Cannot read property 'apply' of undefined
    at Xq (ima3_debug.js:321)
    at Vq.R (ima3_debug.js:322)
    at sh (ima3_debug.js:93)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
videojs version = 5.19.2

#### browsers
what browser are affected?
Chrome, safari on Mobile devices
#### OSes
what platforms (operating systems and devices) are affected?
IOS, Android
### plugins
are any videojs plugins being used on the page? If so, please list them below.
Google IMASDK platform 
ima3.js

**Comment by GLStephen** [comment]
I'm seeing similar behavior:

Uncaught TypeError: Cannot read property 'apply' of undefined
    at gp (ima3.js:723)
    at ep.M (ima3.js:724)
    at Ag (ima3.js:492)
    at Q (ima3.js:490)
    at Ro.B (ima3.js:714)
    at xg (ima3.js:488)
    at ug (ima3.js:489)
    at ima3.js:486

**Comment by shawnbuso** [comment]
Are you able to repro this in our sample at http://googleads.github.io/videojs-ima/examples/advanced/ ? I'm not seeing it there when I test on my Pixel or iPhone. We had something similar reported in #183 that has since been resolved, so can you make sure that you're on the latest version? You can check if you have that fix by looking for the `onAdsLoaderError_` method in the plugin source you're using and checking if it has the line `adContainerDiv.style.display = 'none';`

**Comment by shawnbuso** [comment]
I'm going to close this for lack of response - if you're still seeing the issue feel free to re-open. Thanks!
