### ISSUE TITLE
How to read VAST file from videojs-ima

### ISSUE THREAD

**Issue by sgromkov** [googleads/videojs-ima#397]
Hello!

Faced with the task: I should read a VAST file, and if there is a custom `<Extension type="linkTxt">` display the custom element with reached text over the advertising. ([Vast file custom extensions screenshot](http://joxi.ru/DrlOlxySvEZ97A)).

I figured out how to create my own elements on top of advertising ([did it here](https://github.com/sgromkov/videojs-ima/commit/d3f63b2d80d546caf0dc72e62b0e5bfbaefbf200)).

Could you give me some advice how to get the content of the VAST file, to pull out of it my extension value?

**Comment by shawnbuso** [comment]
Hey there,

Unfortunately the plugin can't offer access to the underlying VAST - all of the parsing and handling is done by the IMA SDK, and that SDK does not expose the VAST response to us.

**Comment by sgromkov** [comment]
Thank you, shawn!
