### ISSUE TITLE
concat all files produces error

### ISSUE THREAD

**Issue by leccyril** [googleads/videojs-ima#398]
when i concat all those files :  

    
    <script src="./js/video.js" type="text/javascript" ></script>
    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script src="./js/videojs.ads.js" type="text/javascript" ></script>
    <script src="./js/videojs.ima.js" type="text/javascript" ></script>

it make me an error : 

local.js:804 Uncaught TypeError: Cannot read property 'Events' of undefined
    at local.js:804
    at local.js:804

it happens when i add videojs in top of all files it is mandatory for me to concat all files because only one file will be integrated on websites...

any idea?

**Comment by shawnbuso** [comment]
Do you have a copy of the concatenated file I can take a look at? Also we *strongly* recommend against hosting your own copy of ima3.js - that file gets regular updates, and if you store it and use your own copy you'll miss out on those updates, which could break things in the future.

**Comment by leccyril** [comment]
just contact with first video.js, then ima3.js sdk then ads.js then ima.js...mine is specifiq to me... that files is regular updated but for example brightcove recompile for his need and incorpore it into his js file.... i need to do the same thing and have a light SDK file how can i do ?

**Comment by leccyril** [comment]
[test.txt](https://github.com/googleads/videojs-ima/files/1167528/test.txt)

**Comment by shawnbuso** [comment]
Unfortunately the use case you describe for ima3.js is not supported - the SDK should error out if it sees that it's loaded from any domain other than the one on which we host it. Does this work if you concatenate all of the files except for ima3.js?

**Comment by leccyril** [comment]
it is working with ima3.js after delete the exception in minimified JS... i will try it and say to you... but it is mandatory we have only one JS file -(

**Comment by shawnbuso** [comment]
Unfortunately as noted above this is not supported - you'll need to load ima3.js from our servers, and not store a local copy of your own.

**Comment by leccyril** [comment]
you say if i manage to get it locally and have for example the problem i have now it is not supported ? so no one could fix this issue ? thanks for great help!

**Comment by shawnbuso** [comment]
I'm sorry I can't be of more help, but the SDK is reliant on you using the latest version at all times, so we enforce the policy that you cannot store the SDK file locally to ensure that you're always on the latest version.
