### ISSUE TITLE
Video Starts from beginning after Midroll On Iphone

### ISSUE THREAD

**Issue by yaakovbg** [googleads/videojs-ima#399]
A few months ago there wasn't such a Issue.

What ever happens is: preroll runs, video starts running until 15 seconds, midrolls run, after last midroll the video begins from the start(time 0:00).

I have even tested on the samples:https://googleads.github.io/videojs-ima/examples/simple/.

Your Iphone sample doesn't have a midroll so I copied the code to the following link:http://player.sport5.co.il/vidclean/adstest/testads3.html?v=3 and added the tag with midrolls.

I have tested on Iphone 6 and Iphone 5, furthermore the bug seems to happen also on the chrome emulator when the device is set to Iphone 5 or 6.

**Comment by shawnbuso** [comment]
Thanks for the report - we're aware of this one and it's an issue in the IMA SDK that will be fixed in the next release. This won't require a new release of the plugin - we'll automatically pick up the fix when IMA releases it.

**Comment by shawnbuso** [comment]
FYI this should now be fixed - let me know if you're still seeing it.

**Comment by ypavlotsky** [comment]
Closing this one as we haven't heard back for a while. Let me know if you're still seeing this.
