### ISSUE TITLE
Add better iPhone support

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#4]
iPhone support requires custom ad playback, which is not yet supported by the plugin.

**Comment by samichamoun** [comment]
@shawnbuso I've had a look at your iPhone sample and I'm wondering whether you could explain why its using GPT? My understanding is that companion ads are a feature of DFP is that correct?

I currently use AFV (adsense for video) and am looking to integrate my adTag into the VideoJS player. This works fine using the basic sample supplied here: https://googleads.github.io/videojs-ima/examples/simple/ads.js

however this does not work on iPhone as you are aware. I'm not running DFP and was hoping I could just plug my general adTag into the plugin which I've done, but when looking at the iPhone example I feel this sample isn't relevant to someone with my setup. Are you able to supply an alternative solution?

**Comment by samichamoun** [comment]
To clarify - I want to run video preroll not just banner companion ads

**Comment by shawnbuso** [comment]
@samichamoun you're correct - the iPhone sample is using GPT to support companions. Our samples use DFP tags, which is why we add companion support. GPT and companions aren't requirements for the SDK, though - the iPhone sample should work just fine with your tag. If you're not using companions, you can remove the GPT code as well. If your tag isn't working with the iPhone sample let me know!
