### ISSUE TITLE
Macros replacement in Ad Tag URL not working

### ISSUE THREAD

**Issue by dingman** [googleads/videojs-ima#401]
Hi! I'm testing out the Macros for adTagURLs but I don't see it being replaced when the ad tag is called via Network tab in Chrome.

I have my tag setup

```
var options = {
  id: 'content_video',
  adTagUrl: 'http://v.lkqd.net/ad?pid=12345&sid=12345&output=vastvpaid&support=html5flash&execution=any&placement=&playinit=auto&volume=100&width=768&height=432&pageurl={window.location.href}&rnd={random}'
};
```

But when the ad tag is called, it doesn't replace the values of {random} or {window.location.href} like I expected it to.

How do I get the macros working so it replaces the values with the real values during the ad tag call?

**Comment by shawnbuso** [comment]
Hey there,

I don't think the IMA SDK is expecting these macros, so we're just ignoring them. I think you'll need to fill them in manually like so:

```
var tag = 'http://v.lkqd.net/ad?pid=12345&sid=12345&output=vastvpaid&support=html5flash&execution=any&placement=&playinit=auto&volume=100&width=768&height=432&pageurl=' + encodeURIComponent(window.location.href) + '&rnd=' + Math.floor(Math.random() * 100000000000000000);
```

**Comment by dingman** [comment]
Hi Shawn

That's what I ended up doing.

`function tagReplacement(tag) {
    var player_id = '#content_video';
    tag = tag.replace("__player-width__", getComputedStyle(document.getElementById('content_video')).width);
    tag = tag.replace("__player-height__", getComputedStyle(document.getElementById('content_video')).height);
    tag = tag.replace("__page-url__", encodeURIComponent(window.location));
    tag = tag.replace("__player-width__", getComputedStyle(document.getElementById('content_video')).width);
    tag = tag.replace("__random-number__", Date.now());
	tag = tag.replace("__referrer__", encodeURIComponent(document.referrer));
    return tag;
}
var adTagUrl = tagReplacement('http://ts4vh-f6a2n.ads.tremorhub.com/ad/tag?adCode=this&playerWidth=__player-width__&playerHeight=__player-height__&playerPosition=1&srcPageUrl=__page-url__');`

Odd though, because the github page says there is macro support for standard macros and I can add my own, but was never able to get it working. Dont know if we should close this issue or not.

**Comment by shawnbuso** [comment]
If you're using the videojs-ima plugin then you're in the right place - maybe those are contrib-ads macros that I'm not aware of? Glad to hear you got it working, though - let me know if there's anything else I can do to help.

**Comment by spormeon** [comment]
i'm getting the same issue as this,  i have contrib ads and its setting the url of the page that you we're on before and a lot of ad suppliers are telling me that they are getting domains of facebook.com etc (prob getting the url of where the user came from before hitting first page on site)  how do i fix this,  ima is supposed to override this url:  anyway?

![DevTools_-_www_twentyfournews_com_homepage_latest-news_png_and_Latest_News_Archives_-_Twentyfournews_com](https://user-images.githubusercontent.com/8503167/90008773-c6fd9700-dc94-11ea-934e-0ca4c9da3187.png)
