### ISSUE TITLE
VAST/VPAID Waterfall on adserror

### ISSUE THREAD

**Issue by dingman** [googleads/videojs-ima#402]
I've been researching it, but haven't found any concrete documentation on it.

How would I setup an IMA waterfall where I could put in X number of VAST/VPAID tags as pre-roll, and it would try each one until an ad is found. Or ping all of them and see which one returns an ad first - either would work.

TIA!

**Comment by shawnbuso** [comment]
Currently this multiple-tag set-up isn't supported with the IMA SDK - the way we do this is with a single ad tag that returns multiple ads. We'll try to play the first, and if it fails move on to try to play the second, etc.

**Comment by dingman** [comment]
@shawnbuso so it's not possible to setup a waterfall with X number of different ad networks, even within a single ad tag?

**Comment by dingman** [comment]
@shawnbuso I tried what you suggested in the other issue, trying to use vast.xml and calling that single file with multiple networks within it. Maybe I formatted it incorrectly, but it wasn't firing anything, even 100% fill test tags from Google.

https://github.com/googleads/videojs-ima/issues/278

Appreciate any help you can provide to accomplish this kind of "waterfall" like approach.

**Comment by shawnbuso** [comment]
@dingman that recommendation from #278 should still work - if you pass along the VAST response you created I can take a look and let you know if it looks ok.

**Comment by dingman** [comment]
Hi @shawnbuso thanks for the follow-up.

Here's what I have, which should provide 100% fill rates, but I'm not seeing any ads when I use this file as the adTagUrl

```

  | <?xml version="1.0" encoding="UTF-8"?>
-- | --
  | <vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
  | <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
  | <vmap:AdSource id="preroll-ad-1" allowMultipleAds="false" followRedirects="true">
  | <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&ppos=1&lip=true&min_ad_duration=0&max_ad_duration=30000&vrid=6496&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=https://github.com/videojs/videojs-contrib-ads/issues/117&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
  | </vmap:AdSource>
  | </vmap:AdBreak>
  | <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
  | <vmap:AdSource id="preroll-post-bumper" allowMultipleAds="false" followRedirects="true">
  | <vmap:AdTagURI templateType="vast3"><![CDATA[https://pubads.g.doubleclick.net/gampad/ads?slotname=/124319096/external/ad_rule_samples&sz=640x480&ciu_szs=300x250&unviewed_position_start=1&output=xml_vast3&impl=s&env=vp&gdfp_req=1&ad_rule=0&vad_type=linear&vpos=preroll&pod=1&bumper=after&min_ad_duration=0&max_ad_duration=10000&vrid=6496&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&url=https://github.com/videojs/videojs-contrib-ads/issues/117&video_doc_id=short_onecue&cmsid=496&kfa=0&tfcd=0]]></vmap:AdTagURI>
  | </vmap:AdSource>
  | </vmap:AdBreak>
  | </vmap:VMAP>
  |  
```

**Comment by dingman** [comment]
Actually I think I got it, looks like a CORS restriction that I spotted on another site. I allowed CORS and it worked great.

Now the issue is, most of the tags I have, require macros to be replaced on runtime. Such as player-width, player-height, cachbuster, referrer, current page URL. Is it possible to pass those values to the XML file and process, without using some server-side logic? Wouldn't work for responsive either since that changes based on the screen size.

Thoughts?

**Comment by shawnbuso** [comment]
Unfortunately that's not accessible :/ The IMA SDK doesn't provide access to the raw VAST response data, and doesn't have a window in which you can modify it before it makes the request.

**Comment by dingman** [comment]
I ended up rolling my own with some server-side processing to power the macros - https://www.jonathan.vc/tech/2017/08/setup-vastvpaid-waterfall-videojs

Thanks for all your help @shawnbuso!

**Comment by cameronchurch** [comment]
@dingman I know you closed this issue but if you're interested we've developed a videojs plugin (for our Video Ad Analytics platform called Ad Tracer) that has a macro system that works client side.  Happy to discuss it more if you're still in need.

**Comment by dingman** [comment]
Hi @cameronchurch absolutely, I'm using a server-side solution right now, but something client side would be much more functional so it can be fully hosted on a CDN.

Are there any docs on the new feature?
