### ISSUE TITLE
Pre-roll loaded but now showing on Ipad

### ISSUE THREAD

**Issue by canhnm** [googleads/videojs-ima#407]
Hi everyone,

I am currently implementing Videojs with IMA and facing issue while playing pre-roll ads.
Player loads the ads successfully but the ads content and also catches the ads events weel but does not show, seems like it is hidden behind the player element.
The demo is on http://test.mst.24h.com.vn/canhnm/24hplayyer/examples/index-preroll.html , it's the second video player!

Anyone got this issue? Please give me your advise!

Cheers,
Canh

**Comment by KevinBrogan** [comment]
Works for me. 13 inch ipad pro v2 ios 10

**Comment by shawnbuso** [comment]
Canh are you still seeing this issue? It's working for me on my iPad as well.

**Comment by shawnbuso** [comment]
Closing for lack of response. If you're still seeing this issue feel free to re-open. Thanks!

**Comment by canhnm** [comment]
@shawnbuso I am able to fix it by using:
video-js-5.20.1
videojs-contrib-ads 5.0.3
videojs-ima 0.6.0

Tried with many different version of these dependencies and it did not work well!

**Comment by shawnbuso** [comment]
Hmm ok are you saying with those versions the issue goes away? I'd like to try replicating with the latest version of our plugin, v1.0.1, since that was a major refactor that involved some internal logic changes that may resolve this.

**Comment by canhnm** [comment]
@shawnbuso yes those version work well! Sice version 1.0.1 is having issue with IE 11, I will wait to test it again on 1.0.3 as mentioned!
