### ISSUE TITLE
Custom ima player UI

### ISSUE THREAD

**Issue by thanhthai3010** [googleads/videojs-ima#408]
I'm using videojs-ima in my android and iOs app.
But, can I custom the ima player UI such as change the text.

Thank you so much.

**Comment by shawnbuso** [comment]
What is it exactly that you're looking to do? You can use IMA [AdsRenderingSettings](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRenderingSettings) in our options to change things like the text language, but the text itself cannot be changed arbitrarily.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need assistance feel free to re-open. Thanks!
