### ISSUE TITLE
How to change ads dynamically?

### ISSUE THREAD

**Issue by sgromkov** [googleads/videojs-ima#409]
Hey!
I solve the problem: after finishing the one ads, I should request from the server the next VAST, and run the ads from it, at the right time. I have a prerolls, overlays, midrolls, and postroll. 

Now I want to ask you the best way to change the current ads settings and restart ima.

First of all, I'll show you how I solved it:

1. When the player init, I send request for the first VAST and if it contains the ad, I pass it to the "adsResponse", and init the ima.
2. After ads ending I send the next request and if it contains the ad, I pass it to the "adsResponse" and restart IMA:
```
this.settings.adsResponse = vmapString;
resetIMA_();
this.requestAds();
```
I generate VMAP from my VAST, so it helping me to start the ad in the right time with the right settings. I founded that overlay (gif-banner) working much better if it wrapping in VMAP.

Here is the code in line 578 if you wanna see it: https://github.com/sgromkov/videojs-ima/commit/e78663691813b5fdaac1e49ecbad8da10a1dd4a0

The real example: https://matchtv.ru/athletics/matchtvvideo_NI770411_clip_Hellen_Onsando_Obiri_stala_chempionkoj_mira_v_bege_na_5000_m. In the network console you can see the request to ads. Just filtering it by "ad.mail" words.

So, everytime I do the same: waiting for ads ending, sending request to the server and after getting the response VAST, I convert it to VMAP, pass the result to `adsResponse` property, and call `resetIMA()`, then call `requestAds()`. And it's working. I have some issues with mobile devises, but it's really working. 

I ask you for your advice: am I going the right way to change the ad during playback of a one video?

**Comment by shawnbuso** [comment]
@sgromkov though pretty hacky, this sounds fine to me as long as it's working for you :)

@kystkysto what @sgromkov proposed is actually a solution, not a problem - does his method work for you?
