### ISSUE TITLE
IE11: AD is invisible with fluid and aspectRation options

### ISSUE THREAD

**Issue by 580** [googleads/videojs-ima#414]
OS: Windows 10
Browser: IE 11

AD is invisible with fluid option enabled and aspect ration set to 16:9.
I am seeing the issue from videojs-ima with both vjs5 and vjs6.

Here's a link to reproduce this issue: 
[https://jsbin.com/vofigafuno/edit?css,js,console,output](https://jsbin.com/vofigafuno/edit?css,js,console,output)

Please review the link with IE. (If you look into the size of the AD container, it's 0 in width and 0 in height). The link is copied from the issue: [https://github.com/googleads/videojs-ima/issues/316](https://github.com/googleads/videojs-ima/issues/316)
I am not sure if it's the same issue as 316 or not, but it is a good example to replicate the bug I am seeing. 

Thanks,

**Comment by shawnbuso** [comment]
It looks like, for some reason, getComputedStyle(this.player.el()) is returning '0px' when we set the linear ad slot width. Working on a fix now, but need to make sure it won't break everything else.
