### ISSUE TITLE
No compatible source was found for this media. after playing post-roll ads

### ISSUE THREAD

**Issue by ahmadawada11** [googleads/videojs-ima#415]
Hi,
i am playing ads after the video playback ended the ads play correctly and after it finish i get the error "No compatible source was found for this media". i am using videojs 6.2.6 and hls.

thank you.

**Comment by ahmadawada11** [comment]
i fixed the problem by changing the onAllAdsCompleted_ event code 
line 453 to
```
 this.player.src({
                src: this.player.currentSource().src,
                type: this.player.currentSource().type
            });
```
after replay the video i noticed that the progress bar is not clickable and it has yellow color so i called the resetIMA_(); function after the above code.

if there is better solution please advice.

**Comment by shawnbuso** [comment]
Hi there,

We're still working with VJS 5.3.0, we haven't had a chance to update for VJS 6. If this solution is working for you I'd stick with it until we have official support for newer VJS versions.

Thanks,
Shawn

**Comment by adamdonahue** [comment]
This still seems to be a problem in the latest code base.

```javascript
/**
 * Handles when all ads have finished playing.
 */
PlayerWrapper.prototype.onAllAdsCompleted = function () {
  if (this.contentComplete == true) {
    if (this.h5Player.src != this.contentSource) {
      this.vjsPlayer.src(this.contentSource);
    }
    this.controller.onContentAndAdsCompleted();
  }
};
```

`this.contentSource` above is a single URL, without typing information, which triggers an error for us during this hook (and resulting in the 'no compatible' overlay).  Shouldn't the actual contentSrc value be preserved here?
