### ISSUE TITLE
play ads on mobile doesn't work with videojs 6.2.5

### ISSUE THREAD

**Issue by ahmadawada11** [googleads/videojs-ima#416]
Hi,

i am trying to play ads on mobile but it doesn't work i tired your example(iphone and advnaced) it is working fine with videojs 5.3 but it is not working with videojs 6.2.5

thanks

**Comment by shawnbuso** [comment]
Hi,

We haven't had a chance to update to VJS 6 compatibility yet - we're currently working with 5.3.

Thanks,
Shawn
