### ISSUE TITLE
Android Autoplay Stopped Working

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#422]
Link: http://player.dotstudiopro.com/share/587909f39fcf70170eafa7d4?targetelm=.player&companykey=56798e9197f815d36f339ee4&autostart=true

Staging Env Link: http://staging.player.dotstudiopro.com/share/587909f39fcf70170eafa7d4?targetelm=.player&companykey=56798e9197f815d36f339ee4&autostart=true

Android autoplay used to work flawlessly, and has for several months.  As of the last week or so, it's been throwing an error: `html5.js:369 Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.`

I have autoplay, muted, and playsinline attributes set to `true` on the video.

In staging, I've tried using the player.muted(`true`) function to set the muted attribute as well, with the same results.

Android Plugin used to instantiate ads: http://dujv48zc2yhmk.cloudfront.net/js/videojs-ima-ads/videojs-ima-ads-vmap-android.js?bust=1505282520624

iOS Plugin used to instantiate ads: http://dujv48zc2yhmk.cloudfront.net/js/videojs-ima-ads/videojs-ima-ads-vmap-ios.js?bust=1505282520624 -- In case a comparison is necessary.

**Comment by stoicbuddha** [comment]
The related plugins and their versions:
`"video.js": "5.19.1",`
`"videojs-contrib-ads": "^5.0.3",`
`"videojs-ima": "^0.6.1",`

**Comment by shawnbuso** [comment]
Is the [autoplay sample](http://googleads.github.io/videojs-ima/examples/autoplay/) working for you? That's still working for me in Chrome on Android O. If so you can compare your implementation to that one to try to spot the difference. If you have an unobfuscated copy of your code I can take a look at that as well, but it's pretty impossible to debug obfuscated code.

**Comment by stoicbuddha** [comment]
Somehow, that worked!

I've been using the same implementation for awhile, but we went through and de-jQuery'd our player, but the code was still operationally the same.  I'm not sure why this is working when it wasn't on the other end of things, but no matter.  Thanks!
