### ISSUE TITLE
VPAID ads ignoring sound options

### ISSUE THREAD

**Issue by chriscampbell888** [googleads/videojs-ima#423]
Hello,

I am having an issue that I hope you can help with.  I have been having issues with VPAID ads that are either not picking up the player's sound settings or ignoring them.  I put together a basic example that shows this.

[http://newshauler.com/demo/videojs-basic/videojs-basic.html](http://newshauler.com/demo/videojs-basic/videojs-basic.html)

This player should be loading the ad and the content in a muted state and auto playing. On its own this player will load and play the content and keep it muted, but the ads play with sound.  I have also tried VAST tags which will respect the player volume.  If you load the player and let it play through to the content, after having sound on for the ad it will turn the sound back off for the content.

Muted is set to true and the volume is set to 0 in the VideoJS setup.

Needing some help with this issue as I have been unable to find a solution.  Thank you.

**Comment by shawnbuso** [comment]
Thanks for the info - this is actually a known issue with the IMA SDK and we're working on fixing it. Once it's fixed there the plugin will get the fix automatically.

**Comment by chriscampbell888** [comment]
Thank you for the quick reply.  Have you heard of when this bug might end up getting fixed?

**Comment by shawnbuso** [comment]
I don't have a timeline but we are looking into it now.

**Comment by chriscampbell888** [comment]
Thank you.  Do you have a link to an online source from Google that acknowledges that it is a known issue?  I have been looking for some kind of notes page or resource I can search through when these sort of issues occur.

**Comment by shawnbuso** [comment]
We don't have an external issue tracker for the SDK itself, but I will follow up here as we make progress on it.

**Comment by chriscampbell888** [comment]
Perfect.  Thank you.

**Comment by sgromkov** [comment]
Hi, Shawn!
I have the same issue in your example: https://googleads.github.io/videojs-ima/examples/advanced/

With that tag: https://ad.mail.ru/vast/3930?dl=https://matchtv.ru/preroll-1/&puid1=80&puid2=1&puid3=1&puid4=1&puid5=9&puid6=57&puid7=4&puid8=14&puid9=0&puid16=7&puid11=1&puid13=3&puid20=12189&duration=0&content_id=133529&preview=1&puid19=12189&puid10=1&puid12=16

The volume button shows me that the volume is on. But there is no sound in ad. 

2 weeks ago I had not sound's problem with that ad.

**Comment by shawnbuso** [comment]
Hi there,

It sounds like you're running into the same problem - the SDK team is still looking into this one. I'll update here once it's resolved.

Thanks,
Shawn

**Comment by sgromkov** [comment]
Hi there,

Settings `vpaidMode` to `INSECURE` solved my problem with sound: 
`vpaidMode: google.ima.ImaSdkSettings.VpaidMode.INSECURE`

How to setup: https://github.com/googleads/videojs-ima#additional-settings

About VpaidMode: https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis?hl=ru#ima.ImaSdkSettings.VpaidMode

**Comment by KevinBrogan** [comment]
@sgromkov  That would indicate to me that there is a bug in the sdk introduced by the secure code branch. This is good news for me because before I had been leaning towards malicious creative providers not respecting the ima sdk.

Unfortunately, insecure mode is not an option for me as I can't be exposing the publisher to the arbitrary vpaid javascript of ad providers.

**Comment by sgromkov** [comment]
@KevinBrogan I find one more thing: vpaid not working in `Insecure` mode in Safari 11 desktop version. It's frizzes on first frame. But if I change vpaidMode to `Enabled`, the ad is working but without sound. Only in Safari 11 (september's last version update).

**Comment by shawnbuso** [comment]
We're aware of issues in the SDK for VPAID ads in secure mode, but ads in insecure mode should be working as long as you're following the new guidelines for autoplaying video introduced in Safari 11. @sgromkov your ad author will need to make sure that the video element they're using for their ad is either muted at start or loaded/played via a user action.

**Comment by shawnbuso** [comment]
Sorry, immediately after sending that I got an update from our engineering team that there *is* a fix necessary for insecure mode support as well as secure mode. We're working on all of these issues currently.

**Comment by shawnbuso** [comment]
Hi all,

We've made a number of changes to the SDK since the last update that should fix this issue. If you're still seeing this issue could you please reply with a sample page where I can replicate it?

Thanks!
Shawn

**Comment by bcbrendan** [comment]
Hi there, @shawnbuso.

Would you be able to elaborate on the specifics of the aforementioned changes, please?

Additionally, would you be able to confirm the version(s) of the SDK containing the changes?

Many thanks, in advance.

**Comment by shawnbuso** [comment]
This is for the IMA SDK, not this plugin. We made a change back in 3.182.0 that fixed an issue we were seeing where VPAID ads weren't syncing their volume with the content on start. After we resolved that we got a few more reports of the same issue, but in all cases it turned out to be an issue with the VPAID ad itself and not the SDK. So if you're still seeing this issue we can take a look at the ad to see if that's where the issue lies.

You can see the full release notes for the IMA SDK [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history.
