### ISSUE TITLE
videojs-contrib-ads has not seen a loadstart event 5 seconds.

### ISSUE THREAD

**Issue by MZeeshanSiddique** [googleads/videojs-ima#424]
videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization

I am getting this error on following browser:

Google Chrome
Version 61.0.3163.79 (Official Build) (64-bit)

![2017-09-14](https://user-images.githubusercontent.com/15931045/30468473-f6f3d120-9a04-11e7-8c91-fc23e6a6e21c.png)

Implementation:

app.controller('VideoPlayer', function ($scope, $rootScope) {
    // hide Audio Player
    stopAudioPlayer();
    $rootScope.showAudioPlayer = false;
    // init Video Player

    $scope.video = null;
    $scope.player = null;
    $scope.playerControls = null;
    $scope.options = {
        autoplay: true,
        controls: true
    };

    $scope.events = [
        google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
        google.ima.AdEvent.Type.CLICK,
        google.ima.AdEvent.Type.COMPLETE,
        google.ima.AdEvent.Type.FIRST_QUARTILE,
        google.ima.AdEvent.Type.LOADED,
        google.ima.AdEvent.Type.MIDPOINT,
        google.ima.AdEvent.Type.PAUSED,
        google.ima.AdEvent.Type.STARTED,
        google.ima.AdEvent.Type.THIRD_QUARTILE,
        google.ima.AdErrorEvent.Type.AD_ERROR
    ];

    $scope.init = function (video) {
        $scope.video = video;
    };

    //listen for when the vjs-media object changes
    $scope.$on('vjsVideoMediaChanged', function (e, data) {
        console.log('vjsVideoMediaChanged event was fired');
    });

    $scope.$on('vjsVideoReady', function (e, data) {
        //data contains `id`, `vid`, `player` and `controlBar`
        //NOTE: vid is deprecated, use player instead
        console.log('video id: ' + data.id);
        console.log('video.js player instance: ' + data.player);
        $scope.player = data.player;
        console.log('video.js controlBar instance: ' + data.controlBar);
        $scope.playerControls = data.controlBar;

        var adTagUrl = 'https://an.facebook.com/v1/instream/vast.xml?placementid=229499500518933_1048464968622378&pageurl=' + encodeURIComponent($scope.video.shareUrl);
        //var adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480|336x280|300x250&iu=/136009255/Taazi_Sample_Player_Multiple_Sizes&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]'
        //var adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=970x70&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='

        console.log(adTagUrl);

        var options = {
            debug: true,
            timeout: 10000,
            prerollTimeout: 500,
            id: 'video_player',
            adTagUrl: adTagUrl,
            forceNonLinearFullSlot: true
        };

        // This must be called before player.play() below.
        $scope.player.ima(options, bind(this, adsManagerLoadedCallback));

        $scope.player.on('adserror', function () {
            incrementContentCount('video', $scope.video.id);
        });

        // Remove controls from the player on iPad to stop native controls from stealing
        // our click
        var contentPlayer = document.getElementById('video_player_html5_api');
        if ((navigator.userAgent.match(/iPad/i) ||
            navigator.userAgent.match(/Android/i)) &&
            contentPlayer.hasAttribute('controls')) {
            contentPlayer.removeAttribute('controls');
        }

        $scope.player.one('ready', function () {
            $scope.player.ima.initializeAdDisplayContainer();
            $scope.player.ima.requestAds();
        });

        // Start ads when the video player is clicked, but only the first time it's
        // clicked.
        /*var startEvent = 'click';
         if (navigator.userAgent.match(/iPhone/i) ||
         navigator.userAgent.match(/iPad/i) ||
         navigator.userAgent.match(/Android/i)) {
         startEvent = 'touchend';
         }

         $scope.player.one(startEvent, function () {
         $scope.player.ima.initializeAdDisplayContainer();
         $scope.player.ima.requestAds();
         $scope.player.play();
         });*/

        $scope.player.on(['loadstart', 'play', 'playing', 'firstplay', 'pause', 'ended', 'adplay', 'adplaying', 'adfirstplay', 'adpause', 'adended', 'contentplay', 'contentplaying', 'contentfirstplay', 'contentpause', 'contentended'], function (e) {
            //console.info('VIDEOJS player event: ', e.type);
        });
    });

    function adsManagerLoadedCallback() {
        for (var index = 0; index < $scope.events.length; index++) {
            $scope.player.ima.addEventListener(
                $scope.events[index],
                bind(this, onAdEvent));
        }
        $scope.player.ima.startFromReadyCallback();
    }

    function onAdEvent(event) {
        //console.log(event.type);
        if (event.type == google.ima.AdEvent.Type.ALL_ADS_COMPLETED || event.type == google.ima.AdErrorEvent.Type.AD_ERROR) {
            incrementContentCount('video', $scope.video.id);
        }
    }

    function bind(thisObj, fn) {
        return function () {
            fn.apply(thisObj, arguments);
        };
    }
});

someone please help me out in understanding the problem and how can solve it.

**Comment by shawnbuso** [comment]
I think the problem is that you're waiting for vjsVideoReady to call  $scope.player.ima(options, bind(this, adsManagerLoadedCallback)). Does your code work if you move that line to soon after you create your video.js player instance? You can see in our [sample](https://github.com/googleads/videojs-ima/blob/master/examples/simple/ads.js) that we call that almost immediately after initializing the player, and that's what initializes the ads plugin.

**Comment by jsonMartin** [comment]
I was having this issue also, and moving the `ima` function call to right after the video.js player instance is created fixed it for me, thanks 🤠

**Comment by engr-mzs** [comment]
Hi guys thanks for your help. i figure out the issue in the angular js directive written by https://github.com/LonnyGomes/vjs-video. I want help from you guys is this i want to inform this person about the issue and the fix i made in his SDK. What i have to do ?
