### ISSUE TITLE
Should localContentEndedListener attached to the 'contentended' event instead of 'ended'?

### ISSUE THREAD

**Issue by Nistenf** [googleads/videojs-ima#429]
Hello.
In both onContentResumeRequested_ and onContentPauseRequested_ the localContentEndedListener function is attached (or deattached) to the 'ended' event. This caused an issue in my code: when a video ended (and it was time to play the postroll), the contrib-ads redispatcher was redispatching the original 'ended' event as a 'contentended' event, which is expected behavior, and this was causing the localContentEndedListener not to fire and the 'postroll?' state to timeout. What's weird is that sometimes the original 'ended' event was being handled by videojs-ima before being redispatched by contrib-ads, and in those cases the postroll worked correctly.

Is the use of the 'ended' event correct? in that case I guess I'm causing the problem somewhere myself, is that possible?

videojs: 5.19.2
contrib-ads: 5.0.0
videojs-ima: 0.7.0

**Comment by shawnbuso** [comment]
Hey there,

Do you have a sample I can take a look at? If I plug my [sample post-roll tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=&debug_experiment_id=1269069638) into our [sample player](http://googleads.github.io/videojs-ima/examples/advanced/) it does work, so it may be something in your implementation.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need help feel free to re-open. Thanks!
