### ISSUE TITLE
Move nonLinear recall button when controls are active so nonLinears can be recalled

### ISSUE THREAD

**Issue by shawnbuso** [googleads/videojs-ima#43]
Branching off of #22.

Currently when a nonLinear is closed, the recall button renders under the video controls. You can click it if you're quick, but I'd like to be able to bump it up on the y plane when controls are activated so you can click on it more easily.

**Comment by dacast** [comment]
I confirm. I think the problem is in ima3.js.
same issue if I set nonLinearWidth and nonLinearHeight

**Comment by shawnbuso** [comment]
We should expand this to move the entire ad up when controls are shown, if possible.

**Comment by dacast** [comment]
maybe just a vertical offset given as option during ad init can do it.

**Comment by dacast** [comment]
any update on this issue?

**Comment by shawnbuso** [comment]
I'm currently working on this - unfortunately it's not trivial. There are so many elements layered on top of one another that the mouse events (mouseover, mouseout) are not acting as they should. I'd really like to avoid having the ad 30 pixels above the bottom of the video when the controls aren't showing because it looks awful. If you'd like that option then it's easy to add on your own - just change the "top" style on the adDisplayContainer div from 0px to -30px (video.js controls in the current version are 30px high, but you may need to change this for future releases).

**Comment by shawnbuso** [comment]
I've opened https://github.com/videojs/video.js/issues/1879 in an attempt to remedy the above issue.
