### ISSUE TITLE
Reset or reload Google IMA Plugin

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#430]
Hi guys,
there is a way for reset or reload Google IMA Plugin after that the vast caused an error?
I ask you this because i want to make a new vast call, after a vast error.
Is it possible?
Thanks

**Comment by sgromkov** [comment]
IMA has the public method:
```
/**
 * Changes the ad tag. You will need to call requestAds after this method
 * for the new ads to be requested.
 * @param {?string} adTag The ad tag to be requested the next time requestAds
 *     is called.
 */
this.changeAdTag = function(adTag) {
  resetIMA_();
  this.settings.adTagUrl = adTag;
}.bind(this);
```

Maybe it will help you:

```
player.on("adserror", function(){
    player.ima.changeAdTag("newUrl");
    player.ima.requestAds();
    player.play();
});
```

I did't tried that code, so there could be errors.

**Comment by ibraalek10** [comment]
Thanks @sgromkov for the answer,
I want to ask you if there is a method for passing an xml file instead of a "newUrl".
I need to pass an xml file to my player and then i need to override the "adsResponse" option.
Thanks

**Comment by sgromkov** [comment]
@ibraalek10 
try this one:
```
player.on("adserror", function(){
    player.ima.changeAdTag(null); // really null
    player.ima.settings.adsResponse = "your xml";
    player.ima.requestAds();
    player.play();
});
```

Here I use `player.ima.changeAdTag(null)` to call `resetIMA_()`. And then set the `adsResponse` value.

**Comment by ibraalek10** [comment]
Thanks a lot @sgromkov ..
Last question.. Why this workaround doesn't works with "901 error"???

**Comment by shawnbuso** [comment]
@ibraalek10 a 901 error means there was an issue in the VPAID ad you tried to play. Are you seeing that error with your first or second request?

**Comment by ibraalek10** [comment]
@shawnbuso i saw this error after the first request..
In fact, i want to play the second request after this error on the first request..

**Comment by shawnbuso** [comment]
In that case this workaround should still work - do you have a sample page where I can replicate the issue?

**Comment by ibraalek10** [comment]
no @shawnbuso , I haven't!!!
but I confirm that when there is this error my second request doesn't play while if there is another errors like 301 or 303, my second request plays successfully!!!

**Comment by shawnbuso** [comment]
Hmm this will be tough to debug if I can't reproduce it - would you be able to share with me the tag that's producing the 901 error?

**Comment by ibraalek10** [comment]
Hi @shawnbuso ,
i have understood what was the problem.
If i have a "901 error" after the first request and in my page i don't have a "source" tag after a "video" tag, the plugin reset doesn't happen.
For this reason, i have added an empty "source" tag, and the reset happens successfully. 
Thanks a lot for your time 👍
