### ISSUE TITLE
Mute not respected with some tags

### ISSUE THREAD

**Issue by denisvlr** [googleads/videojs-ima#431]
Hello,

I've ran into tags from Spotx that don't respect the "mute" setting. CodePen here:
https://codepen.io/anon/pen/dVmjwW

This is a problem for mobile devices such as iOS which block autoplay with sound on.
The problem doesn't appear with the sample DFP tags in the examples.
When calling ima.adsManager.setVolume(0) as soon as it's instantiated, it's already too late, the error is already triggered on iOS.

Is there a way to force "mute" before the ad is loaded? There should be a method at the IMA settings level.

**Comment by shawnbuso** [comment]
Hi there,

This is an IMA SDK issue that we're aware of and working on. I'll keep you posted as we work on a fix. This is related to #428, but it's separate issues for linear video and VPAID ads.

Thanks,
Shawn

**Comment by jarsj** [comment]
In the same boat. Was wondering if there's a timeline for this ? Seems like a bunch of related issues in IMA SDK since last few weeks. Sorry, I am new here, so not sure I have a handle on how long it usually takes for IMA SDK to fix these things.

**Comment by shawnbuso** [comment]
A fix for this should be included in the next IMA SDK release. If testing goes well that will be out some time next week.

**Comment by ypavlotsky** [comment]
This should be fixed. Please let me know if you're still seeing this.
