### ISSUE TITLE
Video.js version supported

### ISSUE THREAD

**Issue by valse** [googleads/videojs-ima#432]
Hi,
   I'm new to video.js world and I'm trying to setup this plugin to serve our DFP video ads.

I've some issues with the latest 6.2.8 video.js version so I downgrade it to the 5.20.1 one (the last v5 release I think) and it seems ok... but what is your "testing" video.js version? It would be useful to write it on main plugin page?

Thanks
Marco

**Comment by shawnbuso** [comment]
Hi there,

You can find that info in our [package.json](https://github.com/googleads/videojs-ima/blob/master/package.json#L27). Currently we're at 5.3.
