### ISSUE TITLE
AdsLoader error: AdError 303: No Ads VAST response after one or more Wrappers

### ISSUE THREAD

**Issue by ahmadawada11** [googleads/videojs-ima#436]
Hi,
i am trying to play the following ads but it throws the following error "AdsLoader error: AdError 303: No Ads VAST response after one or more Wrappers" on safari 11 but working fine on google chrome. also i tryied to run this ads on the advanced example https://googleads.github.io/videojs-ima/examples/advanced/ and it has the same issue.

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/40784803/Rotana_net_All&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]

**Comment by shawnbuso** [comment]
Hi there,

I think this is an issue with your ad serving set-up - when I look at the network traffic for that tag in Safari I see the pubads.g.doubleclick.net request return a wrapper to an an.facebook.com URL, but that just returns empty VAST.  When I test the tag in Chrome it doesn't return a redirect URL but rather goes straight to an AdSense ad. I would speak with your account manager, or if you don't have one reach out to DFP via their [support channels](https://support.google.com/dfp_premium/?hl=en#topic=7505988), to see what needs to change in your serving to get the same behavior in Safari that you have on Chrome.

Thanks,
Shawn

**Comment by ahmadawada11** [comment]
Thanks Shawn, i will check.

**Comment by shawnbuso** [comment]
No problem - I'm going to close this issue but feel free to re-open it if you need more help.
