### ISSUE TITLE
Preroll fails on Android stock browser

### ISSUE THREAD

**Issue by bindoff** [googleads/videojs-ima#438]
I am unable to play IMA ads on Android stock browser and Chrome < v53. Eg Samsung Galaxy S6 fails to play ads and also the play button fails to play the video when tapped. Chrome v58 on Samsung Galaxy S6 plays the video and ads without issue.

If I do not initialise IMA the video plays fine.This issue can be seen in the demo:
https://googleads.github.io/videojs-ima/examples/autoplay/

Anyone know how to get these browsers to play the ads and video?

**Comment by shawnbuso** [comment]
Do you have any browser logs that you can share with us? Thanks!

**Comment by bindoff** [comment]
Thanks for checking @shawnbuso!

Here's the log from a Samsung S6 Edge / Android 6.0.1 / SM-G925F with useragent `Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G925F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36`

The error displayed occurs on startup. When tapping the play button, nothing occurs and no errors are logged.

Could you please post the useragent of your test device?

![screen shot 2017-10-27 at 10 55 24](https://user-images.githubusercontent.com/254375/32099189-3a97139c-bb07-11e7-84d8-607b4a3d9a3e.png)

**Comment by shawnbuso** [comment]
Hmm are you trying to autoplay the ad and content? If so you'll need to make sure it's muted or the browser will stop it form playing. If it's click to play, make sure your call to play() is a *direct* result of a user action, like a click or tap.

My test device UA is Mozilla/5.0 (Linux; Android 4.4.2; en-us; SAMSUNG SPH-L720 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/1.5 Chrome/28.0.1500.94 Mobile Safari/537.36

**Comment by bindoff** [comment]
So yes, the demo is autoplay and muted and it's using the big play button to play.

While autoplay is preferred, we just cannot get Samsung devices with the SamsungBrowser to play ads even when autoplay is disabled. We've also found other devices such as the LG G4 and HTC One M9 exhibit the same behaviour. The HTC has UA of `Mozilla/5.0 (Linux; Android 6.0; HTC One M9 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36`

We had found that Chromium browsers < v53 failed and v53 and up worked, but with yours being v28 and working our assumptions there cannot be correct.

Can you think of anything else that we've missed?

**Comment by shawnbuso** [comment]
Now I'm a bit confused - is it autoplay, or is it click-to-play on the big play button? Can you share your test page with me, or are you using one of ours?

**Comment by bindoff** [comment]
It is autoplay - it just doesn’t autoplay for these devices with that error above. After that error tap to play doesn’t work. 

It can be seen in the demo link above.

**Comment by shawnbuso** [comment]
Aha ok, I was only testing click to play. In that case the issue is just that mobile autoplay is not supported on the browsers on which you're testing - Chrome didn't support it until v53, which you noticed, and I don't think the native browsers ever officially had support for it. We're still working on making fallback to click-to-play work. In the meantime we suggest as a workaround that you use the UA to check the browser version, and only autoplay if it's v53+.
