### ISSUE TITLE
Controls not returned to player after Skip Ad

### ISSUE THREAD

**Issue by skmelendez** [googleads/videojs-ima#439]
Hiya,

I am having an issue with videojs ima where when an ad is skippable, after clicking skip-ad, the controls are not returned to the player. No hovering works. I can click on the player and it will pause. But I cannot get the control bar to show back up. However, if I let the ad play out, the control bar works fine. 

Thank you

**Comment by shawnbuso** [comment]
Are you able to repro this in our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/)? If I plug our [test skippable tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=) in there it works as expected.

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need assistance let us know. Thanks!

**Comment by Nishu2696** [comment]
Hi @shawnbuso 

I was able to re-produce this issue, when I ran the [advance sample](https://googleads.github.io/videojs-ima/examples/advanced/) example code in the mobile view

**Comment by Kiro705** [comment]
Hello @Nishu2696 ,

This issue has been closed for ~7 years. If you are experiencing an issue, please open a new one, and add details to reproduce there.

Thank you,
Jackson
IMA SDK team
