### ISSUE TITLE
IE 10/11 support

### ISSUE THREAD

**Issue by yegorov-andrey** [googleads/videojs-ima#44]
Accessing elements of ```NodeList``` via ```[]``` is not supported in IE browsers.

```element.childNodes[element.childNodes.length]``` may be replaced with ```element.childNodes.item(element.childNodes.length)``` and may be replaced with ```undefined``` (because indices are zero-based and the index of the last child is ```element.childNodes.length - 1```).
```Element#insertBefore(newChild, undefined)``` will work like ```Element#appendChild(newChild)```.

So, instructions like ```element.insertBefore(newChild, element.childNodes[element.childNodes.length])``` may be replaced with ```element.appendChild(newChild)```.
Verified with these changes player will work in IE.

**Comment by zrehmani** [comment]
Thanks for this!!  I can  confirm with this change - plugin is able to load and play VAST/VPAID ads in IE 10.  Not sure if IMA is supported on IE 9.

**Comment by scothiam** [comment]
I'm trying this now, so far unsuccessful, was there any other changes required? Could you provide an example of the new code? Thanks,
