### ISSUE TITLE
Support for Flash_api

### ISSUE THREAD

**Issue by damianvila** [googleads/videojs-ima#441]
We're using this plugin for our player, and need compatibility with HLS videos on IE 11. Right now, our solution is forcing Flash on this browser. We noticed that videos were not playing, and it was because videojs-ima gave an error that `this.contentPlayer` was undefined when trying to get `hasAttribute('autoplay')`.

I realized that the plugin was establishing the ID strictly by appending "_html5_api" to the plugin settings ID.

We solved it locally by using the following line:

`this.contentPlayer = document.getElementById(this.settings.id).getElementsByClassName('vjs-tech')[0];`

Since both `object` and `video` have this class when the player is instanced.

Can this be included in the plugin?
Thanks.

**Comment by shawnbuso** [comment]
We should be able to add this, as long as it doesn't break anything. We also accept pull requests if you're able to sign our SLA and you're feeling ambitious :)

**Comment by damianvila** [comment]
Done deal! Thanks.

**Comment by shawnbuso** [comment]
Resolved by #442
