### ISSUE TITLE
TypeError: a.search is not a function

### ISSUE THREAD

**Issue by damongant** [googleads/videojs-ima#446]
This worked a few hours ago, I can't figure out what's going on

`a` seems to be an internal object:

```
{"common":{},"video":{"client":{"sdkTag":true}}}
```

```
TypeError: a.search is not a function
    at Jd (ima3.js:48)
    at Aq (ima3.js:359)
    at wq.L (ima3.js:357)
    at ImaPlugin.eval (eval at module.exports (iv.js:577), <anonymous>:240:22)
    at Object.initIma (iv.js:1050)
    at Object.updateSrc (iv.js:1061)
    at HTMLDivElement.bound (iv.js:61942)
    at HTMLDivElement.data.dispatcher (iv.js:61575)
    at trigger (iv.js:61704)
    at Player.trigger$$1 [as trigger] (iv.js:62505)
```

**Comment by shawnbuso** [comment]
Do you have a sample page where I can repro the issue? I'm not seeing it on [our samples](http://googleads.github.io/videojs-ima/). Also, what's the platform (desktop browser, mobile browser, etc.).

**Comment by damongant** [comment]
I'm seeing this on Chrome 62 Linux.

This is fortunately only on a local development container. Which also means I can't really share it (unless you want to somehow privately message me for a SSH forward). I'll see if I can throw together a reduced test case. It's a pretty big webpack bundle I have to unwind.

This is the code that initializes IMA:

```
            try {
                if (this.ima !== false && typeof this.player.ima !== "undefined" && !imaInit) {
                    var id = "picarto-player-" + this.pid;
                    console.log("initIma", id, $("#" + id))
                    this.player.ima({
                        id: id,
                        adTagUrl: self.ima
                    })
                    this.player.ima.requestAds();
                    imaInit = true
                }
            } catch (ex) {
                console.warn("IMA SDK Init Failure")
                console.log(ex)
            }
```

The `console.log` confirms that the player exists with that ID. This happens immediately before a source is set and play is called.

**Comment by shawnbuso** [comment]
Do you know which line in that code is leading to that error? Is it on this.player.ima() or requestAds()?

It looks like this error is coming from within the IMA SDK, so it will be tough to debug if I can't repro on my end. If you have a page I can use to reproduce it I can proxy an uncompiled version of the SDK to see what's going on.

**Comment by damongant** [comment]
`requestAds` seems to be the culprit. I can reverse proxy the port out, but I'd rather not share it publicly. You can drop me a line at schittler@picarto.tv (or any other way you prefer) and I'll get that set up

**Comment by shawnbuso** [comment]
Taking a look at the SDK code, it *could* be an issue with your ad tag. Are you able to repro in our [advanced sample](http://googleads.github.io/videojs-ima/examples/advanced/) if you put your ad tag in there?

**Comment by shawnbuso** [comment]
Closing for lack of response - if you still need assistance feel free to re-open. Thanks!
