### ISSUE TITLE
When will next release come out?

### ISSUE THREAD

**Issue by fantasy4z** [googleads/videojs-ima#447]
Sorry if this is not the place to ask this question.

I noticed a recent commit 83fec5a which makes it tech agnostic. That's the cure our project needs. It would really help when next release with this fix is ready.

May I ask when next release will come out? Thanks in advance.

**Comment by shawnbuso** [comment]
This is a fine place to ask the question :) I just cut 0.8.0 which should be available now and includes everything on master.
