### ISSUE TITLE
Customize controls height

### ISSUE THREAD

**Issue by denisvlr** [googleads/videojs-ima#448]
Today you can't fully customize the design of the controls, in particular the height of controlsDiv is hard coded inside the hideAdControls_ and showAdControls_.

It would be better to instead add and remove a CSS class, for example "ima-controls-div-showed", which would then allow anyone to override the design without having to fork the repo.

Any reason for that?
(I'm willing to contribute with a PR to implement this, let know if it makes sense).

**Comment by shawnbuso** [comment]
Thanks for the suggestion. I'm currently working on a refactor and I can look into adding this as part of that process. If you want to contribute a PR that would be welcome as well, I can copy that work into the refactor if it ends up being submitted before that's complete.

**Comment by denisvlr** [comment]
Ok, will do!

**Comment by shawnbuso** [comment]
It looks like this was fixed as a part of the refactor - we now have the controls-hidden height in `.ima-controls-div` and the controls-showing height in `ima-controls-div.ima-controls-div-showing`.
