### ISSUE TITLE
chrome and firefox on android tablet

### ISSUE THREAD

**Issue by neverdoit** [googleads/videojs-ima#45]
Hi,

The pre-roll does not play in chrome and firefox on a tablet. I have to hit two times play and the actual video (not the preroll) starts. Im using videojs 4.11.3 and contrib ads 0.5.0

**Comment by shawnbuso** [comment]
Hi there,

That version of video.js wasn't supported at the time that you submitted this, and I'm guessing that's the issue. I currently have a pull request that will add support for video.js 4.12 and that is working on Android tablet.
