### ISSUE TITLE
Broken since ima sdk update 3.184.2, 3.185.1	11/6/2017, 11/16/2017

### ISSUE THREAD

**Issue by bpletzer** [googleads/videojs-ima#451]
Hi @shawnbuso 

since the  ima sdk update 3.184.2, 3.185.1 | 11/6/2017, 11/16/2017 we are experiencing a drop in preroll ads (~ -15%)

While VAST file is being fetched, not all times the creative is being fetched and shown.

See for example [http://www.chip.de/news/Online-einkaufen-EU-beschliesst-neues-Gesetz_128364904.html](http://www.chip.de/news/Online-einkaufen-EU-beschliesst-neues-Gesetz_128364904.html)

We are using videojs with videojs-ima (0.8.0 tag, but also with 0.6.0 the problem was there).

thank you in advance
Benedikt

**Comment by shawnbuso** [comment]
Are you seeing this on specific browsers or platforms? I tried reproducing on my Linux desktop in Chrome but I'm getting an ad every time.

**Comment by sschenke** [comment]
Hi Shawn,
I'm working on that topic aswell, here are some details and an HTTP archive for you to reproduce it.

There are no specific browsers or platforms where we see that problem.
We can see the problem happening sometimes, with no specific pattern. Sometimes it works, sometimes it doesn't.

https://drive.google.com/file/d/1dWS2EBaKDQJ8zP5Jb3v13J0KYO1g4Mym/view?usp=sharing
That's the HTTP archive, where I opened up http://www.chip.de/news/43-Zoll-Fernseher-bei-Aldi-Guenstiger-UHD-TV-im-Check_128370104.html?adkeyword=demoads_videoads.
The adkeyword=demoads_videoads parameter triggers a Sponsorship campaign that always delivers an ad. As you can see there is a 400x300 request to DFP and the XML is delivered correctly. Then nothing happens with it though, the content video is just playing and there are no VAST events triggered, no play event, not even an error event. Since this is not always happening, it's very hard to debug and leaves us a bit blind on how to fix this.
I'm not sure if this might be an issue with the IMASDK itself, but as we heard there is no global problem known. Since it happened since the last IMASDK update (the exact day) we assume it has to do something with it, but as it's not reproducable in 100% of the cases, we can't prove it.

If I can give any further information that would help you, let me know!

**Comment by shawnbuso** [comment]
Hey Sascha,

Would it be possible to collect some logs using ima3_debug.js and setting debug to true in the video.js IMA plugin? We may be able to gather something from the logs that tells us why the ad isn't being played. Thanks!

**Comment by bpletzer** [comment]
Hi Shawn,

I did this for me, rewriting the request using an chrome extension.

I can either do this again and send you the log, or I‘ll provide you with a way to switch to _debug.js using a flag (or similar)

Coming back from a business trip right now, unfortunately I will not be able to do this before tomorrow morning. It takes some time to really see this effect, hence it takes time to prepare. But thinking of it, we will send you an example log as well as a normal one to have a comparison.

Viele Grüße
Benedikt

**Comment by shawnbuso** [comment]
If you could send me the log that would be great. I think setting the debug flag to true in the IMA plugin will be more helpful than loading _debug.js, which I can't do with a proxy, so if it's possible to make that change let me know.

**Comment by bpletzer** [comment]
ah ok, was not aware of the difference. is there a documentation on where to set the flag? (but I will find)

Viele Grüße
Benedikt

**Comment by shawnbuso** [comment]
Yep, it's in our [README](https://github.com/googleads/videojs-ima) under "Additional Settings."

**Comment by bpletzer** [comment]
Hi Shawn,
having issues using the debug flag - will try on, but following the console log positive (with preroll) and negative (w/o preroll), using a test-campaign:

https://gist.github.com/bpletzer/c6360b90c145728cb8f7ae13be6b3c52

further colleagues noticed:

1. The article http://www.chip.de/news/Handy-mit-faltbarem-Display-Ein-Hersteller-koennte-schneller-sein-als-Samsung-und-Apple_124959707.html has two video-players, first one is auto-play, second one is click-to-play. Problem seems to happen only with the first one. We noticed a timeout in that case using IMA Debug

2. We tested redirecting the imasdk.googleapis.com/js/sdkloader/ima3.js to s0.2mdn.net/instream/html5/ima3.js (the code used in focus). Same code, but we did not notice the problem then


Will come back as soon I have more, especially the versions using debug: true instead of _debug.js


regards
Benedikt

**Comment by bpletzer** [comment]
Dear @shawnbuso 
we may have narrowed down the problem.
We do actually have a system which centrally provides us with the video-markup (since we have several applications using the same player) 

One can call this url service directly, since we use it for iframes and alike as well. see https://gist.github.com/bpletzer/e22d518ced833ba7ead55a09a530f181

This is calling an test-adcampain (benini, falling berries). We noticed it works fine, until one opens network panel in chrome and disables caching, then sometimes other campaigns are shown, sometimes none are shown at all.

We are working on exposing the debug-flag in this setup. But this is a huge step ahead showing a problem quite exposed

(One can switch between autoplay with the query-param in the url)

Please let me know whether you can follow my example.


regards
Benedikt

**Comment by bpletzer** [comment]
I notice, in case of no ad the following seems to be in log, while not in positive case:
[  1.711s] [ima.adslist.AdBreak] Destroying the ad break, 0

**Comment by shawnbuso** [comment]
I tried reproducing with that test page but I'm still getting an ad every time :/ I'm also not seeing the ima3_debug.js logs there. I do see a few errors coming from video.js though: "VIDEOJS: ERROR: TypeError: Cannot read property 'category' of undefined" but those don't seem to be affecting ad playback.

**Comment by bpletzer** [comment]
Hi Shawn,
I have updates. 

you may now use the query-param imadebug=true to enable debugging

Further than that I still think the problem has been triggered in constelation with the sdk-update. But I do also think at the moment we have to solve the issue ourselves.

To reproduce problems, one has to open the provided url, disable cache and slow down download speed to 1.000kb/s - in that scenario I almost always ran into problems. Maybe you could at least try once to reproduce and have a look at the log, whether it tells you something.

But other than that you may close the ticket for now, since I think we have to solve a slow running ad-provider in our system.


regards
Benedikt

**Comment by shawnbuso** [comment]
I'm still working on repro-ing this one. The issue I have now is the page kinda breaks if I set the network speed to 1 KB - it loads forever and never resolves. If you were able to mitigate this on your end I'll mark this as fixed - let me know if it becomes a bigger issue. Thanks!
