### ISSUE TITLE
Duplicate countdown overlay on iOS devices

### ISSUE THREAD

**Issue by jbnicolai** [googleads/videojs-ima#453]
On (emulated and physical) iOS devices a duplicate countdown overlay is rendered, as can be seen in this screenshot of the [advanced demo implementation](https://googleads.github.io/videojs-ima/examples/advanced/)

![image](https://user-images.githubusercontent.com/3891755/33386107-8539e0e0-d52a-11e7-848f-7b97bbd4a394.png)

Steps to reproduce:

1. Emulate or use an iOS device, and open the [demo](https://googleads.github.io/videojs-ima/examples/advanced/)
2. Enter the following vast tag, and press play. 
```
http://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&impl=s&output=xml_vast2&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]&iu=/6353&sz=640x360&ad_rule=0&cust_params=appelman-kv%3Dcase5-2780000020132%26
```

This will return the direct trafficked, DFP hosted and non-skippable inline VAST with the mp4 asset that can be found [here](https://storage.googleapis.com/pds-emea/appelman/5-2780000020132/video.mp4)

This same tag will play without duplicate overlay in both the [IMA SDK for HTML5 Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) and the [JW Player Ad Tester implementation of the SDK](http://demo.jwplayer.com/ad-tester/), leading me to believe the problem is most likely in `videojs-ima`

**Comment by shawnbuso** [comment]
It looks like we'll need to disable our UI in favor of the IMA SDK's on mobile devices.

**Comment by Kogoruhn** [comment]
Same problem.

**Comment by Kogoruhn** [comment]
Checked now. After update of all packages - even on desktop. And after adplay got an error "this.vjsPlayer.ads.inAdBreak() in not a function".  Nvm, I'll figure it out later.

**Comment by Kiro705** [comment]
Fix here. https://github.com/googleads/videojs-ima/pull/836
