### ISSUE TITLE
Issue with mobile click event.

### ISSUE THREAD

**Issue by kenanbalija** [googleads/videojs-ima#454]
Hello Guys, 
**Sorry for the ugly code look I'll try to edit it better**
I am using videojs & videojs-ima v0.6.0. 
Example can be seen on this [site](site: http://www.onecooloffers.com/?p=1428.)
Workflow is: When user clicks play the request is sent to server which returns a url for content video/audio and it automatically starts ads and after them the content.
On desktop everything is fine.
On mobile I have to **click twice** for ads to play. First is post. Second is Play. This needs to work from one click.  If i put mute/autoplay it will start on first click but I can't hear ads/content on iPhone.

First click is actually a post request, which loads data. I can do this without post request but it overloads the server and crashes it because the player has over 20k+ views a day. 

This is the full **ads.js** file: 
`let Ads = function() {`
    `this.player = videojs('content_video');`
   ` this.adTagInput = document.getElementById('tagInput');`
    `let contentPlayer =  document.getElementById('content_video_html5_api');`
    `if ((navigator.userAgent.match(/iPad/i) ||`
            `navigator.userAgent.match(/Android/i)) &&`
        `contentPlayer.hasAttribute('controls')) {`
        `contentPlayer.removeAttribute('controls');`
    `}`
    `this.options = {`
       `id: 'content_video',`
       `nativeControlsForTouch: false,`
       `debug: true,`
   ` };`
   ` this.events = [`
        `google.ima.AdEvent.Type.ALL_ADS_COMPLETED,`
       `google.ima.AdEvent.Type.CLICK,`
       `google.ima.AdEvent.Type.COMPLETE,`
       `google.ima.AdEvent.Type.FIRST_QUARTILE,`
        `google.ima.AdEvent.Type.LOADED,`
        `google.ima.AdEvent.Type.MIDPOINT,`
        `google.ima.AdEvent.Type.PAUSED,`
        `google.ima.AdEvent.Type.STARTED,`
       ` google.ima.AdEvent.Type.THIRD_QUARTILE`
    `];`
    `this.player.ima(this.options, this.bind(this, this.adsManagerLoadedCallback));`
`};`

`Ads.prototype.init = function(content) {`
    `this.player.ima.setContentWithAdTag(content, this.adTagInput.value, true);`
    `this.player.ima.requestAds();`
    `this.player.play();`
`};`

`Ads.prototype.onSampleAdTagClick_ = function() {`
    `this.adTagInput.value = this.SAMPLE_AD_TAG;`
`};`

`Ads.prototype.adsManagerLoadedCallback = function() {`
    `for (let index = 0; index < this.events.length; index++) {`
        `this.player.ima.addEventListener(`
            `this.events[index],`
            `this.bind(this, this.onAdEvent));`
    `}`
    `this.player.ima.startFromReadyCallback();`
`};`

`Ads.prototype.onAdEvent = function(event) {`
    `console.log(event.type);`
    `if (event.type === 'loaded') {`
    `}`
`};`

`Ads.prototype.bind = function(thisObj, fn) {`
    `return function() {`
        `fn.apply(thisObj, arguments);`
    `};`
`};`

And This is **Dumbed Down** code that contains click/touchend event
`let _4sAds = new Ads();`
`let startEvent = 'click';`
`formData.append('text', _4stext);`
`document.getElementsByClassName('vjs-button')[0].addEventListener(startEvent, post);`
`function post() {`
   ` _4sAds.player.ima.initializeAdDisplayContainer();`
    `document.getElementsByClassName('vjs-button')[0].removeEventListener('click', post);`
`...`
       ` if (xhr.readyState === 4 && xhr.status === 200)`
       ` {`
            `_4sAds.init(xhr.responseText);`
        `}`

This is part of the html/blade file where player is:

`<div id="ima-container">`
            `<div>`
                `<input type="text" size="75" id="tagInput" value="{{ $commercial }}"/>`
            `</div>`
        `</div>`
        `<div id="ima-videoplayer">`
            `<audio id="content_video" class="video-js skin-2"`
                   `controls preload="auto" width="" height="30" autoplay>`
            `</audio>`
        `</div>`
        `<div id="ima-companionDiv">`
            `<script type="text/javascript">`
               ` googletag.cmd.push(function() { googletag.display('ima-companionDiv'); });`
            `</script>`
Any suggestions?

**Comment by shawnbuso** [comment]
Hi there - your implementation looks OK, so this could be something funny happening in the plugin or the SDK. I'll take a look and let you know what I find.

**Comment by ypavlotsky** [comment]
Closing this as it hasn't been updated in months. Please comment or re-open if this is still affecting you.
