### ISSUE TITLE
How do replace player from ad the video end

### ISSUE THREAD

**Issue by iflixweb** [googleads/videojs-ima#455]
Hi!,I want to replace the player by at the ad end with image file.How do i do that.
I tried,not work.. want to replace the image after video ad end.
here is my code with  player: http://iflixweb.stream/jquery-dfp/mute.html
Thanks!

**Comment by shawnbuso** [comment]
Currently the plugin does not support this out of the box. You could do something like this programmatically by placing an img tag over the video player and displaying whatever image you'd like there.
