### ISSUE TITLE
iOS not playing preroll after reset

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#458]
I'm testing our player [here](http://staging.player.dotstudiopro.com/share/58c48e8397f8158a5e1ad4ff?targetelm=.player&companykey=56798e9197f815d36f339ee4&loopplayback=false&autostart=true&muteonstart=false&enablesharing=false&skin=0000ff&debug=true&recommendation=true).  Our current setup for this particular player instantiation is that the player will change to a new video at the end of the current one.

When the first video plays in iOS, I get a preroll.  That works fine.  On the next video, however, no preroll plays.  It tries to request the ads, but never actually does.

On Android, however, this works fine, and I get a preroll with each video.  The difference between the two is that Android uses `player.ima.startFromReadyCallback()`, while on iOS, we just play the video, because `player.ima.startFromReadyCallback()` hasn't worked properly before.

I decided to try `player.ima.startFromReadyCallback()` again tonight as a possible solution to this, as the SDK has been updated many times since I last made the attempt.  However, I get the following error: `Ad error: AdError 400: There was an error playing the video ad. Caused by: Error: AdError 1205: The browser prevented playback initiated without user interaction.`

This error will return even with the first preroll.  However, if I set it to just do `player.play()` instead, the first preroll plays fine and doesn't throw that error.  Because of that, I'm utterly baffled as to why that error is thrown in iOS with the same method of starting ads.

I think it's possible that it's related to [this Groups thread](https://groups.google.com/forum/#!topic/ima-sdk/w15fTbJcwYk).

**Comment by shawnbuso** [comment]
Which version of the contrib-ads plugin are you using? We saw an issue similar to this in the past, where playlist videos weren't showing ads after the first video, and it ended up being a contrib-ads issue that was fixed in their 5.1.3 release.

**Comment by stoicbuddha** [comment]
I'm using 5.0.3.  I'll upgrade it and see if that solves the problem.

**Comment by stoicbuddha** [comment]
Upgrading is causing the following error on iOS:
`videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization`

I'm using require, so I don't know if that makes a difference.  I did have to manipulate the plugin code a little bit to get it to stop trying to also require videojs (again) so I don't know if it's a plugin issue or the changes I had to make.  But it works fine on Desktop.

**Comment by shawnbuso** [comment]
Hrm ok in that case I think you'll need to wait for #456 which updates the plugin to work with the latest contrib-ads.

**Comment by stoicbuddha** [comment]
Do you have an ETA on when that is getting merged into master?

**Comment by shawnbuso** [comment]
Should be good to go as soon as @ypavlotsky is done looking at it. I'm not sure what his timeline is on that.

**Comment by stoicbuddha** [comment]
Hey Shawn, this was v1 of what? And was your update in the plugin or in the IMA SDK?

**Comment by shawnbuso** [comment]
v1 of the plugin. The update was to the plugin, though there have been updates to the IMA SDK recently as well.

**Comment by stoicbuddha** [comment]
Ok awesome.  I was thinking you were already in v1, so I was confused for a moment.  I'll be updating our plugin version sometime within the next couple of weeks and testing.  The holidays might force that to be pushed until after the new year but I will make sure to test this on iOS as soon as possible and get back to you.

**Comment by shawnbuso** [comment]
Sounds good, let me know!

**Comment by shawnbuso** [comment]
@stoicbuddha did the update fix this issue for you? Thanks!

**Comment by dannyf620** [comment]
I had the same problem, the update solved the problem and now everything works very well, now it reproduces the advertising without any problem.
but it does not work with the version of video-js v6.6.3. With version 5.20.4 works perfectly

**Comment by shawnbuso** [comment]
Good to hear, thanks! We're currently only able to support VJS 5, we don't have VJS 6 support yet.
