### ISSUE TITLE
Unable to set extra ads plugin settings

### ISSUE THREAD

**Issue by ironsidevsquincy** [googleads/videojs-ima#46]
We are unable to pass different settings to the ads plugin (`timeout`, `prerollTimeout`, etc), as the call is set in https://github.com/googleads/videojs-ima/blob/master/src/videojs.ima.js#L823

The ability to pass any params to the ads init would be useful

**Comment by hc2p** [comment]
:+1: have the same problem. Please make it possible to configure timeouts.
