### ISSUE TITLE
No dist or source

### ISSUE THREAD

**Issue by mimse** [googleads/videojs-ima#460]
Hi,

I just tried to install v1.0.0 using npm. This is what I´m getting

![image](https://user-images.githubusercontent.com/1250254/33928614-caecefda-dfe6-11e7-9ce3-3a3edff51b87.png)

Think you forgot to include source and dist in the package :-)

**Comment by shawnbuso** [comment]
Whoops, it looks like my pre-publish build went awry, so there was no dist folder when I published :confounded:. I just put out 1.0.1 which has dist and src.
