### ISSUE TITLE
Ad requests do not load ads after second request

### ISSUE THREAD

**Issue by Aauslander920** [googleads/videojs-ima#463]
Hi!

I'm experiencing an issue after two successful ad requests. On the third (and any other subsequent) request, our adTagUrl returns a valid response, but the request hangs here: [135.019s] [ima.loader.SequentialAdsLoader] Starting request from queue (full debug below). Ad events aren't triggered, so nothing loads.

Our use case is rather complicated - we have 4 unique instances of VideoJS, each with its own instance of the IMA plugin. Before each new ads request (except the first), I call `setContentWithAdTag(null, this.adTagUrl, false)` on each plugin instance. Our adTagUrl changes slightly on each request, based on the current page's URL.

When I test our adTagUrl in the Video Suite Inspector, I get an ad every time. I'm sure the issue is with my implementation; I'm just having trouble figuring out why.

Fortunately, this doesn't affect content playback, but I do rely on ad events to display the right UI at the right time. 

Do you have any ideas as to what might be causing this? Thank you in advance!

Best,
Abi

Debug of third request:
 [ 55.808s] [ima.loader.AdsLoaderWrapper] Requesting ads using new ads loader.
videojs.ima.js:242  [ 55.809s] [ima.loader.AdsLoaderWrapper] requestAds, processing external request.
videojs.ima.js:242  [ 55.809s] [ima.loader.SequentialAdsLoader] Enqueued new request.
videojs.ima.js:242  [ 55.810s] [ima.loader.SequentialAdsLoader] Starting request from queue.
videojs.ima.js:242  [ 55.810s] [ima.loader.AdsLoaderImpl] creating instance of GptRequestActivity.
videojs.ima.js:242  [ 56.352s] [ima.loader.AdSourceFetcher] Creating VastAdSource.
videojs.ima.js:242  [ 56.353s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1
videojs.ima.js:242  [ 56.353s] [ima.loader.VastAdSource] getNextAd, this.currentAdSource: null
videojs.ima.js:242  [ 56.354s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1
videojs.ima.js:242  [ 56.355s] [ima.loader.VastAdSource] processNextAd_, currentAdIndex: 0, ads.length: 1
videojs.ima.js:242  [ 56.355s] [ima.loader.VastAdSource] processInlineAd, successCallback with 1 ads
videojs.ima.js:242  [ 56.356s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: 0
videojs.ima.js:242  [ 56.357s] [ima.loader.AdsLoaderWrapper] dispatchAdsManagerLoadedEvent_, ads.length: 1
videojs.ima.js:242  [ 56.358s] [ima.managers.AdsManagerFactory] createAdsManagerFromAds_, adType: video
videojs.ima.js:242  [ 56.360s] [ima.loader.SequentialAdsLoader] Starting request from queue.

**Comment by shawnbuso** [comment]
HI there,

It sounds like you do indeed have a rather complicated use case :) Do you have a sample page I could take a look at to replicate this on my end?

Thanks
Shawn

**Comment by Aauslander920** [comment]
@shawnbuso Thank you for your quick response! We've set up a test page here: https://www.earthcam.com/clients/google/pagetest.html?cam=tsrobo1

My implementation can be found in the script here: /js/earthcam/ecnplayerhtml5/js/player_ima.js?20171212a
An associated script that may help shed some light is here: /js/earthcam/ecnplayerhtml5/js/player.js?20171212a

The JS is minified, so my implementation is somewhat difficult to debug. Do you have an email address that I could send the relevant unminified JS to?

Thank you!
Abi

**Comment by shawnbuso** [comment]
Sure thing - you can use ima-sdk-support@google.com to send us info you don't want to share publicly. We have a frontline team that fields questions there, so put a note in your message that you're already working with me and ask them to escalate to me. 

Do you have repro steps for that page? When I first loaded it I got an ad, but if I refresh the page or switch streams I don't see any additional ad requests going out.

**Comment by Aauslander920** [comment]
@shawnbuso Fantastic - I sent a note to the support mailbox.

We fixed some data settings on our side to force ads to always play - if you clear the cache/cookies and refresh, there should be an ad request every time you switch streams. Please let me know if you need anything else; thank you again for being so responsive!

**Comment by shawnbuso** [comment]
Sounds good - I got your email so I'll follow up there :)

**Comment by Singularetantum** [comment]
Hi,
we are facing the same issue in one of our players.
The player stops at "Starting request from queue.", without any ad_error or content_resume_requested event.

We having this issue on iOS >= 10 and only with a couple of ADs and is working fine on android and desktop browser.
I can provide a testpage by mail if needed.

Thanks
Sebastian

**Comment by shawnbuso** [comment]
If you could send a test page to ima-sdk-support@google.com that would be great, thanks :) Let them know you're working with me via the issue tracker and they'll make sure it gets to me.

**Comment by shawnbuso** [comment]
Hey there,

I was taking a look at this again today, and it looks like your [test page](https://www.earthcam.com/clients/google/pagetest.html?cam=tsrobo1) may be having issues - when I load it up the player loads forever and I get a few errors in the console:

```
events.event.class.min.js?20171212a:5 TypeError: this._videoJS360PanoPlayer1.panorama is not a function
    at window.earthcam.Player.initializePlayer (player.js?20171212a:318)
    at window.earthcam.Player.windowMountedHandler (player.js?20171212a:157)
    at Array.e (jquery.3.2.1.min.js?20171212a:2)
    at a.dispatchEvent (events.event.class.min.js?20171212a:4)
    at window.earthcam.VideoWindow.render (videowindow.js?20171212a:154)
    at window.earthcam.VideoWindow.init (videowindow.js?20171212a:77)
    at window.earthcam.PlayerArea.initVideoWindow (mediaplayercomponent.js?20171212a:233)
    at window.earthcam.PlayerArea.playerChangeHandler (mediaplayercomponent.js?20171212a:163)
    at Array.e (jquery.3.2.1.min.js?20171212a:2)
    at a.dispatchEvent (events.event.class.min.js?20171212a:4)
```
and
```
events.event.class.min.js?20171212a:5 TypeError: Cannot read property 'paused' of undefined
    at window.earthcam.Player.volumeChangeHandler (player.js?20171212a:1046)
    at Array.e (jquery.3.2.1.min.js?20171212a:2)
    at a.dispatchEvent (events.event.class.min.js?20171212a:4)
    at window.earthcam.VolumeSlider.dispatchControlEvent (volumeslider.js?20171212a:169)
    at window.earthcam.VolumeSlider.<anonymous> (volumeslider.js?20171212a:96)
```

Do you have a working page I can take a look at?

Thanks!
Shawn

**Comment by shawnbuso** [comment]
It's been a while since we've heard from you, so I'm going to close this out. If you're still seeing issues feel free to respond here and we'll re-open it. Thanks!
