### ISSUE TITLE
Volume control not responding  

### ISSUE THREAD

**Issue by DanielnetoDotCom** [googleads/videojs-ima#472]
I don't know if it is a know bug or is only me.
When the player plays an ad the volume control do not respond anymore.
You can see this happening here: https://demo.youphptube.com/
If I remove the ad the controls back to work normally.

BTW I am using 

- Video.js 6.2.8
- videojs-contrib-ads 5.1.5
- ima3.js
- videojs-ima 1.0.1

**Comment by shawnbuso** [comment]
I tested on my end and it's working for me - what OS and browser are you using?

**Comment by DanielnetoDotCom** [comment]
Hi @shawnbuso 

Very thanks for your attention.
To be able to reproduce this bug follow this steps
1. when an AD play, try to change the volume of the AD
2. Skip the AD or let it finish
3. try to change the video.js player volume
then you will notice you can not change anymore and it is always 100%

Tested on :

- Chrome 63.0.3239.84
- Firefox 57.0.3

**Comment by DanielnetoDotCom** [comment]
but if I remove the plugin the volume works fine
also if I do not touch the plugin volume also works fine.
but FYI i am using video.js persistvolume plugin

**Comment by shawnbuso** [comment]
Do you have this issue if you remove the persistvolume plugin? That may be interfering with the video.js plugin.

**Comment by shawnbuso** [comment]
Closing out this issue since it's been >1 month with no response. If you're still seeing this issue let me know - thanks!
