### ISSUE TITLE
this.vjsPlayer.ads is not a function (no adBlock)

### ISSUE THREAD

**Issue by Kogoruhn** [googleads/videojs-ima#473]
Hi! Didnt understand why it is so, but:

> bundle.js:100686 Uncaught TypeError: this.vjsPlayer.ads is not a function
>     at new PlayerWrapper (bundle.js:100686)
>     at new Controller (bundle.js:102509)
>     at new ImaPlugin (bundle.js:103132)
>     at Player.init (bundle.js:103302)
>     at Player.basicPluginWrapper [as ima] (bundle.js:27984)
>     at Object.<anonymous> (bundle.js:62424)
>     at __webpack_require__ (bundle.js:20)
>     at exports.__esModule (bundle.js:63)
>     at bundle.js:66

This error is displayed both in FF and Chrome.

**webpack.config.js**:

```
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module:{
   loaders: [
     {test : /\.css$/,
       loader: 'style!css!'},
     {loader: 'url-loader?limit=100000',
     test: /\.(png|woff|woff2|eot|ttf|svg)$/
}
   ]
 },
 resolve: {
  alias: {
    webworkify: 'webworkify-webpack-dropin'
  }

```

**index.js**:

```
import videojs from 'video.js';
import * as HLS from 'videojs-contrib-hls';
window.videojs = videojs;

import 'videojs-contrib-ads';
import 'videojs-ima';


require('!style-loader!css-loader!video.js/dist/video-js.css');
require('!style-loader!css-loader!videojs-contrib-ads/dist/videojs.ads.css');
require('!style-loader!css-loader!videojs-ima/dist/videojs.ima.css');


let player = videojs('rbc');
let options = {
  id: 'rbc',
  adTagUrl: '//data.videonow.ru/?profile_id=1634796&format=vast&container=preroll'
};

  player.ima(options);
```

**index.html**:

```
<video id="rbc" class="video-js vjs-default-skin" controls preload="auto" width="640" height="268" data-setup='{}'>
    <source src="https://online-video.rbc.ru/online/rbctv.m3u8" type="application/x-mpegURL">
  </video>

  <script src="dist/bundle.js"></script>
```

"Cloud" version of scripts works well, but my bundle.js - no.

**Comment by Kogoruhn** [comment]
In addition, here is **package.json**:

```
{
  "name": "player",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack -w",
    "dev": "webpack-dev-server"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "video.js": "^6.6.0",
    "videojs-contrib-hls": "^5.12.2",
    "videojs-ima": "^1.0.1"
  },
  "devDependencies": {
    "cors": "^2.8.4",
    "css-loader": "0.28.7",
    "express": "^4.16.2",
    "file-loader": "^1.1.6",
    "style-loader": "^0.19.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7",
    "webworkify-webpack-dropin": "^1.1.9"
  }
}
```

**Comment by Kogoruhn** [comment]
I found a solution. Maybe not cool but.. it works.

First of all, its necessary to add videojs-contrib-ads in your project.
Then split `entry` into two parts: one for declaring videojs and hls:

```
import videojs from 'video.js';
import * as HLS from 'videojs-contrib-hls';
window.videojs = videojs;
```
second - for ads and player options:
```
import * as videojsContribAds from 'videojs-contrib-ads';
window.videojsContribAds = videojsContribAds;
import 'videojs-ima';

let videoID = 'rbc';

let player = window.videojs(videoID);
let options = {
  id: videoID,
  adTagUrl: '//data.videonow.ru/?profile_id=1634796&format=vast&container=preroll'
};
  player.ima(options);
```

and in html put them under player code.

But it is only one part. You also need to replace in `videojs.ads.js` and `videojs.ima.js`
`registerPlugin = videojs.registerPlugin || videojs.plugin; `
by
`registerPlugin = window.videojs.registerPlugin || window.videojs.plugin;`

Dont forget to remove from `/videojs-contrib-ads` file `videojs-contrib-ads.es.js`
Webpack takes it for build by default.

html after all:
```
  <video id="rbc" class="video-js vjs-default-skin" controls preload="auto" width="640" height="360" data-setup='{}'>
    <source src="https://online-video.rbc.ru/online/rbctv.m3u8" type="application/x-mpegURL">
  </video>
  <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
  <script src="dist/videojsWithHLS.js"></script>
  <script src="dist/playerAndAds.js"></script>
```

**Comment by incompl** [comment]
I think ultimately the right solution for this is for the videojs-contrib-ads dependency to be imported using a module system by videojs-ima. I created an example of how to do this:

https://github.com/videojs/videojs-contrib-ads/pull/312/files

**Comment by shawnbuso** [comment]
Thanks for the info - filing as an FR to import contrib-ads via a module system.

**Comment by Kogoruhn** [comment]
Hi guys! After all, I found another solution.
First, this is nesessary to add in `webpack.config.js` ProvidePlugin with videojs:

```
  plugins: [
    new webpack.ProvidePlugin({
      videojs: 'video.js'
    })
  ]
```

After that every module will "know" about videojs; you dont needed in import of this, nowhere.

Second, in your `<main.js>` after import of videojs-contrib-ads U must manually register this plugin:

```
import './somePlugin';
import 'anotherPlugin'; 
// no need in videojs import!

import * as contribAds from 'videojs-contrib-ads';
videojs.registerPlugin('ads', contribAds.default); 
import 'videojs-ima'; 
```

**Comment by incompl** [comment]
Awesome to hear you all figured it out! Would either of you be willing to make a PR with brief instructions on how to integrate contrib-ads with webpack?

**Comment by Kogoruhn** [comment]
@incompl Thanks a lot!:) 
Im new in git, so please let the experienced person do it.

**Comment by brendanairvuz** [comment]
I'm having a similar issue but with videojs-ima. I get `ima` is not a function.

**Comment by Kogoruhn** [comment]
@brendanairvuz 
Have you already [tried it](https://github.com/googleads/videojs-ima/issues/473#issuecomment-358914973)?

**Comment by brendanairvuz** [comment]
@Kogoruhn I have tried exactly that. Strangely, it tells me that ads is already registered as a plugin when I manually register it. Anyway, it still doesn't work. I'll keep working at it...

**Comment by Kogoruhn** [comment]
@brendanairvuz Okay... 
Then, post plz version of node.js and versions of modules from package.json

**Comment by ypavlotsky** [comment]
Closing this out. Please let me know if you're still having issues with this.

**Comment by mohaalak** [comment]
my code is 
in index.js I have
```
import videojs from "video.js";
import "videojs-contrib-ads";
import "videojs-ima";
```
when I get videojs.getPlugins() in index.js it does not see ima or ads, but if I edit ima in node_modules and console.log videojs.getPlugins() after registerPlugin I can see that it has the plugins.
it's like that there are two videojs

**Comment by MrWiLofDoom** [comment]
so... when is version 7 coming out and will you have fixed your plugins?

**Comment by Flyover-ArtSk** [comment]
i have the same problem `ima is not a function`
Why i cannot use your plugin with webpack?

**Comment by MrWiLofDoom** [comment]
So for me, I had a race condition. Try putting a load event listener on the main videojs file, then load all of the plugins.

It's a hail Mary, I know
