### ISSUE TITLE
Display Ad Makers

### ISSUE THREAD

**Issue by codex-corp** [googleads/videojs-ima#475]
Hi,

Is there a way to display the ad markers in the video timeline like the image below,

or just function to return the list of time offsets for all available ads in a vmap list.

![image](https://user-images.githubusercontent.com/775654/34379541-6396673e-eb04-11e7-88a6-cba2e6285086.png)

**Comment by onatcelmen** [comment]
To get array of time offsets(cue points):

var cuePoints = player.ima.getAdsManager().getCuePoints(); // It may also return an empty array

Note that preroll is represented by 0 and postroll is represented by -1.
All other values are represented in seconds.

Hope this helps!

**Comment by shawnbuso** [comment]
It looks like you should be able to use a combo of @onatcelmen's response and https://github.com/spchuang/videojs-markers to accomplish this - let me know if there's more I can do to help out!

**Comment by Barahten** [comment]
Hello
I would like to see a more detailed example. Otherwise it is not entirely clear where, how and where to insert the code from the answer [@onatcelmen](#issuecomment-354101752)   and it is also not entirely clear whether the task was solved

Thank

**Comment by sanduluca** [comment]
> Hello I would like to see a more detailed example. Otherwise it is not entirely clear where, how and where to insert the code from the answer [@onatcelmen](#issuecomment-354101752) and it is also not entirely clear whether the task was solved
> 
> Thank

This would be a more detailed example using [videojs-markers](https://github.com/spchuang/videojs-markers)
```jsx
player.on('ads-manager', function (response) {
  const { adsManager } = response;
  const cuePoints = adsManager.getCuePoints(); // It may also return an empty array

  const markers = cuePoints.map(time => {
    return { time, text: "Advertisment" }
  })

  video.markers({ markers });
})
```
