### ISSUE TITLE
Hide Controls From Ads

### ISSUE THREAD

**Issue by shimronMars** [googleads/videojs-ima#477]
Hi Guys,
I'm trying to hide the controls from the ad but without success.
![image](https://user-images.githubusercontent.com/16895901/34513283-4175e42e-f070-11e7-9d8b-89c8f90e9995.png)
I tried to use the additional settings you gave (showControlsForJSAds : false) in the options body and it doesn't work for me.

IMA v 1.0.1
Videojs 5.2
Videojs-contrib-ads 5.1.4

**Comment by shawnbuso** [comment]
That setting only applies to VPAID JavaScript ads, and I think what you have is a standard linear video ad. I can file this as an FR to add another setting, showAdControls, that applies across the board regardless of the ad type.

**Comment by shimronMars** [comment]
Hi again,
I replaced my ad src to  VMAP XML template that wraps VPAID JS ads and it seems to be working fine now.
Additionally, I ran into another issue, the adWillPlayMuted prop not working on the VPAID JS ad.
Should I open another issue for this one?

Thanks a lot!

**Comment by shawnbuso** [comment]
If you don't mind that would be great - then we can close this one out. Thanks!

**Comment by Vladislavik** [comment]
[Solution](https://github.com/googleads/videojs-ima/issues/756#issuecomment-462245172)
