### ISSUE TITLE
Correlator value does not change per request

### ISSUE THREAD

**Issue by stoicbuddha** [googleads/videojs-ima#481]
We use a VMAP [like this](https://api.dev.myspotlight.tv/vmap/5a13199f6ee98b5167c2eafd/792/446/5a13199f6ee98b5167c2eafd/https%3A%2F%2Fdev.player.dotstudiopro.com%2Fshare%2F5a13199f6ee98b5167c2eafd%3Ftargetelm%3D.player%26companykey%3D57bdf792d66da8b744a33855%26skin%3D228b22) in our player via the plugin to call ads.

Each ad request by the plugin has the same correlator value.  I know the plugin uses its own per the docs, but using the same one each time is problematic.

Per a discussion [on this GG thread](https://groups.google.com/d/msg/ima-sdk/3KUuGSnixY0/Xu98SD5WAgAJ), it's possible to get that correlator value to change.  My question is, will this have any adverse effects on the playing of ads past the point we destroy the adsManager?  If so, is there a different/better way to accomplish the goal of having the correlator change per request?

**Comment by ypavlotsky** [comment]
You definitely shouldn't destroy adsManager while you're still playing ads. But you can destroy it after ads have finished playing and then call contentComplete on adsLoader to get a new correlator when you make another ads request.

**Comment by ypavlotsky** [comment]
I think I misunderstood what your use case was. If you're putting all of your ads in one VMAP, the plugin will treat it as one ads request, and you'll have one correlator for the entire request. Also, don't destroy the adsManager directly because that'll confuse the plugin.

**Comment by stoicbuddha** [comment]
So there is absolutely no way for the correlator value to change per request based on our use case?

**Comment by ypavlotsky** [comment]
I don't think there's a way to change the correlator within one ads request in the plugin. A workaround might be splitting the ads into multiple requests. What issues are you running into with the same correlator value being used for all the ads in the request?

**Comment by stoicbuddha** [comment]
The issue ends up being that DFP stops sending back ads.  If you run the same request with the same correlator value, it stops serving ads on the 3rd request, meaning that a video with a preroll and 3 ad pods will see 2 total ads.  So you have however many midrolls that will get back nothing from DFP even though the ad requests are legit and the VMAP provides random correlator values.

**Comment by stoicbuddha** [comment]
So is there anything we can do?

**Comment by ypavlotsky** [comment]
Right now, the only way to get the plugin to send a new correlator value is to make a new ad request. You could try splitting your single VMAP into multiple VMAPs, which would send a new correlator value per VMAP.

I can also talk to the rest of the team about handling your specific use case as an enhancement / feature request.

**Comment by stoicbuddha** [comment]
So as a feature request, is there a ballpark on approx when that could be implemented?  Not looking for a date, but like a month?  2 weeks?  Several months?

**Comment by ypavlotsky** [comment]
Unfortunately, we don't have any timetables right now. I'll talk to the rest of the team and get back to you when I have some info.

**Comment by sboth** [comment]
@ypavlotsky - is there a specific support document we can review in relation to creating a scenario where a new correlator value is generated on a secondary video ad request in a pre-loaded videoJS player?  

The sequence a current is as follows: player load -> dfp video preroll ad request (correlator on one example of 3275972710672460) ->ad play/complete ->video content play ->new dfp preroll adrequest (unfortunately with the same correlator value of 3275972710672460) ->next video ad content play.  We want to make sure the correlator value on the each video preroll request is a new and different value to ensure DFP chooses the correct line items in the line item selection process.  Can you please point me in the right direction of some documents on this?

**Comment by Kiro705** [comment]
Hi all, I am looking into this issue.

Based on the correlator documentation (https://support.google.com/admanager/answer/1068325?hl=en#correlator) my understanding is that the correlator value should remain the same for the same page view. Based on that I believe the correlator value remaining the same is correct.

If it is important to get a new value, I recommend taking steps to make a new ads request when the new correlator value is needed.

Because of this, I do not see this as an issue with the videojs-ima plugin. Please feel free to reopen the issue if you think a change needs to be made.

**Comment by hoola14** [comment]
Hi to All, I just wanna share the approach that our team did regarding on this issue, I hope it helps our fellow developers in the future with same problem as ours.

We have this similar requirement that the correlator value must have different value per adrequest/adbreak but as I read thru the forums, you can only have a new correlator value when you perform a new ad request. In our case, we have a **custom vmap with multiple vast tags and adbreaks**. **Our goal is to have different correlator per adbreak** but unfortunately when the vmap is generated all of the vast tag inside the xml will have the same correlator value no matter what you put in it. 

I also read on other forum, a user suggested, if we want to have different correlator value, we should create another vmap request and perform the following :

>adManger.destroy()
>adsLoader.contentComplete()
>window.adTag = 'your new adTagUrl'
>ads.requestAd()

The suggested procedure above is working, but we've encountered multiple issues when we tried the it with the same vmap. It resets the state of the adManager resulting to call the pre-roll again or whichever ads comes first for each ad request. So we need to split the vmap for each adbreak to achieve the behavior that we want. This will result to multiple vmap files. 

To avoid multiple vmap files on our end, what we did was, we've manipulated the vmap source (with 4 adbreaks), then we programmatically serves the adbreak 1 by 1. With this, we managed to produce a new correlator value each adbreak by creating a new vmap on it and the ads servers smoothly each adbreak without wasting any ads call on the network.

We are using akamai for the player and we performed the vmap.xml manipulation on .net core c#
