### ISSUE TITLE
Advert Not Playing / Freezing On First Frame on iOS

### ISSUE THREAD

**Issue by AssyriaGameStudio** [googleads/videojs-ima#487]
Hey, I'm trying to get a really simple implementation of this working on iOS. My code is here:
https://www.happiest.net/vast_instant_article.html

It's working perfectly fine on all desktop browsers, but on iOS it freezes on the first frame of the advert. Having experimented with the advanced example, I can see that it triggers "Ad event: loaded", but Ad event: Start is never called.

If I click on the ad a few times (pause, then play it) then it does start eventually, but the actual video then refuses to play after the advert.

A video of the issue can be found here: https://www.dropbox.com/s/wgr6u1m5mer992m/video_ads_issue_iOS.mov?dl=0

Weirdly the example / samples (https://googleads.github.io/videojs-ima/) work perfectly on iOS, but when I run essentially the exact same code; for me it's not working and for the life of me I can't figure out why.

I've attempted getting it to work with version 1.0.4, 1.0.3 and 1.0.1 and haven't managed to get it working on any version.

Here's my full code:

```
<!doctype html>
<html>

	<head>
		<link rel="stylesheet" href="//www.happiest.net/node_modules/video.js/dist/video-js.min.css?=1" />
    	<link rel="stylesheet" href="//www.happiest.net/node_modules/videojs-contrib-ads/dist/videojs.ads.css?=1" />
    	<link rel="stylesheet" href="//www.happiest.net/node_modules/videojs-ima/dist/videojs.ima.css?=1" />
	</head>

	<body style="margin: 0px;">


	        <video id="content_video" class="video-js vjs-default-skin"
		        poster = "https://www.happiest.net/wp-content/uploads/2018/01/dog-shot-in-head.jpg" controls preload="auto" width="640"
		        height="360">
		      <source src="https://storage.googleapis.com/happiest-site.appspot.com/example_video.mp4"
		          type="video/mp4" ></source>
		    </video>

		    <!-- Load dependent scripts -->
		    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
		    <script src="//www.happiest.net/node_modules/video.js/dist/video.min.js?=1"></script>
		    <script src="//www.happiest.net/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js?=1"></script>
		    <script src="//www.happiest.net/node_modules/videojs-ima/dist/videojs.ima.js?=1"></script>
		    <script src="//www.happiest.net/video_ads_test.js?=3"></script>

	</body>

</html>
```

And the video_ads_test.js contents:

```

var player = videojs('content_video');


var options = {
  id: 'content_video',
  adTagUrl: 'https://an.facebook.com/v1/instream/vast.xml?placementid=TEST_PLACEMENT_ID&pageurl=test.com&__mref=message_bubble'
};

player.ima(options);

// Remove controls from the player on iPad to stop native controls from stealing
// our click
var contentPlayer =  document.getElementById('content_video_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
  contentPlayer.removeAttribute('controls');
}

// Initialize the ad container when the video player is clicked, but only the
// first time it's clicked.
var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
  startEvent = 'touchend';
}

player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
});
```

Can anyone see where I might be going wrong?

**Comment by AssyriaGameStudio** [comment]
Ok, it does appear to work when I use the following script tags from codepen:

```
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/node_modules/video.js/dist/video-js.min.css" />
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.css" />
<link rel="stylesheet" href="//googleads.github.io/videojs-ima/dist/videojs.ima.css" />

<script src="//googleads.github.io/videojs-ima/node_modules/video.js/dist/video.min.js"></script>
<script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
<script src="//googleads.github.io/videojs-ima/node_modules/videojs-contrib-ads/dist/videojs.ads.min.js"></script>
<script src="//googleads.github.io/videojs-ima/dist/videojs.ima.js"></script>
```

Because of this I've narrowed it down to seemingly an issue in versions 1.0.1 and up.

**Comment by shawnbuso** [comment]
Those links from codepen are for the latest version, which is currently 1.0.4 - do you maybe mean an issue with 1.0.1 and below?

**Comment by AssyriaGameStudio** [comment]
I don't think so; 1.0.4 is the first version I tried? Attempting 1.0.0 now / pulled the files from here: https://github.com/googleads/videojs-ima/tree/gh-pages. Will let you know if that resolves the issue or not.

**Comment by AssyriaGameStudio** [comment]
Ok yep; can confirm... If I pull the node_modules folder, and dist from https://github.com/googleads/videojs-ima/tree/gh-pages it works perfectly... Using the node_modules folder accessed via npm works on desktop, but fails on mobile / iOS.

**Comment by shawnbuso** [comment]
Ah ok so the difference is specifically in the node_modules folder? That tells me that an update was pushed to either video.js or videojs-contrib-ads that's causing this. I'll see if I can replicate on my end and debug further.

**Comment by AssyriaGameStudio** [comment]
Sounds good! Let me know if ya manage to resolve it and I'll update to the latest after :)!

**Comment by Kogoruhn** [comment]
@AssyriaGameStudio Just in case:

`var contentPlayer =  document.getElementById('content_video_html5_api');`

is `==`

`var contentPlayer =  document.getElementById(options.id +'_html5_api');` ?

**Comment by shawnbuso** [comment]
Hi there - are you able to reproduce if you do a fresh npm install? 

```
rm -rf node_modules/
npm i
```

I just tested your code with a fresh npm install and I'm seeing the ad play fine on my test iOS device. Thanks!

**Comment by shawnbuso** [comment]
Hi all, any update on results from the above suggestion? Thanks!

**Comment by shawnbuso** [comment]
I'm going to close this out since we haven't heard back in a few weeks - if it's still an issue for you feel free to re-open or start a new issue. Thanks!
