### ISSUE TITLE
Learn More text icon position setting

### ISSUE THREAD

**Issue by mizmaar3** [googleads/videojs-ima#488]
Seems like there is no option to move `Learn More` text from right to left. 
Good to have it as mostly ads have default close icon on right side like on attached image

![screen shot 2018-01-22 at 12 11 30 pm](https://user-images.githubusercontent.com/735285/35218163-dc8dae22-ff6d-11e7-8284-d323b7854e6e.png)

**Comment by shawnbuso** [comment]
Hey there - this UI layout and positioning is enforced by Google and cannot be changed as per their ToS, so unfortunately there's nothing we can do about that.

**Comment by mizmaar3** [comment]
ok
Where to ask ? if want to request for positioning and localizing ? (i.e. change wordings in other language)

**Comment by shawnbuso** [comment]
For localization you can use the `locale` option for the plugin. Unfortunately the positioning cannot be changed.

**Comment by mirabo-dattnt** [comment]
@shawnbuso 
May I modify 'Learn more' to  'Click here for additional details'?
Thanks
