### ISSUE TITLE
Many requests to google domains!

### ISSUE THREAD

**Issue by EhsanCh** [googleads/videojs-ima#489]
IMA loader send some request to google domains including YouTube

YouTube is censored in some countries , and it prevent our ads from loading in those countries.
we use our custom ad server that provide VPAID ads.
i used google.ima.ImaSdkSettings.VpaidMode.INSECURE and it prevent iframe to be proxied and Ads are shown now.

but some other requests are sent from our page. can somebody explain what is them and help us to prevent sending request (if possible) or host them ourself?

these are requests :
https://s0.2mdn.net/instream/video/client.js
https://www.youtube.com/iframe_api
https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl52DM8h/www-widgetapi.js
https://www.youtube.com/yts/cssbin/www-player-vfl2WYBRV.css
https://www.youtube.com/yts/jsbin/www-embed-player-vfl22pZBg/www-embed-player.js
https://www.youtube.com/yts/jsbin/player-vflNX6xa_/en_US/base.js
https://www.google.com/js/bg/bFTlhINJvs7OMnyC84Sf0-IlM_2i_0Q_vKPnFeKA_u0.js
https://static.doubleclick.net/instream/ad_status.js
https://www.youtube.com/youtubei/v1/log_interaction?alt=json&key=...STEHLGCilw_Y9_11qcW8

**Comment by ypavlotsky** [comment]
Hi there,

The IMA SDK which the video.js IMA plugin uses is a Google product that relies on a number of Google resources, but we can't comment about the specifics of these dependencies.

--Yury

**Comment by EhsanCh** [comment]
i saw ima  somewhere else (with flowplayer) and it didn't send request to many of these urls, specialy to youtube.
i asked it from IMA team and they said me that i [should contact videojs-ima developers](https://groups.google.com/d/msg/ima-sdk/t1i-ZyXQn1g/tZn5MQ3BAwAJ).

i need at least remove youtube.com requests...

**Comment by ypavlotsky** [comment]
All requests that the video-js ima plugin makes originate from the IMA SDK. To put it another way, the plugin itself isn't making these requests.
