### ISSUE TITLE
Mute icon does not work after click on Volume Bar

### ISSUE THREAD

**Issue by mizmaar3** [googleads/videojs-ima#490]
Here: https://googleads.github.io/videojs-ima/examples/simple/
Wait for preroll ad, after clicking on `Volume Bar` the mute toggle does not work.

If you drag or click on `Volume Level Bar` once and then click on `mute icon` the mute icon does change Volume Level to 0 but video does not mute neither the `unmute icon` change to `mute icon`. If you manually click on far left to the `Volume Level Bar` to make it 0 then video does mute.

**Comment by ypavlotsky** [comment]
Thanks for bringing this to our attention.

**Comment by ypavlotsky** [comment]
I don't think this is happening anymore.
