### ISSUE TITLE
iOS: The browser prevented playback initiated without user interaction

### ISSUE THREAD

**Issue by Kogoruhn** [googleads/videojs-ima#494]
HI all!
 Got this error on iPhone 6S with iOS 11.2.2
Mac OS, Windows browsers and Chrome for Android works.

On iPhone - content video starts immediately but ads container is visible for a split second.
When i muted ad through editing `ima.js` ( this.adsManager.setVolume(0) ), the countdown timer and title "Advertisement" became visible, but no ad itself.
(then I discard the changes)

I added log in every event of Ad Playback State Machine (`contrib-ads.js`, var `states`), 
and watch out for 'adserror' event, in log i can see the following:

```
content-set: adsready
ads-ready: play
preroll?: adstart
ad-playback: adend
ad-playback: adserror

Error message: {"l":"There was an error playing the video ad.","h":400,"o":"adPlayError",
"g":{"l":"The browser prevented playback initiated without user interaction.","h":1205,"o":"adPlayError"}}
```

I can not understand what's wrong, I do everything according to the instructions...
This is content of my files:

`player.js`

```
var playerId = 'videoPlayer';
var player = videojs(playerId);
var options = {
  id: playerId,
  adTagUrl: 'https://ads.adfox.ru/168627/getCode?p1=bdcfe&p2=ekza&pfc=zymd&pfb=dkvcj&plp=a&pli=a&pop=a&puid1=',
  debug: false,
  prerollTimeout:100
};

player.ima(options);

  var contentPlayer =  document.getElementById(playerId + '_html5_api');
  if ((navigator.userAgent.match(/iPad/i) ||
        navigator.userAgent.match(/Android/i)) &&
      contentPlayer.hasAttribute('controls')) {
    contentPlayer.removeAttribute('controls');
  }

  var startEvent = 'click';
  if (navigator.userAgent.match(/iPhone/i) ||
      navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) {
    startEvent = 'touchend';
  }

  player.one(startEvent, function() {
      player.ima.initializeAdDisplayContainer();
  });

player.on('adserror', function (e) {
  document.getElementById('loghere').innerHTML +=
  '<div>Error message: ' + (e.data && e.data.AdError ? JSON.stringify(e.data.AdError) : 'no info') + '</div>';
  console.log(e.data.AdError);
});

```

index.html:

```
<video id="videoPlayer" class="video-js vjs-default-skin vjs-big-play-centered"
    controls playsinline preload="auto" width="640" height="360">

    <source src="http://83.222.205.40/zvezda/playlist.m3u8?md5=OrcfklZaTH3WoHfqBf3XBg" type="application/x-mpegURL">
  </video>

    <!-- common -->
  <script  src="node_modules/video.js/dist/video.js"></script>
  <script  src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
  <script  src="node_modules/videojs-contrib-hls/dist/videojs-contrib-hls.min.js"></script>
  <script  src="node_modules/videojs-contrib-ads/dist/videojs-contrib-ads.js"></script>
  <script  src="node_modules/videojs-ima/dist/videojs.ima.js"></script>

  <script src="src/player.js"></script>

  <div id="loghere"></div>
```

versions of modules:

    "video.js": "^6.6.2",
    "videojs-contrib-ads": "^5.1.6",
    "videojs-contrib-hls": "^5.12.2",
    "videojs-ima": "^1.0.4"

**Comment by ypavlotsky** [comment]
Hi,

For muted autoplay to work, you have to include the muted flag in the <video> tag, it's not enough to set the AdsManager's volume to 0. Check out our [autoplay](http://googleads.github.io/videojs-ima/examples/autoplay/) sample for a working implementation.

**Comment by Kogoruhn** [comment]
@ypavlotsky Thanks for tip, Yury! But what about non-muted ad w/o autoplay? Its real for now?

**Comment by ypavlotsky** [comment]
Without autoplay? Our basic sample is click-to-play (as are all of the other samples other than our autoplay sample). If you're asking about non-muted autoplay, iPhone doesn't support it.

**Comment by Kogoruhn** [comment]
@ypavlotsky Oops, now I understand what's the matter... Many thanks to you!

**Comment by ypavlotsky** [comment]
Glad to be of help!

**Comment by Kogoruhn** [comment]
Hi! @ypavlotsky I checked player with 'autoplay playsinline muted'. 
Nothing changed, yellow ad bar is visible and in progress, but it shows on freezed content frame. No ad video presence.

**Comment by ypavlotsky** [comment]
Are you using the autoplay sample with your own tag?

**Comment by Kogoruhn** [comment]
@ypavlotsky  Yup. 
Finally, ad works on iOS. No need in `autoplay` and `muted`, keep only `playsinline` option.
Besides usual `id` and `adTagUrl` it was only necessary to pass `disableCustomPlaybackForIOS10Plus`.
Argh, old good 'rtfm'...
Thanks for your help and patience!
