### ISSUE TITLE
Ad Clicktrough on mobile

### ISSUE THREAD

**Issue by therethere** [googleads/videojs-ima#496]
Hi there,

On this example: 
https://googleads.github.io/videojs-ima/examples/simple/

The clicktrough on mobile doesn't seem to work. It only pauses the ad. 

i'm planning to start using this plugin to setup some vast ads from doubleclick but on mobile got some problems with click trough (ios and android) and IOS native player.

thanks

**Comment by shawnbuso** [comment]
Which platform are you using to test? You should see a "Learn more" button in the top right corner of ads on mobile, which takes you to the clickthrough landing page.

**Comment by therethere** [comment]
Ok, my bad I really thought the click through was the full video container. So basically if I want it to be that way I just need to expand the click div, is that right?

Thanks again!

**Comment by shawnbuso** [comment]
The IMA SDK doesn't support modifying the ad UI - that's something enforced by the SDK, so on mobile you'll have to stick with the Learn more button.

**Comment by therethere** [comment]
Ok, thanks a lot for the info. Case closed.
