### ISSUE TITLE
in mobile ads playing to the right

### ISSUE THREAD

**Issue by shravanthanvi** [googleads/videojs-ima#497]
The ads are playing properly in website when it comes to the mobile the ads are playing to the right from the half the screen. 

you can check the link in
https://www.ursadda.com/vid-20180113-wa0007-1515898600354

![adsplaying](https://user-images.githubusercontent.com/6723935/35607736-a51fb704-067b-
11e8-9011-8150ceea7467.png)

**Comment by Kogoruhn** [comment]
@shravanthanvi It happens on real device or in simulator/emulator?

**Comment by ypavlotsky** [comment]
I'm not seeing any ads at all when I go to the page.

**Comment by shravanthanvi** [comment]
hi

The ads will come once you cross the red marker on the videojs toolbar.
https://www.ursadda.com/vid-20180109-wa0012


Regards
Shravan

**Comment by shravanthanvi** [comment]
you can close the issue. Actually it is comming from my PHP page rectified
the same now the ads are playing properly.

regards
Shravan

**Comment by ypavlotsky** [comment]
Ok, closing it out.
