### ISSUE TITLE
any plans to release typescript

### ISSUE THREAD

**Issue by shravanthanvi** [googleads/videojs-ima#498]
Hi 

Any plans to release typescript for this. So that we can use the same in angular2(5  version)

regards
Shravan

**Comment by Kogoruhn** [comment]
@shravanthanvi  Hi.

> So that we can use the same in angular2

5 seconds on Google "videojs angular2".

> Any plans to release typescript for this

See [there](https://github.com/videojs/video.js/issues/4332)

**Comment by ypavlotsky** [comment]
Right now, we don't have any plans to release a Typescript version.

**Comment by vicolaspetru** [comment]
Hi,

I have to use this package and I need a Typescript version. Is there a way to easily achieve that? Or I have to add a custom `d.ts` file in my project and provide all types by myself?

Thank you!
