### ISSUE TITLE
adWillPlayMuted option is not working

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [googleads/videojs-ima#504]
Hi,

I have a simple config for my video ad setup - 

```
const options = {
    id: 'ad',
    debug: true,
    adWillPlayMuted: true,
    adTagUrl: // my ad tag url
};

this.ima(options);
```

The ad runs as expected but it is not muted. Is there something that I've missed.
Please let me know. 

I am using videojs-ima `v1.0.4`.

Thank you!

**Comment by ypavlotsky** [comment]
Hi there,

`adWillPlayMuted` will not change ad playback, it's a signal that you intend to play your ads muted. You're still responsible for muting the volume of the video player.

**Comment by ArunMichaelDsouza** [comment]
I am already muting the volume of my video player by setting the player's `muted` option to `true`.

**Comment by ArunMichaelDsouza** [comment]
Hi, any update on this ?

**Comment by aymanabbas92** [comment]
Hi,
I have faced the same problem, you can mute your ads after calling adsManager by:
player.ima.getAdsManager().setVolume(0).
Thanks

**Comment by ypavlotsky** [comment]
Are you still seeing this issue with the latest version of videojs-ima? When I add `muted` to my video tag, and run the [simple example](http://googleads.github.io/videojs-ima/examples/simple/), the preroll plays muted.

**Comment by kenguie** [comment]
Can you elaborate on what you changed in the simple example @ypavlotsky ?

I added this to my ad options but the player still plays the ads unmuted. 
"adWillPlayMuted: true, "

I actually used volume(0) as well and it works for video but not ads. 
I'd love to be able to code the ad to pause or play muted, not able to find a solution yet. 

Thanks

**Comment by kenguie** [comment]
Due to Google rolling out the can't play video unmuted yesterday, I basically had to code up a change so autoplay is false if in chrome. Not the best solution but I haven't been able to get our version of VideoJS and IMA plugin to mute or pause the preroll coming in. 

Please chime in anyone if you know of a way to actually do this properly. 

Thanks!

**Comment by ypavlotsky** [comment]
We've deprecated the `adWillPlayMuted`setting in our plugin because the plugin now deduces it from whether the player is muted or its volume is 0.

**Comment by ypavlotsky** [comment]
Closing this out, feel free to comment if this is still an issue.
