### ISSUE TITLE
videojs-ima and youtube api

### ISSUE THREAD

**Issue by mysuf** [googleads/videojs-ima#506]
I use videojs-youtube plugin along with video.js and videojs-ima and I noticed that it loads youtube API with all bunch of sources(css, widget, etc) multiple times.

Example:
I have two videos on one page, both use videojs-ima. One videojs use youtube tech, another mp4. In network table I see:
- 3 requests to https://www.youtube.com/yts/cssbin/www-player-webp-vfla51d7j.css
- 3 requests to https://www.youtube.com/yts/jsbin/www-embed-player-vflmRzL1A/www-embed-player.js
- 3 requests to https://s.ytimg.com/yts/jsbin/www-widgetapi-vflUq8lG1/www-widgetapi.js

2 series belongs to videojs-ima, 1 to videojs-youtube

Is this necessary?  Apparently, videojs-youtube use same resources as videojs-ima. It leads me to idea that it could be handled more gracefully only via switching techs.

videojs-ima custom control bar is reason why I investigated it. I want preserve video.js control bar design when playing ads and I think that it is possible - via videojs-youtube tech. Now it only can be done through duplicating css I guess..

You probably know more about it so I would appreciate some short explanation.

P.S. I would imagine videojs-youtube subclass bringing new tech (for example video/ad or video/youtube-ad). You can override all methods that needs to be customized. Then videojs-ima's Controller could handle switching sources via sdkImpl. In other words, you can create second instance of videojs player with your own tech, overlaping/hiding first one.

Thanks guys

**Comment by ypavlotsky** [comment]
Hi,

It sounds like you're trying to monetize your YouTube videos. You should refer to [YouTube's instructions](https://support.google.com/youtube/answer/72857?hl=en) on how to do that.

If that's not the case, could you describe your use case for videojs-youtube so we can look into it?

Thanks,
Yury

**Comment by mysuf** [comment]
It is not that case. Now I have generic loader that attach videojs-ima to every player just for test purposes.  I can provide other example with four html5 videos with 15 duplicit requests to urls mentioned above. So my question is:
Why every player with ima load resources that was already loaded before?
Why not use videojs-youtube or similar approach to preserve player's look?

Thanks

**Comment by ypavlotsky** [comment]
Thanks for the clarification, I understand what you're trying to do.

However, we don't have any plans to integrate with the videojs-youtube plugin.

**Comment by mysuf** [comment]
videojs-youtube is nothing else than very simple tech plugin using youtube api. You can make your own. Just think about it. Anyway thank you for your time. I'm closing this suggestion as delivered.
