### ISSUE TITLE
Hide specific control component

### ISSUE THREAD

**Issue by mizmaar3** [googleads/videojs-ima#512]
According to videojs doc you can hide any specific control component http://docs.videojs.com/docs/guides/components.html

i.e. 

```
let player = videojs('myplayer', {
  controlBar: {
    fullscreenToggle: false,
    playToggle: false
  }
});

player.ima( {...} );
```

But it doesn't seems to work. Is it a bug or there is another way to hide specific control icon ? (not with css)

**Comment by shawnbuso** [comment]
Are you trying to modify the ad controls or the content controls? This won't work for the ad controls - we don't have a way to modify those right now. If it's an issue with content controls, you should file an issue in the [video.js issue tracker](https://github.com/videojs/video.js/issues). Thanks!

**Comment by mizmaar3** [comment]
Not modifying, I wanted to hide play/pause button.
https://www.awesomescreenshot.com/image/3170310/ec72a82af818ca492df28a3ce4263af7

Without CSS of course if possible

**Comment by shawnbuso** [comment]
Currently the only way to hide that is via CSS. We can take this as an FR to add an option to hide it programmatically, but it will be low priority since there's already a workaround to do this with CSS.

**Comment by Kiro705** [comment]
Because this has a work around using CSS I am closing the issue. Please feel free to reopen the issue if the current work around is not satisfactory or if something else comes up.
