### ISSUE TITLE
bug with videojs 6.6.3 in ios safari

### ISSUE THREAD

**Issue by Pong420** [googleads/videojs-ima#513]
demo:
[https://codepen.io/pong420/pen/bLROjO](https://codepen.io/pong420/pen/bLROjO)
same as the autoplay example except the video.js version

bug:
- video ad cannot display
- content video turn into fullscreen instead of video ad when click on togglefullscreen button

**Comment by mizmaar3** [comment]
videojs-ima support until VJS `5.20.4` and the reason is [ videojs-contrib-ads plugin](https://github.com/videojs/videojs-contrib-ads) supports until VJS `5.20.4`

**Comment by shawnbuso** [comment]
What @mizmaar3 said is correct - currently we only support up to VJS 5. Are you seeing this issue if you downgrade the VJS version you're using?

**Comment by Pong420** [comment]
thanks for reply,
if downgrade the VJS version work fine
