### ISSUE TITLE
Click on the Advertisement

### ISSUE THREAD

**Issue by adrianotadao** [googleads/videojs-ima#52]
When the user click on the advertisement:
- is opened a new tab and load the advertiser's page
- the advertisement is paused
- when the user click on the advertisement to resume, the same will be paused. The problem is that when click on ad again to resume, the new tab opens again.

**Comment by shawnbuso** [comment]
Is there a specific browser on which you're seeing this? In all of our tests (except iPhone, see #30) when I click on the ad and return to the page I get a play button in the overlay in the bottom right of the video. Clicking that resumes the ad without opening the clickthrough page.

**Comment by thijsdamen** [comment]
I am experiencing the same issue. When clicking on the advertisement itself it will open the adlink and pause / resume the video. This means that when you return to the video after clicking on it once, the ad is paused, clicking on the ad itself again resume the ad, but also opens another window with the adlink.

The play/pause is triggered by the google.ima.AdEvent.Type.CLICK event. Internally (I think) the ima library opens the new window.

My question to follow up on this would be: Is it possible to prevent the new window from opening when the ad is clicked in the 'paused' state

**Comment by shawnbuso** [comment]
You can put your own div over the ad when it gets paused, which should intercept the click from the IMA SDK and prevent it from opening the clickthrough page again. Let me know if that works for you. This will not, however, re-start the ad. For that the best solution is to use the built-in ad UI controls provided by the plugin.
