### ISSUE TITLE
Ads and video playing at the same time

### ISSUE THREAD

**Issue by TobiasCintrao** [googleads/videojs-ima#529]
Hi
We are experiencing unexpected behaviour with videojs-ima plugin along with videojs 5.20.2. and some preroll video Ads.
So, normal behaviour would be that as soon the preroll starts playing the video gets paused, and resumed after ad is skipped or reached its end.
What is happening is that the ad starts playing and the video appears to keep playing in the background at the same time, the sound of both preroll and video play at the same time and when the ad is skipped, the video is already at second X where X = ad duration.
The problem does not occur on every atttempt, but you can reproduce it very often on the link bellow:
`http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=kY3uVc_Nsu4YvNWw1AUwvPHl2wWIAYCAgKDr7Ym9Fg&op=set&redirect=http://videos.gameblog.fr/player/index/1/2/9&redirect_hash=AJlzBa3QKmgSwddmETEG-hIRi7Ije5PNyg&lineItemId=4584453534&creativeId=138225740981`

**Comment by ypavlotsky** [comment]
Hi,

I tried your link and I'm not seeing the behavior you mentioned. Are there any further instructions to reproduce?

**Comment by TobiasCintrao** [comment]
Hi,

The problem occurs on some Ads not all and the browser may be important We've tested on Windows 10, chrome 64 and Firefox 58.0.2 and verify the problem on both.
Another link where we the problem occur (note if you pause the Ad, the video will continue, and you can hear the sound of it): 
`http://pubads.g.doubleclick.net/gampad/preview_cookie?gct=DUDxAWx_ydcYw9Cw1AUww-zl2wWIAYCAgKDr7YnB-QE&op=set&redirect=http://www.gameblog.fr/news/73629-mavericks-proving-grounds-un-battle-royale-de-1000-joueurs-a&redirect_hash=AJlzBa34Kw9h3grBxR7_t1RfUwFsL-gFmw&lineItemId=4584453534&creativeId=138225740981`

**Comment by federicopuntoni** [comment]
Same issue here.

You can check here:
http://test-player-ads.s3-website-eu-west-1.amazonaws.com/

every time you open a new incognito window (not tab) in the latest chrome browser.

If you disable mute and pause the ads you can ear the video under.

**Comment by ypavlotsky** [comment]
As of version 1.0 of the plugin, you no longer have to call `play()` on the video player to request ads. So if you call it directly now, you're unpausing the paused backgrounded content player while ads are playing. We tested removing the call to `this.play()` and it fixed the issue, so we recommend doing that.

**Comment by federicopuntoni** [comment]
I removed all this.play() except one for mid-roll ads (not this case) but the problem persists.

**Comment by ypavlotsky** [comment]
Could you send us a sample page with the play() commented out so we can see what's going on? Removing it seemed to fix the issue in our experiments.

**Comment by federicopuntoni** [comment]
The same page as above :

http://test-player-ads.s3-website-eu-west-1.amazonaws.com/

Inviato da iPhone

**Comment by ypavlotsky** [comment]
I'm not seeing the issue on that page anymore. When I open it up and unmute the ad and then pause, I don't hear any content playing in the background and if I let the ad finish, the content starts from the beginning.

**Comment by ypavlotsky** [comment]
Going to close this out as there hasn't been any activity in a while. Feel free to reopen if this is still an issue.
