### ISSUE TITLE
Changing source with empty postroll

### ISSUE THREAD

**Issue by mysuf** [googleads/videojs-ima#530]
I implemented quality switcher and it works well in most cases, except when postroll VAST is empty. When video is ending, it throws:

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)

and error modal appers. It bubbles through func onAllAdsCompleted. I printed src values inside onAllAdsCompleted where` this.contentSource` is "", `h5player.src` is valid link to mp4. It calls vjsPlayer.src(this.contentSource) when `h5player.src !== this.contentSource` so it feeds player with empty string. Dunno why this is happening only when I switch sources during playing. As contrib-ads advices, during switching source I do:

```
if (player.ads) {
    player.ads.contentSrc = selectedSource.src;
} 
```

Thanks

**Comment by shawnbuso** [comment]
Do you have a sample page where I could repro this? Thanks!

**Comment by mysuf** [comment]
Sure. https://games.tiscali.cz/player/vjs-testpage.html During playing, just switch resolution and seek to end
Thank you

**Comment by shawnbuso** [comment]
I think the issue is that you're trying to work with the contrib-ads plugin directly, as shown in the snippet above, which we can't support with the videojs-ima plugin. In order to maintain the right state, you'll need to let the videojs-ima plugin handle all of the interaction with the contrib-ads plugin. We also don't yet support changing the content source while an ad is playing, so I don't think we'll be able to support this use case right now.

**Comment by mysuf** [comment]
Yea. I  thought that ima probably does not recognize that so I tried to handle it directly. Also I use videojs v6 so I guess this isn't last issue I faced. You are depended on contrib-ads..so do you know what is contrib-ads progress on migration to v6? It will be almost year since major release and I believe that plugin migration 5 -> 6 is not massive change.. Thank you.

**Comment by shawnbuso** [comment]
It looks like the latest version of contrib-ads, v6, does support video.js 6+. That just released today though so we haven't had a chance to test it with our plugin to see if we need to make any modifications for it to work.

**Comment by mysuf** [comment]
Anyway, that are good news. Hope, that implementation to ima will be piece of cake. Thank you for your help.

**Comment by mysuf** [comment]
@shawnbuso Ah. Looking at link that I provided, I see that it happens everytime, even if not changing source. So it could be related to version support or empty postroll ad.

**Comment by shawnbuso** [comment]
Yea I'm guessing it's a version support issue - hoping it resolves itself when we support VJ6, but if not I will come back to investigate further.

**Comment by mysuf** [comment]
Ok. Got it. Thanks again.
