### ISSUE TITLE
Support changing ad tags mid-stream

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#534]
Hello,

Using contrib-ads v 5.1.6 with video ima 1.1 mid-rolls and post rolls do not fire at all, i even tried with v 6 of contrib-ads same issue.

example: http://rs.vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1

contrib-ads V6 with video ima 0.8 work with no issue at all, the problem is videojs-ima when above V 0.8

example: http://vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1

our problem starts with V 1.0 onward maybe you can allow us to know what is the migration required to move to version 1.0 + with no issues.

regards,

**Comment by shawnbuso** [comment]
Hi there,

We did refactor the plugin a bit with V1.0. Have you taken a look at our examples? They've been updated to work with V1.0 as well.

It looks like you're trying to change your ad tag while content is playing, which isn't officially supported yet by the plugin - the alternative to this is to use a VMAP tag, which lays out a scheudle for different VAST tags to be requested and played ahead of time.

**Comment by sdahdaah** [comment]
unfortunately VMAP is not currently an option for us. Can you let us know
if you will have a support for similar tag in VAST in the near future.

we will look to the example and do the required changes to have V1.x soon.

thank you.

**Comment by shawnbuso** [comment]
I don't have a timeline for supporting changing ad tags right now, but I can leave this open as an FR to look into it.

**Comment by Pong420** [comment]
Hi @sdahdaah ,

Here is my solution to handle **midroll** and **postroll** by changing ad tags
[demo](https://videojs-ads.herokuapp.com/)

**Comment by sdahdaah** [comment]
i did something similar to what you shared but the problem is with replay button where the ads do not fire at all on replay. i am unable to initiate the ads on replay.

**Comment by shawnbuso** [comment]
@sdahdaah Can you try doing something like what we do in the [playlist example](https://github.com/googleads/videojs-ima/tree/master/examples/playlist)? Instead of switching the source and tag when the user clicks a video thumbnail, you can just change the tag, which would effectively be a replay button.

**Comment by sdahdaah** [comment]
I disregarded this fuctionality... not required for us anymore.
