### ISSUE TITLE
ads error 1009 on iOS iPhone

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#535]
Hello,

using the latest contrib-ads even with earlier versions with ima 0.8 or 1.1 whenever you try on iOS iPhone or using safari 11 with user-agent iOS iPhone the following link; http://vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1 ads fire 1009 response.

http://rs.vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1  (ima 1.1 and contrib-ads 6)

any method to solve it.

**Comment by shawnbuso** [comment]
Currently we only support up to contrib-ads 5.

Aside from that, ad error 1009 means that your VAST response is coming back empty. Can you confirm that your ad serving settings are such that it will deliver ads to iOS Safari?

**Comment by sdahdaah** [comment]
Hello Shawn,

whether using contrib ads 5 or 6 it is the same issue.

trying the same VAST tag on JWPlayer works with no issue on iOS.

which version of contrib-ads do you suggest we use with IMA 0.8?

**Comment by shawnbuso** [comment]
I can look into this further to try to see why you're not getting ads back.

[For version 0.8 it looks like we were working with contrib-ads 5.0.](https://github.com/googleads/videojs-ima/blob/0.8.0/package.json#L20)

**Comment by sdahdaah** [comment]
it will be excellent.

**Comment by shawnbuso** [comment]
I'm not able to replicate the 1009 error, but I do see a different issue. It looks like your tag is returning YouTube-hosted AdSense ads, which are not supported on mobile web. You can see more about what is and is not support on our [support and compatibility page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).

**Comment by shawnbuso** [comment]
Closing this out since I think my last response should resolve it - if that's not the case feel free to re-open or start a new issue. Thanks!
