### ISSUE TITLE
Ads on Playlist

### ISSUE THREAD

**Issue by Sudhakar-Sukumar** [googleads/videojs-ima#544]
Hi

is there any options for running ads on playlist.

ads should be run for all vidoes under playlist
https://googleads.github.io/videojs-ima/examples/playlist/

Thanks,

**Comment by ypavlotsky** [comment]
Hi there,

Do you mean you want to automatically play a second video in a playlist? You can do something like what I suggested [here](https://github.com/googleads/videojs-ima/issues/493#issuecomment-365038946).

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity here in a while. Feel free to reopen if necessary.
