### ISSUE TITLE
VideoJs Ima in Android

### ISSUE THREAD

**Issue by taniabarreira** [googleads/videojs-ima#545]
Hi,
Someone can help me?
In a page with videojs v5, and Google IMA, i can see ad in pc and iphone, but in android chrome browser's can't!
http://rr.sapo.pt/videojs/imagoogle.html

**Comment by ypavlotsky** [comment]
I'm seeing an AdError 1009 when I go to that page on Android, so likely your ad tag is returning something incorrectly for Android. I would check with your ad server.

**Comment by taniabarreira** [comment]
ok, thanks @ypavlotsky 
I also missed that I was conflicting the events of Google.Ima with the events of the own videojs player, I changed the order and seemed to improve ..
