### ISSUE TITLE
Initialize adsManager

### ISSUE THREAD

**Issue by aymanabbas92** [googleads/videojs-ima#547]
I need your help.
How I can initialize adsManager inside videoJS code.
If there is any example code, it will be better.

Thanks

**Comment by shawnbuso** [comment]
Hey there,

The idea behind this plugin is that it does almost all of the work for you - you shouldn't have to directly initialize the adsManager yourself. I'd recommend taking a look at our [examples](https://github.com/googleads/videojs-ima/tree/master/examples), starting with the [simple example](https://github.com/googleads/videojs-ima/tree/master/examples/simple), to get an idea of how the plugin works.

Thanks,
Shawn

**Comment by shawnbuso** [comment]
Unfortunately the IMA SDK doesn't support this - once an ad is played you can't re-play the same ad without making another ad request and going through the whole workflow again.
