### ISSUE TITLE
When pause video, ads load again

### ISSUE THREAD

**Issue by taniabarreira** [googleads/videojs-ima#556]
Hi @shawnbuso , Maybe you can help me, sometimes, after preroll run one time and jump for my video correctly, if i pause my video, adsloader run again and show me again ads..
You can see in http://rr.sapo.pt/videojs/imagoogle.html

**Comment by taniabarreira** [comment]
Okay, I think I got it sorted out. Because of the mobile versions, it had the following code:
        player.one(startEvent, function () {
            player.ima.initializeAdDisplayContainer();
            player.ima.requestAds();
            player.play();
        });

if i remove player.ima.requestAds(); ,i think it works

**Comment by hack4mer** [comment]
What you did by mistake is what I needed to do intentionally and this helped me out, thanks, buddy!
