### ISSUE TITLE
How to play dfp playlist ad from vmap

### ISSUE THREAD

**Issue by codex-corp** [googleads/videojs-ima#557]
Hi @shawnbuso 

Kindly check the below link, 
https://goo.gl/s4bTCj

![image](https://user-images.githubusercontent.com/775654/37276108-8b0b6b6e-25e9-11e8-8a18-76d4d7f9bf5e.png)

The link below generate vMAP list with Vast ads
[Click here](http://player.mangomolo.com/v1/video/adsMap/26796514)

[Video sample on my website](http://player.mangomolo.com/v1/video?id=26796514&user_id=71&countries=Q0M=&zone=&w=100%25&h=100%25&filter=DENY&jwplayer=7&signature=2b01d077fcf4bd8f4bc79e77be27f175
)

Please your advice?
Regards
Hany

**Comment by ypavlotsky** [comment]
Hi there,

You can have the plugin serve canned ads by specifying the VAST or VMAP directly in the `options` via `adsResponse`:

```
var options = {
  fluid: true,
  id: 'content_video',
  adsResponse: '<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">' +
'<vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">' +
'<vmap:AdSource id="preroll-463" allowMultipleAds="false" followRedirects="true">' +
'<vmap:AdTagURI templateType="vast3">' +
'<![CDATA[ ]]>' +
'</vmap:AdTagURI>' +
'</vmap:AdSource>' +
'</vmap:AdBreak>' +
'</vmap:VMAP>',
};
```
Note that the VMAP you provided doesn't have any ad tags in it, so you'd still need to modify it with your ad tag URI.

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity for a while. Feel free to reopen.
