### ISSUE TITLE
Autoplay videos occasionally fail to play in Safari 11

### ISSUE THREAD

**Issue by yonbeastie** [googleads/videojs-ima#560]
I'm running into an issue where autoplay videos are inconsistent in Safari 11 (but fine in Chrome and Firefox). Specifically, triggered events in `videojs-contrib-ads` (preroll) sometimes do nothing and the video requires a click to play, even though the `video` element has `muted=true` and `autoplay`.

Using:

- `video.js@6.7.3`
- `videojs-ima@1.2.1`
- `videojs-contrib-ads@6.0.0`

To clarify, the video plays correctly with preroll ads about 70% of the time, with this debug output from `videojs-contrib-ads`:

<img width="404" alt="screen shot 2018-03-13 at 2 32 03 pm" src="https://user-images.githubusercontent.com/3318403/37366956-012e94a6-26d0-11e8-8a81-5f194014fd83.png">

About 30% of the time, the `adsready` event is triggered with no subsequent events, causing the video to no autoplay:

<img width="376" alt="screen shot 2018-03-13 at 2 32 55 pm" src="https://user-images.githubusercontent.com/3318403/37367003-2726ba4e-26d0-11e8-950a-a442adf778a7.png">

The AdTagURL being tested is: 

https://pubads.g.doubleclick.net/gampad/ads?correlator=2179236500362919&cust_params=beta%3D0%26google%3D1%26slot%3Dvideo%26test%3Dhouseads%26video_service%3D3%26video_id%3Dm2jtspultyvb4avdhubv%26player_version%3D2.1.3%26categories%3Darts-and-entertainment-movies%2Carts-and-entertainment-television%2Carts-and-entertainment%2Carts-and-entertainment-celebrity-fan-sla%26player%3D2.1.4%26ap%3D2%26ctp%3D0&description_url=http%3A%2F%2Fwww.thehollywoodgossip.com&env=vp&gdfp_req=1&iu=%2F1030006%2Fthehollywoodgossip_video&output=xml_vast3&sz=640x480&unviewed_position_start=1&url=null&eid=324123020%2C495644009&sdkv=h.3.195.4&sdki=3c0d&scor=554421001053338&adk=2876963133&u_so=l&osd=2&frm=0&sdr=1&is_amp=0&vpa=auto&vpmute=0&mpt=videojs-ima&mpv=1.2.1&afvsz=200x200%2C250x250%2C300x250%2C450x50%2C468x60%2C480x70&ged=ve4_td1_tt0_pd1_la1000_er0.0.0.0_vi0.0.1321.637_vp0_eb16491

Any guidance would be appreciated!

**Comment by ibraalek10** [comment]
Hi all,
Safari 11 blocks the video with autoplay and with sound.

doc: https://www.howtogeek.com/326532/safari-now-disables-auto-playing-videos.-heres-how-to-allow-them-for-certain-sites/

A.

**Comment by ehoch** [comment]
@ibraalek10 As mentioned in the issue, this is on videos with the muted attribute.

**Comment by ibraalek10** [comment]
Yes, but i had same problems months ago also with the "muted" attribute.. 
For this reason i shared this article..
Take a test..

A.

**Comment by ypavlotsky** [comment]
I'm not seeing this in using our [autoplay](https://github.com/googleads/videojs-ima/tree/master/examples/autoplay) example when I replace the tag with your tag. We're also in the process of updating our autoplay example to be more robust [here](https://github.com/googleads/videojs-ima/issues/341).

**Comment by ypavlotsky** [comment]
Going to close this out as there hasn't been some activity here for a while. Feel free to reopen if this is still an issue.
