### ISSUE TITLE
Preroll does not work on newest version on mobile browser

### ISSUE THREAD

**Issue by canhnm** [googleads/videojs-ima#561]
Hi,

I am using latest version of videojs-ima and got issue with mobile browser(tested with safari, chrome, firefox).
Even using the sample pages: https://googleads.github.io/videojs-ima/

Error from console when started playing video:

> Ad error: AdError 400: There was an error playing the video ad. Caused by: AdError 1205: The browser prevented playback initiated without user interaction.

The only one works well is the autoplay sample which has "muted playsinline" defined, so on mobile do we need to set "muted playsinline" on video html default to prevent this error?

**Comment by canhnm** [comment]
hi @ypavlotsky I found the solution, by adding **playsinline** attribute into the video element, it works well on mobile browser!

**Comment by ypavlotsky** [comment]
I'm still seeing the same error with `playsinline`. What are you testing on, in terms of device and OS?

**Comment by canhnm** [comment]
@ypavlotsky I am testing with all OS including iOS, Android(Safari, Chrome, Firefox).
May be try to run your test with muted playsinline attribute?

**Comment by canhnm** [comment]
@ypavlotsky 
Update: Sometime, preroll video still stopped due to the warning about user interaction with the implementation using playsinline, muted

**Comment by selected-pixel-jameson** [comment]
+1

**Comment by canhnm** [comment]
Update: Mobile Preroll works on vjs 5.20.4, vjs contrib ads 5.1.6 and vjs ima 1.1.1. Tested with Safari, Chrome, Firefore on iOS, Android.
Solution is:
On mobile mute the player and provide setting adWillPlayMuted + mute the ads before request preroll vasttag with: this.player.ima.requestAds();

**Comment by ypavlotsky** [comment]
Still haven't heard back from the SDK team on this issue, will update here when I have more information.

**Comment by dannyf620** [comment]
Right after error 1205 appears, another error comes out

Uncaught TypeError: Cannot read property 'v' of null
at nA (bridge3.202.0_en.html:427)
at bridge3.202.0_en.html:501

http://imasdk.googleapis.com/js/core/bridge3.202.0_en.html

**Comment by dannyf620** [comment]
some mobile browsers requires user interaction to load or play media 
> touchstart touchend touchmove touchleave touchcancel click keydown keyup keypress

I had used other button to play the audio 
```javascript
$('.player-button').click(function () {
    playerId.player.play();
}
```
to solve the problem I call the click of the player button videojs by code and listen the click event "this is a user interaction"

```javascript
$('.player-button').click(function () {
    $('.playerContainer .vjs-big-play-button')[0].click();
}
```
```javascript
this.player.one('click', function () {      
      _this.player.ima.setContentWithAdTag(null, _this.adUrl, false);
      _this.player.ima.requestAds();
      _this.player.ima.initializeAdDisplayContainer();
      _this.start = true;
    });
```
this just worked calling the initializeAdDisplayContainer method at the end

**Comment by ypavlotsky** [comment]
This should be fixed with [this PR](https://github.com/googleads/videojs-ima/pull/613) now. If it's still happening, feel free to reopen.
