### ISSUE TITLE
Mouse handler bound incorrectly, breaks volume controls

### ISSUE THREAD

**Issue by grobolom** [googleads/videojs-ima#568]
Hey all!

I've been doing some work with this plugin recently, and noticed a bit of code that seems to be mistyped:

https://github.com/googleads/videojs-ima/blob/504644037262cb78fc5656762054dc1d3eee72fd/src/ad-ui.js#L87
https://github.com/googleads/videojs-ima/blob/504644037262cb78fc5656762054dc1d3eee72fd/src/ad-ui.js#L92

Both of the lines above in the AdUI module bind a different method to the same property. As a result, the `mousemove` handler here:

https://github.com/googleads/videojs-ima/blob/504644037262cb78fc5656762054dc1d3eee72fd/src/ad-ui.js#L310

does not call the correct method. This presents in the UI by causing the ad controls to behave oddly - if you click anywhere on the control bar to the left of the volume slider, the volume gets muted.

The fix (which we've tested locally) is to change line 92 above to `boundOnMouseMove`. Then, everything works correctly, including `click -> drag -> release` on the volume slider.

Thanks for your time!

**Comment by shawnbuso** [comment]
Thanks for the info! Should be a quick and easy fix.
