### ISSUE TITLE
postroll with hls cause issue

### ISSUE THREAD

**Issue by codex-corp** [googleads/videojs-ima#570]
The postroll is well played, and when the postroll is finished; one error appears. 

Error:
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. MediaError {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}

Fix,
```
PlayerWrapper.prototype.onAllAdsCompleted = function () {
  if (this.contentComplete == true) {
    if (this.h5Player.src != this.contentSource) {
        this.player.autoplay(false);
        if(this.contentSource != "") {
            this.vjsPlayer.src(this.contentSource);
        }
    }
    this.controller.onContentAndAdsCompleted();
  }
};
```

Tested with **hls.js** and **videojs-contrib-hls**

https://github.com/googleads/videojs-ima/blob/504644037262cb78fc5656762054dc1d3eee72fd/src/player-wrapper.js#L465

**Comment by Pong420** [comment]
i have the same problem and solved by this PR #433

**Comment by codex-corp** [comment]
@shawnbuso do you want it in PR?

**Comment by ypavlotsky** [comment]
Did the PR fix this issue? Is this still happening?

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity for a while. Feel free to reopen if it's still happening.

**Comment by codex-corp** [comment]
@ypavlotsky yes it does.

**Comment by wizquest-labs** [comment]
we are using version 1.5.1 available on npm, but still getting this issue.

Also, it seems like the above mentioned fix i.e. PR #433 is not available in this version. Unless I'm missing anything here.
