### ISSUE TITLE
Video should be pause when player is out of active screen

### ISSUE THREAD

**Issue by akashsky44** [googleads/videojs-ima#577]
hello,
I am using videojs-ima where I facing a problem, why video player playing active player screen out.
Please suggest me how to stop this thing when player out of active screen.

Thanks

**Comment by ypavlotsky** [comment]
Hi,

If you're asking for us to pause the video player when it's off-screen, such as when the user scrolls a page and the video is no longer visible, it's not something we support. However, you can try to implement the feature yourself, as we provide the ability to pause and resume ads whenever you need to.

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity for a while. Feel free to reopen if necessary.
