### ISSUE TITLE
player.ima is not defined in ionic app

### ISSUE THREAD

**Issue by hellomrdavis** [googleads/videojs-ima#578]
I am integrating this into our ionic/angular app but am consistently getting a "player.ima is not a function" error. 

Our function that is called on video click: 
`onPlayingVideo(event){
    event.preventDefault();

      var videoPlayerID = event.target.id;
      var player = window.videojs(videoPlayerID);

      var options = {
        id: videoPlayerID,
        adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&' +
            'iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&' +
            'impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&' +
            'cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&' +
            'vid=short_onecue&correlator='
      };

      player.ima(options);

      // Remove controls from the player on iPad to stop native controls from stealing
      // our click
      var contentPlayer =  document.getElementById(videoPlayerID +'_html5_api');
      if ((navigator.userAgent.match(/iPad/i) ||
            navigator.userAgent.match(/Android/i)) &&
          contentPlayer.hasAttribute('controls')) {
        contentPlayer.removeAttribute('controls');
      }

      // Initialize the ad container when the video player is clicked, but only the
      // first time it's clicked.
      var startEvent = 'click';
      if (navigator.userAgent.match(/iPhone/i) ||
          navigator.userAgent.match(/iPad/i) ||
          navigator.userAgent.match(/Android/i)) {
        startEvent = 'touchend';
      }
      player.one(startEvent, function() {
          player.ima.initializeAdDisplayContainer();
      });

      // play the first video that is chosen by the user
      if (this.currentPlayingVideo === undefined) {
          this.currentPlayingVideo = event.target;
          this.currentPlayingVideo.play();
      } else {
      // if the user plays a new video, pause the last one and play the new one
          if (event.target !== this.currentPlayingVideo) {
              this.currentPlayingVideo.pause();
              this.currentPlayingVideo = event.target;
              this.currentPlayingVideo.play();
          }
      }
  }`

The video element. These are dynamically created with 20 videos on the page. 
`<ion-card class="video-articles" *ngFor="let videoItem of videoItems">
          <ion-card-content>
              <video (playing)="onPlayingVideo($event)" id="player_{{videoItem.videoCount}}" style="width: 100%; height: 180px;" preload="auto" playsinline webkit-playsinline="webkit-playsinline" class="video-js" controls="controls" poster="{{videoItem.image}}"><source src="{{videoItem.videoURL}}" type="video/mp4"></video>

            <div>
              <ion-card-title>{{videoItem.title}}</ion-card-title>
            </div>
          </ion-card-content>

        </ion-card>`

![screen shot 2018-03-22 at 11 48 59 am](https://user-images.githubusercontent.com/1133512/37781616-6d516336-2dc7-11e8-9f28-b0aeb6b8386c.png)

Any help or guidance would be appreciated.

**Comment by ypavlotsky** [comment]
Hi there, I'm not familiar with these frameworks, but if it's anything like the [reactjs issue](https://github.com/googleads/videojs-ima/issues/552) opened, the plugin doesn't really handle being put in a module via webpack.

**Comment by MrWiLofDoom** [comment]
> Hi there, I'm not familiar with these frameworks, but if it's anything like the reactjs issue opened, the plugin doesn't really handle being put in a module via webpack.

So what options do we have? It seems like all of the plugins suffer from this.

**Comment by Kiro705** [comment]
Hi all,

I recently closed the [reactjs/webpack issue](https://github.com/googleads/videojs-ima/issues/552) based on the inclusion of the recent [webpack guide](https://github.com/googleads/videojs-ima#es6-imports).

I am also going to close this issue. Please let me know if the guide does not resolve the issue for the Ionic/angular setup and feel free to reopen the issue..
