### ISSUE TITLE
Delayed playback after ads on iOS native player

### ISSUE THREAD

**Issue by ngood97** [googleads/videojs-ima#579]
I'm having this issue where after an ad plays in the iOS native player the player appears to freeze until the desired content is ready to play.

The result is if the content is slower to load that the user is very confused because it just has a completed video showing in the native player.

The expected behaviour I'm looking for is the player should switch to the 0 second mark of the next video as soon as the ad is done so the user can see that their content is loading and they won't want to close the player.

I noticed that the 'adend' event only fires once the next video is ready so I can't force the video to switch once the ad is done because the event is fired too late. Is there a way I can obtain the desired behavior?

**Comment by incompl** [comment]
Possibly related to https://github.com/googleads/videojs-ima/issues/567

**Comment by ypavlotsky** [comment]
Going to close this out as there hasn't been any activity for a while. Let me know if this is still happening.
