### ISSUE TITLE
Custom Ad Playback

### ISSUE THREAD

**Issue by mysuf** [googleads/videojs-ima#582]
Hi, I am trying to understand inner IMA SDK logic. There is option to set custom video element for ad playback according to https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdDisplayContainer. videojs-ima pass there contentPlayer video element ([sdk-impl.js](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L161)), but when I inspected html during ad playback, I saw new video element (actually there were two - one hidden) inside ima container playing this ad. It seems that IMA SDK ignores content player and do it on their own. Any idea? Thank you!

**Comment by shawnbuso** [comment]
There are some platforms that don't have good support for more than one video element - like iPhone, for example. On those platforms the SDK will re-use the content player to play ads, so there's no need for it to render a second player. The overwhelming majority of platforms (desktop browsers, Android devices, etc.) don't have this problem with multiple video players, so the SDK renders its own ad player on top of the content player.

**Comment by mysuf** [comment]
Is there way to force sdk to re-use that player?

**Comment by mysuf** [comment]
I am playing with videojs-ima little bit and I would like to use prepared empty videojs player for it. But when sdk ignores contentPlayer, that bridge is too far :) Thanks

**Comment by shawnbuso** [comment]
Currently we don't offer a way to force the SDK to re-use the content player for ads.
