### ISSUE TITLE
Ads are not playing in inactive tab

### ISSUE THREAD

**Issue by aicreate** [googleads/videojs-ima#583]
I have a player that works good in active tab, but when I am trying to run ads in inactive tab, it gives me an error 

> Ad error: AdError 402: VAST media file loading reached a timeout of 8 seconds.

my code is below
```
window.playeroutreach = videojs('test_player', {
    blackPoster: false,
    techOrder:["html5"],
    textTrackSettings: false,
    controls: true
});

var options = {
    id: 'test_player',
    adsResponse: xhr.responseText, //VAST xml here
};

window.playeroutreach.ima(options);
var contentPlayer =  document.getElementById('content_video_html5_api');
playeroutreach.ima.initializeAdDisplayContainer();
playeroutreach.ima.requestAds();
playeroutreach.play();

```
Any possibility to solve the problem ?

**Comment by ypavlotsky** [comment]
Hi there,

What browser/platform are you seeing this issue on? If you check out the [sample player](http://googleads.github.io/videojs-ima/examples/advanced/), does it work for you?

**Comment by aicreate** [comment]
the problem was in my ima3 file. the file from google domain works well
