### ISSUE TITLE
Click through url in webview

### ISSUE THREAD

**Issue by mizmaar3** [googleads/videojs-ima#587]
Whenever their is a click through url in VAST the ima creates `Learn More` clickable text on top right corner (basically there is an iframe created by ima and whole iframe is clickable to goto url). The issue is when the VAST is loaded in webview the click through url opens within webview instead of on `_top` target which is quite strange because it does work fine directly browsers i.e. if VAST loaded in an iframe, clicking on `Learn More` opens url as target is `_top`.

So my question is: Is there any way to access vast's `Click Through Url` in code so I can create overlay <a> tag on video with same Click Through Url and `target=_top` ? 

I figured out that `player.ima.getAdsManager().getCurrentAd()` object have `clickThroughUrl` but only in a simple VAST i can access it. If their is a VPAID with one vast tag is wrapped another vast tag, the `clickThroughUrl` im same object is empty.

**Comment by ypavlotsky** [comment]
Hi,

The IMA SDK does not provide a way to access click-through information for ads. 

When I load the videojs simple example in a WebView, clicking Learn More opens the clickthrough page in Chrome, so I'm not seeing the behavior you're experiencing. Can you provide more details on how to reproduce the issue?

Thanks!

**Comment by mizmaar3** [comment]
Thanks for quick reply, and sorry I figured it out its our own internal webView which opens links within webview until we append a special queryParam to url.

But of there is no way to access `Click Through` url I think I cannot fix it.

But can you tell me how does IMA work to create that `Learn More` link ? because I cannot see any a tag, looks like its a click listener on iframe (or its body) which leads you to the click through url ?

**Comment by ypavlotsky** [comment]
Sorry, I can't share any details about how the IMA SDK creates the 'Learn More' link. You should be able to treat it as a black box that you don't modify.

**Comment by mizmaar3** [comment]
all right :)
Thanks
