### ISSUE TITLE
Functioning iPhone example?

### ISSUE THREAD

**Issue by redavis** [googleads/videojs-ima#59]
@shawnbuso I am having issues with the iPhone example.

I took the code straight from docs, swapped out my ad URL and everything functions correctly(even on iPad) until I test on an iPhone. I can clearly see it hits http://pubads.g.doubleclick.net/gampad/ads?slotname= and pulls backs a proper XML file.

The debug events always want to stop at VIDEOJS: ads adtimeout triggered: preroll? -> content-playback and for some reason player.ima.onAdLoaded_ is never called.

 I get a 'Access-Control-Allow-Origin' error from all the example pages so couldn't validate it is in working order.

Do you have any insight to what may be causing this?

Thanks in advance.

**Comment by scienced** [comment]
Are the other examples working for you? I'm not seeing any ads in all the example videos? (tested it on multiple devices)

**Comment by redavis** [comment]
@scienced None of the examples work for me but the plugin does work. I suspect the cause is that the ad request URL's are http: and the demo is on https:

**Comment by scienced** [comment]
@shawnbuso can you update the demo's to get them working again? I would love to see a working demo to have some evidence it works.

**Comment by scienced** [comment]
@redavis demo looks like it's http:
![image](https://cloud.githubusercontent.com/assets/10393564/6487550/25e6b332-c292-11e4-896c-f7c1fa6c82f0.png)

**Comment by shawnbuso** [comment]
Hi folks, sorry about the issues here. The tag we were using for the demos expired so I'll need to update it. Will get that done ASAP to get these demos working again.

**Comment by redavis** [comment]
Thanks @shawnbuso 

Any ideas on why the iPhone is not loading the ads after xml file is fetched before I start investigating further?

Almost seems related to why the implementation is different in first place and an event is not being triggered.

**Comment by shawnbuso** [comment]
Could you send me the complete tag that you're using to test?

**Comment by redavis** [comment]
Sure. http://dev4.leetemplates.com/app/ryan/google_ima/mobile.html

Everything is exactly the same as example minus the placeholder has text rather than poster image.

Note that there are a couple Youtube prerolls mixed in with the 5 or so test ads so those are expected to fail on iPhone since its only in FLV format. They both have <AdTitle>Preroll YouTube Test</AdTitle> in response so you will have to ignore and refresh the page if you get those.

**Comment by shawnbuso** [comment]
It looks like the issue with your particular tag is that it's serving a skippable ad, and IMA doesn't support skippable ads on iPhone (we can't render a skip button on top of the video). Are you able to test your page with a non-skippale ad?

**Comment by redavis** [comment]
@shawnbuso That did the trick. Testing that didn't even cross my mind. Many thanks!
