### ISSUE TITLE
DRM + google ima: currentTime and remainingTime not updating

### ISSUE THREAD

**Issue by Jakuboslav** [googleads/videojs-ima#590]
Hello,
I have issue with DRM protected videos and google ima plugin.
When I play video without DRM protection, currentTime and remainingTime are updating correctly and everything works as expected.
When I turn on DRM protection, currentTime and remainingTime stops working. Ad is playing correctly, but countdown shows (-1:-1). I logged into console both currentTime and remainingTime, but they are not changing. I found out ( https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis ) that getRemainingTime() returns -1 if "ad is not loaded yet or has finished playing", which is not true obviously.

Consequesce is that I can not pause video and countdown is showing wrong time.

My versions:
Videojs 6.7.4
DashJS  2.6.7
Videojs contrib ads 5.1.6
Videojs Dash 2.9.1 
Videojs Ima 1.1.1

Did anybody encounter this issue? Is it my side failure? 

This is my first issue report ever, so let me know, if you need any aditional info.

Thanks in advance.

**Comment by shawnbuso** [comment]
Do you have a sample page where I can reproduce your issue? Thanks!

**Comment by Jakuboslav** [comment]
Hello,
I have no possibility of sharing example with you at this moment since our development servers are not public. I will get sample page in few day.

In meanwhile I found out that this issue appears only in Chrome. FF works correctly without this problem. 
I was not 100% accurate with description. This issue appears occasionaly even in videos without DRM protection, but more or less very rarely.

My implemention is basic according to your guide, without intervention into videojs ima nor dashjs, so this issue might be replicated with versions mentioned above.

Thank you.

**Comment by shawnbuso** [comment]
I haven't seen any issues in the little bit of work we've done testing DASH, so I think it'll be easier if I test with the sample page you have. Let me know if you can get one to me. Thanks!

**Comment by shawnbuso** [comment]
I took a quick look at this - it looks like you're using a VPAID ad. With VPAID ads, it's up to the ad itself to tell the IMA SDK what it's remaining time is. So it looks like your DRM plugin is interfering with the VPAID ad and causing it to misreport its timing. Do you have a contact with whoever wrote the ad so you can work with them to troubleshoot?

**Comment by Jakuboslav** [comment]
Hello,
I apologize myself, now you should see also non-vpaid ads, where the problem is present. I don't think that vpaid ad is causing this issue, since in normal video is remaining time 0:00, but in DRM video it is -1:-1.

Thanks.

**Comment by shawnbuso** [comment]
Now when I load the page I see a pod of 2 ads - the first ad is a normal video ad, and I see the countdown timer working as expected. The second ad is the same VPAID ad as before, where it reports the time as 0:00 for the whole ad.

**Comment by Jakuboslav** [comment]
I have sent you 2 links. I can confirm this behaviour for first link ( non DRM). I have double checked DRM version, it was ok, but after reload, issue I have described appeared.

**Comment by shawnbuso** [comment]
After a whole bunch of debugging, I think I know what's going on. **tl;dr** you need to remove your call to player.ima.requestAds(). I tested on my end, and commenting out that line caused the remainingTime to display properly for the video ad.

Long story: When we refactored with v1, we removed the need to call requestAds() in your implementation - we do that part for you now. It looks like you still have that call, though, so you had 2 ad requests going on at the same time - the one you made via player.ima.requestAds, and the one the plugin made automatically for you. When the second request was made, the IMA SDK threw out the original request and ran with the second one. The adsManager instance the plugin retained, however, was for the first request. So when we called adsManager.getRemainingTime(), that adsManager instance wasn't playing an ad, so it just returned -1. And we didn't have a handle to the adsManager instance that actually was playing the ad.

**Comment by Jakuboslav** [comment]
Hello,
This solved my issue. I really appreciate your help.
