### ISSUE TITLE
Translateable "of" string

### ISSUE THREAD

**Issue by anvalchev** [googleads/videojs-ima#591]
Can the "of" string be translatable?

https://github.com/googleads/videojs-ima/blob/dba1a51975e5b2d5c8bb300e0d472f375162ad05/src/ad-ui.js#L271

**Comment by shawnbuso** [comment]
Currently we don't have translation support for the plugin, just for the underlying SDK. You could modify this yourself in a fork, though, if you're interested.

**Comment by anvalchev** [comment]
Done that and made a pull request, if you are interested.
