### ISSUE TITLE
Example using npm installation

### ISSUE THREAD

**Issue by Alphapage** [googleads/videojs-ima#593]
Hello,

I'm trying to `import 'videojs-ima'` without success.
I'm getting `TypeError: Cannot read property 'getElementsByClassName' of null` at line 135 of `videojs.ima.js`:
`this.h5Player = document.getElementById(this.controller.getSettings().id).getElementsByClassName('vjs-tech')[0];`

Maybe I am missing something.
Thank you in advance for your help.

**Comment by shawnbuso** [comment]
Could you send your full code so I can see what else is going on? Thanks!

**Comment by Alphapage** [comment]
Here is my component:

```import React, { Component } from 'react';
import videojs from 'video.js'
import 'video.js/dist/video-js.css'
import 'videojs-contrib-ads'
import 'videojs-contrib-ads/dist/videojs.ads.css'
import 'videojs-ima'
import 'videojs-ima/dist/videojs.ima.css'

export class VideoPlayer extends Component {
  
  componentDidMount() {
    videojs.registerPlugin('adsPlugin', function() {
      this.ads();
     // Ad integration logic goes here      
   });
    // instantiate Video.js
    this.player = videojs(this.videoNode, {...this.props,  fluid: false, controlBar: { fullscreenToggle: true } }, function onPlayerReady() {
      this.adsPlugin();
      var options = {
        id: this.id,
        adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator='
      };      
      this.ima(options);
     const videoSources=[{src:"https://ridrstorage.blob.core.windows.net/temp/ridr.mp4"}]
     this.src(videoSources)
    this.play();
    });
  }

  // destroy player on unmount
  componentWillUnmount() {
    if (this.player) {
      this.player.dispose();
    }
  }

  render() {
    return (
       <div data-vjs-player>
          <video ref={ node => this.videoNode = node } className="video-js vjs-big-play-centered vjs-fill vjs-tech" controls preload="auto"></video>
         </div>
    );
  }
}
```

Then I call it like this: `<VideoPlayer/>` in my main root.

For info, I use webpack but I don't think it is the problem.
If you need more info, let me know. Thank you.

**Comment by Alphapage** [comment]
This snippet ?
`this.h5Player = document.getElementById(this.controller.getSettings().id).getElementsByClassName('vjs-tech')[0];`
It comes from line 135 of `videojs.ima.js`

**Comment by shawnbuso** [comment]
Ah I didn't realize that, I thought it was in your implementation. If that line is failing, it means there's no element in the DOM with the ID that you're providing. I haven't done any work on integrating the extension into a component like this - do you have access to the DOM so you can see if the element we're trying to access exists or not?

**Comment by Alphapage** [comment]
Yes, the id is correct. But from my investigations, 
` Component.prototype.id = function id() {
    return this.id_; // should be this.vjsPlayer.id_
  };`
at line 3462 of `video.cjs.js`

**Comment by Alphapage** [comment]
So the controller is not videojs player.

**Comment by Alphapage** [comment]
Finally I caught the error: 
`var options = {
        id: this.id_,
        adTagUrl: 'http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpod%26deployment%3Dgmf-js&cmsid=496&vid=short_onecue&correlator='
      }; `
Sorry for taking your precious time.
I'm getting another error but related to `this.vjsPlayer.ads(adsPluginsSettings)` but it comes from videojs-contrib-ads I think.

Thank you anyway.

**Comment by shawnbuso** [comment]
The controller is an object created by the IMA extension, it's not the video.js player. When we access `this.controller.getSettings().id` we're accessing the `id` parameter you provide in the settings. In our [samples](https://github.com/googleads/videojs-ima/tree/master/examples/), that's the id of the video player you create that eventually turns into the video.js player.

**Comment by shawnbuso** [comment]
Glad you got it worked out!

**Comment by ksvbrother** [comment]
TypeError
Cannot read properties of null (reading 'getElementsByClassName')
PlayerWrapper.onPlayerReady
https://szy7pk.csb.app/node_modules/videojs-ima/dist/videojs.ima.es.js:247:62
eval
https://szy7pk.csb.app/node_modules/video.js/dist/video.es.js:1988:7
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.


Same issues still have? any one resolve the problem?
