### ISSUE TITLE
Show Pod duration instead of the duration of the single ads

### ISSUE THREAD

**Issue by anvalchev** [googleads/videojs-ima#594]
I'm not sure if this is for here, but I couldn't find a solution and was wondering if it's possible to show the duration of the Pod with all its ads and count down from there, instead for each ad individually?

Say you have a max 45 sec pod with 5 ads, adding up to 41sec. I'd like to show the label "Advertisement: 00:41" and count down from there until all 5 ads have played.

**Comment by ypavlotsky** [comment]
Hi there,

You can get the `Ad` from the `AdEvent` and then get the `AdPodInfo.getMaxDuration()` from that, but depending on your ads, you'd still not be able to change the ad UI to show this information unless you're providing your own ad UI.

**Comment by alyona-mordas** [comment]
Hi @ypavlotsky 

how do you get access to AdPodInfo class ? it is not on player.ima , nor on window.google.ima

**Comment by Kiro705** [comment]
Hello @alyona-mordas ,

You can access the AdPodInfo class by calling [Ad.getAdPodInfo()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.Ad#getAdPodInfo).

You can access the Ad class by calling [AdEvent.getAd()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent#getAd) for a number of ad events including `LOADED` and `STARTED`.

**Comment by alyona-mordas** [comment]
@Kiro705 
On the attached screenshot is an object, that appears on "ads-ad-started", it doesn't have any function or property to access and Ad class 


'ads-ad-started' , 'ads-manager' , 'ads-loader',  'ads-request' are the only events being fired 


<img width="829" alt="Screenshot 2022-06-14 at 17 54 33" src="https://user-images.githubusercontent.com/95859516/173622345-069684f8-fe81-453a-86eb-b4924ea460d2.png">

**Comment by Kiro705** [comment]
Hello @alyona-mordas ,

Sorry for the delay in replying. You will want to look into the IMA events for this feature.

See this section of the advanced example:
https://github.com/googleads/videojs-ima/blob/main/examples/advanced/ads.js#L104-L107

If you edit it with the following changes you will be able to access the [AdPodInfo](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdPodInfo) APIs:
```
Ads.prototype.onAdEvent = function(event) {
  var message = 'Ad event: ' + event.type;
  console.log(message);
  var type = event.type;
  switch(type) {
    case google.ima.AdEvent.Type.STARTED:
      let ad = event.getAd();
      let pod = ad.getAdPodInfo();
      break;
    default:
      break;
  }
};
```

**Comment by alyona-mordas** [comment]
hello and thanks for getting back to me :) 
 yes, we have it implemented just like that
