### ISSUE TITLE
adsManager.getRemainingTime return handled incorrectly 

### ISSUE THREAD

**Issue by alexey-zaharchenko** [googleads/videojs-ima#595]
Sometime label "Advertisement: -1:-2" appears, it seems because return of adsManager.getRemainingTime in SdkImpl.prototype.onAdPlayheadTrackerInterval is not correctly handled, there is no check for -1 that mean  "remaining time is undefined" via https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManager.getRemainingTime

**Comment by shawnbuso** [comment]
Do you have a tag that demonstrates this? I'm trying to determine why we're getting the bad value from the SDK - it looks like this could be related to #590

**Comment by alexey-zaharchenko** [comment]
Yep, I have tag, but I'm not sure that my company policy allows me publish it publicly.  My case DRM free. May we contact in some chat ?

**Comment by shawnbuso** [comment]
You can email ima-sdk-support@google.com - let them know you're working with me on the issue tracker here and they'll pass along the info.

**Comment by shawnbuso** [comment]
Sounds good, I'll follow up there :)

**Comment by dilburt** [comment]
I'm having this same or a very similar problem after upgrading to videojs.ima version 1.3.0. I've also tried 1.2.0 and 1.1.0 and have the same problem with all versions. The time will typically display -1:-1 and the timeline will be at the end (full). However the time value at the top-left of the videojs player is working correctly. I'm currently running with video.js 6.7.3, videojs.ads 6.2.1 and videojs.ima 1.3.0. I get the same results in all browsers so as far as can tell it's getting incorrect values from getRemainingTime() as above.

I had a copy of a 1.0.4 version dated 11-4-2017 and can confirm the time and timeline work correctly with that version (although there are other problems running that version with videojs 6.7.3 and/or videojs.ads 6.2.1). I noticed that 1.0.4 is no longer available online but I know this came from npm.

This problem can be reproduced 100% of the time in my environment so let me know if I can send you anything to help find this.

Thanks,

D

**Comment by shawnbuso** [comment]
If you could send me an ad tag I can use to reproduce this that would be great. Thanks!

**Comment by dilburt** [comment]
Hi Shawn,

Sure, I setup a couple of examples on one of our test servers for you:

videojs.ima 1.3.0 with the time/timeline problem: https://js.applixir.com/index2.html
videojs.ima 1.0.4 without the problem: https://js.applixir.com/index.html

Thanks,

Dean

**Comment by shawnbuso** [comment]
Hey there - I think you're running into the same issue that our user in #590 ran into. The plugin will now call requestAds for you - you don't have to call it yourself. If you do (and your implementation does), things get all kinds of screwy. I tested by commenting out your requestAds call (in your compiled code it's `d.ima.requestAds(p)`) and now the countdown timer is working. If you have any other issues let me know!

**Comment by dilburt** [comment]
Hi Shawn,

Thank you very much for figuring this out. One question though, requestAds took the adRequest parameters such as linear/non-linear slot sizes and such. There are methods for setAdWillAutoPlay and setAdWillPlayMuted but where do I specify the linear/non-linear slot sizes now?

Thanks,

D

**Comment by shawnbuso** [comment]
Hey @dilburt,

The linear width and height will always be set to the same size as the content player, because linear ads should cover the whole player. For non-linear ads, you can specify `nonLinearWidth` and `nonLinearHeight` in the plugin settings (the object passed to `player.ima()`).

Thanks!
Shawn
