### ISSUE TITLE
major revision question

### ISSUE THREAD

**Issue by mysuf** [googleads/videojs-ima#599]
Hi guys,
I would like to ask if my fork is usable for you (i.e. for future major revision).  I am thinking about next move which could be either contribution to your project or new repo and rewriting rest of videojs-ima related code. My fork is radical move from how videojs-ima works now, but I believe that pros prevail cons. Currently it supports only videojs v6, but adding v5 support shouldnt be a big problem. It also passes your vjs6 test. Of course, there is some work waiting to do yet.
Regards, PS.

**Comment by shawnbuso** [comment]
Hey there,

We appreciate the work you did - but I think we're going to stick with what we have for now. Your refactor looks a lot like what the plugin looked like [before the refactor](https://github.com/googleads/videojs-ima/blob/0.8.0/src/videojs.ima.js), and we didn't like that it was just one giant file - we wanted to make it use better OO principals. I agree that jumping from file to file isn't great, so we're looking into ways to make that better.

Thanks,
Shawn
