### ISSUE TITLE
After ad play can not to resume HLS at TV application

### ISSUE THREAD

**Issue by softgen** [googleads/videojs-ima#601]
Its working for desktop application but not working at TV application.

I debugged myself at desktop application where IMA creating an another VIDEO tag for ad playing in iframe, but at TV application IMA can not to create another VIDEO tag. Here IMA replacing parent VIDEO src and playing ad. After complete the ad IMA adding blob source URL. After that can not to resume the content.
And given error that your parent video source are removed. So how I will solve the problem?

This problem only for HLS file. MP4 is working fine.

**Comment by ypavlotsky** [comment]
Hi, what platform are you using the plugin on? It's possible that the platform doesn't support multiple video players but the IMA SDK and the plugin doesn't realize that.

**Comment by softgen** [comment]
@ypavlotsky I am using VIZIO and VEWD TV application. You are right that the platform doesn't support multiple video players. So please give some suggestion.

Now I am doing again reload the player after completing the ads and playing from last current time.

**Comment by ypavlotsky** [comment]
The SDK probably doesn't realize that the TVs only support one video player, and that's something that would have to be fixed on the IMA SDK side. I recommend posting to their [support forum](https://groups.google.com/forum/#!forum/ima-sdk).

**Comment by Sivitas** [comment]
I have what sounds like the same issue on our prod servers on a Vizio smart cast TV. But if I use our staging url, it does work. It's the same code and build. We've tested a multitude of ads including sources from spotx, aerserv, doubleclick, and freewheel and it's the same situation across the board, broken on prod but working in staging (and in both cases working in desktop browser)

Looking at the prod logs I see 2 extra warning/error lines that does not appear on staging.
![screen shot 2018-04-30 at 16 27 53](https://user-images.githubusercontent.com/4080198/39455067-791c6f72-4c93-11e8-844b-3617b04bb54a.png)

Hoping that this might give some insight on where the issue might be.

We are using:
videojs-ima 1.3.0
videojs-contrib-ads 6.1.0
videojs-contrib-hls: 5.14.1

**Comment by ypavlotsky** [comment]
We currently don't support smart TVs because the IMA SDK doesn't.

**Comment by ypavlotsky** [comment]
Closing this out.

**Comment by genelamarellis** [comment]
I know this issue is closed but I'm wondering who has a work around. Hey @softgen, do you mind sharing your code snippet for re-loading the player and listening for the ad to complete?

**Comment by Sivitas** [comment]
I figured out part of the issue on Vizio. When the ad starts, the player thinks it's a video, so the events it fires are both ad events and video events. Once the ad ends, it also thinks the video ended and that's the problem.

I tried all kinds of hacks to get to this conclusion and a working fix: when an ad starts, ignore all video events. When the ad end event triggers, call `player.src()` with the same video, call `player.play()` and start listening to video events again. Might have to call play after a small delay. 

Doing it this way, it resumes the video where it left off (for midrolls) and keeps later midroll ads in place as well

**Comment by genelamarellis** [comment]
Thank you!

**Comment by genelamarellis** [comment]
Do you have a small code snippet that you don't mind sharing? That would be very helpful. Thanks!

**Comment by Sivitas** [comment]
Here's a quick abstraction of what we're using

```javascript
var _currentAd

player.ima.addEventListener(google.ima.AdEvent.Type.STARTED, onAdStarted)
player.ima.addEventListener(google.ima.AdEvent.Type.COMPLETE, onAdComplete)

function onAdStarted (ev) {
  _currentAd = ev.getAd()
}
function onAdComplete () {
  if (options.forceReload) { // only if we decide it's needed
    var adPod = _currentAd.getAdPodInfo()
    var podInfo = {
      podPosition: adPod.getAdPosition(),
      podLength: adPod.getTotalAds()
    }
    _forceReload(podInfo)
  }
  _currentAd = null
}

function _forceReload (podInfo) {
  if (podInfo.podPosition < podInfo.podLength) { return }
  // _getSrc() returns something like { url: 'https://...', type: 'video/mp4' }
  player.src(_getSrc())
  setTimeout(function () { // might not be needed
    player.play()
  }, 200) // arbitrary
}
```

**Comment by aakashsingh-maz** [comment]
@Sivitas this solution works for all ads except google Linear Vpaid ads, any ideas on that ?
