### ISSUE TITLE
6 second (Bumper ads) are not playing

### ISSUE THREAD

**Issue by Jakuboslav** [googleads/videojs-ima#602]
Hello,
I am having issue with playing Bumper ads. 
Issue can be replicated in your sample player. ( https://googleads.github.io/videojs-ima/examples/advanced/ )
When I request 10second ad, everything works correctly. When I request 6 second ad, it simply doesn't play.
It seems to me, that this is similar issue: https://github.com/googleads/googleads-ima-android/issues/16 

Here is my ad tag:

https://adserver.adtech.de/?advideo/3.0/1045.1/0/0/-1/noperf=1;cc=2;header=yes;cookie=yes;adct=204;alias=video_Novaplus_superstar;key=id2132793+superstar%202018+serial+SuperStar%202018+superstar+ss;vidAS=mid_roll;vidbreaknum=7;vidbreaklen=120;cors=yes;acao=https://imasdk.googleapis.com;misc=1524816615861;vidnofmt=yes;vidRT=VAST_APVSCL;vidRTV=3.0

It returns both 6s and 10s ads but only 10sec ad will be played.

Thanks in advance.

**Comment by ypavlotsky** [comment]
I get an empty VAST when I try that tag out.

**Comment by Jakuboslav** [comment]
I apologize myself, it turned out, that is was some kind of our side issue.
