### ISSUE TITLE
How to let video width adaptive device width?

### ISSUE THREAD

**Issue by YzerZh** [googleads/videojs-ima#605]
First , I hope video width adaptive device width, up to 100%, but I do not know where the control width of the code, please explain,thank your!
Second, I played on a mobile device.  My mobile device is  Android 7.1. Several browsers do not respond to advertisements, but some browsers respond.

**Comment by shawnbuso** [comment]
The plugin should handle resizing ads automatically for you if you use video.js fluid - do you have a sample page where the resizing isn't working for you? If so I can take a look and try to debug.

For your second issue, can you give examples of devices and browsers where ads aren't working? Thanks!

**Comment by YzerZh** [comment]
Hi,  @shawnbuso 
Thank you so much for answering my inquiry  quickly.
But VIDEO.JS does not adapt to the width of the player, I can not find the code to set the width of the plug-in, It did not work after changing the width of the VIDEO tag as a percentage, and now my goal is to automatically width after the player is loaded.please help me. my test page is [http://ww.cloudz360.com/gad/vod/index.html](url)
Second,in Chinese 360 mobile browser Ads aren't working ,it Skip ad to start playing video ,my test page is 
In addition, when I set the player to center, the ad only shows half in PC Google Chrome  and all of Browser in Android ，I sent the Screenshots to you
![20180510100331](https://user-images.githubusercontent.com/25808322/39848618-8d85f8a8-543a-11e8-87dd-c1403d53aee2.jpg)
 ,the test page is [http://www.cloudz360.com/gad/vjsima/index.html](url),
Thank you so much!

**Comment by YzerZh** [comment]
Hi, @shawnbuso
Thank you so much for answering my inquiry quickly.
But VIDEO.JS does not adapt to the width of the player, I can not find the code to set the width of the plug-in, It did not work after changing the width of the VIDEO tag as a percentage, and now my goal is to automatically width after the player is loaded.please help me. my test page is http://www.cloudz360.com/gad/vod/index.html
Second,in Chinese 360 mobile browser Ads aren't working ,it Skip ad to start playing video ,my test page is
In addition, when I set the player to center, the ad only shows half in PC Google Chrome and all of Browser in Android ，I sent the Screenshots to you
![20180510100331](https://user-images.githubusercontent.com/25808322/39848984-b33d513e-543c-11e8-95a4-2884eeee389e.jpg)

,the test page is http://www.cloudz360.com/gad/vjsima/index.html
Thank you so much!

**Comment by shawnbuso** [comment]
Hi there,

For your first issue, have you tried setting vjs-fluid? You can read more about that [here](http://blog.videojs.com/post/130143694631/video-js-5/).

For your second issue, it sounds like you're using a browser that the IMA SDK does not support. You can see a list of supported browsers [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility#platforms).

Your third issue is a known issue with the IMA SDK when it's inside of <center> tags in specific scenarios. We're working on a solution for that.

Thanks,
Shawn

**Comment by YzerZh** [comment]
Hi Shawn,
I'm so sorry,I don't know about vjs-fluid. I didn't make any changes to your examples, including all of the following JS and CSS. I don't know which line of the CSS and JS  is controlling the width of VIDEO. I tried to change the Percentage  width of the VIDEO tag in INDEX.HTML but it didn't succeed.Could you tell me more about vjs-fluid or give me any examples.
And,If you successfully solve the third question above, cloud you inform me immediately?
Thank you very much!
Yzer

**Comment by shawnbuso** [comment]
You can append "vjs-fluid" to the class list of the player, like so:
```
<video id="content_video" class="video-js vjs-default-skin vjs-fluid"
        poster = "../posters/bbb_poster.jpg" controls preload="auto" width="640"
        height="360">
      <source src="//commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
          type="video/mp4" ></source>
    </video>
```

In my testing that makes the player take up the full window. I'll let you know when we fix the third issue mentioned above. Thanks!

**Comment by YzerZh** [comment]
Thank you for your answer patiently. At your prompt, I studied the **video-js.min.css** code carefully and successfully set the adaptive width. Thank you very much.

**Comment by shawnbuso** [comment]
Glad you got it working, thanks for the update!
