### ISSUE TITLE
Overlay issue with VMAP

### ISSUE THREAD

**Issue by alouane** [googleads/videojs-ima#607]
Hi @shawnbuso 
Is it normal that overlay ads disappear in a couple of seconds after impression when using vmap?
Here is the ad demo tag that I'm testing in video suite inspector:
https://s3-eu-west-1.amazonaws.com/vidsens-front/AdTags/Toyota_pre_mid_post_demo.xml

We have a full slot ad (preroll) + overlay (midroll) + full slot ad (postroll)
-The overlay disappears after a couple seconds of impression

Also, I noticed that the full slot ad does work only when `adsRequest.nonLinearAdSlotHeight = height;`
It's like if the full slot ad is considered as a non linear ad
When **nonLinearAdSlotHeight** equals the **window innerheight**, the overlay ad **(320x50)** takes all the player's height, which prevents the user from interacting with the player
When we set **nonLinearAdSlotHeight** = **80** to fix the overlay issue, the full slot ad doesn't work

Any help is appreciated

Thanks

**Comment by shawnbuso** [comment]
Hi there,

I'm trying to test your tag in our [hosted sample](http://googleads.github.io/videojs-ima/examples/advanced/) but I'm getting a CORS error. Do you have a sample tag that will work on that page, or a sample page where I can see the issue?

Thanks!
Shawn

**Comment by alouane** [comment]
Ok can you check this one:
https://front.vidsens.com/AdTags/Toyota_pre_mid_post_demo.xml

Thanks

**Comment by shawnbuso** [comment]
Yep, that worked! Normally you should be able to make the ad stick around by getting rid of the "minSuggestedDuration" in the VAST. However, it looks like there is a bug in the IMA SDK where that causes the ad to be cleared after 15 seconds. I've reported that to the team. Until then unfortunately I think the best you can do is display the ad for those 15 seconds.

**Comment by shawnbuso** [comment]
Hmm do you have a sample page where I can reproduce this?

**Comment by alouane** [comment]
Yeah sure, go ahead and use this tag :
https://s3-eu-west-1.amazonaws.com/vidsens-front/AdTags/Banner_demo.xml
if it doesn't work try this one: https://front.vidsens.com/AdTags/Banner_demo.xml

You ll notice that the overlay gets the full height, which prevents any click or interaction with the player
You have actually the same behavior in the demo page

![image](https://user-images.githubusercontent.com/3225153/39887349-eff30824-5489-11e8-8d61-516c1804b3c1.png)

Many thanks

**Comment by shawnbuso** [comment]
Ah ok, this is a known issue with the video.js plugin. We're looking into the best way to fix this.

**Comment by alouane** [comment]
Ok that's awesome, I ll keep track of these 2 issues

Thanks @shawnbuso for the support
