### ISSUE TITLE
ad pause events are not sent to videojs

### ISSUE THREAD

**Issue by KevinBrogan** [googleads/videojs-ima#612]
Pausing and resuming an ad emits no events.

Sending a pause or resume event to videojs while the admode is set should automatically be redispatched by the videojs-contrib-ads dependency as an adpause and adresume event. Instead no event is emitted, leaving users of the library unable to respond to ad pauses.

**Comment by shawnbuso** [comment]
Which events are you referring to? I only see `adstart`, `adend`, and `adkskip` in the [contrib-ads documentation](https://github.com/videojs/videojs-contrib-ads/blob/master/docs/integrator/api.md).

**Comment by shawnbuso** [comment]
It's been a while since we've heard from you, so I'm going to close this out. If you're still seeing issues, feel free to respond here and we'll re-open :)
