### ISSUE TITLE
DFP Video Units

### ISSUE THREAD

**Issue by kokoko420** [googleads/videojs-ima#618]
how do Integrate this plugin with wordpress or If this not possible then how can i use this plugin on my Wordpress site and most important  i am asking this question for DFP Videos units

**Comment by ypavlotsky** [comment]
Hi there,

I don't know if this works with WordPress or not. I assume if the video.js player works with something, this plugin will as well.

As far as DFP support, please contact them directly or look at their [support pages](https://support.google.com/dfp_premium/#topic=7505988)

**Comment by canhnm** [comment]
@kokoko420 The DFP adunit, it has to be Video Adunit, use Generate Tag on DFP UI to get the VAST URI, then DFP will deliver ads through this.

I am developing wp plugin to work with this kind of vast but it is not available public due to testing, if you are interest in pilot run pls message me!

**Comment by ypavlotsky** [comment]
Going to close this out. Feel free to re-open if there are issues.
