### ISSUE TITLE
Postroll plays when was triggered "Postroll abort (adtimeout)"

### ISSUE THREAD

**Issue by SergeyTretyak** [googleads/videojs-ima#620]
Hello.
I catch one bug and can't resolve it, I didn't found any information about something similar.

Postroll starts to play immediately after 'ended' event, while ima plugin does not trigger any ad event, and after "postrollTimeout" the plugin triggers: "VIDEOJS: ADS: Postroll abort (adtimeout)", "VIDEOJS: ADS: Postroll -> AdsDone".
In result player don't correct handle some buttons, and has wrong behaviour.

**Expected result:** 
Player should trigger 'adstart' and other ad events, and should has the same behaviour as 'preroll'

**Checked on:**
- Google Chrome 66
- Firefox 61.0b5 (64-bit)
- Google Chrome 66 on android

**Code example in the attached file**
[index.html.txt](https://github.com/googleads/videojs-ima/files/2017554/index.html.txt)

**Browser log:** 
video.min.js:1 VIDEOJS: ADS: Using cancelContentPlay to block content playback
18:37:07.039 video.min.js:1 VIDEOJS: ADS: Received adsready event (BeforePreroll)
18:37:08.750 video.min.js:1 VIDEOJS: ADS: Playback was canceled by cancelContentPlay
18:37:08.751 video.min.js:1 VIDEOJS: ADS: Received play event (BeforePreroll)
18:37:08.752 video.min.js:1 VIDEOJS: ADS: BeforePreroll -> Preroll
18:37:08.753 video.min.js:1 VIDEOJS: ADS: Triggered readyforpreroll event (Preroll)
18:37:09.039 video.min.js:1 VIDEOJS: ADS: Starting ad break
18:37:19.508 video.min.js:1 VIDEOJS: ADS: Ending ad break
18:37:19.523 video.min.js:1 VIDEOJS: ADS: Preroll -> ContentPlayback
18:37:23.124 video.min.js:1 VIDEOJS: ADS: ContentPlayback -> Midroll
18:37:23.127 video.min.js:1 VIDEOJS: ADS: Starting ad break
18:37:33.447 video.min.js:1 VIDEOJS: ADS: Ending ad break
18:37:33.460 video.min.js:1 VIDEOJS: ADS: Midroll -> ContentPlayback
18:37:54.016 video.min.js:1 VIDEOJS: ADS: Received readyforpostroll event
18:37:54.016 video.min.js:1 VIDEOJS: ADS: ContentPlayback -> Postroll
18:37:59.017 video.min.js:1 VIDEOJS: ADS: Postroll abort (adtimeout)
18:37:59.019 video.min.js:1 VIDEOJS: ADS: Postroll -> AdsDone

**Version of components:**
video.js 6.6.0
videojs-contrib-ads 6.3.0
videojs-contrib-hls 5.12.2
videojs-ima 1.3.0

**Comment by shawnbuso** [comment]
For some reason our code was explicitly skipping the call to startLinearAdMode for post-rolls. I think there was a bug around that in a (very) old version of contrib-ads, because it's been in there since the beginning. Unfortunately I didn't comment why we were skipping it. I removed that condition and did some tests, and it looks to be behaving fine, so I think whatever issue we were running into ~4 years ago has been fixed.
