### ISSUE TITLE
Do we really need to have an id attribute in the options??

### ISSUE THREAD

**Issue by DoomTay** [googleads/videojs-ima#621]
Digging through the source code I found that these lines "force" you to 

https://github.com/googleads/videojs-ima/blob/2e8dd8f9d08664ed1ae159d7f7eb4ec3b7aaa9de/src/controller.js#L99-L105

Accidentally setting the id wrong exposed one place where it is used

https://github.com/googleads/videojs-ima/blob/d1eb372734253bad216f6afdca933110b50ab71f/src/player-wrapper.js#L269

which could simply be changed to `this.vjsPlayer.id_).getElementsByClassName( `.

Ditto for these lines

https://github.com/googleads/videojs-ima/blob/2e8dd8f9d08664ed1ae159d7f7eb4ec3b7aaa9de/src/ad-ui.js#L108-L109

**Comment by ypavlotsky** [comment]
Hey, thanks for pointing out that inconsistent comment. As for using vjsPlayer.id_, it's a private variable that we currently have access to, but we're leery of relying on that since it could go away in the future as its not part of the videojs API.

**Comment by DoomTay** [comment]
`this.vjsPlayer.id()`, then. The method is referenced in [the docs](http://docs.videojs.com/docs/api/component.html#Methodsid) so I assume it would be "legal" to get the id that way.

**Comment by DoomTay** [comment]
Shouldn't the readme be updated to reflect this change?

**Comment by gschoppe** [comment]
Docs update has now been merged.
