### ISSUE TITLE
How Can I use the playAdBreak play many times ads?

### ISSUE THREAD

**Issue by danny1lee** [googleads/videojs-ima#622]
Hi,
I wan to call the ad url many times in a movie.
In the sample, I can only succeed for the first time.
http://html5.dandan.idv.tw:7070/ads/advanced/

After the second time, the screen will lock, can't play the video control bar.
And I don't know how to call the setAdBreakReadyListener function,
it always not a funvtion.
Could you give me any advices, Thanks for your help.

**Comment by ypavlotsky** [comment]
Hi,

Setting `autoPlayAdBreaks` to `false` is designed to let you control the timing of playing ad breaks, not to play the same ad multiple times. The way you would do manual ad breaks is register an ad break ready listener in `setAdBreakReadyListener` and then you know that once the callback is called, your ad can be played. Trying to play the ad before the ad break is ready is not supported.

If you want to play an ad multiple times, either set up your ad playlist or VMAP to include multiple ads, or make another ad request.

**Comment by danny1lee** [comment]
Thank for you help!
But the player.ima(options) , support a string array of adTagUrl?
like this,
```
var options = {
  id: 'content_video',
  autoPlayAdBreaks : false,
  adTagUrl: {'A_url','B_url'}
};
```
Thanks!

**Comment by danny1lee** [comment]
Thanks, Could you tell me how to make multiple ad request?
I register two player, but the second one has some error.

`
var player = videojs('content_video');

var options = {
  id: 'content_video',
  autoPlayAdBreaks : false,
  adTagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='
};

player.ima(options);

var contentPlayer =  document.getElementById('content_video_html5_api');
if ((navigator.userAgent.match(/iPad/i) ||
      navigator.userAgent.match(/Android/i)) &&
    contentPlayer.hasAttribute('controls')) {
  contentPlayer.removeAttribute('controls');
}

var startEvent = 'click';
if (navigator.userAgent.match(/iPhone/i) ||
    navigator.userAgent.match(/iPad/i) ||
    navigator.userAgent.match(/Android/i)) {
  startEvent = 'touchend';
}
player.one(startEvent, function() {
    player.ima.initializeAdDisplayContainer();
});

 player.on('play', function(){
	console.log('play');
	this.ima.playAdBreak();
  });
   
var player2 = videojs('content_video');
player2.ima(options);

player2.one(startEvent, function() {
    player2.ima.initializeAdDisplayContainer();
});

 player2.on('ended', function(){
	console.log('ended');
						this.ima.playAdBreak();
  });
`
I appreciate all you do. Thanks!

**Comment by ypavlotsky** [comment]
The normal way to request multiple ads would be to use a VMAP. Barring that, what sort of error do you get on the second player?
