### ISSUE TITLE
video interactions killed by overlay ads. 

### ISSUE THREAD

**Issue by Snowbell92** [googleads/videojs-ima#626]
duplicate of #427 , but I don't think that got solved.

My ad is a simple image overlay (300 x 60), visible through the entire playback. The problem is that the iframe covers the entire video playback area (I can see that on devtools), so I can't interact with the video at all (clicking on the video has no effect now, doesn't pause the video). 

what should I do? Manually resizing doesn't seem to be a very good solution to me - may mess with ad rendering or mess up responsiveness.

**Comment by shawnbuso** [comment]
Do you have a sample tag I can use to reproduce your issue? Thanks!

**Comment by Snowbell92** [comment]
Middle of the night here, I'm going to make a demo page for you in the morning. :)

**Comment by shawnbuso** [comment]
Ok cool, thanks :) If it's easier you can just drop your tag into our [sample player](http://googleads.github.io/videojs-ima/examples/advanced/) - if you can repro there then you just need to give us the tag, not a whole demo page.

**Comment by Snowbell92** [comment]
here's the ad tag (produces the same problem in the advanced sample player too) 

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/251998432/CustomVideoAdsUnit&ciu_szs=640x480&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]`

here's my codepen [https://codepen.io/samia92/details/aGeGNQ/](codepen) too, the exact (almost, plugin have been commented out) code I have. Expected behavior - first load should show the pre-roll ad and normal playback, if you refresh- the pre-roll goes away and the image ad shows up and stays visible throughout the entire playback. 

Thanks in advance.

**Comment by shawnbuso** [comment]
Hmm, I'm getting an error for that tag and sample page - "AdError 1009: The response does not contain any valid ads." Is it still working for you? If so, is your serving maybe region-locked?

**Comment by Snowbell92** [comment]
hi, sorry yes it was region blocked. I didn't notice. Here's the updated one: 

`https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/251998432/CustomVideoAdsUnit&ciu_szs=640x480&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]`

**Comment by shawnbuso** [comment]
Thanks - when I load that tag I am still able to access the controls, it's just that clicking on the video itself doesn't have an effect. I can still click on play/pause, seek, etc. Unfortunately I think the best solution is to try to resize our ad container to be the exact size of the ad, but that can get super hairy very quickly. Since the controls are still working, I can leave this open as an FR, but it will be lower priority since we have a workaround.

**Comment by Snowbell92** [comment]
@shawnbuso I finally had some time to go through all the code and (kinda) worked out a solution. I have only ever faced this problem if the ad is non-linear and turns out, there's an `onLoad` event already for a non-linear ad on line 924. So I added a class to it and then resized the container to 90px, the max allowed height for overlay ads in Adsense for video. 

_in videojs.ima.js_: 

    AdUi.prototype.onNonLinearAdLoad = function () {
      // add this class to resize the parent div to max
      // allowed size. 90px in adsense.  
        this.addClass(this.adContainerDiv,'aspect-mode');
    
      // For non-linear ads that show after a linear ad. For linear ads, we show the
      // ad container in onAdBreakStart to prevent blinking in pods.
       this.adContainerDiv.style.display = 'block';
    
       // Bump container when controls are shown
       this.addClass(this.adContainerDiv, 'bumpable-ima-ad-container');
     };

_and in my own stylesheet:_ 

       .ima-ad-container.aspect-mode{
            top: 80%;
            overflow: hidden;
            height: 90px;
        }
        .ima-ad-container.aspect-mode > div [style]{
            height: 90px !important;
        }

I'd still love a solution without those 'magic numbers" though. If you have any better ideas on how to solve this, point me towards it and I'll try it.

**Comment by Kiro705** [comment]
Image of the bug here https://github.com/googleads/videojs-ima/issues/607#issuecomment-388146378

**Comment by dioramayuanito** [comment]
I use https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator= as an adRules for videojs-ima v1.9.1 , but player interaction is still stuck

**Comment by dioramayuanito** [comment]
> I use https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator= as an adRules for videojs-ima v1.9.1 , but player interaction is still stuck

ok i got the problem now @Kiro705 i think that we never use AdUi.prototype.onAdContainerClick in videojs-ima v1.9.1. we should use it in AdUi.prototype.createAdContainer :

/**
 * Creates the ad container.
 */
AdUi.prototype.createAdContainer = function () {
  this.assignControlAttributes(this.adContainerDiv, 'ima-ad-container');
  this.adContainerDiv.style.position = 'absolute';
  this.adContainerDiv.style.zIndex = 1111;
  this.adContainerDiv.addEventListener('mouseenter', this.showAdControls.bind(this), false);
  this.adContainerDiv.addEventListener('mouseleave', this.hideAdControls.bind(this), false);
  this.adContainerDiv.addEventListener('click', this.onAdContainerClick.bind(this), false);
  this.createControls();
  this.controller.injectAdContainerDiv(this.adContainerDiv);
};
