### ISSUE TITLE
Autoplay HLS Live VideoJS 7

### ISSUE THREAD

**Issue by tedtucker** [googleads/videojs-ima#629]
I am trying to get Google IMA Pre-roll or any ads to work with my live HLS feed... The ad triggers but then the video doesn't autoplay. Console doesn't show any errors.

https://codepen.io/terrafox/pen/27fc73aba1c2823370f1c84c872e8965/

**Comment by tedtucker** [comment]
If I git play... the video plays... but it doesn't autoplay... what am I missing?

**Comment by ypavlotsky** [comment]
Are you sure that your videojs player is set up to play HLS content? What happens if you try to play your stream without ads?

**Comment by tedtucker** [comment]
Yes. And like I said, just hit play and it plays, it just doesn't autoplay after the ad.

**Comment by tedtucker** [comment]
Delete lines 16,17 and 18 in codepen (link above) to remove the videojs-ima scripts. Then the video plays just fine.

**Comment by shawnbuso** [comment]
I did a bunch of digging on this one, and ultimately it comes down to some logic in contrib-ads. Our plugin assumes that `endLinearAdMode` will ultimately result in a call to `play()` on the player. The contrib-ads implementation assumes that live streams continue to play in the background during ad breaks, and as such, don't call play on the content player in `endLinearAdMode`.

In `adBreak.end()`:
```
if (!player.ads.shouldPlayContentBehindAd(player)) {
    snapshot.restorePlayerSnapshot(player, player.ads.snapshot);
}
```

and in `plugin.js`:
```
shouldPlayContentBehindAd(somePlayer) {
      return !videojs.browser.IS_IOS &&
             !videojs.browser.IS_ANDROID &&
             somePlayer.duration() === Infinity; // Here's the issue - if the content is live, assume it kept playing during the ad break
    },
```
So when we call `endLinearAdMode()` after the pre-roll, we expect that to result in a call to play() on the video player, and it doesn't.

@incompl, any tips on how to handle this?

**Comment by incompl** [comment]
The live video support in contrib-ads is designed for ID3 cuepoints. Support for prerolls before live videos would need to be carefully planned and built from scratch. It's on the list of things we'd like to do, but for now, I wouldn't expect it to work.

**Comment by shawnbuso** [comment]
@incompl will I confuse contrib-ads if I call `play()` on the vjs player from within my plugin? In the short term we could add a new option to videojs-ima, `isLiveStream` or something like that, which will call `play()` on the vjs player when the pre-roll ends. I could call it after `endLinearAdMode()`, so hopefully it won't mess with contrib-ads.

**Comment by incompl** [comment]
I think what I'd like to do in contrib-ads is have the current behavior (live ads on metadata cuepoints while live stream plays muted behind ads) be an option, and have the default behavior be useful for prerolls before live streams, since that seems to be what most people want. Does that make sense?

**Comment by tedtucker** [comment]
That is exactly what I am trying to achieve.. Preroll before the livestream..

**Comment by mysuf** [comment]
My two cents: calling `play()` after `endLinearAdMode()` (and `pause()` before `startLinearAdMode()`) does not break anything (atleast I never saw any issue yet). I use it just for sure and because both methods are Promise-based so multiple calls should be safe..

**Comment by mrtucker** [comment]
Did this issue every get any attention?

**Comment by incompl** [comment]
@mrtucker videojs-contrib-ads 6.5.0 introduced the `liveCuePoints` feature to address this scenario. I'm not sure if videojs-ima has been updated to use it or how much updating would be needed.

Docs: http://videojs.github.io/videojs-contrib-ads/integrator/options.html

**Comment by deeperid** [comment]
@ypavlotsky @shawnbuso Are there any updates re incompl's last comment?  I'm currently running into this very issue & would love a solution!  Thank you in advance!

**Comment by Kiro705** [comment]
Hi @deeperid,

I'm taking a look into this issue. Did you ever find a solution to your issue?
