### ISSUE TITLE
SdkImpl.initAdObjects invoked before PlayerWrapper.onPlayerReady causes "skippablevideo is not supported" error on mobile

### ISSUE THREAD

**Issue by gawhyte** [googleads/videojs-ima#633]
I'm running into an issue on mobile: the dreaded `AdError 1005: The provided ad type: skippablevideo is not supported`

I found this very helpful: https://groups.google.com/forum/#!msg/ima-sdk/jYE6j4_YCko/m6HuIkM9uKMJ, except it wasn't working... Looking at code I thought `opt_videoElement` was being provided to `google.ima.AdDisplayContainer(containerElement, opt_videoElement)` in `SdkImpl.initAdObjects`. However, it turned out `controller.getContentPlayer()` was returning `null` because `PlayerWrapper` hadn't yet set its value so I was still getting the 1005 error.

I was able to solve this for myself by moving the `initAdObjects` call out of `SdkImpl`s constructor and into `PlayerWrapper.onPlayerReady` handler.

My question is: am I doing something wrong, or is this a valid fix? I can submit my patch if it is.

**Comment by ypavlotsky** [comment]
Could you provide an ad tag where you were seeing the error? Also, what mobile platforms where you getting the error on?

**Comment by gawhyte** [comment]
Sure! The tag that was creating the problem for me: [https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/8749/Omniti&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]](foo)

I was able to recreate the issue on both Safari (iOS) and Chrome (Mac with dev tools' device/mobile view). 

(Changes that fixed the issue for me: https://github.com/gawhyte/videojs-ima/commit/b182fc1aed438d08f7777d242c436fff5731ac1e)

**Comment by ypavlotsky** [comment]
I'm still seeing the issue (even with the changes) in the [Advanced Example](https://googleads.github.io/videojs-ima/examples/advanced/) and getting the skippable error.

**Comment by gawhyte** [comment]
I believe you'll also need to set `disableCustomPlaybackForIOS10Plus: true` in the IMA configuration options. (and possibly set `playsinline` on the video element too)

**Comment by gawhyte** [comment]
PR is submitted!
