### ISSUE TITLE
Feature: please provide a SCSS source file

### ISSUE THREAD

**Issue by axten** [googleads/videojs-ima#636]
Because of node-sass dropping support for importing css files, it would be great to have an scss source file to include.

see https://github.com/sass/node-sass/issues/2362

**Comment by shawnbuso** [comment]
I'm not super familiar with SCSS, but it looks like it supports CSS - if I just made a copy of videojs.ima.css and named it videojs.ima.scss, would that work?

**Comment by axten** [comment]
yes this would work, because sass is a superset of css.

**Comment by shawnbuso** [comment]
We don't have a set schedule - I can cut one once the 2 most recent PRs in the open PR list have been merged.
