### ISSUE TITLE
Are the video ads streaming load or downloading the video and then playing

### ISSUE THREAD

**Issue by dshaw002** [googleads/videojs-ima#64]
We have implemented the video ad on our site, but we wanted to make sure that it loads the video ad in a streaming fashion and not as a full video download.

Thanks.

**Comment by tensafefrogs** [comment]
The SDK doesn't control when the ad starts. That depends on how the video is transcoded. If the ad comes from an ad network, they will likely be encoded so they start before downloading completely.

If you see ads that are not starting until the download is complete, you should contact the ad network that serves them and report the issue to them.
