### ISSUE TITLE
Problem with click on mobile

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#642]
Hi all, 
I noticed that there is a problem with click on video player..
When I click on video player, there isn't a redirect on vast click url but activates the audio on player..
If I do another click, the player goings stop..
What's the problem???
If you want a test page: https://www.4wmarketplace.com/demo/formato-video-4wtv/
Thanks to all,

A.

**Comment by shawnbuso** [comment]
Hi - on mobile you should see a "Learn more" link in the top right of the video. You can tap that to go to the clickthrough page. Tapping the ad outside of that area should pause or resume it.

**Comment by ibraalek10** [comment]
Hi @shawnbuso ,
thanks for the answer..
There is a workaround for making the entire area tappable??? 
Thanks a lot,

A.

**Comment by shawnbuso** [comment]
Not currently - this is a standard UI enforced by the IMA SDK for all video players that implement it.

**Comment by ibraalek10** [comment]
Ok @shawnbuso ,
thanks a lot for your answer..

A.
