### ISSUE TITLE
onAdError does not reset adsActive and adsPlaying

### ISSUE THREAD

**Issue by grobolom** [googleads/videojs-ima#645]
https://github.com/googleads/videojs-ima/blob/822257093b27d34a8c8564891074f278844016cf/src/sdk-impl.js#L356

Hey all!

Our team found a minor issue in the code that leads to inconsistent state - the `onAdError` method in the `sdkImpl` does not reset the state of the `adsActive` and `adsPlaying` settings, so anything tracking the ad state based on these values doesn't update this. The fix would be to add
```
this.adsActive = false;
this.adsPlaying = false;
```
to the method linked above.

Is this reasonable? I don't see how it would have any cascading effects, and modifying this code locally seems to work just fine. Please let me know if I am misunderstanding the code's intention.

I've opened a PR here: https://github.com/googleads/videojs-ima/pull/646 with the relevant changes.

**Comment by ypavlotsky** [comment]
Seems reasonable to me!

**Comment by ypavlotsky** [comment]
Fixed by #646
