### ISSUE TITLE
Requesting ads concurrently 

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#650]
I have vast waterfalls of 10-20 tags. These can take quite some time to load, especially on slow devices or bad internet connection. Is there any way to call tags concurrently?

**Comment by ypavlotsky** [comment]
No, there's no functionality to do this in videojs-ima.

**Comment by Slind14** [comment]
If I would implement this my self, could I sent vast xml directly to videojs-ima?

**Comment by ypavlotsky** [comment]
You can request ads using XML instead of a tag URL by setting `adsResponse` instead of `adTagUrl` in the options.

**Comment by Slind14** [comment]
ahh, thank you. What format does it expect? Stringified xml?

**Comment by ypavlotsky** [comment]
Yep. Should be either a VAST, VMAP or ad rules response in a string.

**Comment by Slind14** [comment]
Top, thank you.
