### ISSUE TITLE
Post roll console error on iOS Safari

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#651]
After upgrading to 1.5.1 after postroll i get the below on iOS Safari, it just appears after post-roll.

IMA 1.5.1
Contrib-ads: 6.4.1
Player: 6.7.3

VIDEOJS: – "ERROR:" – "(CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED)" – "No compatible source was found for this media."
st

code: 4

message: "No compatible source was found for this media."

st Prototype

MEDIA_ERR_ABORTED: 1

MEDIA_ERR_CUSTOM: 0

MEDIA_ERR_DECODE: 3

MEDIA_ERR_ENCRYPTED: 5

MEDIA_ERR_NETWORK: 2

MEDIA_ERR_SRC_NOT_SUPPORTED: 4

code: 0

constructor: function(t)

MEDIA_ERR_ABORTED: 1

MEDIA_ERR_CUSTOM: 0

MEDIA_ERR_DECODE: 3

MEDIA_ERR_ENCRYPTED: 5

MEDIA_ERR_NETWORK: 2

MEDIA_ERR_SRC_NOT_SUPPORTED: 4

arguments: null

caller: null

defaultMessages: {1: "You aborted the media playback", 2: "A network error caused the media download to fail part-way.", 3: "The media playback was aborted due to a corruption…media used features your browser did not support.", 4: "The media could not be loaded, either because the …rk failed or because the format is not supported.", 5: "The media is encrypted and we do not have the keys to decrypt it."}

errorTypes: ["MEDIA_ERR_CUSTOM", "MEDIA_ERR_ABORTED", "MEDIA_ERR_NETWORK", "MEDIA_ERR_DECODE", "MEDIA_ERR_SRC_NOT_SUPPORTED", "MEDIA_ERR_ENCRYPTED"] (6)

length: 1

name: "st"

prototype: st {code: 0, message: "", status: null, MEDIA_ERR_CUSTOM: 0, MEDIA_ERR_ABORTED: 1, …}

Function Prototype

message: ""

status: null

Object Prototype
Je — video.min.js:1377
error — video.min.js:1410
error — video.min.js:5764:243
(anonymous function) — video.min.js:5713
r — video.min.js:1527

Regards,

**Comment by ypavlotsky** [comment]
I'm not seeing this error after a post-roll in the hosted Advanced Example on iOS. How do you reproduce the error?

**Comment by ypavlotsky** [comment]
Hi, I'm seeing this error in your page, but it's a [video.js player error](https://github.com/videojs/video.js/blob/master/src/js/media-error.js#L88), not one we fire. Is there anything your postroll is doing that's specific to it or not standard? I'm not sure what's actually triggering this error. If you want to try your ad tag in our [advanced example](http://googleads.github.io/videojs-ima/examples/advanced/) and see if it works there, it might be a player implementation issue.

**Comment by Kiro705** [comment]
Hi @sdahdaah,

It looks like this issue may have been resolved. Please feel free to reopen it if that is not the case.
