### ISSUE TITLE
Submitting AdsRequest Object

### ISSUE THREAD

**Issue by dilburt** [googleads/videojs-ima#653]
Hi,

I understand that the latest versions of videojs-ima don't require a call to ima.requestAds and that doing so will cause problems. However, I cannot find anything in the API docs or in your sample code that shows how to submit the AdsRequest object. There are 2 methods associated with AdsRequest -  setAdWillAutoPlay and setAdWillPlayMuted along with a number of option fields which includes the ad sizes, keywords, duration and several others. Since these were previously passed as the first parameter to requestAds which you are calling internally now, how do we include the AdsRequest object?

Thanks,

D

**Comment by shawnbuso** [comment]
Can you clarify what you mean by "these were previously passed as the first parameter to requestAds"? The requestAds method, as far as I can tell, has never taken any parameters - it was just a call to tell the plugin to send the ads request it had created to the ad server.

I do see that there are properties of the [AdsRequest](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRequest) object that are missing from IMA settings, but I don't think we ever had a way to provide these to the plugin. I can take this as an FR to allow you to pass a JSON object in the settings that contains your AdsRequest properties.

**Comment by dilburt** [comment]
Thanks, that's perfect!
