### ISSUE TITLE
In Iphone autoplay is not working

### ISSUE THREAD

**Issue by sudhakarsukumar** [googleads/videojs-ima#655]
we are using the contrib-hls, google ima we needed to autoplay on scroll in view but it works well and good in chrome and android but not in iphone and safari browser. could you please help with it. thanks

**Comment by shawnbuso** [comment]
I believe this is an iPhone limitation - iPhone requires a user interaction on the video element to start a video player with audio, and scrolling the page is not considered a user interaction. Do you have an example of someone else's page where this is working as you want yours to work?

**Comment by shawnbuso** [comment]
It's been a while since we've heard from you, so I'm going to close this out. If you still need help feel free to let us know :)
