### ISSUE TITLE
Plugin won't work with require.js

### ISSUE THREAD

**Issue by DoomTay** [googleads/videojs-ima#659]
The page will attempt to load %PATH%/video.js, which will fail, and the console will give the error `Script error for "video.js", needed by: ima`.

Even if a script was successfully retrieved, the console will instead give the error `player.ima is not a function`.

Thankfully, the fix appears to be simple; references to `require('video.js')` and `define(['video.js'], factory) ` need to be changed to `videojs`.

[Here](https://github.com/googleads/videojs-ima/files/2104122/test.zip) is a minimal test case and the result of the above fix

**Comment by shawnbuso** [comment]
Thanks for the thorough debugging info - I'll try out this change and make sure it doesn't affect our non-require.js set-ups.

**Comment by DoomTay** [comment]
According to https://github.com/videojs/videojs-contrib-ads/issues/399#issuecomment-404296354 the actual fix might involve something completely different

**Comment by Kiro705** [comment]
Hi @DoomTay, was this issue resolved through videojs-contrib-ads or is it something that still requires attention for the videojs-ima team?

I'm going to close this issue but please reopen if it is something we can work on.
