### ISSUE TITLE
Skipping to 2nd playlist item after ad completes

### ISSUE THREAD

**Issue by genelamarellis** [googleads/videojs-ima#665]
This is a strange one. The pre-roll advertisement completes successfully, but instead of playing the first playlist video, it jumps to the second one. When I do not play an ad, it plays the first playlist video. So it seems that something is going on when control is being handed back to the video player from the advertisement. Any ideas?

**Comment by ypavlotsky** [comment]
Do you have a tag to reproduce this? Have you tried putting it in the [playlist example](http://googleads.github.io/videojs-ima/examples/playlist/)?

**Comment by ypavlotsky** [comment]
That does sound strange. I'm guessing you don't see that when you try the same page on desktop? What happens if you remove the second video and try to play the preroll? Does it play the first content video after the ad then?

**Comment by Kiro705** [comment]
It looks have though this issue may have been resolved. If not, feel free to reopen the issue and I can take another look.
