### ISSUE TITLE
Videojs Ima ads Events

### ISSUE THREAD

**Issue by adnanmokhtar** [googleads/videojs-ima#667]
i want to listen if ads get error. How to do that?

i using this code but it is not working.

player.ima(options, function () {
        player.ima.addEventListener(google.ima.AdEvent.Type.STARTED, function () {
            player.removeClass('vjs-ad-loading');
            console.log('sssssssssssssssssssssss')
        });
        player.ima.addEventListener(google.ima.AdEvent.Type.LOADED, function () {
            console.log('sssssssssssssssssssssss')
        });

        player.ima.addEventListener(google.ima.AdErrorEvent.Type.AD_ERROR, function () {
            console.log('sssssssssssssssssssssss')

        });

        player.ima.addEventListener(google.ima.AdEvent.Type.COMPLETE, function () {
            console.log('sssssssssssssssssssssss')
        });
        player.ima.startFromReadyCallback();
    });

**Comment by ypavlotsky** [comment]
Hi,

The plugin doesn't accept the `adsManagerLoadedCallback` as  parameter to the plugin. You have to add your event listeners in the way done in the [Advanced Example](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js#L77). To get the ad errors, you need to listen to the video.js player's `adserror` event:

`player.on("adserror", function(event) { ... } );`
