### ISSUE TITLE
Video JS  HLS IMA ads not playing in iphone 

### ISSUE THREAD

**Issue by sudhakarsukumar** [googleads/videojs-ima#670]
Ads not playing in iphone in particular. Please help us to overcome this issue

**Comment by shawnbuso** [comment]
Do you have a sample page I can use to reproduce this issue? Thanks!

**Comment by canhnm** [comment]
It works here with video.js 5.20.4, video.js IMA 1.2.1, video.js HLS 5.14.1

**Comment by shawnbuso** [comment]
We haven't heard from you in a while so I'm going to close this out - if you still need anything let us know!
