### ISSUE TITLE
Ads not playing in iphone in particular.

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#674]
Ads not playing in iphone in particular. Please help us to overcome this issue. the sample page is http://106.51.1.175/mmp_new/

**Comment by ypavlotsky** [comment]
Hi, I'm seeing a `Ad error: AdError 1005: The provided ad type: skippablevideo is not supported.
Je — ex8.min.js:1:30577` error on your page. This is probably because you're trying to play a skippable video and haven't set `setDisableCustomPlaybackForIOS10Plus` in your plugin settings and/or haven't set `playsinline` to `true` on your video tag.

**Comment by Kumaran29** [comment]
Hi @ypavlotsky ,
                           Thanks for your reply. Even after including the playsinline and muted attribute, the ads not playing as expected. Could you please refer this sample page http://106.51.1.175/mmp_new/ and help us
Also could you please help us to set the setDisableCustomPlaybackForIOS10Plus in our plugin (VideoJs with GoogleIMA, with HLS).

Cheers,
Kumaran

**Comment by ypavlotsky** [comment]
Here's an example of how to set `disableCustomPlaybackForIOS10Plus` in the plugin's options:

```
var player = videojs('content_video');

var options = {
  id: 'content_video',
  adTagUrl: 'YOUR_AD_TAG'
  disableCustomPlaybackForIOS10Plus: true
};

player.ima(options);
```

Hope that solves your issue!

**Comment by Kumaran29** [comment]
This works. Thanks a lot @ypavlotsky .

**Comment by ypavlotsky** [comment]
Great! Closing this out.

**Comment by Jakuboslav** [comment]
Hello, 
I  have exactly the same issue, but unfotunatelly I was not able fix it. I have both playsinline and disableCustomPlaybackForIOS10Plus as you can see in the screenshot. 

![screenshot](https://user-images.githubusercontent.com/38281059/43645071-1d2c96fe-9731-11e8-8985-0b3c0b868888.jpg)

disableCustomPlaybackForIOS10Plus is added in the way you mentioned.

Is there any another possible causes of this behaviour? I would be grateful, even if there is any possible walkaround for this issue.

Thanks in advance.

**Comment by yashraj-02** [comment]
@Jakuboslav were you able to figure out a reason for this?

**Comment by dioramayuanito** [comment]
somehow, in my experience ima.js will throw this error if :
1. fail to get the duration of video ad. Duration == 0 sec.
2. skip offset value is greater than video ad duration.
3. complicated process of vpaid is occur.

**Comment by yashraj-02** [comment]
Got it. Thanks man
