### ISSUE TITLE
Infinite scroll - autoplay issue and Fullscreen issue

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#675]
1. In the following link the video is implemented to autoplay play in viewport. When we scroll down the next page loads on downwards scroll (infinite scroll) . When we scroll down to the next page (after unmute the video from the first page)new player loads however the audio from the previous video continuous to play in the background. 

http://programmatic.private.wittyfeed.com/relationship-advice-for-newly-weds-66628

2. Also, when we scroll back to the previous video, there's an entirely new video in display with the previous audio still playing in the background

3. The video pauses whenever a full screen event is triggered.

**Comment by shawnbuso** [comment]
I took a look at your page but after scrolling all the way to the bottom I only see one video.js player - has it changed since you initially filed this?

**Comment by Kumaran29** [comment]
Sorry for the delay in response. It did change, we will implement in a different page and will post it in few days. Thanks for your help

**Comment by shawnbuso** [comment]
It's been a while since we've heard from you, so I'm going to close this - if you still need help feel free to respond and we'll re-open it. Thanks!
