### ISSUE TITLE
AdX Youtube Ad Support

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#676]
Hi there,
I noticed that when using this implementation, there aren't any youtube (skippable) ads being played. I'm using the same tag on different players and with videojs-ima there is never any youtube like ad. Is this not supported?

**Comment by ypavlotsky** [comment]
Hi,

The plugin, being based on the IMA SDK, should support AdX ads. For AdX specific questions, please refer to the [DFP support forum](https://productforums.google.com/forum/#!forum/dfp).
