### ISSUE TITLE
Self Hosted VMAP files

### ISSUE THREAD

**Issue by samueleastdev** [googleads/videojs-ima#677]
Hi @shawnbuso 

I am trying to manually create a vmap xml file and host it myself on AWS and I can't seem to get it to work.

Here is my xml file: https://s3.amazonaws.com/videojs-vmap-tests/vmap.xml

I have just taken the ads from the example file here: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=

I am obviously just doing this to test I was hoping to be able to change the timeOffset value in the xml to get a better understanding of how it works.

When I run a test here: https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

I get the error: 
~~~
Ad error: AdError 1009: The response does not contain any valid ads.
~~~

Not sure what I am doing wrong or if this cant be done ideally I would like to manually generate a vmap file with my vast urls from Google DFP so I can ad custom midroll times etc.

Would appreciate any help with this 

Thanks

**Comment by shawnbuso** [comment]
It looks like you just need to change your `<AdTagURI ...` and `</AdTagURI>` tags to `<vmap:AdTagURI ...` and `</vmap:AdTagURI>`. You can use our [sample VMAP tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=) as a reference if you run into any further issues. Let me know if that works!

**Comment by jnthnclrk** [comment]
Hi, I'm also getting:

`AdsLoader error: AdError 1009: The response does not contain any valid ads.`

But we're already using vmap:AdTagURI in our VMAP: https://cdn.famefocus.com/vmap.xml

Any other thoughts on this error?

**Comment by shawnbuso** [comment]
Yep, that would be the issue - you can see the list of things that are not yet supported [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).

**Comment by samueleastdev** [comment]
thanks @shawnbuso that was indeed the issue :smile:

**Comment by genelamarellis** [comment]
Hey @samueleastdev. I'm trying to do the exact same thing. Trying to create custom mid-roll times based on the VAST url. Not clear on how to affect the timeoffset of the VAMP tag from the VAST url. Any guidance you can offer would you much appreciated! Thanks!
