### ISSUE TITLE
Error logging tracking responsible vast tag (VMAP)

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#678]
Hi there,
I'm getting a lot of missed opportunities due to errors which are not handled in a clean way which would allow the next ad to run. Hence I would like to implement some error logging which gives insight on the quality of tags. Unfortunately I couldn't find a way to get the responsible vast tag when an error occurs. I'm using vmap, so there are multiple. Is there any way and if not could one be added or is it all closed ima sdk?

**Comment by shawnbuso** [comment]
The IMA SDK doesn't expose the VAST tags inside your VMAP response, we should be cleanly handling all errors. Do you have more info on things that aren't being handled cleanly so we can fix that? Thanks!

**Comment by Slind14** [comment]
I'm under the impression that we are loosing around 30% of the opportunities due to errors which videojs-ima is not recovering from.
Is it possible that we will ever see some reports about the vast tag from ima?

**Comment by shawnbuso** [comment]
The IMA SDK team doesn't have this on their roadmap, but we are looking into exposing more info on ads that fail to load to troubleshoot issues like this.

**Comment by Kiro705** [comment]
Hi @Slind14,

I wanted to reach out to you about this issue. Is identifying the specific VAST tag erroring within a VMAP something you require?

I am going to close this issue, but please feel free to reopen if you would like us to look into that possible feature.
