### ISSUE TITLE
Getting AdError 1009 when no ad breaks present

### ISSUE THREAD

**Issue by icamys** [googleads/videojs-ima#681]
According to [VMAP specification](https://www.iab.com/wp-content/uploads/2015/06/VMAP.pdf) (see paragraph 2.6) in case of absence of any ad breaks, the primary ad server response should contain only root vmap tag:

```
<vmap:VMAP xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0"/>
…
</vmap:VMAP>
```

When I return empty root tag I am getting error:
```
AdsLoader error: AdError 1009: The response does not contain any valid ads.
```
Is there any way to return vmap without any ad breaks?

**Comment by shawnbuso** [comment]
I'm a little confused about your intended use case - when you request ads, we expect to get ads back. So if the response comes back with no ads, we log that error you provided. Do you want to request an empty VMAP tag and not see the error? I'm curious what the use case is for that.

**Comment by icamys** [comment]
Hi Shawn! Thank's for your response!

Here's the use case.
I have a certain logic in showing mid-rolls that depends on video content duration. To follow this logic I send to my ad server request for VMAP with an additional parameter - video duration. Using this duration ad server creates custom VMAP for this particular video content. The point is that in some rare cases, according to my specification, no ads should be shown at all. 

While testing this use case I caught the mentioned error.

**Comment by shawnbuso** [comment]
In that case this is working as intended - if you send a request and get no ads back, we consider that to be an error. Are you seeing any issues resulting from this error? The plugin should just play the content, which would be what you want if you don't have any ads returned.

**Comment by icamys** [comment]
At first I got some issues and lamented this error. The reason was my mistake in plugin configuration. I'm sorry for troubling you.

Now I see the mentioned error but no issues noticed. The player plays as it should.

However I believe that this error should not appear. The specification requirements are met but we get an error. It's confusing.

If you think that it's ok, the issue can be closed.
