### ISSUE TITLE
vpaid not work on chrome 

### ISSUE THREAD

**Issue by Pong420** [googleads/videojs-ima#682]
Hi,

I have a vpaid ad, tested with [IMA Video Suite](https://goo.gl/SamWbc) work every time.
When tested with your [advanced example](https://googleads.github.io/videojs-ima/examples/advanced/) not work on some device/browser. tested on 
- iMac / Macbook Chrome version 67.  // Always fails
- Window 10 Chrome version 67. // better, sometimes fails
- iMac/Macbook Safari // work every time

error return
```
Ad error: AdError 402: VAST media file loading reached a timeout of 8 seconds.
```

Here is the VAST: 
https://svastx.moatads.com/mindsharethnestledcmvpaid959394448801/201806_NICJun_Extreme_Nama-223336906_js.xml 

Thanks

**Comment by shawnbuso** [comment]
Hey there,

Are you still seeing this issue? I tested on the platforms you mentioned and I'm not able to reproduce on my end.

Thanks,
Shawn

**Comment by Pong420** [comment]
Seems to be solved but not sure the reason
Anyway, thank you
