### ISSUE TITLE
AdsLoader error: AdError 1009

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#683]
Hi,

As part of the sign-up process to AdSense AFV, Google requests a test page that demonstrates a player running a test AdSense AFV tag. However, when we run our test tag in Videojs-ima, we're getting this error:

`videojs.ima.js?ver=4.9.6:1368 AdsLoader error: AdError 1009: The VAST response document is empty.
SdkImpl.onAdsLoaderError @ videojs.ima.js?ver=4.9.6:1368`

The AdSense AFV tag works fine in the Videojs-ima and the VAST Inspector ( https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector ).

Any tips for me when trying to get AFV to load on our site?

**Comment by jnthnclrk** [comment]
Anyone else used AdSense AFV with Video.js?

**Comment by jnthnclrk** [comment]
I think I solved this. Our Google rep advised us to add the test account ID to our ads.txt file. Then, after a delay, it now appears to be working! ;)

**Comment by ypavlotsky** [comment]
Great, I'll close this out then.

**Comment by pkramr** [comment]
> I think I solved this. Our Google rep advised us to add the test account ID to our ads.txt file. Then, after a delay, it now appears to be working! ;)

@jnthnclrk I have the same problem with you. Can you advise me more details?
Thanks in advance

**Comment by jnthnclrk** [comment]
Did you add the AdSense test account to your ads.txt…?

**Comment by spormeon** [comment]
i'm getting this issue as well now, added ads.txt and nothing.  The weird thing is , on a test page it works sparadically, when I put on the site template, where it has to be for the G rep to look, not a thing, zip, nada.  no errors or anything and exactly the same code is the outside site test page

**Comment by WesleyCarnicl** [comment]
> I think I solved this. Our Google rep advised us to add the test account ID to our ads.txt file. Then, after a delay, it now appears to be working! ;)

How do I get my ads.txt for google ad manager
