### ISSUE TITLE
Setting current time gets reset to beginning after preroll

### ISSUE THREAD

**Issue by davidjamesherzog** [googleads/videojs-ima#684]
Using the advanced example in this repo, I am trying to set the current time of a video prior to it playing which is a requirement I have for starting a user from where they last left off in a video.  I've added a one time listener to set the current time of the video once the video has loaded.

```
  var _this = this;
  this.player.one('loadedmetadata', function() {
    _this.log('setting current time to 60 seconds');
    _this.player.currentTime(60);
  });
```

Once the preroll completes, the video is started from the beginning and not from the current time.   When I add similar type code to my production code, I see slightly different behavior.  The current time is set correctly but then any preceding midrolls are played prior to the video starting which is not what I want.  Would I have to set the `autoPlayAdBreaks` to false and put my own custom logic in the ad break listener to determine if the midroll should be played or not?  Or is there a better way to handle that situation?

Here is an example - https://codepen.io/davidjamesherzog/pen/XYLBaQ

**Comment by shawnbuso** [comment]
I'm not seeing the `loadedmetadata` listener get called at all in that example, so I think that's the reason that you're not starting at 60 seconds.

As far as skipping ads goes, if you want to play the pre-roll but skip the mid-rolls then yes, you would need to set `autoPlayAdBreaks` to `false` and write your own logic for handling ad breaks. The SDK does offer `adsRenderingSettings.playAdsAfterTime`, which will skip all ads before the provided time, however this would include the pre-roll as well as any mid-rolls before that time. So if you want the pre-roll, this wouldn't be an option for you.

**Comment by davidjamesherzog** [comment]
I want to play the preroll prior to the video playing so I will set `autoPlayAdBreaks` to false.  Thanks for the help.

**Comment by shawnbuso** [comment]
No prob, let us know if you need any more help!
