### ISSUE TITLE
Any tips on making pre-roll race conditions smoother?

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#686]
I've noticed the following sequence a lot in testing. It makes for a very distracting effect on pre-roll ads:

1. Player is started by click/ touch
2. Play button disappears
3. First frame of content loads!?!
4. Play button re-appears!?!
5. Screen goes black
6. Pre-roll plays
7. Pre-roll finishes
8. On returning to content play button is still visible!?!
9. Content plays

Here's an example of the above sequence: 

https://www.dropbox.com/s/qndbesx6x48kqkq/screencast%202018-07-07%2012-36-18.mp4?dl=0

IMHO, if pre-roll is available the sequence should be:

1. Player is started by click/ touch
2. Play button disappears
3. Screen goes black
4. Pre-roll plays
5. Pre-roll finishes
6. Content plays

Perhaps some of this can be improved by simple CSS and JS rules?

**Comment by shawnbuso** [comment]
Hmm yours is the only implementation for which I've seen this - are you using additional plugins besides videojs-ima? I'm wondering if another plugin is potentially interfering with our flow.

**Comment by jnthnclrk** [comment]
Not that I'm aware of. Our lead developer think's it's because we're using custom poster images for our videos.

**Comment by shawnbuso** [comment]
Hmm our examples are using posters as well, and we're not seeing the same issue. Is this page hosted anywhere that I can get access to it to test?

**Comment by jnthnclrk** [comment]
Sure, thanks: https://www.destinationtips.com/videos/12-things-not-thailand/

**Comment by shawnbuso** [comment]
I can see what's happening, but I'm not sure why. It looks like your player is entering a paused state while the pre-roll is loading, which causes the play button to show. When the pre-roll finishes, you see the content with the play button for a second, then the player goes from paused to playing and the play button disappears. Would you be able to specify `debug: true` in your video.js plugin options so we can get an event log for contrib-ads? Thanks!

**Comment by jnthnclrk** [comment]
I'll add this today and revert back here…

**Comment by shawnbuso** [comment]
I tested out your page with videojs-contrib-ads 6.0 and I'm no longer seeing the issue - are you able to update to that version and see if it fixes it on your end as well?

**Comment by jnthnclrk** [comment]
Thanks, @shawnbuso. I don't think we're using videojs-contrib-ads at all. I thought that lib was for writing plugins. I'll speak with our dev who is back to work on Monday…

**Comment by shawnbuso** [comment]
videojs-contrib-ads is a dependency of videojs-ima :)

**Comment by jnthnclrk** [comment]
Right, I see it now, in our code ( videojs.ads.min.js ).  And we're already on 6.0.0.

<img width="545" alt="screenshot 2018-07-13 15 30 43" src="https://user-images.githubusercontent.com/498192/42710357-b883a40c-86b1-11e8-859c-63b2dbd19444.png">

**Comment by shawnbuso** [comment]
Yea you're right - I wonder if this is a race condition of some kind, and maybe that's why my proxying a different file seemed to fix it.

**Comment by jnthnclrk** [comment]
Looks like our dev figured it out. Your example videos start with a single black frame. Ours don't. You can see the flickery effect in the side by side comparison here:

https://staging.destinationtips.com/examples/simple/

Should we and other users start producing videos that start with a single black frame?

**Comment by Kiro705** [comment]
Hi @jnthnclrk,

I wanted to check in on the status of your issue here.

I was looking into this and did not see the behavior you were describing even with a video with a non-black first frame. I did however see some similar behavior when throttling the network connection to slower speeds.

Let me know any changes on your end, if the issue is still a problem.

**Comment by jnthnclrk** [comment]
No longer an issue. Go ahead and close this.
