### ISSUE TITLE
Videojs-IMA - Multiple Players in a single page

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#687]
We are trying to implement multiple players with the Video Js, Google IMA and HLS in a single web page dynamically, but we can't able to achieve that on the same. Here is our sample player. http://106.51.1.175/mmp_new_optimized/. Here the second instance get loaded well but not the first. Could anyone please assist us to get the solution for us.

**Comment by ypavlotsky** [comment]
Hi there,

I wasn't able to view your sample, as it kept timing out for me. However, I suggest you take a look at our multiple player sample, it might be a good place to start:

http://googleads.github.io/videojs-ima/examples/multiple/

**Comment by Kumaran29** [comment]
Hi ypavlotsky,
Good Day, Thank you for your reply. Sorry for the server timeout last time. Please check the following link,
http://www.tinubeans.com/mmp_new_optimized

where we placed two players. The first one fails to load while the second one does. Please take a look when you can. Meanwhile we are working based on the link you provided me (http://googleads.github.io/videojs-ima/examples/multiple/)

Looking forward for your reply.

**Comment by Kumaran29** [comment]
Thanks a lot . This worked
