### ISSUE TITLE
Normalising audio between content and ads

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#689]
Of course, all the video ads I'm seeing in testing are significantly louder than our content. Is there anyway to dynamically boost our content volume or reduce the ad volume? Or perhaps we need to re-process our content? It's pretty jarring when ads load significantly louder than the content.

**Comment by ypavlotsky** [comment]
You could modify the plugin to call `changeVolume` in the same way the ad-ui.js does to change the ad volume, but how are you going to dynamically know how loud the ads actually are? It's probably more straightforward to re-process the content, IMHO.

**Comment by jnthnclrk** [comment]
Yeah, agreed. Do you know of any suitable standards out there for video audio production? Our current video files come from YouTube, so there probably normalised to work with that platform.

**Comment by ypavlotsky** [comment]
Sorry, it's not something I know anything about :)

**Comment by jnthnclrk** [comment]
OK, thanks
