### ISSUE TITLE
AdEvent.Type.COMPLETE doesn't appear to fire for overlay ad breaks

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#691]
So, AdEvent.Type.COMPLETE doesn't appear to fire for overlay ad breaks; however, the event is caught by `debug: true`:

    VIDEOJS: ADS: Starting ad break
    VIDEOJS: ADS: Ending ad break

The above was generated by an overlay full screen style responsive display ad:

<img width="837" alt="screenshot 2018-07-12 13 05 23" src="https://user-images.githubusercontent.com/498192/42648226-4c6bdec0-85d4-11e8-9a05-cbce92e9b5e4.png">

How can I hook into the "ending ad break" event?

**Comment by ypavlotsky** [comment]
Hi there,

You can work around this by hooking into the IMA SDK's `CONTENT_RESUME_REQUESTED` event, which happens after an ad break completes. Alternatively, you can hook into the videojs player's `adend` event a la:

```
this.player.on('adend', function(event) {
    console.log("AD ended");
});
```

**Comment by jnthnclrk** [comment]
Thanks, that's just what I need!

**Comment by ypavlotsky** [comment]
Great, closing this issue out.

**Comment by jnthnclrk** [comment]
Ah, unfortunately, this code doesn't work for non linear display ads. AdEvent.Type.IMPRESSION is best from my experience. Although it doesn't confirm whether an was completed.
