### ISSUE TITLE
ima3.js not loading under Safari

### ISSUE THREAD

**Issue by dilburt** [googleads/videojs-ima#693]
Hi,

I'm running into a problem that is causing or being caused by ima3.js not loading. The symptom is a log entry of "[Error] ReferenceError: Can't find variable: google" generated by the line "const adsRequest = new google.ima.AdsRequest();" However, it appears that the root problem is that ima3.js isn't loading due to a CORS error that only occurs in Safari (Mac or iPhone).
[Error] Blocked a frame with origin "https://" from accessing a frame with origin "https://**". Protocols, domains, and ports must match.\
This is followed by logging from ima3.js which is pretty cryptic:
Nh (ima3.js:91)
Oh (ima3.js:92)
start (ima3.js:356:165)
This is followed by logging from show_ads_impl.js (there is much, much more I didn't copy):
Ft (show_ads_impl.js:1:162176)
yt (show_ads_impl.js:1:171721)
At (show_ads_impl.js:1:161025)
uu (show_ads_impl.js:1:181688)
(anonymous function) (show_ads_impl.js:1:48771)
si (show_ads_impl.js:1:48481)\

Our systems are on AWS and the files being accessed are in an S3 bucket with standard AWS CORS headers that work for all other desktop and mobile browsers and have worked for Safari in the past so I'm not sure what changed. All ads for this are coming from Google (Doubleclick) servers. You can test this using Safari at:
https://apps.facebook.com/applixirtest

Let me know if you have any idea why the Safari error is stopping ima3.js from loading.

Thanks,

D

**Comment by ypavlotsky** [comment]
Hi there,

I'm not seeing that error in our samples when I try them on Safari. Just going to the [simple example](http://googleads.github.io/videojs-ima/examples/simple/), ima3.js is loading normally for me.

Your test page requires me to log in. Do you have another page I can repro this on? Thanks!

--Yury

**Comment by dilburt** [comment]
This only happens when logged in for some reason. Git dumped PM's but is there somewhere I can send you test account info?

D

**Comment by ypavlotsky** [comment]
You can send me an email at ima-sdk-support@google.com and I'll take a look.

**Comment by dilburt** [comment]
I just figured it out this morning and didn't have a chance to report back to you before you tested again. Thanks for your help. This can be closed.
