### ISSUE TITLE
Non-linear overlay ads break the big play button

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#694]
Non-linear overlay display ads, when closed by the user, break the big play button functionality.

<img width="862" alt="screenshot 2018-07-13 13 36 28" src="https://user-images.githubusercontent.com/498192/42705612-db600f98-86a1-11e8-8f31-8247fa9d6460.png">

Once the ads is closed by the user, the content can no longer be controlled using the big play button:

<img width="771" alt="screenshot 2018-07-13 13 38 17" src="https://user-images.githubusercontent.com/498192/42705663-0857d170-86a2-11e8-8727-928f08c4b059.png">

Play and pausing can then only be controled by the main control strip at the bottom of the player:

<img width="297" alt="screenshot 2018-07-13 13 39 03" src="https://user-images.githubusercontent.com/498192/42705687-1e67ff9e-86a2-11e8-8f7a-312c06b69c49.png">

**Comment by ypavlotsky** [comment]
Sorry, not sure what button we're talking about here. Do you have an example page where I can see this happening?

**Comment by jnthnclrk** [comment]
Yup, but you have to be lucky enough to catch a non-linear ad. Not sure how to force them. If you see one, close it, and then try and use the big on screen play button.

https://www.destinationtips.com/videos/12-things-not-thailand/

**Comment by jnthnclrk** [comment]
I caught one on video. Notice the clicks/ taps on the video. I first close the non-leaner banner and then try and pause the video by clicking the screen. It's perhaps some kind of CSS layer thing. The non-linear ad after being close disrupts the big button CSS. I think…

https://www.dropbox.com/s/pom1zu8qnz473sg/screencast%202018-07-13%2015-42-28.mp4?dl=0

**Comment by ypavlotsky** [comment]
Looks like some kind of issue with the videojs skin that you're using, which I'm not familiar with. Do you see the issue if you put your ad tag into one of our [samples](http://googleads.github.io/videojs-ima/)?

**Comment by jnthnclrk** [comment]
OK, thanks, taking a closer look at skin…

**Comment by Kiro705** [comment]
This issue looks like it was related to the videojs skin. I will be closing the issue.

**Comment by ravishankar518** [comment]
is Exoplayer posible to play non-linear ads play  or not ?

**Comment by Kiro705** [comment]
Hello @ravishankar518 ,

The video.js-ima plugin is specific to HTML5/web playback while ExoPlayer is an Android player.

That being said, ExoPlayer + IMA should be able to play non-linear ads on Android.
IMA also offers the [ExoPlayer IMA extension](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/exoplayer-extension) which offers a quick way to start with ExoPlayer and IMA.
