### ISSUE TITLE
Is it possible to output the ad creative "format" to the console?

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#695]
I've been unsuccessfully searching the docs ( https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.CompanionAdSelectionSettings.CreativeType ) for this, but how do I print the following ad formats to the console?

- In-stream skippable
- In-stream standard
- Overlay text linear
- Overlay image linear
- Overlay text non-linear
- Overlay image non-linear
- Others?

Thanks!

**Comment by ypavlotsky** [comment]
Hi,

You can see if an ad is linear by querying `Ad.isLinear()` and that should tell you if it's instream or overlay. Otherwise, you can also call `Ad.getContentType()` and `Ad.getSkipOffset()` to approximate some of this information.

**Comment by jnthnclrk** [comment]
Thanks, I'll that out!

**Comment by jnthnclrk** [comment]
I guess these functions need to be called whilst the ad is actually downloaded and playing. Can you recommend a good listener for these functions?
