### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported

### ISSUE THREAD

**Issue by sdahdaah** [googleads/videojs-ima#697]
Hello,

Many DFP pre-rolls are showing this error after playing back on iOS iPhone and block the HLS playback.

![image](https://user-images.githubusercontent.com/36862659/42815269-9fd3f0ee-89cf-11e8-9d01-96676e658b82.png)

any hint?

**Comment by ypavlotsky** [comment]
That error comes from the videojs player when it can't load the media. Do you have a sample ad tag that I could test with?

**Comment by sdahdaah** [comment]
if you try the same video without ads it works with no issue.

if you use any device different than iOS it works with no issue. i am quite sure that this problem is being caused by the ad-plugin.

here is an example: https://www.otv.com.lb/new-live.php but it is not necessary that the tag fires an error on playback it doesn't happen on each playback. 

You need to do multiple trials.

**Comment by sdahdaah** [comment]
as you can see in my screenshots since i am running console while trying, you can see that the stream has already preloaded as we have configure it and the ads have fired however when they were done they caused this error.

![screen shot 2018-07-17 at 6 05 12 pm](https://user-images.githubusercontent.com/36862659/42826069-382f36a2-89ec-11e8-9ef0-c7bdd70a4fe0.png)
![screen shot 2018-07-17 at 6 05 33 pm](https://user-images.githubusercontent.com/36862659/42826076-3fcdc48c-89ec-11e8-92bf-820a6240fe04.png)

**Comment by ypavlotsky** [comment]
I went to your example site on an iPhone, but I'm seeing the same pre-roll ad every time I refresh and it works for me with no error.

**Comment by Nicola1976** [comment]
Hi

I have the same problem.
Could you please tell me if you have any solution?

This is a very serious problem that impacts all the IOS mobile video advertising.

A test page:

**https://video.corriere.it/?adunit=35821442/TEST_corriere.it/stagingtvtris** 

Thanks a lot

**Comment by Kiro705** [comment]
Hi @sdahdaah and @Nicola1976 ,

It looks as though this issue may have been resolved. I went to the above mentioned page on an ios device and the ad and video played as expected.

Because of that I will be closing the issue, but please reopen the issue if you would like me to take a look.

**Comment by Jerome-lara** [comment]
Hi @sdahdaah and @Nicola1976 ,
I have the same problem.
Could you please tell me if you have any solution?
