### ISSUE TITLE
Requests blocked by chromes CORB

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#699]
Hi there,
I noticed that other players e.g. bridtv do not have this issue using the same vmap tag and ima sdk. Can we resolve/work around it? I'm under the impression that it leads to a good amount of dropped requests/fill. (brid has twice the amount of requests on the same tag)

![image](https://user-images.githubusercontent.com/3914677/42847649-e00f521e-8a1c-11e8-92de-42da3dbf89ac.png)

**Comment by ypavlotsky** [comment]
Hi,

These warnings shouldn't affect the ad requests in any way. It's complaining that it couldn't receive responses to pings that were sent out. The ping are still sent out normally.

**Comment by Slind14** [comment]
ahh, I see. Do you have an idea why I'm only getting this with video.js + ima and not with other players?

**Comment by ypavlotsky** [comment]
It should be happening with any IMA SDK integration. Not sure about other players.

**Comment by Slind14** [comment]
hmm, odd. They use the same IMA SDK link and I can reproduce it without issues on different devices.

**Comment by ypavlotsky** [comment]
I can't troubleshoot other implementations. The basic IMA reference implementation at http://googleads.github.io/googleads-ima-html5/simple/ shows the same CORB warnings.

**Comment by Slind14** [comment]
hmm, interesting. I wonder if they suppress it somehow
