### ISSUE TITLE
Ad Scheduling

### ISSUE THREAD

**Issue by genelamarellis** [googleads/videojs-ima#702]
We have a VAST tag that plays ads successfully. The ad is running in the pre-roll position, although we would like it used for mid-roll. Our ad network advised is to target the ad tag for the mid-roll position. How is that done? Does this plugin have an ad scheduler? The only way I have seen a mid-roll with this plugin is through VMAP. Is there another way? Thank you!

**Comment by ypavlotsky** [comment]
Hi,

This plugin doesn't have an ad scheduler, to schedule a mid-roll ad, you should use VMAP.

**Comment by genelamarellis** [comment]
Ok thank you!
