### ISSUE TITLE
Video content not loading after ad (iOS Safari).

### ISSUE THREAD

**Issue by abi3** [googleads/videojs-ima#703]
I am facing the issue on the website,  it is using ima js. 
Please check the following website on iPhone Safari. 
https://shahid.mbc.net/ar/

Regards

**Comment by ypavlotsky** [comment]
Hi,

When I go to your page on iPhone Safari, I'm seeing several AWS 502 and 504 errors, so maybe it's something related to that? I don't see any videojs or IMA errors.

**Comment by abi3** [comment]
this website using the player
