### ISSUE TITLE
ima.requestAds()

### ISSUE THREAD

**Issue by dilburt** [googleads/videojs-ima#705]
I just noticed that in examples/advanced/ads.js that you are calling player.ima.requestAds() which I thought had been deprecated. Are there still scenarios where that should be used or did this just get missed?

Thanks,

D

**Comment by Kiro705** [comment]
Hi @dilburt 

From my understanding the method call [player.ima.requestAds()](https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L193-L236) is not deprecated.

I believe previously, the IMA SDK deprecated adsLoad.requestAds() with zero parameters (I think support for this has now been removed). It does support [adsLoader.requestAds(adsRequest, opt_userRequestContext)](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsLoader.requestAds).

Please let me know if I am missing something. In terms of setup for the advanced example, its built for the use case of loading a video player then having the user input an ad tag. You can take a look at the simple example to see an instance of loading ads without calling player.ima.requestAds().

I will be closing the issue but feel free to reopen if something comes up.
