### ISSUE TITLE
Event when preload ad is ready or timeout reached

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#706]
Hi there,
I would like to make the player sticky as soon as an ad is ready or the timeout has been reached (not earlier) like other players e.g. brid are doing it. 
Unfortunately I wasn't able to find appropriate events. On desktop I can use `google.ima.AdEvent.Type.LOADED` but this fires after the play() and hence doesn't fire on mobile due to browser restrictions when the content is out of view at the time being.
Are you aware of events or workarounds that might help?

**Comment by Kiro705** [comment]
Hi @Slind14 ,

Did you ever find a solution to your issue?

By sticky do you mean a player that stays in the corner as a user scrolls? Would it be possible to use some of these [events](https://github.com/googleads/videojs-ima#ima-plugin-ad-events) to get the player at this time.

If not we can look into adding the appropriate player events.

I will be closing this issue, but please reopen if you did not find a solution yet.
