### ISSUE TITLE
'silent' ad error event breaking Ad UI

### ISSUE THREAD

**Issue by grobolom** [googleads/videojs-ima#707]
Hey all!

I've noticed some strange behavior on specific ads that use the VPAID bridge tech to run. Certain ads are triggering asset fallback, but I don't see any actual errors coming through the IMA SDK. [If you go to the following URL](http://glimmer.hearstapps.com/api.html?embedId=cce3f0c1-d723-437d-b581-fd866da0b523&dataLayer=none&adTag=&aspectRatio=16%3A9&volume=1&muted=on&autoplay=on&token=rubicontest) and refresh a few times, you should be able to see something like the following:
![image](https://user-images.githubusercontent.com/445806/43202947-d958983a-8fea-11e8-90fb-1eb217304e9d.png)

An ad fails, and videojs/videojs-ima doesn't know to clean up after itself. As a result, it plays the actual video content as an ad and does not properly dispose the Ad UI. You can see the jankiness by looking at the events in the logs - it fires ad start events even though this is on the content.

Using this ad tag, I've been able to reproduce this behavior similarly on other players across the web - for example, both JWPlayer versions (7 and 8) show the same bad event flow, as well as the google ad tester itself. However, there must be a way to get the player back into a 'sane' state, I'm just not sure how to get it there.

If someone could briefly take a look at this it would be much appreciated. I'd jump into the code myself but I'm not yet sure where to look - for now I'm debugging the videojs-ima plugin and trying to see if breakpoints at any of the normal integration points trigger from this ad error, but no luck yet.

Thanks!

**Comment by grobolom** [comment]
Just as a follow-up, this may be something on our side with the VPAID bridge tech being totally busted, but either way I feel like there should be a sane fallback. Not sure if that would be right to do here (handling random, ever-increasing list of failures seems like a bad idea), but it's an idea.

**Comment by Kiro705** [comment]
Hi @grobolom ,

I would be interested in adding better handling for the videojs-ima plugin, but was having trouble reproducing the behavior you mentioned.

I am going to close this issue but please reopen if you have a reproducible case.
