### ISSUE TITLE
Forcing certain aspect ratios?

### ISSUE THREAD

**Issue by jnthnclrk** [googleads/videojs-ima#709]
Hi,

One of the requirements of Google Ad Exchange video is maintaining a certain aspect ratio:

> 4:3, 16:9, 1:1, 3:4, or 9:16, or as otherwise approved by Google

https://support.google.com/dfp_premium/answer/6210382?hl=en#minimum-size-and-aspect-ratio-requirements

Are there any controls we can use in Videojs-ima to force a ratio like 16:9? Or are we obliged to use custom CSS to satisfy AdX requirements?

**Comment by Kiro705** [comment]
Hi @jnthnclrk ,

I think the best way to satisfy this would be to use the videojs methods to set the aspect ratio. Here are their [docs on aspect ratios](https://docs.videojs.com/tutorial-layout.html). I am going to close this issue, but please feel free to reopen if that does not solve it.
