### ISSUE TITLE
adsRequest.contentTitle & contentDuration & contentKeywords

### ISSUE THREAD

**Issue by onix-sergey** [googleads/videojs-ima#710]
Hello,

Please advise how to specify these options to the ad request. 

https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRequest.contentKeywords

Thanks.

**Comment by Kiro705** [comment]
Hi @onix-sergey ,
I would recommend using the ads request event to get the [ads request](https://github.com/googleads/videojs-ima#ima-plugin-ad-events) and then setting the [contentKeywords](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRequest.contentKeywords) on that revived ads request.

I am going to close this ticket (it has been quiet for awhile), but please reopen it if that does not solve your issue.

**Comment by mtkopone** [comment]
Hi. I'm wondering how this works, as videojs-ima calls requestAds before triggering the 'ads-request'-event, see: https://github.com/googleads/videojs-ima/blob/master/src/sdk-impl.js#L240

I'd assume it's too late to add these parameters after requestAds. But of course this is very dependent on the implementation of ima.js. I also can't see any relevant changes in the requests to admanager after adding these.
