### ISSUE TITLE
Domain referral always appears as googleapis.com 

### ISSUE THREAD

**Issue by monyiliev** [googleads/videojs-ima#712]
Hi all,

We are experiencing an issue where the domain in our reports DFP/DCM always shows as googleapis.com. Presumably, this should've been the value of the url parameter that the IMA SDK [sets automatically](https://support.google.com/dfp_premium/answer/1068325?hl=en#url).

The url is properly set yet the reports always show googleapis.com.

In order to eliminate possible erroneous implementation on our end, we used the [autoplay example](https://github.com/googleads/videojs-ima/tree/master/examples/autoplay) without any modification except for the ad tag that was replaced by ours. Unfortunately the results are the same.

I would highly appreciate anyone's help in resolving this issue and/or a possible direction in rectifying this.

Test player with autoplay example is available here: https://player.stg.watchstadium.com/videojs-ima/VOD_Player6/examples/autoplay/index.html

The ad tag used is:
```
https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/32984737/YY_Updated_SDKTesting/A_VOD/VOD_Player6&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&description_url=VOD_Player6&ad_rule=1
```

Thank you.

**Comment by grobolom** [comment]
@monyiliev this is very likely a google issue, either on the IMA or the DFP side. Our team at Hearst faced a similar issue, particularly on AMP, where all URLs were being listed in our DFP reports as coming from the google AMP cache domain. They were supposed to have fix this issue, though it is possible it is still happening.

The `url` field is unfortunately not controllable by the videojs-ima plugin, it is controlled entirely by the IMA SDK itself, even if you override it. It may be better to open an issue on the IMA SDK forums themselves.

**Comment by monyiliev** [comment]
@grobolom , Thank you so much for your response.

Initially, I thought that this should be addressed with IMA or DFP, but then we tested the same ad tags with Google's [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) the domain in the report was google.com which seems correct as the dynamic value for url is `https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector`.

Do you still think that IMA/DFP would be the more appropriate place to raise this issue?

**Comment by Kiro705** [comment]
Hi @grobolom ,

Did you create an issue for this on the IMA forum? Or were you able to resolve it another way?
