### ISSUE TITLE
VIDEOJS: WARN: Unexpected adsready event

### ISSUE THREAD

**Issue by jehadnasser** [googleads/videojs-ima#718]
Hello,
I am trying to request Ad at the end of the content:
```
this.videojs.on('ended', function() {
    this.ima.initializeAdDisplayContainer()
    this.ima.setContentWithAdTag(null, this.adTagUrl, true)
    this.ima.requestAds()
});
```
but I am getting this: `VIDEOJS: WARN: Unexpected adsready event` and nothing to play.
any advice? thanks

**Comment by ypavlotsky** [comment]
Hi,

The plugin doesn't support requesting ads at any point in content, it is tied to the life-cycle of content playback. If you want to play a post-roll at the end of content, you can provide a VMAP tag to the plugin with a post roll in it, such as this [sample ad](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=), and it will automatically play at the end of content.

**Comment by Pong420** [comment]
Hi, 
may be you should listen `contentended` instead of `ended`
```js
this.videojs.on('contentended', function() {
    this.ima.initializeAdDisplayContainer()
    this.ima.setContentWithAdTag(null, this.adTagUrl, true)
    this.ima.requestAds()
});
```

**Comment by jehadnasser** [comment]
@ypavlotsky thanks for the information, currently we are trying to prevent the ending of the content so we can make ad-requests whenever we want, by removeEventListener of related events.

@Pong420 thank you for the help, I have tried this before, the same behavior.

**Comment by Kiro705** [comment]
Hi @jehadnasser ,

Like @ypavlotsky was saying, the plugin does not support requesting ads during content playback.

What is it you are trying to achieve from requesting ads during content playback?

**Comment by jehadnasser** [comment]
Hi @Kiro705 
I am no longer in the Ad business, but as I remember I was trying to request a new ad once the content ends but ending the content means no possibility to make an ad request.
