### ISSUE TITLE
Release needed

### ISSUE THREAD

**Issue by davidjamesherzog** [googleads/videojs-ima#719]
I need a release to get the fix in for #680 since we are experiencing the same problem that is fixed in this issue.  What determines when releases are done?

**Comment by ypavlotsky** [comment]
Hi there,

We currently do not have a set release schedule, and release on a best-effort basis. I'll work on putting together a new release ASAP.

**Comment by ypavlotsky** [comment]
I put together a v1.5.2 release from master/. Hope that fixes your issue.

**Comment by davidjamesherzog** [comment]
Thanks, I'll check it out.
