### ISSUE TITLE
DFP SB is not compatible with the plugin

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#72]
You can't run a mid-roll with DFP SB. You can't run overlay. You can't run post-roll.
If this is not an issue, I don't understand the purpose of the plugin!

This is in respect to issue: https://github.com/googleads/videojs-ima/issues/39
Which was closed without any chance of explaining why there is a problem/bug.

**Comment by shawnbuso** [comment]
Hi there,

It sounds to me like your complaint is that you can't run mid- or post-rolls with DFP SB. DFP missing features that you need is completely separate from this plugin. This plugin has full support for mid- and post-rolls - it's up to you to find an ad server that will serve them. Again, an ad server lacking support for mid- or post-rolls is *not* a bug with the plugin - the plugin supports mid- and post-rolls just fine.
