### ISSUE TITLE
Uncaught referee Error

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#721]
We are using videojs with ima plugin. we are getting the following error "Uncaught ReferenceError: Ex8_Player is not undefined"
Note : We are getting error whenever we clear cache , when it loads second time i.e from browser cache its working fine
Link : http://www.tinubeans.com/playlist-without-widget/
can you check and let us know pls?

**Comment by Kumaran29** [comment]
Can someone help pls?

**Comment by ypavlotsky** [comment]
Hi,

I don't know what that error is, but it's not an error that the plugin or IMA SDK fires, so it might be another error from elsewhere on your page.

**Comment by Kumaran29** [comment]
We were able to resolve this. Thanks for your feedback. I will close this issue
