### ISSUE TITLE
IE 11 limitation?

### ISSUE THREAD

**Issue by Slind14** [googleads/videojs-ima#722]
Hi there,
looking at yesterday data of our player evaluation we are seeing a huge difference in impressions on IE11. Is there a known limitation of videojs-ima regarding this browser?

![image](https://user-images.githubusercontent.com/3914677/43962487-1adf9f5e-9cb8-11e8-93cd-45433ecc21fc.png)

**Comment by ypavlotsky** [comment]
Not as far as I know. I looked at our [simple example](http://googleads.github.io/videojs-ima/examples/simple/) in IE 11, and it worked fine. Are you seeing any specific errors?

**Comment by Slind14** [comment]
Yeah it is working in IE for me as well. Yet the amount of requests and filled impressions tells a story of issues compared to other players using the IMA SDK as well. Since I'm not getting any errors with IE 11 my self, I'm kind of stuck trying to resolve this.

**Comment by mackinven** [comment]
HI, Slind14.
I did find an issue with IE11 and the autoplay implementation - ads would not load.
Take a look at this:
https://github.com/googleads/videojs-ima/issues/733

**Comment by Kiro705** [comment]
Hi all,

I will be closing this issue, but will take a look into the https://github.com/googleads/videojs-ima/issues/733 issue.
