### ISSUE TITLE
AdDisplayContainer size issue

### ISSUE THREAD

**Issue by onix-sergey** [googleads/videojs-ima#724]
Hi, 

When the player is initialized inside a hidden container, adsManager is not initialized.
```
<div style="display:none">
var player = videojs()...
player.on("adserror", function (data) {
    console.error("adserror", data); // console doesn't show any errors
});
player.ima(options);
player.one('click', function() {
    player.ima.initializeAdDisplayContainer();
    player.ima.requestAds();
});
</div>
```
adsLoader doesn't  trigger AD_ERROR or ADS_MANAGER_LOADED events.
if take a look on "SdkImpl.initAdObjects" then I see:
adDisplayContainer.width is 0 
adDisplayContainer.height is 0 
getPlayerWidth() - 900
getPlayerHeight() - 560

and here is screenshot of AdLoader after click / requestAd: 
![image](https://user-images.githubusercontent.com/6874846/44034296-6a45a7f0-9f15-11e8-8e0d-4a706aacd805.png)

Please advise how to correctly initialize plugin in such situation.

Thanks.

**Comment by ypavlotsky** [comment]
Hi,

You can't initialize the IMA SDK in a hidden container. You can initialize it when the container is un-hidden or before it is hidden.

**Comment by onix-sergey** [comment]
OK. we do not control and do not know that the container is hidden.
How to initialize only "ADS" part? and start initialization of IMA by the user click?

if initializes the plugin by a click, it does not work, and the ADS plugin trigger an error: plugin must initialize immediately after the player...

**Comment by ypavlotsky** [comment]
You can initialize the ad display container as a result of user click as in our [simple example](https://github.com/googleads/videojs-ima/blob/master/examples/simple/ads.js#L54), where `initializeAdDisplayContainer()` is called after the user clicks.

**Comment by onix-sergey** [comment]
as you see in the snippet above, it's initialized (initializeAdDisplayContainer()) by user click, the same like in your example, but it doesn't solve an issue, Ad container dimensions - 0.

**Comment by mysuf** [comment]
Note that `display: none` results in no width/height while `visibility: hidden` hides element, but preserve dimensions.

**Comment by Kiro705** [comment]
Hi @onix-sergey ,

I am going to close this issue, but please feel free to reopen if the problem persists.
