### ISSUE TITLE
Play all skipped mid-roll ads when using VMAP

### ISSUE THREAD

**Issue by bbleds** [googleads/videojs-ima#725]
This is a great plugin, but I've come across a use case/ issue when there are multiple mid-roll ad breaks that should be played and the user skips multiple ( to be fair, I realize this may not necessarily be an "issue"  but rather a set of functionality that may not need to be baked in by default :) ). 

**Current Functionality:** 
1.  Player loads a 50s video that will have pre-roll single ad, post-roll single ad, and multiple mid-roll ad break points (occurring every 10s after start)

2. User starts video, pre-roll ad plays, user seeks forward to the 31s point of the video 

3. Player plays a single set of mid-roll ads from ad break

4. Player continues play at 31s

**Ideal Functionality (in my case):** 
1.  Player loads a 50s video that will have pre-roll single ad, post-roll single ad, and multiple mid-roll ad break points (occurring every 10s after start)

2. User starts video, pre-roll ad plays, user skips forward to the 31s point of the video 

3. Player plays mid-roll ads from ad break that was scheduled for 10s

4. Player plays mid-roll ads from ad break that was scheduled for 20s

5. Player plays mid-roll ads from ad break that was scheduled for 30s

6. Player continues play at 31s

Is this a set of functionality that has ever been discussed? One clear solution to achieve this in my case would be for me to implement some tracking and manually set the player to a certain point after an ad break event, but I was hoping that someone had already come across this before. 

If needed, here is an [example](https://codepen.io/bbleds/pen/BPeBBJ) on codepen that uses an [example](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=) VMAP from google (taken from VMAP sample tags and described as : "VMAP - Pre-roll Single Ad, Mid-roll Standard Pods with 5 Ads Every 10 Seconds for 1:40, Post-roll Single Ad")

In any case, I appreciate it 👍

**Comment by ypavlotsky** [comment]
Hi,

This is a limitation of the underlying IMA SDK, so there is no way to do what you're asking in the plugin.

Thanks,
Yury

**Comment by bbleds** [comment]
No worries, appreciate you taking a look!
