### ISSUE TITLE
Cannot read property 'getRemainingTime' of null

### ISSUE THREAD

**Issue by onix-sergey** [googleads/videojs-ima#728]
please add verification for adsManager in onAdPlayheadTrackerInterval.
```
{snip} totype.onAdPlayheadTrackerInterval=function(){var e=this.adsManager.getRemainingTime(),t=this.currentAd.getDuration(),n=t-e;n=n>0?n:0;var i= {snip}
```

**Comment by ypavlotsky** [comment]
It should never be the case that AdsManager is null in this function. How do you reproduce this error?

**Comment by onix-sergey** [comment]
I can't reproduce this error self, but I see that this happens in 3% of users.

**Comment by onix-sergey** [comment]
looks like it happens on midroll state immediately after "reset". 
do you have idea why reset doesn't clear interval?

**Comment by Kiro705** [comment]
Hi @onix-sergey ,

It looks like this issue may have been resolved with https://github.com/googleads/videojs-ima/pull/814 .

I am going to close the issue, but if that is not the case, please feel free to reopen so I can look into fixing it.
