### ISSUE TITLE
Issues in Streaming Youtube Videos

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#729]
Good Day,
We are trying to stream our videos from youtube to our sites. We are facing the issue while streaming our Youtube content in videojs Ima. While playing the youtube videos with the ima ads the player itself toggle to full-screen. And on exiting the full-screen the ads get played and the player gets paused. This occurs in the IOS. Please review the player in iphone . Could you please suggest us a solution on the same. 

Sample player is in the following link, 
http://106.51.1.175/mmptt_youtube

**Comment by ypavlotsky** [comment]
Hi there,

Just to be clear, are you saying you're having trouble serving ads for YouTube content? If so I'd suggest you read through the [terms of service for the IMA SDK](https://support.google.com/adsense/answer/1706015), specifically: "Publishers cannot use IMA products to monetize YouTube-hosted content. For YouTube content, publishers must monetize through the [YouTube partner program](https://www.youtube.com/yt/creators/benefits/)." If you have any additional questions let us know.

Thanks,
Yury
