### ISSUE TITLE
Ima is not registered in videojs

### ISSUE THREAD

**Issue by kapilropani** [googleads/videojs-ima#730]
I'm using video7 along with google imaSDK3
import React from 'react';

import * as dialogActions from '../../actions/dialogActions'
import videojs from 'video.js'
import '../../bootstrap/js/videojs-contrib-ads';
import 'videojs-ima/dist/videojs.ima'

import '../../bootstrap/css/videojs-contrib-ads.css'
import '../../bootstrap/css/video-js.css'
export default class VideoPlayer extends React.Component {
  constructor(props) {
    super(props);
    this.player = null;
    
  }

  componentDidMount() {
    window.scrollTo(0, 0); //this code is represent the scroll to top
    if(this.player === null){
      let video =  document.getElementById("contentVideo");
      // $(video).on({
      //   mouseenter: function () {
      //     video.setAttribute("controls","controls")
      //   },
      //   mouseleave: function () {
      //     video.removeAttribute("controls");
      //   }
      // });
      
      this.player = videojs(this.videoNode, this.props, function onPlayerReady() {});
  
      // this.player.on('mouseout', function(){ 
      //   controlBar.addClass('vjs-fade-out'); 
      // });
  
      // this.player.on('mouseover', function(){ 
      //   controlBar.removeClass('vjs-fade-out'); 
      // });
      if(this.player.hasPlugin("ima")){
        this.player.ima({
          id: 'contentVideo',
          // adTagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=%2F39243592%2F413851632&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]',
          adTagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/39243592/387337752&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]',
          adsManagerLoadedCallback: () => {
            var events = [google.ima.AdEvent.Type.ALL_ADS_COMPLETED
              ,google.ima.AdEvent.Type.CLICK
              ,google.ima.AdEvent.Type.COMPLETE
              ,google.ima.AdEvent.Type.FIRST_QUARTILE
              ,google.ima.AdEvent.Type.LOADED
              ,google.ima.AdEvent.Type.MIDPOINT
              ,google.ima.AdEvent.Type.PAUSED
              ,google.ima.AdEvent.Type.STARTED
              ,google.ima.AdEvent.Type.THIRD_QUARTILE];
            for (var index = 0; index < events.length; index++) {
              if (events[index] === google.ima.AdEvent.Type.CLICK){
                this.player.ima.addEventListener(events[index],(e) => {
                  e.preventDefault();  
                  return false;
                });
              }
              
              if(events[index] === google.ima.AdEvent.Type.COMPLETE || events[index] === google.ima.AdEvent.Type.ALL_ADS_COMPLETED){
                this.player.ima.addEventListener(events[index],(e) => {
                  this.player.play(); 
                  if (this.props.download !== "" && this.props.download !== undefined){
                    window.open(this.props.download, "_blank");
                    dialogActions.setModal(this.props.dispatch, false,"","");
                  } else {
                    dialogActions.setText(this.props.dispatch, "Video has been started");
                  }
                });
              }
            }
          }
        });
        // this.player.ima.requestAds();
        // this.player.hasAttribute('controls')
        if ((navigator.userAgent.match(/iPad/i) ||
          navigator.userAgent.match(/Android/i))) {
            // this.player.removeAttribute('controls');
        }
        this.player().ima.requestAds();
      }
      
      var startEvent = 'click';
      if (navigator.userAgent.match(/iPhone/i) ||
        navigator.userAgent.match(/iPad/i) ||
        navigator.userAgent.match(/Android/i)) {
        startEvent = 'touchend';
      }
  
      this.player.one(startEvent, function () {
        // console.warn(this.player);
        
        if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/Android/i)) {
          if(this.player().hasPlugin("ima")){
            this.player().ima.initializeAdDisplayContainer();
          }
        }
        this.player().play();
        this.player().pause();
  
      });
      this.player.on("ready", function(){
        this.player().play();
      });
    } 
  }
  
  componentWillUnmount() {
    if (this.player) {
      this.player.dispose()
    }
  }

  end(){
    // console.log("ended");
    this.ended = true;
    this.player.bigPlayButton.show();
  }

  play(){
    if(this.ended == true){
      // console.log("replay");
      this.props.onReplay();
      // this.player.ima.requestAds();
      // if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/Android/i)) {
      //   this.player.ima.initializeAdDisplayContainer();
      // }
      // // this.player.play();
      // this.player.pause();
      // this.ended = false;  
      // return false;
    }
    // console.log("play");
  }
  // wrap the player in a div with a `data-vjs-player` attribute
  // so videojs won't create additional wrapper in the DOM
  // see https://github.com/videojs/video.js/pull/3856
  render() {
      return (
        <div data-vjs-player>
          <video id='contentVideo' ref={node => this.videoNode = node} playsInline onPlay={this.play.bind(this)} onEnded={this.end.bind(this)} className="video-js" controls="true"></video>
        </div>
      );
  }
}

**Comment by Kiro705** [comment]
I @kapilropani ,

It looks like you may have found a solution to your issue. I would direct you to the [es6 import guide](https://github.com/googleads/videojs-ima#es6-imports) for how successfully import the videojs-ima plugin.
