### ISSUE TITLE
ima is not a function when i trying to use ima plugin with webpack project

### ISSUE THREAD

**Issue by Flyover-ArtSk** [googleads/videojs-ima#731]
Hi all, a have big problem with using this plugin in my project.
Libs:
```
video.js: v7.1.0
videojs-ima: v1.5.1
```
Code:
```
import videojs from 'videojs';
import 'videojs-ima';

class TestIMA {
     constructor() {}
     test() {
          const player = videojs(document.querySelector('.videojs-test'));
          player.ready(() => {
               player.ima({
                    id: 'video_story_item',
                    adTagUrl: '...'
               });
          });
     }
}

const testIMA = new TestIMA();
testIMA.test();
```
And i'm getting error 
`ima is not a function`

**Comment by neoantox** [comment]
I have the same problem

**Comment by ypavlotsky** [comment]
I'm seeing the error you mention, but I'm not an expert on integrating with webpack. Perhaps someone here has had some success trying it?

**Comment by dilburt** [comment]
You may also be able to solve the problem by doing this at the top of your webpack entry.js file:

const videojs = require('my-path-to/video.js');
window.videojs = videojs;

You may also need to do this for to deal with external functions in webpack. At the bottom of each module do:

window.myExternalFunc = myExternalFunc;

**Comment by CaddyDz** [comment]
a small note on @chadladensack solution 
You  would have to install `exports-loader` and `imports-loader`
```shell
npm i exports-loader imports-loader
```
If by any chance you're using [laravel-mix](https://laravel-mix.com) like I am this is how you can bundle it
```javascript
mix.webpackConfig({
  module: {
    rules: [
      {
        // omg, WHY!?!?!1!
        test: /videojs.ima.js$/,
        use: [
          {
            loader: 'imports-loader',
            options: {
              define: ">false",
              exports: ">false",
              holder: ">{name:null, init:null}",
              this: ">{videojs:{registerPlugin:(name,init) => {holder.name = name; holder.init = init;}}}",
            }
          },
          {loader: 'exports-loader', options: "holder"},
        ]
      },
    ]
  }
});
```

**Comment by Kiro705** [comment]
Hi all,

It looks as though the issue has been resolved. Please see our [import guide](https://github.com/googleads/videojs-ima#es6-imports) if you are using webpack for your app.
