### ISSUE TITLE
Extremely high CTR reported by AdNetworks

### ISSUE THREAD

**Issue by swaraasolutions** [googleads/videojs-ima#732]
Hi Team,

We have developed a player using videojs and videojs-ima we are using videojs-youtube plugin to play videos. Our implementation is basically a single script that generate the player and manage the videojs-ima.

However, the CTR that is captured by the adnetworks are extremely high we are using VMAP format for adTagURL.

Thanks

**Comment by Kiro705** [comment]
Hi @swaraasolutions , 

It looks as thought you may have found a solution to your abnormal CTRs. I am going to close the issue but please feel free to reopen it if your issue persists.
