### ISSUE TITLE
IE 11 Autoplay Ads issue

### ISSUE THREAD

**Issue by mackinven** [googleads/videojs-ima#733]
Firstly, love your work on this plugin. Much appreciated.

I've just noticed this morning that autoplay ads doesn't seem to work on IE 11. Had assumed it was something in my code but while testing found that the example doesn't load either in IE11: https://googleads.github.io/videojs-ima/examples/autoplay/

The video seems to stay very small - like a thumbnail size - both at the example above and also in my own implementation.

Any suggestions appreciated.

**Comment by mackinven** [comment]
Further to this - IE debugger says the issue is at line 27 of ads.js at line 16, suggesting the , should be replaced with a colon
    .then(({result, error}) => {

https://docs.microsoft.com/en-us/scripting/javascript/misc/expected-colon

**Comment by mackinven** [comment]
I've messed around with the script and tried some of the debugger suggestions - unfortunately I'm not a js ninja and can't get it working yet. Will update if I stumble on something.

**Comment by mackinven** [comment]
Update - just sharing this to help debug.
With further digging I've found IE doesn't like arrow functions
https://stackoverflow.com/questions/40216015/arrow-function-not-working-in-ie-why

A bit of help from my brother and it seems this works in IE for the first function

```
var autoplayAllowed = false;
var autoplayRequiresMute = false;
var player, wrapperDiv = undefined;

function checkUnmutedAutoplaySupport() {
  const options = {timeout: 100, muted: false};
  function thenFn(result, error) {
        if (result === false) {
          checkMutedAutoplaySupport();
        } else {
          autoplayAllowed = true;
          autoplayRequiresMute = false;
          initPlayer();
        }
  }
  canAutoplay.video(options).then(thenFn);
}
```

The function checkMutedAutoplaySupport will need the same treatment I guess

**Comment by mackinven** [comment]
I've modified the first two functions in ads.js for the autoplay example and I have ads loading now in IE, here is my code if it helps:

var autoplayAllowed = false;
var autoplayRequiresMute = false;
var player, wrapperDiv = undefined;

function checkUnmutedAutoplaySupport() {
  const options = {timeout: 100, muted: false};
  function thenFn(result, error) {
        if (result === false) {
          // Unmuted autoplay is not allowed.
          checkMutedAutoplaySupport();
        } else {
          // Unmuted autoplay is allowed.
          autoplayAllowed = true;
          autoplayRequiresMute = false;
          initPlayer();
        }
  }
  canAutoplay.video(options).then(thenFn);
}

function checkMutedAutoplaySupport() {
  const options = {timeout: 100, muted: false};
  function thenFn(result, error) {
        if (result === false) {
          // Unmuted autoplay is not allowed.
          autoplayAllowed = false;
          autoplayRequiresMute = false;
        } else {
          // Muted autoplay is allowed.
          autoplayAllowed = true;
          autoplayRequiresMute = true;
        }
        initPlayer();
  }
  canAutoplay.video(options).then(thenFn);
}

**Comment by Kiro705** [comment]
Hi @mackinven ,

I am planning to take a look into this issue, but wanted to check with you first if it is still reproducible.

**Comment by mackinven** [comment]
Hi Kiro, Yes it is still reproducible. The fix above is what we are running on our site. Cheers.

**Comment by Kiro705** [comment]
Hi @mackinven ,
Thanks for getting back to me. 

In terms of our sample, the issue was untranspiled es6 running on ie11. I have a fix for it here https://github.com/googleads/videojs-ima/pull/848 .

I did not find other issues with the sample, but wanted to double check with you that that was same sort of thing you found.

In the end, it looks like just an issue with the sample code and the plugin can remain unchanged.

Let me know what you think and I can merge in the changes.
