### ISSUE TITLE
Question re videojs-ima + videojs-contrib-hls + loadedmetadata event

### ISSUE THREAD

**Issue by opinxit** [googleads/videojs-ima#736]
We are using videojs-contrib-hls in conjunction with videojs-ima and playlists (this issue is related to  https://github.com/googleads/videojs-ima/issues/735). We found when we move through the playlist items, if we use the `setContentWithAdTag` a race condition could cause the player to freeze if the ad started playing before the content loaded, specifically if the loadedmetadata/loadeddata events trigger after the ad has started playing. It appears the player is paused because of the event handler on `loadedmetadata` in `changeSource` in player-wrapper.js.

Would it be possible for the videojs-ima plugin to check if ads are playing before performing any seek or pause actions in that event handler? Or is there a better solution?

**Comment by Kiro705** [comment]
Closing issue based on closing issue https://github.com/googleads/videojs-ima/issues/735 .

If you would like farther investigation into this issue, please feel free to reopen this issue.
