### ISSUE TITLE
Continuous calls being made to client.js

### ISSUE THREAD

**Issue by Wouter85** [googleads/videojs-ima#745]
We encounter the following problem.
If you load up this page: https://googleads.github.io/videojs-ima/examples/simple/ 
you can see in the performance tab that every x second a timer function inside client.js is being made.

The calls are being made to this file: https://s0.2mdn.net/instream/video/client.js 
and to this function: 
`
S.prototype.Ha = function() { 
if (this.enabled) { 
var a = u() - this.$; 
0 < a && a < .8 * this.I ? this.o = this.R.setTimeout(this.V, 
this.I - a) : (this.o && (this.R.clearTimeout(this.o), 
this.o = null), 
this.dispatchEvent("tick"), 
this.enabled && (this.o = this.R.setTimeout(this.V, this.I), 
this.$ = u())) 
} 
} 
`

Is it possible to stop this calls? because it seems these calls are generating lots of GC garbage.

Please also see this video: http://puntoo.nl/Sep-27-2018.mp4

**Comment by Wouter85** [comment]
Any suggestions on why this is happening and how we can prevent it?

**Comment by ypavlotsky** [comment]
Hi Wouter85, this is something that's part of the IMA SDK that videojs-ima uses, so we can't disable or modify it.
