### ISSUE TITLE
ad plays in background while content is paused full-screen on iPhone

### ISSUE THREAD

**Issue by lezoudali** [googleads/videojs-ima#747]
Going fullscreen while the ad is playing doesnt behave as expected.
The ad plays in the background but the fullscreen player show the video content paused.

steps to reproduce:
1. visit this [url](http://glimmer.hearstapps.net/api.html?embedId=49b9c982-bd8b-4a54-ab9f-3468e4b18713&dataLayer=none&adTag=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fsingle_ad_samples%26ciu_szs%3D300x250%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvast%26unviewed_position_start%3D1%26cust_params%3Ddeployment%253Ddevsite%2526sample_ct%253Dskippablelinear%26correlator%3D&aspectRatio=16%3A9&volume=1) (on iPhone)
2. Press play and click on fullscreen button while the ad is playing.

package.json dependencies:
`"videojs-ima": "^1.4.0",`
`"video.js": "^6.6.0",`

**Comment by dilburt** [comment]
I don't have an iPhone here to test with but this sounds like the issue where the default player intercepts inline videos. Try placing playsinline=1 webkit-playsinline=1 as parameters on the <source src= line in your <video element definition as follows:

<video id="my-video (other settings)
<source src="mydomain.com/myvideo.mp4" playsinline-1 webkit-playsinline=1

You may need to make sure you only use these parameters for iPhones since I've noticed them causing problems in other environments, especially in Firefox.

D

**Comment by hrehman200** [comment]
@dilburt I applied your settings .. but still having the issue. This happens on iOS devices. Looks like the default player uses our videojs stream in full screen .. and thus does not use the ima-sdk container's view.

**Comment by minasaywhat** [comment]
We had to set google.ima.settings.setDisableCustomPlaybackForIOS10Plus(true); in our player implementation to support skippable ads on iphone - a requirement from our Advertisers, business stakeholders and for the audiences on our sites (UX). 

Apparently that change causes ad playback to break when users click the full-screen button on mobile - which leads to a really horrible experience, and clearly this is a known issue, as I see it noted in the Google IMA SDK docs: 
https://developers.google.com/interactive-media-ads/docs/sdks/html5/skippable-ads

Do you have an ETA for this fix, so we can support skippable ads AND the full-screen button during ad playback (a requirement for Innovid certification and our sponsors)?

**Comment by Kiro705** [comment]
Hi all,

In regards to setting up a player using IMA, there is not a single set-up for every possible playback scenario. Please refer to this [Custom Playback APIs for IMA HTML5 and Mobile Safari guide](https://ads-developers.googleblog.com/2017/06/new-custom-playback-apis-for-ima-html5.html) for more information.

Also, feel free to reach out here if you continue to have issues.
