### ISSUE TITLE
response timeout is not supported!!!

### ISSUE THREAD

**Issue by yanfaingold** [googleads/videojs-ima#748]
i was implementing your plugin and it seems way better then the mail online one but i found a big setback.. , while implementing the plugin i found no way to set up the response timeout which is possible in the mail plugin (loadVideoTimeout and vastLoadTimeout not helping).

to reproduce the issue i just set a timeout on the response using fiddler, in the mail online plugin setting a higher response timeout still worked while in the ima i couldnt find any solution to this issue.

is there any solution to this?

the error i recieve is:  AdsLoader error: AdError 301: Ad request reached a timeout.

**Comment by Kiro705** [comment]
Hi @yanfaingold ,

I am not familiar with the mail plugin, but would like to help debug your issue.

Do you have a code sample or test page that you could share?
