### ISSUE TITLE
for streaming m3u8 files

### ISSUE THREAD

**Issue by fahadpk01** [googleads/videojs-ima#752]
This is the code from this page: https://www.npmjs.com/package/videojs-ima

> 

<html>
  <head>
    
    <link href="path/to/video-js.css" rel="stylesheet">
    <link rel="stylesheet" href="path/to/videojs-contrib-ads.css" />
    <link rel="stylesheet" href="path/to/videojs.ima.css" />
  </head>
 
  <body>
    <video id="content_video" class="video-js vjs-default-skin"
        controls preload="auto" width="YOUR_VIDEO_WIDTH" height="YOUR_VIDEO_HEIGHT">
      <source src="PATH_TO_YOUR_CONTENT_VIDEO" type="YOUR_CONTENT_VIDEO_TYPE" />
    </video>
    
    <script src="/path/to/video.js"></script> 
    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script> 
    <script src="/path/to/videojs-contrib-ads.js"></script> 
    <script src="/path/to/videojs.ima.js"></script> 
    <script src="player.js"></script> 
  </body>
</html>

In player.js, load the ads library and set up the IMA plugin:

var player = videojs('content_video');
 
var options = {
  id: 'content_video',
  adTagUrl: 'YOUR_AD_TAG'
};
 
player.ima(options);

> 

**MY PROBLEM**

When i changed the "source src"  to m3u8" and type with "application/x-mpegURL" /> in codepen it did not work and gave error "No compatible source was found for this media"

Can anyone tell me the correct and complete working code for m3u8 streaming files with google ads?

Regards

**Comment by fahadpk01** [comment]
I need someone to provide me a working and correct code for m3u8 files with google ads. I am not a programmer but i tried and i am not able to find the correct code.

**Comment by fahadpk01** [comment]
![screenshot_2](https://user-images.githubusercontent.com/43779347/46408416-84c7ae00-c72b-11e8-96e1-fe03588c351b.png)

**Comment by fahadpk01** [comment]
Can we edit the above code for m3u8 or is there a completely different code for m3u8 with google ads?

**Comment by mimse** [comment]
What formats your ads are delivered to the browser in. Is as far as I know setup in DFP.

The Google IMA SDK will then choose the format that best goes with the browser used. 

ex. HLS (m3u8) for Safari.

Try to play around with 

https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

And look at the network traffic.

**Comment by fahadpk01** [comment]
I simply need to play m3u8 files with videojs player that plays google pre roll ads and where i just have to insert my unique adsense ad id in "ad url tag" field.

**Comment by pradhyumn94** [comment]
@fahadpk01  IMA  SDK  doesn't play  m3u8  streams even   where  they are supported.
If you want to  discuss about implementing your  own  vast parser  and ad player, I can provide some insight as I  have already done  same  for TIMES OF INDIA business.

**Comment by Kiro705** [comment]
Hi @fahadpk01 ,

I was able to set up a player playing a m3u8 stream with a preroll. Can you share any sample code or test page where you are running into an error?

**Comment by fahadpk01** [comment]
Exactly, this is what i am looking for. I need to set up a player with a
pre roll using m3u8. Can you help me set up that










Thanks & Regards,
*Fahad Aftab*
*Managing Director | My Online Campaign*
*support@myonlinecampaign.net <support@myonlinecampaign.net>|
www.myonlinecampaign.net <https://www.myonlinecampaign.net>*

<http://drprem.com/>
Connect with Fahad
Email <support@myonlinecampaign.net> | Twitter
<https://twitter.com/mocampaign> | LinkedIn
<https://www.linkedin.com/in/fahad-aftab> | Facebook Page
<https://www.facebook.com/MyOnlineCampaign> | Skype - myonlinecampaign

**Comment by Kiro705** [comment]
If you follow the example set up but use a m3u8 source, I was able to get it to work.

**index.html**
```
<html>
  <head>

    <link href="//vjs.zencdn.net/6.7/video-js.min.css" rel="stylesheet">
    <link rel="stylesheet" href="./sample.css">
  </head>

  <body>
    <video id='content-player' class="video-js">
        <p class='vjs-no-js'>
            To view this video, please enable JavaScript and consider upgrading to a web browser that
            <a href='https://videojs.com/html5-video-support/' target='_blank'>supports HTML5 video</a>
        </p>
    </video>

    <script src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script src="ads.js"></script>
  </body>
</html>
```

**ads.js**
```
import videojs from 'video.js';
import 'videojs-contrib-ads';
import 'videojs-ima';

var videoOptions = {
  controls: true,
  sources: [{
      src: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8'
  }]
};

var player = videojs('content-player', videoOptions);

var imaOptions = {
  adTagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator='
};

player.ima(imaOptions);
```

**sample.css**
```
.ima-ad-container {
    display: none;
}
```
