### ISSUE TITLE
Support video.js 7.x

### ISSUE THREAD

**Issue by orlov-vo** [googleads/videojs-ima#753]
Hello!

What about video.js 7.x?

**Comment by minasaywhat** [comment]
When will videojs-ima support video.js 7.x?

**Comment by cristian-atehortua** [comment]
@dioramayuanito Yeah, it is possible to use videojs-ima with video.js 7.x but only if you are not using a package manager. When you use a package manager like npm, a different version of video.js is installed just for videojs-ima. That causes that the plugin is not registered in the video.js object that you are using in your app but in the other video.js object.

**Comment by gschoppe** [comment]
We are currently in the process of testing the version bump to 7.x support, to ensure that there are no unexpected conflicts.

**Comment by bcomerford** [comment]
Package manager like npm was working for 7.6 but not 7.7 for me. Any other reports of this?
