### ISSUE TITLE
Skip ad programmatically

### ISSUE THREAD

**Issue by mihalikv** [googleads/videojs-ima#755]
Hello,
I have following case:

1. pre-roll + video
2. video
3. video
4. pre-roll + video
5. video
6. video

I have just one VMAP file where i have defined pre-roll. Everytime when i want to show pre-roll i am calling following functions:

```
this.player.ima.setContentWithAdTag(
    this.currentVideo.url,
    this.adData.video.ad.googleUrl,
    false);
this.player.ima.requestAds();
```

When i want to not show Ad i just don't run this code but on start and on end of video there is some timeout and player waiting for ad and loading spinner is shown. 

Question: Is it possible somehow tell to ima plugin to not load any ad and just skip to another video ?

**Comment by Kiro705** [comment]
Hi @mihalikv ,

I wanted to check if you found a solution to your issue or if you wanted us to look into it.

Jackson
IMA SDK DevRel

**Comment by mihalikv** [comment]
Hi @Kiro705 ,
I am not sure how I solve this issue, it was year ago :(. So we can close this issue for now.
