### ISSUE TITLE
iOS - Player closes after preroll and new player opens to play new content

### ISSUE THREAD

**Issue by TylerZubke** [googleads/videojs-ima#758]
If you view one of the samples on iOS (https://googleads.github.io/videojs-ima/examples/simple/), you can see after the preroll finishes you briefly see the main webpage again, then the video opens in a new view. Is there a way to have the main content play in the same view the preroll is shown in?

**Comment by Kiro705** [comment]
Hi @TylerZubke ,

I wanted to ask if you are still experiencing this issue, or if you had found a solution to it?

**Comment by TylerZubke** [comment]
@Kiro705 

I ended up using a different plugin on iOS because I couldn't get around this issue. I'll try the newest version of this plugin at some point and see if the issue is still occurring.
