### ISSUE TITLE
AdUI not cleaned up properly after zapping

### ISSUE THREAD

**Issue by rhodh** [googleads/videojs-ima#760]
### Description

When zapping mid advert to a stream with no adverts enabled the AdUI is not cleaned up properly.

### Steps to Reproduce

* Download the example demo showcasing the error from [here](https://github.com/rhodh/AdUiNotCleanedUp).

* Startup the project.

* Load Stream One and wait for adverts

* Zap to Stream Two

#### Expected Results

AdUi is cleaned up and Stream Two plays with no issue.

#### Actual Results

AdUi is not cleaned up and we cannot interact with the player controls.

### Potential fix
I've created a pull request to fix the issue https://github.com/googleads/videojs-ima/pull/727.

### Versions

**videojs-contrib-ads version**:  6.4.1

**Video-js version**: 7.2

**videojs-ima version**:  1.5.1

### Platforms

**Browsers**:  Chrome v69

**OS/Devices**: Windows 10

**Comment by gschoppe** [comment]
a fix is now committed.
