### ISSUE TITLE
Ads pause/resume on click instead of click through on mobile

### ISSUE THREAD

**Issue by nickersonr** [googleads/videojs-ima#762]
The issue is that preroll ads pause/resume on click rather than trigger navigation to the click through url for the ad - but only on mobile devices.

I've been wrestling with this in my implementation so I went back to the advanced example and found the same out-of-the-box behavior with those files. I changed the relative links to absolute just to avoid downloading those files, but otherwise I'm just using the raw example `index.html`, `ads.js` and `style.css` files served via python SimpleHTTPServer. I see this when testing in Chrome as well as on an iOS device.

To reproduce:
1. serve up the advanced example files (somewhere)
2. with the browser window open in normal desktop mode, navigate to the example `index.html`
3. click the sample link to load the sample tag
4. click the play button and see the ad start playing
5. click the ad and see a new window open to the click through url
6. close ad window
7. put browser in mobile simulator mode (for Chrome: opt-cmd-j, toggle device toolbar, select a mobile device - I chose iPhone X)
8. navigate to/refresh example `index.html`
9. click the sample link to load the sample tag
10. click the play button and see the ad start playing
11. click the ad and see the ad pause without opening a new window to the ad click through url as expected

Is this expected behavior that I missed described somewhere? If so, can it be changed to have mobile devices navigate to the ad click through urls? Thanks!

**Comment by nickersonr** [comment]
My slightly altered index.html, just in case that helps...
[index.html.zip](https://github.com/googleads/videojs-ima/files/2544392/index.html.zip)

**Comment by nickersonr** [comment]
So after a few days of poking at this and reading around it looks like this behavior is by design. In my case the only thing on the screen was a navbar at he top that was just tall enough to cover the "Learn More" button on the full screen video. I've now hidden that navbar during video playback and the "Learn More" button shows and works.

The lack of any kind of response here makes me think no one is reading these issues, but on the off chance this does get seen I'd like to suggest finding some way to surface these kinds of issues and make them more visible. I had to dig into update notes 3+ years old (https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/history) to find the information that ads no longer had a full screen tap target. If issues like this are already presented somewhere that I managed to not find (entirely possible), then please point me in that direction so I can refer to that resource with questions like this in the future.

**Comment by canhnm** [comment]
This is designed. On mobile there will be something like "Learn More" button to click through, not the whole player!
