### ISSUE TITLE
IMA SDK - videojs-ima advanced options

### ISSUE THREAD

**Issue by andip42** [googleads/videojs-ima#767]
Hello,

I'm just diving into the world of IMA SDK.  I have been able to tweak the sample Google provides but 
one thing I would like to do is pause the ad on the last frame of the video and add an "learn more" button and a replay button.  Does anyone have any experience with this?

[index2.html.zip](https://github.com/googleads/videojs-ima/files/2635121/index2.html.zip)

**Comment by canhnm** [comment]
FYI: Learn More button handle by the SDK and can not be changed!

**Comment by andip42** [comment]
Thank you for the help
