### ISSUE TITLE
VAST Error 1009: Empty Response freezes video playback on mobile, works on desktop

### ISSUE THREAD

**Issue by hydrosquall** [googleads/videojs-ima#768]
We are using video.js `7.1.0`. When an empty VAST document comes back, the content video plays on desktop, but comes up paused on mobile (IOS 12 Chrome, Safari, etc).

Steps to reproduce

- Visit this site on Desktop: http://staging.aspireist.com/index.html . Click the video thumbnail. Observe the video begin to play.
- Visit this site on Safari, tap the video thumbnail. The video will load, paused, with the loading spinner stuck on top of the video. You need to manually tap the "play" triangle in the bottom controls to get the video to play
- In contrast, visit a different page (http://staging.aspireist.com/season1.html) on either platform, and the video will play after an ad- this is because the other pages have ad tags which are guaranteed to return a video, and so the empty ad tag condition never happens.

The ad tag that we have in place returns an empty VAST document, so there is not ad to play. In desktop, the video just plays as if no video was expected (this is the desired behavior). On mobile, the video is just paused.

We would like for the behavior to be the same on desktop and mobile (for the video to play if even if the ad tag VAST response is empty), and am looking for advice about whether this is something others have experienced before. I wonder if the difference in trigger event (`click` vs `touchstart`) might have caused within this library, or if the code used by this page is using the plugin improperly.

Thanks for your consideration!

**Comment by Kiro705** [comment]
Hello @hydrosquall ,

Could you please try reproducing this issue? I believe it may have been fixed with [v1.7.2 of the plugin](https://github.com/googleads/videojs-ima/releases/tag/v1.7.2).
