### ISSUE TITLE
Does VideoJS-IMA Support DAI ?

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#772]
Hello All,

I'm very sorry, I don't get a clue, where should I write this question.
Does VideoJS-IMA Support DAI ? i mean Dynamic-Ads-Insertion from Google.
Thanks alot.

Best Regards.

**Comment by dioramayuanito** [comment]
from my perspective, VideoJS-IMA is an IAB doc implementation (VAST, VPAID, VMAP etc). Google DAI is other concept of Ads / Stiched Ads that mixin the LiveStreaming and Ads in 1 stream from a Server directly. cmiiw.

**Comment by ott-web** [comment]
I work for a company that uses Google IMA SDK in production and we currently use a different player. I would like to see video.js add this support. It's actually rather easy if you already have the server-side setup and working properly.

https://developers.google.com/interactive-media-ads/docs/sdks/html5/dai/quickstart

**Comment by dioramayuanito** [comment]
you can follow this project https://github.com/googleads/googleads-ima-html5-dai and for VideoJS you should use videojs-hlsjs-plugin as HLS Engine for VideoJS.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Thank you @dioramayuanito for providing the answer.

**Comment by FullstackJack** [comment]
@dioramayuanito I'm more curious to know if this will ever be implemented on `videojs-contrib-ads`.

https://github.com/videojs/videojs-contrib-ads
