### ISSUE TITLE
IMA Post-roll disabling autoplay

### ISSUE THREAD

**Issue by rhodh** [googleads/videojs-ima#773]
**Description**
After a post-roll has occurred autoplay is set to false so subsequent zaps stops the player from autoplaying streams

**Steps to Reproduce**
Download the example demo showcasing the error from [here](https://github.com/rhodh/ima-post-roll-disabling-autoplay
)

1) Start up the project
3) Click "LoadStream" and wait for post-roll to finish. 
4) Load the stream again note Autoplay has been disabled

**Expected Results**
Subsequent "zaps" stream should autoplay 

**Actual Results**
Stream fails to autoplay

**Potential fix**
From my investigation issue is due to the function `PlayerWrapper.onAllAdsCompleted()` it looks like the line `this.vjsPlayer.autoplay(false);` has been added to stop the stream being replayed when resetting the source. There's a question why the src is can change after a post-roll and why is setting the src necessary. But the main issue is the `this.h5Player.src` and `this.contentSource` are not equivalent, `this.h5Player.src` doesn't store the original URL but a blob URL.  A more valid check would be to check against `this.vjsPlayer.currentSrc()` like how `this.contentSource` is initialised, this would in most cases I have seen stop the src been set unnecessarily.

Pull request here: 
https://github.com/googleads/videojs-ima/pull/774 

**Versions**
videojs-contrib-ads version: 6.4.1

Video-js version: 7.2

videojs-ima version: 1.5.2

**Platforms**
Browsers: Chrome v71

OS/Devices: Windows 10

**Comment by zgzong** [comment]
@gschoppe Sorry to bring you to this thread directly, could you review this PR while you prepare next release, please? 
When finishing post-roll ad, the player don't need update the source, @rhodh pointed out this.h5Player.src is either a hosted media file or a blob, that won't equal to this.contentSource, then it reset the source and removed the autoplay attribute which changed the original player behaviour.

**Comment by gschoppe** [comment]
Reviewed and merged, just keep an eye out for orphaned comments when you strip code :wink:
