### ISSUE TITLE
Catch 'Unexpected startLinearAdMode invocation (Preroll)' warning

### ISSUE THREAD

**Issue by zhulduz** [googleads/videojs-ima#775]
Hi,
I use playlist example with autoplay settings for video.js.

Sometimes when I switch src for the player, I get `Unexpected startLinearAdMode invocation (Preroll)'` warning  => autoplay doesn't work.

I researched the issue, the flag `this.contentResuming` from `video-contrib-ads` is false (at the error situation), but I couldn't find where this flag becomes to false (there are two places at `video-contrib-ads`, where `this.contentResuming` is set to false, none of them isn't called)

Can you help me understand, how I can fix this issue?

**Comment by mimse** [comment]
Hi @zhulduz I was having the same issue. You can see my PR here

https://github.com/videojs/videojs-contrib-ads/pull/454

Was not accepted tho, but maybe it can give you a hint to how to fix the issue.

With regards,

Morten

**Comment by cristian-atehortua** [comment]
The Warn is caused because videojs-ima is calling this method after adstimeout event occurs.

This bug makes the player's behavior erratic. For example the class `vjs-ad-playing` is not added to the videojs element while the ad is playing.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months. 

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0)

Thank you!

**Comment by stomata** [comment]
I currently encounter the same issue.
While changing src when pre-roll is playing. 
these are the versions I am using.
    "video.js": "7.7.5",
    "videojs-contrib-ads": "6.6.5",
    "videojs-ima": "1.8.0"

And for some reasons, this is only happening on Safari browsers for me...
