### ISSUE TITLE
Getting "No compatible source was found for this media error" when used "this.player.ima.changeAdTag"

### ISSUE THREAD

**Issue by Kumaran29** [googleads/videojs-ima#777]
Hi,We are using video js ima with hls. Player is set to autoplay so we deliver multiple videos and ads in single session, when the first video gets completed the second video starts and the preroll ads starts (we are changing the source of ad  during video ended event) and plays when the ad ends. However we are getting "VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media error" 
when used  "this.player.ima.changeAdTag("https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator="); "
demo : https://console.ex8.io/vast_mediation/test.html

Is there something we are doing wrong?

**Comment by arnaudcasame** [comment]
Hi,

The issue you reported does not seem to be with the IMA SDK. Given the error message received, the VideoJS part if the plugin is telling you that the media type passed to the videojs src is not supported. This is not an issue with Videojs-IMA, it's an issue with the media type of your video content not being supported.

**Comment by arnaudcasame** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
