### ISSUE TITLE
Some Ads Requests Return Empty VAST Tags

### ISSUE THREAD

**Issue by AKlein920** [googleads/videojs-ima#778]
Hello!

Thank you for your plugin - it has been extremely useful to us across a variety of projects and use cases.

Our newest project integrating Google ads uses React and only one instance of a VideoJS player, playing HLS streams. We request ads after the first 10 seconds that the user sits on the page, and then every 10 minutes. Our issue is that some ads requests return empty VAST tags, so ads are not played at our desired intervals. 

Our implementation involves dynamically appending the 3 necessary scripts (Google IMA SDK, videojs-contrib-ads, and videojs-ima), then instantiating the IMA plugin on the player instance if it hasn't been instantiated already, and finally requesting ads. For subsequent ads requests, we use `setContentWithAdTag` and then request ads. While the requests are made, the majority of our VAST tags seem to return empty. The IMA plugin then logs the message: 

> AdsLoader error: AdError 1009: The VAST response document is empty.

Here's the implementation:
```
handlePlayAd = () => {
    const {
      adTagUrl,
      adChannels,
      incrementAdsPlayed,
      player,
      toggleIsPlayingAd,
    } = this.props;

    const currentWindowLocation = encodeURIComponent(window.location.href);
    let updatedAdTagUrl;

    utils.appendAdsScripts();

    if (adTagUrl.match('#####')) {
      updatedAdTagUrl =
        adTagUrl.replace('#####', String(adChannels.default)) +
        currentWindowLocation;
    } else {
      updatedAdTagUrl = adTagUrl + currentWindowLocation;
    }

    const imaOptions = {
      id: player.id_,
      adTagUrl: updatedAdTagUrl,
    };

    this.handlePlayAdTimer = setTimeout(() => {
      try {
        if (typeof player.ima === 'function') {
          player.ima(imaOptions);
          player.ima.requestAds();
        } else {
          player.ima.setContentWithAdTag(null, updatedAdTagUrl, true);
          player.ima.initializeAdDisplayContainer();
          player.ima.requestAds();
        }
      } catch (err) {
        console.log(err); // eslint-disable-line
      }
    }, 3000);

    player.on('adsready', () => {
      player.pause();
    });

    player.one('adstart', () => {
      incrementAdsPlayed();
      toggleIsPlayingAd(true);
    });

    player.one(['adend', 'adserror', 'adskip', 'adscanceled'], e => {
      toggleIsPlayingAd(false);
      player.play();
      player.trigger('play');
      this.setAdTimer();
      // console.log(e);
    });
  };
```
We've set up a test page if you'd like to see what's going on: [https://public.earthcam.net/tJ90CoLmq7TzrY396Yd88IyNkZovC7VvK3MKrO-H1OY!/National%20Aquarium%20Cam/Shark%20Cam/Live](url)

We are using:
VideoJS 7.1.0
videojs-contrib-ads 4.2.8
videojs-ima 0.8.0

Do you have any insights on this issue? Thanks in advance for your help!

In case this is useful, here's the debug log for 3 requests - the first 2 came back with empty tags, but the third succeeded:

> [  0.019s] [ima.loader.AdsLoaderWrapper] Requesting ads using new ads loader.
bridge3.272.0_debug_en.html:897  [  0.021s] [ima.loader.AdsLoaderWrapper] requestAds, processing external request.
bridge3.272.0_debug_en.html:897  [  0.022s] [ima.loader.SequentialAdsLoader] Enqueued new request.
bridge3.272.0_debug_en.html:897  [  0.022s] [ima.loader.SequentialAdsLoader] Starting request from queue.
bridge3.272.0_debug_en.html:897  [  0.363s] [ima.loader.SequentialAdsLoader] Starting request from queue.
videojs.ima.js:9 AdsLoader error: AdError 1009: The VAST response document is empty.
bridge3.272.0_debug_en.html:897  [ 13.385s] [ima.loader.AdsLoaderWrapper] Requesting ads using new ads loader.
bridge3.272.0_debug_en.html:897  [ 13.385s] [ima.loader.AdsLoaderWrapper] requestAds, processing external request.
bridge3.272.0_debug_en.html:897  [ 13.385s] [ima.loader.SequentialAdsLoader] Enqueued new request.
bridge3.272.0_debug_en.html:897  [ 13.386s] [ima.loader.SequentialAdsLoader] Starting request from queue.
bridge3.272.0_debug_en.html:897  [ 13.708s] [ima.loader.SequentialAdsLoader] Starting request from queue.
videojs.ima.js:9 AdsLoader error: AdError 1009: The VAST response document is empty.
bridge3.272.0_debug_en.html:897  [ 26.720s] [ima.loader.AdsLoaderWrapper] Requesting ads using new ads loader.
bridge3.272.0_debug_en.html:897  [ 26.721s] [ima.loader.AdsLoaderWrapper] requestAds, processing external request.
bridge3.272.0_debug_en.html:897  [ 26.722s] [ima.loader.SequentialAdsLoader] Enqueued new request.
bridge3.272.0_debug_en.html:897  [ 26.723s] [ima.loader.SequentialAdsLoader] Starting request from queue.
bridge3.272.0_debug_en.html:897  [ 27.030s] [ima.loader.AdSourceFactory] Creating VastAdSource.
bridge3.272.0_debug_en.html:897  [ 27.335s] [ima.loader.AdSourceFactory] Creating VastAdSource.
bridge3.272.0_debug_en.html:897  [ 27.338s] [VastAdSource] processInlineAd, successCallback with 1 ads
bridge3.272.0_debug_en.html:897  [ 27.338s] [VastAdSource] processInlineAd, successCallback with 1 ads
bridge3.272.0_debug_en.html:897  [ 27.341s] [ima.loader.SequentialAdsLoader] Starting request from queue.
bridge3.272.0_debug_en.html:897  [ 27.355s] [ima.managers.AdsManagerFactory] createAdsManagerFromAds_, adType: video
bridge3.272.0_debug_en.html:897  [ 28.400s] [ima.vast.VastAdServerReporter] Reporting urls for event : show_ad

**Comment by canhnm** [comment]
You are using dfp vast right?
"https://googleads.g.doubleclick.net/pagead/ads?...."
So it is all about DFP ad delivery!

Let try with one of the vast uri from Google example page and see how is going?
https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0).

Thank you!
