### ISSUE TITLE
Wrong dimension (width and height) while Fullscreen then Rotate to Landscape in Postoll VMAP

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#779]
Hello friends,

I got something interesting when playing VMAP (preroll+midroll+postroll). Only in postroll, if we click Fullscreen then device rotated in a landscape orientation, Ad will be displayed in wrong dimension and truncated just like displaying in a portrait orientation. I knew that it happened because of Fluid style in VideoJS and only on some VMAP cases.
are there any chance how to avoid these wrong dimension of Postroll VMAP?
Thanks a lot.

Best Regards.

NB: I'm using VideoJS v7.1.0 + VideoJS-HLSjs-Plugin + VideoJS-IMA v1.5.2 + VideoJS-Contrib-Ads v6.6.1. Sorry i can't make reproduce of URL because my experimental server is behind a VPN of my company. Playing VMAP from Android device, Opera Android browser latest edition.

**Comment by dioramayuanito** [comment]
https://ibb.co/683Wv9h

**Comment by dioramayuanito** [comment]
https://ibb.co/sHXPT8f

**Comment by dioramayuanito** [comment]
OK i got the clue. inside PlayerWrapper.prototype.localContentEnded wes should avoid clearInterval of resizeCheckHandler. i commented that line and this bug goes away.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0)

Thank you!
