### ISSUE TITLE
"imasdk googleapis" as referral

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#782]
Hi all,
i have a problem with referral..
If i set VPAIDMode as INSECURE in Chrome mobile, i haven't any problems with referral but i have this error in console: "VPAIDLoader is not defined" on ima3.js; like this:
<img width="694" alt="schermata 2019-02-07 alle 12 14 32" src="https://user-images.githubusercontent.com/23355148/52408114-67885f00-2ad2-11e9-84f1-e419ba4f400f.png">

If i set VPAIDMode as ENABLED instead, i haven't this error but my referral is "imasdk googleapis"..
How can I resolve this problems???

Regards,
A.

**Comment by ibraalek10** [comment]
Hi all,
Can you help me??

A.

**Comment by dioramayuanito** [comment]
ENABLED

VPAID ads are enabled using a cross domain iframe. The VPAID ad cannot access the site. VPAID ads that depend on friendly iframe access may error. This is the default.

INSECURE

VPAID ads are enabled using a friendly iframe. This allows the ad access to the site via JavaScript.

**Comment by ibraalek10** [comment]
Hi @dioramayuanito ,
thanks for the answer, but my question was another..
I say the difference between ENABLED and INSECURE, in fact for my VPAID i use the INSECURE mode but when i use this mode is generated the error in console "VPAIDLoader is not defined" on ima3.js;"..

**Comment by dioramayuanito** [comment]
you got the bug from ima3.js https://groups.google.com/forum/m/#!topic/ima-sdk/JfZpbjfyF00

**Comment by ibraalek10** [comment]
Hi @dioramayuanito ,
i saw too this topic and doesn't resolve my problem because i have this error on chrome mobile..

**Comment by dioramayuanito** [comment]
you should wait loader.js for fully loading

**Comment by dioramayuanito** [comment]
something like this : 

so something like this:

iframe.contentWindow.document.write('<script id="adloaderscript" src="' + url + '"></scr' + 'ipt>'); const script = iframe.contentWindow.document.querySelector('#adloaderscript') script.onload = function() { // iframe.contentWindow['getVPAIDAd'] will be available here }

**Comment by dioramayuanito** [comment]
https://stackoverflow.com/questions/30393247/how-to-listen-to-a-script-tags-onload-event

**Comment by dioramayuanito** [comment]
you should use onload event of script tag

**Comment by dioramayuanito** [comment]
if the screenshot that you provide can be rewrite like this : 

<script>function scriptonload() { var loader = VPAIDLoader(false, "goog_numbers"); }</script>
<script src="//googleapis.com/loader.js" onload="scriptonload();"></script>

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0)

Thank you!
