### ISSUE TITLE
The event 'volumechange' does not bubble up to the ad

### ISSUE THREAD

**Issue by Grafluxe** [googleads/videojs-ima#783]
Thanks for creating this VideoJS plugin. When working to support our ad layer across players, we've found that when using VideoJS with your plugin, our ad does not receive `volumechange` events.

Note that when testing with other players, the event is received as expected.

```
initAd(width, height, viewMode, desiredBitrate, creativeData, environmentVars) {
  videoSlot = environmentVars.videoSlot;
}
...
videoSlot.addEventListener("volumechange", DOES_NOT_GET_CALLED);
```

Thanks

**Comment by Grafluxe** [comment]
Hello. Can you provide a way to solve this if there are no immediate plans to release a patch?

**Comment by canhnm** [comment]
Did you add listener to the ima AdEvent google.ima.AdEvent.Type.VOLUME_CHANGED ?

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0) 

Thank you!
