### ISSUE TITLE
ima ads playing but not display in video player

### ISSUE THREAD

**Issue by tejas143trj** [googleads/videojs-ima#786]
ima ads playing but not display on videoplayer with videojs class vjs-fluid please help

**Comment by arnaudcasame** [comment]
Hi,

Were you able to reproduce this behavior by making these changes on our [Simple example](https://github.com/googleads/videojs-ima/tree/master/examples/simple)? The ads are displayed as expected when I use this class against my video player.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!

**Comment by buinhansinh** [comment]
Hello! Did you check your latest version ?
div[id*=ima-ad-container] always have display: none , which makes the ads playing but not displaying

**Comment by buinhansinh** [comment]
Ah I found the issue. There is an edge case, when the play button is not in the center. I have to add class 'vjs-big-play-centered' to video
