### ISSUE TITLE
showCountdown problem

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#787]
Hello all,
we currently use VideoJS v7.1.0 and VideoJS-IMA v1.5.2. we have a problem with showCountdown option. if we set true, it shows double texts, but if we set false, it shows nothing. How to avoid double texts in ima countdown?

**Comment by dioramayuanito** [comment]
https://ibb.co/ZKDdzrw

**Comment by arnaudcasame** [comment]
Hi,

It seems like your ad already has a countdown implemented, when you set showCountdown to true, Videojs-IMA and the ad's countdown are displayed and overlaying each other. You would have to turn one of them off so you don't have both countdowns being displayed simultaneously and overlaying each other. The other option would be for your ad provider to display their countDown layout at the top of the video player.
