### ISSUE TITLE
Empty VAST causes player to be unable to be interacted with

### ISSUE THREAD

**Issue by zergnetkim** [googleads/videojs-ima#789]
This is similar to issue #778 - we are using adResponse to specify a VMAP that includes direct non-DFP calls to the advertiser SpotX.

SpotX does not have 100% fill, as no ad partner can reasonably be expected to have.

The problem is:  when SpotX returns an empty VAST tag as their response, the Ad playback subroutine begins, showing the ima-ad-container... but because there is no ad, there is no "end of ad" event to remove the ima-ad-container, leaving an invisible shim over the player and rendering the player unable to be interacted with.

How can I prevent this?  Is there another callback I can hook into to hide the ad container in the event of an empty VAST tag?  Is there a way I can intercept the VAST response to validate it in setAdBreakReadyListener?

Demo page here: http://dev.thelist.com/vid.php
Ad plays after 30 seconds, then behavior can be observed.

**Comment by zergnetjake** [comment]
Note:  I'm using setAdBreakReadyListener because I only want to play ads if the user has unmuted the player

**Comment by canhnm** [comment]
Take a look at the example https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js

You can add listener to the VAST response like:
`Ads.prototype.adsManagerLoadedCallback = function() {
  var events = [
    google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
    google.ima.AdEvent.Type.CLICK,
    google.ima.AdEvent.Type.COMPLETE,
    google.ima.AdEvent.Type.FIRST_QUARTILE,
    google.ima.AdEvent.Type.LOADED,
    google.ima.AdEvent.Type.MIDPOINT,
    google.ima.AdEvent.Type.PAUSED,
    google.ima.AdEvent.Type.RESUMED,
    google.ima.AdEvent.Type.STARTED,
    google.ima.AdEvent.Type.THIRD_QUARTILE
  ];

  for (var index = 0; index < events.length; index++) {
    this.player.ima.addEventListener(
        events[index],
        this.onAdEvent.bind(this));
  }

  this.player.on('adslog', this.onAdLog.bind(this));
};
Ads.prototype.onAdLog = function(data) {
  this.log('Ad log: ' + data.data.AdError);
};
 `
And following IMA SDK document you can add more events to listen to:
https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdError.ErrorCode.VAST_EMPTY_RESPONSE

Then the sample code will be:
`var events = [
    google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
    google.ima.AdEvent.Type.CLICK,
    google.ima.AdEvent.Type.COMPLETE,
    google.ima.AdEvent.Type.FIRST_QUARTILE,
    google.ima.AdEvent.Type.LOADED,
    google.ima.AdEvent.Type.MIDPOINT,
    google.ima.AdEvent.Type.PAUSED,
    google.ima.AdEvent.Type.RESUMED,
    google.ima.AdEvent.Type.STARTED,
    google.ima.AdEvent.Type.THIRD_QUARTILE,
          
    google.ima.AdError.ErrorCode.VAST_EMPTY_RESPONSE,
  ];`

**Comment by zergnetjake** [comment]
@canhnm google.ima.AdError.ErrorCode.VAST_EMPTY_RESPONSE is not a valid event listener type, I think you were thinking of google.ima.AdErrorEvent.Type.AD_ERROR - but this is already bound inside videojs-ima to remove the adContainer which is exactly what I need to do.

google.ima.AdErrorEvent.Type.AD_ERROR is never fired for an empty VAST tag.

But your comment led me down a different path.  Rather than use that array of events, I used

`for ( var index in google.ima.AdEvent )`

This led me to google.ima.AdEvent.Type.LOG which says: "Fired when a non-fatal error is encountered. The user need not take any action since the SDK will continue with the same or next ad playback depending on the error situation."

I added this code, which seems to solve the problem though I have more testing to do:

```           
var player = videojs(v,{debug: true});
player.ima({
     adsManagerLoadedCallback: function() {
          var cb = function(obj) {
               var adData = obj.getAdData();
               if ( adData && typeof( adData.adError ) !== undefined && adData.adError.getErrorCode() == google.ima.AdError.ErrorCode.VAST_EMPTY_RESPONSE ) {
                    this.ima.controller.adUi.onAdBreakEnd();
               }
          };
          var adman = this.ima.getAdsManager();
          adman.addEventListener(google.ima.AdEvent.Type.LOG, cb.bind(this));
     }.bind(player)
});
```

But in my opinion, this is still a bug in videojs-ima - this functionality should happen automatically rather than the user needing to create the code for the empty VAST condition being handled.

**Comment by arnaudcasame** [comment]
Hi,

In your use case, the AD_ERROR event should fire an EMPTY_VAST_ERROR type and then the adDisplayContainer should get released (display: none) after the ad error event was thrown.
I was not able to reproduce the issue using a VMAP where the first ad is an EMPTY VAST, it seems to be with your implementation.

**Comment by canhnm** [comment]
@zergnetjake Sorry I was misunderstanding.
Get the error return by using on('adserror'), then you can catch the empty error event and the code 1009:

this.player.on(
      'adserror',
      function(err) {
        console.log('ads error!');
        console.log(err);

      }.bind(this)
);

![image](https://user-images.githubusercontent.com/705656/54729495-74f73580-4bb6-11e9-8a6a-61f8ce411fac.png)

**Comment by arnaudcasame** [comment]
Are you using the latest version of the videojs-ima plugin? If not, try updating to the latest version of the plugin and test again.

Regards,
Arnaud

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0).

Thank you!
