### ISSUE TITLE
Making multiple ad requests with same adTagUrl

### ISSUE THREAD

**Issue by smithermansl** [googleads/videojs-ima#792]
I'm attempting to make multiple ad requests with videojs & videojs-ima.

This is taken from the HTML5 IMA SDK docs:

> When you request ads more than once, you need to let the ad server know that these are legitimate requests, and not accidental duplicates. The SDK will do this for you with two quick API calls:
> 1. Call destroy() on your AdsManager instance. This prevents any post-rolls from playing when you make the below call to contentComplete(). You'll get a new AdsManager when you make your next request.
> 2. Call contentComplete() on your AdsLoader instance. This resets the SDK so the new ad request doesn't look like a duplicate of the previous one.
> After making the two calls above, you can call requestAds() on your AdsLoader instance to get another set of ads to play for your new video.

But the docs also say to "maintain only one instance of AdsLoader for the entire lifecycle of your page. To make additional ad requests, create a new AdsRequest object but re-use the same AdsLoader."

Is there a way to reuse the same adTagUrl to make new ad requests on 'adend' events throughout the entire lifecycle of the page?

**Comment by arnaudcasame** [comment]
Hi,

You can make a new ad request on ALL_ADS_COMPLETED event with the same ad tag url. The AdsLoader will be reused and the same ad will play repeatedly, but don't forget to destroy the AdsManager before each request.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for a few months.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.0)

Thank you!
