### ISSUE TITLE
Ability to change Skip Ad buttons' location

### ISSUE THREAD

**Issue by hrehman200** [googleads/videojs-ima#793]
Currently, it looks like, there is no way to change Skip Ad button's location. It would be great, if you can add this feature.

**Comment by arnaudcasame** [comment]
Hi,

Currently, the [IMA SDK for HTML5](https://developers.google.com/interactive-media-ads/docs/sdks/html5/) doesn't have any API method that allow you to change the Skip Ad button's location. For the VideoJs-IMA plugin to provide such API, it would have to exist on the [IMA SDK](https://developers.google.com/interactive-media-ads/docs/sdks/html5/) side.

**Comment by hrehman200** [comment]
Hmm, in that case, we will have to wait till IMA-SDK provide it.
