### ISSUE TITLE
How to use for postroll only?

### ISSUE THREAD

**Issue by nightsurge** [googleads/videojs-ima#794]
This may be a noob question, but I can't find it in the docs anywhere, examples, or the api.

How do I use this plugin to only call postroll ads? I don't have the access to use VMAP rules to do it, I need to be able to trigger it manually via this plugin.

**Comment by arnaudcasame** [comment]
Hi,

There's currently no API method that would allow you to ignore pre-rolls, mid-rolls and only display the post-roll of an ad set up. However, you can set a VAST XML to deliver post-rolls to the IMA SDK, an example would be the [post-roll](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=) sample ad tag.

**Comment by nightsurge** [comment]
Hi, thanks for the reply.

I'm not trying to "ignore" pre-roll and mid-roll events. I'm saying I have a generic VAST/VPAID tag url and I want to specifically only use it for post-roll ads. It is not setup to support VMAP and there is no way for me to make it do what you suggest because I have no control over it. I was given the tag by my ad network and I'm just trying to use it in my videos as postroll to avoid annoying my users.

I found a workaround, but it seems dangerous:

`player.ima(options);
player.trigger('nopreroll');
player.one('ended', function(){
  player.ima.playAdBreak();
});`

**Comment by arnaudcasame** [comment]
Hi,

It's safe to use the **nopreroll** flag as it will prevent the ad to be displayed as a pre-rol. However, you could also request and play the ad when the video content ended. Doing this would allow you to not call the **nopreroll** flag but also not display the mid-rolls.
