### ISSUE TITLE
player.stop() dosen 't works on ads videojs

### ISSUE THREAD

**Issue by PilarCastro86** [googleads/videojs-ima#795]
HI! I'm trying to implement videojs with the IMA plugin, and i need to capture the stop and play event from a button outside the videobox in my react app. The thing is i capture the event on my buttons and works fine, but they dosen t work when i want to stop the ADS.. i don t have too much experience, so me bee i m doing something wrong..
i use this example

https://googleads.github.io/videojs-ima/examples/simple/

and here i cature the play/stop event:

  handlePlay = () => {
        if(this.props.showPlay == 'block'){
            const player = window.videojs(`#content_video`)
            player.play() //only work on the video not in ads video

        } else {
            const player = window.videojs(`#content_video`)
            player.pause() //only work on the video not in ads video
        }
   }

**Comment by arnaudcasame** [comment]
Hi,

Calling the .pause() API method on the player object (will pause the video content) won't pause the ad because the IMA SDK is using a different media player to display the ads. If you wanna pause the ad playback, you can call the player.ima.pauseAd() method.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
