### ISSUE TITLE
how can i use plugin in angular 2

### ISSUE THREAD

**Issue by elahehsn** [googleads/videojs-ima#797]
i want to use module in angular 2, but i get error: "player.ima is not a function"
`import videojs from 'video.js';`
`require('videojs-ima')`
`this.player = videojs(document.getElementById(el), options, function() {`
`var myPlayer = this, id = myPlayer.id();`
`var aspectRatio = 9/16;`
`function resizeVideoJS(){`
`var width = document.getElementById('myPlayer').parentElement.offsetWidth;`
	`myPlayer.width(width);`
	`myPlayer.height( width * aspectRatio );`
`}`
`resizeVideoJS();`
`window.onresize = resizeVideoJS;`
` });`
`this.player.ima({`
	`id: 'myPlayer',`
`adTagUrl: '....'`
`});`

**Comment by arnaudcasame** [comment]
Hi,

I see that you're importing the videojs-ima library in your project but didn't assign it to any variable. Can you try assigning it to a variable and then use this variable as a videojs player?

**Comment by elahehsn** [comment]
@arnaudcasame 
tnx for reply,
i fix error by importing videojs-ima in angular.json file, in scripts tag.
