### ISSUE TITLE
Skip ad automatically when skip ad button enabled

### ISSUE THREAD

**Issue by sudhakarsukumar** [googleads/videojs-ima#798]
Need to skip the ad by default when the skip button enabled after 4 or 5 seconds. Or else skip ad button triggers outside from the player. Similar to this example below by replacing the pause ad concept.
https://googleads.github.io/videojs-ima/exatomples/multiple/. Please help us with a solution to this. 

Thanks in advance.

**Comment by arnaudcasame** [comment]
Hi,

Assuming you call the skip button id "btn", you can register a click event on your skip button and then call `player.ima.getAdsManager().skip()` when your skip button is clicked. An example would be:
```
var bouton = document.querySelector("#btn");

bouton.addEventListener('click', function(){
  player.ima.getAdsManager().skip();
}, false);
```
Please note: For the ad to be skipped, it has to be a skippable ad.
