### ISSUE TITLE
AdsLoader error: AdError 1009

### ISSUE THREAD

**Issue by mhayajneh** [googleads/videojs-ima#799]
Hi,

As part of the sign-up process to AdSense AFV, Google requests a test page that demonstrates a player running a test AdSense AFV tag. However, when i run the test tag in Videojs-ima, i'm getting this error:

videojs.ima.js?ver=4.9.6:1368 AdsLoader error: AdError 1009: The VAST response document is empty. SdkImpl.onAdsLoaderError @ videojs.ima.js?ver=4.9.6:1368

The AdSense AFV tag works fine in the Videojs-ima and the VAST Inspector => https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector 

Any tips for me when trying to get AFV to load on our site?

**Comment by arnaudcasame** [comment]
Hi,

You might need to reach out to the Ad Manager Support Team to solve this issue. Some of your ad tag url parameters might be preventing the ad server from returning a complete VAST XML. Can you share the ad tag you were using when you encountered this issue?

**Comment by canhnm** [comment]
Is it related https://github.com/googleads/videojs-ima/issues/683 ?

**Comment by arnaudcasame** [comment]
Hi,

The issue described above is ad serving related, it is not caused by the VideoJS-IMA plugin, reaching out to your ad provider would be the only way to fix it.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!

**Comment by spormeon** [comment]
i'm getting this issue as well now, added ads.txt and nothing. The weird thing is , on a test page it works sparadically, when I put on the site template, where it has to be for the G rep to look, not a thing, zip, nada. no errors or anything and exactly the same code is the outside site test page
