### ISSUE TITLE
resume clip after AdsLoader error

### ISSUE THREAD

**Issue by gincius** [googleads/videojs-ima#80]
How to resume current clip playing, if I get adsloader error? Must click to resume play and this is annoying...

**Comment by shawnbuso** [comment]
Hi there,

Do you have a page where we can see this issue in action? Currently the plugin is triggering adserror on the player when this happens, which should result in the video resuming. I tested with our advanced example and it looks like it's behaving correctly - if I fill in "http://www.example.com" as the ad tag (which obviously does not return a valid VAST response) I see the AdsLoader error and the content plays.

**Comment by gincius** [comment]
Problem is after receiving this error: "AdsLoader error: AdError 1009: The VAST response document is empty."

**Comment by shawnbuso** [comment]
Hi,

Do you have a page where we can see this issue? I tested it on our sample page [here](http://googleads.github.io/videojs-ima/examples/advanced/) but I *do* see the content play after the response comes back empty.

**Comment by shawnbuso** [comment]
Going to close this issue for lack of repeatability / activity on the thread.
