### ISSUE TITLE
Common contrib-ads events

### ISSUE THREAD

**Issue by Swizz** [googleads/videojs-ima#804]
Hi, 

Working on our internal analytics tool we are looking at tracking Ads consumption.
But Videojs-IMA do not trigger all the events we are awaiting.

Following the [videojs-contrib-ads/docs/integrator/common-interface.md](https://github.com/videojs/videojs-contrib-ads/blob/master/docs/integrator/common-interface.md), 
Videojs-contrib-ads promote a convention on events to trigger.

I am open to work on a PR (have already signed the CLA) to implement all these standard events triggers.

Will you accept this such of contribution ? 

Cheer,

**Comment by gschoppe** [comment]
Hi Swizz,

We are happy to review outside PRs for inclusion into the project's codebase, but I cannot make any promises that a specific PR or feature request will be merged. We review feature sets and code quality carefully before accepting PRs, and we have to ensure that the code provided also matches the direction that the project is taking internally.

At a glance, it appears like a PR like this would match the general intentions and direction of the project, but we'd have to review the full code before making a final decision on that front.

Thanks,

Greg Schoppe
IMA SDK Team
