### ISSUE TITLE
Memory leakage issue while playing ad after each video in a playlist.

### ISSUE THREAD

**Issue by gizmeondev** [googleads/videojs-ima#805]
I am using videojs for playing a playlist with remote urls. My aim is to show an ad after each video is played and it worked after requesting ads in corresponding `player.ready` and `player.on("ended")` function. 
The memory used increases while playing an ad and then decreasing when completed, which is fine. But the lowering does not always reaches from where it starts. 
For example, assume the `player` is playing a video at **255 MB**, an ad is requested, which now turns to **310 MB**. After the ad is completed, the memory will now be **260 MB**, which means there is some leakage issue. 
Due to this, after a very long time, it consumes almost full memory which leads to device crash.
So any ideas on how to fix this?

**Comment by arnaudcasame** [comment]
Hi,

It seems that you're not destroying your adsManager after each ad. Please confirm if you are manually requesting an ad after each video content.

**Comment by gizmeondev** [comment]
Yes, I am manually requesting ad after each video ended.

**Comment by arnaudcasame** [comment]
Hi,

To destroy the [IMA SDK's AdsManager](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsManager) instance, you have to register to the ALL_ADS_COMPLETED event and then call the   ` this.player.ima.getAdsManager().destroy() ` method whenever this event is fired (all the ads are done playing). To get an idea of how to register to the ALL_ADS_COMPLETED event, you can take a look at the [Advanced sample](https://github.com/googleads/videojs-ima/tree/master/examples/advanced) implementation.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
