### ISSUE TITLE
Reloading the video player with a fresh ad after an event trigger is not working

### ISSUE THREAD

**Issue by chandanonline4u** [googleads/videojs-ima#810]
Issue
We are facing an issue with Reloading the video player with a fresh ad after an event trigger. In our case an event trigger can be a set timer for auto-refresh or click of a specific button on the UI. 

Overview
 We are using videojs ima plugin to display preroll ads. We have a custom play button and on click of this button we display the video player and it runs the ads; on the “ads end” event we are hiding the player. Everything is working perfectly till here in the first load of the video player. Problem starts when we want to Re-trigger and reload the player with a fresh ad on the same page without refreshing the entire page. 

Here is the link of test page: https://ascendeum.com/videoAd/test/index.html

**Comment by arnaudcasame** [comment]
Hi,

Can you confirm whether or not the `ended` event to which your player registered is being fired. This can be the reason why the ad playback doesn't occur when the content playback is completed.
**The part below:**
```
player.on('ended', function(){
      player.load();
      player.currentTime(0);
      player.ima.initializeAdDisplayContainer();
      player.ima.setContentWithAdTag(null, adTagUrl1, true);
      // player.ima.changeAdTag(adTagUrl1);
      // player.adsManager.start();
      player.ima.requestAds();
    });
```

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
