### ISSUE TITLE
Tests are failing on firefox with vjs6 and vjs7

### ISSUE THREAD

**Issue by cristian-atehortua** [googleads/videojs-ima#812]
Hi,
As the title says, the commands to test with video.js@6 and video.js@7 fail on firefox.

**Comment by arnaudcasame** [comment]
Hi @cristian-atehortua ,

Thank you for reporting this to us. Did you receive any error message from the plugin? I tested the [Advanced sample](https://googleads.github.io/videojs-ima/examples/advanced/)  against the `Firefox 60.8.0esr (64-bit)` using `vjs7.5.4` and the ad displayed successfully.
![videojs_no_error_on_Firefox](https://user-images.githubusercontent.com/12627484/61908249-47701f00-aefd-11e9-87ba-5d7833a59ae0.png)

**Comment by cristian-atehortua** [comment]
Maybe, I wasn't very accurate with the description. The ad is playing but the tests are failing. I mean, when you run `npm run test:vjs6` or `npm run test:vjs7`, it fails.

**Comment by arnaudcasame** [comment]
Hi @cristian-atehortua,

We're already aware of this issue and the team is actively working on reviewing it. I'll get back to this thread once I have more information.

**Comment by cristian-atehortua** [comment]
Thanks!

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
