### ISSUE TITLE
1009: The vast response is empty

### ISSUE THREAD

**Issue by unaseer1993** [googleads/videojs-ima#813]
Hey, 
I just integrated google Ima sdk in ios, when i am running a test ad it is running ok and showing ad. But when i am replacing it with mine unitId it gives me the error: The vast response is empty . I am checking it through video suite inspector and sometime it run my ad and sometime same error, but on simulator it always give me VAST error. My unit Ad ids are : 21680724678 and /21680724678/10

**Comment by arnaudcasame** [comment]
Hi,

This is likely an ad serving issue, you would encounter the same behavior if you ran your ad tag against the [IMA SDK for HTML5 samples](https://github.com/googleads/googleads-ima-html5). I would recommend you to reach out to the [Ad Manager Support team](https://support.google.com/admanager/?visit_id=636828206910826916-1160716667&rd=1#topic=7505988) so they can help you fix the issue.
