### ISSUE TITLE
Incorrect setting name "contentKeywords" in adsRequest object

### ISSUE THREAD

**Issue by dilburt** [googleads/videojs-ima#816]
The ima options (e.g. player.ima(options)) contains an entry for adsRequest which is the object containing a number of settings for each ad request. The setting shown as "contentKeywords" in the IMA SDK Docs is incorrect. When this is passed to player.ima it generates the following error:

bridge3.327.4_en.html:938 Uncaught TypeError: a.za.o.join is not a function
    at tT (bridge3.327.4_en.html:938)
    at MT.sT.h (bridge3.327.4_en.html:926)
    at XT (bridge3.327.4_en.html:942)
    at bridge3.327.4_en.html:942
    at KI.C (bridge3.327.4_en.html:554)
    at Gf (bridge3.327.4_en.html:87)
    at zM.h.dispatchEvent (bridge3.327.4_en.html:85)
    at DM (bridge3.327.4_en.html:672)
    at zM.K (bridge3.327.4_en.html:671)
    at Df (bridge3.327.4_en.html:83)

When I change the setting name to contentKeyword (removing the 's') then the initialization succeeds without errors. I'm not sure if this is an error in videojs-ima or an error in the base ima SDK although I suspect the latter. However, based on several previous issue submissions they ask to have the issues submitted to videojs-ima if that is what you are running.

Let me know if I can provide any additional information.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
