### ISSUE TITLE
Player width/height rounding bug causes sizing and UI issues on responsive layouts

### ISSUE THREAD

**Issue by minasaywhat** [googleads/videojs-ima#819]
The videojs-ima plugin uses parseInt to grab the dimensions to pass to the IMA SDK. When using responsive CSS, setting sizes on a percentage bases, results in dimensions being rounded down to the nearest whole number, while the IMA SDK rounds dimensions up to the nearest whole number. The plugin would benefit from getting the player dimensions in a way that doesn't chop off the decimal places for percent-based CSS. Based on testing, parseFloat appears to work better. 

This presents a UI/UX issue for our audiences, and our advertisers are asking us to fix the 1 pixel line that appears around the player before campaigns go live.

Is it possible to modify the videojs-ima to use parseFloat instead of parseInt to grab player size dimensions?

See screenshots below for reference.
Thank you.

![glimmer-div-container-width-height](https://user-images.githubusercontent.com/1469838/64366622-9a50f200-cfe4-11e9-9da0-0369db69f791.jpg)

![google-imasdk-div-container-width-height](https://user-images.githubusercontent.com/1469838/64366623-9a50f200-cfe4-11e9-97d9-4069e0986939.jpg)

![imasdk-ad-resizing-issue](https://user-images.githubusercontent.com/1469838/64366624-9a50f200-cfe4-11e9-9d71-382854c3ecb7.png)

**Comment by arnaudcasame** [comment]
Hi,

I identified the code that sets the width and height of the IMA SDK iframe through the videojs-ima plugin, it's indeed using the parseInt function to set the values. I'll share your insights with the rest of the team and I'll get back to you once I have more information.

**Comment by minasaywhat** [comment]
Thank you for the fix on this!
