### ISSUE TITLE
Bad release 1.6.1

### ISSUE THREAD

**Issue by Vladislavik** [googleads/videojs-ima#821]
Hi, check file
https://github.com/googleads/videojs-ima/blob/master/dist/videojs.ima.min.js
it is have bad symbols
`<<<<<<< HEAD`
and 
`>>>>>>> f5959c3... Build for samples at v1.6.1`
and code loaded twice in file.

**Comment by Kiro705** [comment]
Nice catch!

Fixed the issue and released version 1.6.2.
