### ISSUE TITLE
Include Closed Captioning support as detailed in the VAST 4.1 specification

### ISSUE THREAD

**Issue by leon486** [googleads/videojs-ima#826]
Hi, [the VAST 4.1 specification](https://iabtechlab.com/wp-content/uploads/2018/11/VAST4.1-final-Nov-8-2018.pdf) introduced closed captioning support.

Videojs-ima doesn't seem to support them at all.
This is important to us because we have a large number of users seeing the ads without audio (about 80%) and also a considerable number of deaf users. We'd like to provide an adequate ad experience to the users in these scenarios as best as we can.

**Comment by arnaudcasame** [comment]
Hi,

The VAST Standard support is brought to the plugin by the [IMA SDK for HTML5](https://developers.google.com/interactive-media-ads/docs/sdks/html5) which currently doesn't support this feature. You can open a ticket and request support for this feature on the [IMA SDK Support forum](https://groups.google.com/forum/#!forum/ima-sdk).

**Comment by leon486** [comment]
Thanks, I'll do that.
