### ISSUE TITLE
tracking errors

### ISSUE THREAD

**Issue by khatibda** [googleads/videojs-ima#832]
i'm trying to track AdsLoader errors, e.g. when the plugin warns AdsLoader Error 1009, i want to be able to listen to that event and capture/log the error and error data.  i'm not sure how to access the AdsLoader directly through the plugin, and therefore how to attach onerror events to it.  thoughts?

**Comment by Kiro705** [comment]
Hi @khatibda,

We just added some events to access things like the AdsLoader as soon as they are ready. Take a look at the [Plugin Ad Events](https://github.com/googleads/videojs-ima#ima-plugin-ad-events) section of the readme for details on the implementation.

This is new in v1.7.0 of the videojs-ima plugin, so make sure you are building with that version for these events. Please follow up if that works for your implementation.

Hope that helps,
Jackson
IMA SDK DevRel

**Comment by khatibda** [comment]
great thanks!!!!

**Comment by owenbt** [comment]
This is helpful, but can you fix the broken links to the IMA documentation here: https://github.com/googleads/videojs-ima#ima-plugin-ad-events
