### ISSUE TITLE
Add volume slider to ima-sdk-player's controls div

### ISSUE THREAD

**Issue by Inlesco** [googleads/videojs-ima#84]
Video.js has an self-explanatory volume slider near the volume mute/unmute button. 

How do you add the same button to ima-sdk-player's controls div?

Preferably, I want the user to be able to control ad's volume, but unable to turn it off to 0%. A parameter for minAllowedVolume and maxAllowedVolume would be great.

**Comment by tensafefrogs** [comment]
+1 to controlling the volume (especially muting the ad) if that isn't already available.

I don't agree with the "min volume" setting. I think it's a little rude to the user, and I've not heard of any advertisers requiring such a feature.
