### ISSUE TITLE
Midrolls (as % of content) and key-value targeting

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#841]
Hi,
I have two questions:
1. Is there any guide how to use the IMA SDK to run midrolls at the middle of the video? Midrolls are generally possible with VMAP (as there is no support to create multiple ad breaks), but IMA SDK doesn't support timestamps different than hh:mm:ss. And when using VMAP, it appears to be impossible to create the timestamp dynamically. 

2. VMAP is generally a wrapper of multiple VASTs. We are using a static VMAP, as Google Ad Manager doesn't have other options (it is not the paid version). However, when integrating with Google Ad Manager, how exactly can key-value targeting related to specific video, when the VMAP is static.

**Comment by arnaudcasame** [comment]
Hi,

Both questions are beyond the scope of this forum hence we cannot give you support.
* The first question should be addressed to the [IMA SDK Support](https://groups.google.com/forum/#!forum/ima-sdk) team via their support forum.
* For the second question, we would recommend you to reach out to the [Ad Manager Support](https://support.google.com/admanager/?visit_id=636828206910826916-1160716667&rd=1#topic=) Team for further assistance on your inquiry.

**Comment by pradhyumn94** [comment]
@cycleos  I  think for the first issue you have  to implement the mid rolls on your own.
Feel free to connect with me if  you want to discuss it further.

**Comment by cycleos** [comment]
We implemented it through a static VMAP. The problem with it is that we can't put it in the middle of the video. Or turn it off for short videos.
Basically the issue for us to have the ads dynamically (time and key value targeting), which is appears to not be possible with static VMAP. Generating dynamic VMAP is overcomplicated...

**Comment by pradhyumn94** [comment]
@cycleos Do you not control video  player ?

**Comment by cycleos** [comment]
I control the player. We can create dynamic VMAP with key-values, but it is a huge investment in development. So I am searching for alternative approaches.

**Comment by canhnm** [comment]
@cycleos I have had it on my own one too, fell free to reach me out.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
