### ISSUE TITLE
How to determine if it is a linear / nonlinear type

### ISSUE THREAD

**Issue by jakubfrydrych** [googleads/videojs-ima#842]
Hello, I want to ask if you can use a method to find out if it's a linear or nonlinear type of ad. Currently I use to determine the content type from which I derive whether it is an image or video data (like image/png or mp4 etc..)

And whether it is possible to find out somehow through the values provided by adsManager through the getCuePoints() method, which returns tag times, but I am not able to tell whether it will be linear or nonlinear. An example of use is needed to render markers on a timeline where it is not desired to render an overlay marker.

Thank you very much in advance for your reply.

**Comment by arnaudcasame** [comment]
Hi,

The IMA SDK only determines if the current ad is linear or not once it is loaded. You can retrieve such value by calling the [isLinear()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.Ad.isLinear) method on the current ad object.
An example would be to call the line below inside the onAdEvent function of our [advanced](https://github.com/googleads/videojs-ima/tree/master/examples/advanced) example sample.
 ```
event.getAd().isLinear()
```

**Comment by jakubfrydrych** [comment]
Thank you very much for your answer
