### ISSUE TITLE
How to get the final AdTagUrl value

### ISSUE THREAD

**Issue by jakubfrydrych** [googleads/videojs-ima#845]
Hello, I would like to ask if you can get the value of the final URL to VAST file? For example, I would like to use it if there are more wrappers in the way and I would like to know the final URL from which the ad will be used.

Just a visual example:

```
<VAST version="3.0">
  <Ad id="1111-2222" sequence="1">
    <Wrapper>
      <AdSystem version="3.0">None</AdSystem>
      <VASTAdTagURI>
        <![CDATA[http://adserver.com/final-vast.xml]]> // I need this URL value
      </VASTAdTagURI>
     .... 
```

Thank you very much in advance for your reply

**Comment by jakubfrydrych** [comment]
![Snímek obrazovky 2019-10-23 v 16 44 03](https://user-images.githubusercontent.com/34452513/67405036-7eb1a300-f5b4-11e9-9418-a4159effd268.png)

At the event LOADED I probably see the information under the letter J, but I haven't found out which method would return this value to me yet

**Comment by arnaudcasame** [comment]
Hi,

The IMA SDK doesn't have an API method or field that you can use to retrieve the VAST Tag URI of a Wrapper ad. However, you can retrieve some other wrapper information such as the:

- Wrapper Ad Ids calling the getWrapperAdIds()
- Wrapper Ad Systems calling the getWrapperAdSystems()
- Wrapper Creative Ids calling the getWrapperCreativeIds()

**Comment by jakubfrydrych** [comment]
Thank you very much, I'll try to compile information from the available IDs.
