### ISSUE TITLE
Event after nonlinear ad time expires (minSuggestedDuration)

### ISSUE THREAD

**Issue by jakubfrydrych** [googleads/videojs-ima#849]
Hi, I want to ask if you can somehow get an event if the nonlinear overlay is complete.

If I look at event logging before overlay is displayed, the following events occur:
```
contentResumeRequested
impression
loaded
start
```

but after the time set in minSuggestedDuration has expired, the overlay will be hidden but no further event will follow. Like COMPLETE?

Thank you in advance for your reply

**Comment by arnaudcasame** [comment]
Hi,

When it comes to non-linear ads, the IMA SDK doesn't fire the COMPLETE event, unless the ad you're requesting is from AdSense and you're setting the [forceNonLinearFullSlot](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdsRequest.html#forceNonLinearFullSlot) to true.

**Comment by jakubfrydrych** [comment]
Well thank you for the answer, I will have to solve it programmatically.

**Comment by komw** [comment]
> Well thank you for the answer, I will have to solve it programmatically.

Did you found a solution how to get information is ad was hided ?
