### ISSUE TITLE
how can we inspect the adTag url response?

### ISSUE THREAD

**Issue by khatibda** [googleads/videojs-ima#852]
Hey - after we request an ad from GAM using an adTagUrl, we are trying to debug the raw GAM response, before the plugin tries to "load" the response, which may or may not work due to various errors.  Is there any way to listen to and inspect the vast xml response before IMA unpacks and loads it?  If not, is there at least a way to get to the Ad object in the case of an Ad Load error (i see ways to grab the ad object from successful events like LOAD, but not via errors).

**Comment by khatibda** [comment]
one first thing we tried to do was to GET the GAM adTagUrl ourselves (http request) and then pass it into SDK via setting the controller adsResponse instead of adTagUrl..but that seems to disable AdX bidding (prebid still works fine).

if you're wondering the use case, we're trying to determine if the winning creative from GAM is a prebid related creative, or a Google EB related creative, so we can assign error tracking accordingly and possibly detect problematic creative (and half the errors happen on AdLoad, not after).

**Comment by Kiro705** [comment]
Hi @khatibda ,

Have you tried the plugin's [Ad Events](https://github.com/googleads/videojs-ima#ima-plugin-ad-events), specifically the Ads Request event.

I believe this would let you inspect the response as soon as it is received.

**Comment by khatibda** [comment]
we didn't see any obvious way to get to the response through that event object, either the response or the ad.  do you have example method or syntax for retrieving from that event?

**Comment by josephtyler** [comment]
Hi @Kiro705, I'm working on this issue with Danny. I've inspected the `AdsRequest` property on the  event, but it doesn't include an `adsResponse` property. It looks like maybe that attribute would only be set if it was set explicitly when creating the request.

But we're hoping to inspect the ads response, when making a request using the `adTagUrl`. Would love to hear if you have any other ideas or if we're missing something here. Thank you!

**Comment by Kiro705** [comment]
Hi @khatibda ,

Looking into your issue more, the IMA SDk does not currently supply the raw VAST tag in its response.

As a possible work-around for this, it is possible to manually inspect the VAST tag in your browser's `Network` DevTools tab. 

Also, the AdObject is not created in the event of an AdLoadError.

If you would like to make a feature request to return raw VAST tag, please make the request in a post to the [Interactive Media Ads SDK Google group](https://groups.google.com/g/ima-sdk).

**Comment by khatibda** [comment]
ok thanks for your support, appreciate it.
