### ISSUE TITLE
ima-countdown-div is never displayed

### ISSUE THREAD

**Issue by cdatehortuab** [googleads/videojs-ima#853]
Hello, there is a bug introduced in PR #836.

If you check line 149 in ad-ui.js there is an if clause:
```javascript
if (!this.controller.getIsMobile) {
```

But `this.controller.getIsMobile` is a function so it always has a truthy value so that clause is never true and `ima-countdown-div` never gets the appropiate attributes and it is always hidden, not only for mobile.

In any case, I think the solution for the bug that the PR #836 tries to solve (#453) is different, because it happens when `showControlsForJsAds` is `true` but a VAST file without VPAID is retrieved.

**Comment by Kiro705** [comment]
Hi @cdatehortuab ,

Thank you for catching this and making the appropriate PR.

I will merge in the change now.
