### ISSUE TITLE
the reasons why in autoplay-mode player.ima.initializeAdDisplayContainer() has never been called

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#857]
are there any reasons why? 

thanks...

**Comment by dioramayuanito** [comment]
i got warning like this : [  0.020s] [ima.common.CompanionAdsManager] Sufficient time not provided for initialization of AdDisplayContainer before request ads.  if i play in autoplay-mode. but in non-autoplay-mode that warning was dissappear

**Comment by arnaudcasame** [comment]
Hi,

This warning comes from the IMA SDK for HTML5 debug library, it doesn't affect the Videojs-IMA plugin in any way, you can safely ignore this warning.
For the `player.ima.initializeAdDisplayContainer()` method to be called, the ad playback must be initiated by the user's action (click the play button or the player's area). In an autoplay context the ad playback begins without any user's action.

**Comment by dioramayuanito** [comment]
thanks a lot sir arnaud

**Comment by dioramayuanito** [comment]
Hello Mr. Arnaud,

i'm sorry, i open again this issue. i just wanna make sure: what happen if we call player.ima.initializeAdDisplayContainer in autoplay mode without user clicking play button/player's area?

**Comment by dioramayuanito** [comment]
I have trouble in Moat Tracker Integration, while in autoplay mode. Their js doesnt run properly in autoplay mode. but when i change the player to run in non-autoplay then their js runs well.

i have assumption their js lib needs adDisplayContainer to run before we call their js initialization. Thanks a lot Arnaud and team...

**Comment by dioramayuanito** [comment]
ok i got the clue now. if i want to call Moat Init after adDisplayContainer.initialize() , i should use manual adBreak...
