### ISSUE TITLE
Videojs IMA Chromecast

### ISSUE THREAD

**Issue by jalowin** [googleads/videojs-ima#861]
Hello everybody:

I have a web page and my player and my ads is working but when I try send to the chromecast with the plugin silrvermine-videojs-chromecast the ads play in my browser and the video play in my chromecast and I want that all play it at the chromecast

https://sportsvr.tv

Thanks for all

Best regards

**Comment by arnaudcasame** [comment]
Hi,

This is beyond the scope of this issue tracker, we don't support the issues related to the [videojs-chromecast ](https://github.com/silvermine/videojs-chromecast) plugin. However, the [IMA SDK](https://developers.google.com/interactive-media-ads/) which is the underlying SDK of our plugin also provides the [IMA SDK for Cast](https://developers.google.com/interactive-media-ads/docs/sdks/cast/client-side) that you can use to integrate ads display feature in your Cast app.

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
