### ISSUE TITLE
Add config option to allow Video Ad prerolls to be clickable in Mobile

### ISSUE THREAD

**Issue by gcarrion-gfrmedia** [googleads/videojs-ima#862]
The current way that video ads work with the IMA SDK Plugin for Video.js is that when in a mobile device when clicked it pauses the ad. The clickthru for the ad is only in the upper-right text link where it says "Learn More". 

I understand that this is done to prevent the user on mobile accidentally clicking the ad, however, it would be great to have the configurable option to allow the video ad to be clickable in the entire player in mobile, just like it works on desktop mode, and not just the "Learn Morre" link.

This is important for CTRs since not all users assume that the clickthru is in the upper-right text link and this affects the CRTs greatly. For example, prior to use the plugin, we had a player that allowed the clickthru in the entire player in mobile. We used to have a CTR of over 3.5%, and when it was only on the "Learn More" link the CTRs dropped to less than 1%. So I'm guessing this is something that it would be very well received the option to have this available in mobile.

Thanks!

**Comment by arnaudcasame** [comment]
Hi,

The click-through overlay is exclusively controlled by the IMA SDK for HTML5, the videojs-ima plugin doesn't have any control over it. On the other hand, the "Learn More" overlay has always been used by the IMA SDK for [Android](https://developers.google.com/interactive-media-ads/docs/sdks/android) and [iOS](https://developers.google.com/interactive-media-ads/docs/sdks/ios) to catch users click. We're pretty sure that the users watching ads on your app already know the purpose of displaying it on player by now.

**Comment by canhnm** [comment]
Noticed the change of ad click changed last year from full player to Learn more button. We also got the CTR dropped!

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
