### ISSUE TITLE
Error: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized

### ISSUE THREAD

**Issue by xhudaman** [googleads/videojs-ima#863]
We are implementing prebid to generate our `adTagUrl`. The ima plugin is initialised after the `adTagUrl` is generated.  We've never seen the error before this, through multiple implementations using ad tags from different sources.  We've attempted to fix the issue via code changes in our code base to no avail.
The basic flow of our code looks like this:
```javascript
const player = videojs('my-player', options);
auction(options, (adTagUrl) => {
  const imaOptions = {};
  player.ima(imaOptions);
});
```
Setup:
Video.Js 7.4.1
videojs-contrib-ads 6.6.4
videojs-ima 1.6.0

**Comment by arnaudcasame** [comment]
Hi,

It seems that you're having issues with your pre-bid implementation, I was not able to reproduce the behavior using the [advanced](https://googleads.github.io/videojs-ima/examples/advanced/) example sample. Have you tried reproducing the behavior after upgrading to the latest version of the plugin?

**Comment by xhudaman** [comment]
So it turns out it was in fact our implementation.  We managed to get it sorted right before closing up shop for the weekend.
Prebid delayed the init long enough to cause issues.  We changed the order of implementation and it sorted itself out.
Thanks for your help and quick reply!
