### ISSUE TITLE
Sometimes, if ad is skipped, onAdComplete failed

### ISSUE THREAD

**Issue by ChoOo7** [googleads/videojs-ima#867]
chunk-vendors.js:formatted:16899 Uncaught TypeError: Cannot read property 'isLinear' of null
    at T.onAdComplete (chunk-vendors.js:formatted:16899)
    at rh (ima3.js?_=1576147226099:101)

currentAd is not an object
https://github.com/googleads/videojs-ima/blob/77da05d28922bb85e74e1cf4e13eea627c940bc7/src/sdk-impl.js#L477

**Comment by arnaudcasame** [comment]
Hi,

I was not able to reproduce the behavior that you're seeing with the onAdComplete event failing if the ad is skipped. Can you share the ad tag you were using when the issue occurred?

**Comment by ChoOo7** [comment]
The is my vast source : 
https://media-cloud-cdn.wedia-group.com/api/v1/media/roll/vastInformation.xml?DepartmentUid=1aac42b7-a847-4245-8bb3-4cc8b0752706&MediaGuid=5d9aed87-973c-4633-a078-fbe41c8b8b89

**Comment by dioramayuanito** [comment]
your ad linear duration is 00:00:00, i have an experience that bad duration value sometime makes strange error...

**Comment by dioramayuanito** [comment]
your ad linear duration should be 00:00:05 from MediaFile mp4 duration

**Comment by ChoOo7** [comment]
Gonna test it, thanks

**Comment by dioramayuanito** [comment]
@ChoOo7 ok

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
