### ISSUE TITLE
response 204 securepubads.g.something

### ISSUE THREAD

**Issue by bajro17** [googleads/videojs-ima#874]
I try implement vast tag and put code on live site but I get GET securepubads.g.something 204 
Some type error I never saw it in my life ads show on Desktop site but when visit from mobile this is what I get

**Comment by arnaudcasame** [comment]
Hi,

Were you able to reproduce the behavior running your ad tag against the [IMA VSI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector)? Can you share the ad tag you were using when the issue occurred? Can you also share a screenshot of the error message logged in the console by the plugin?

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the [latest stable version](https://github.com/googleads/videojs-ima/releases/tag/v1.7.4)

Thank you!
