### ISSUE TITLE
Double black blank while Playing Ad

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#875]
Hello everybody, 

I want to make sure , does this symptom occur maybe because of Fallback in DFP ?

https://m.youtube.com/watch?v=B_lCN46koZA&list=UURRzUay6WwRcPjzGLogjN8A&index=1

We use VideoJS v7.6.6, VideoJS-Contrib-Ads v6.6.5, VideoJS-IMA v1.7.4

Thanks alot everybody

**Comment by arnaudcasame** [comment]
Hi,

Your player seems to be loaded when it's container is on screen, that's probably the reason why there's a delay in loading the video content and the ad. Are you able to reproduce the double black blank using our videojs-ima samples?

**Comment by dioramayuanito** [comment]
yes, it's an article player which uses inscreen and outscreen concept.
but double blank still occurs in a normal player. we will create videojs-ima sample with same adRules. i guess this symptom occurs because PubMatic-VPAID (PMAdMgr.js) calls MOAT-VPAID (moatwrapper.js). Those vpaid are programmatic Ad , so it runs randomly.

**Comment by arnaudcasame** [comment]
Hi,

Were you able to reproduce the double black blank using our videojs-ima samples?

**Comment by dioramayuanito** [comment]
Hi sir Arnaud, i will close this issue because im on vacation
