### ISSUE TITLE
Samsung smart tv(Tizen) file:// instead https://

### ISSUE THREAD

**Issue by gmanenti** [googleads/videojs-ima#877]
locally the library resolve file://pagead2.googlesyndication.com instead of https://pagead2.googlesyndication.com

**Comment by arnaudcasame** [comment]
Hi,

Given that this question was answered on this IMA SDK forum [thread](https://groups.google.com/forum/#!topic/ima-sdk/mDeCDO8s6Pw), I'm closing this issue.

**Comment by hantrungkien** [comment]
@arnaudcasame Hi, 

I have seen the [IMA SDK compatibility](https://developers.google.com/interactive-media-ads/docs/sdks/other#ima_sdk_compatibility) so I have created a example. Ad's shown when run localhost on Browser but not shown on real Tizen TV.

Please let me know IMA has supported Tizen and WebOS at the moment?
