### ISSUE TITLE
what requestMode should i choose for MOAT network?

### ISSUE THREAD

**Issue by dioramayuanito** [googleads/videojs-ima#878]
Hello Everybody,
I just want to ask about requestMode option in VideoJS-IMA v1.7.4 .
What requestMode value should i choose for MOAT network? is it "onLoad" (as default), or "onPlay"?
Thanks a lot.

**Comment by dioramayuanito** [comment]
i ask this question, because i read https://support.brightcove.com/advertising-ima3-plugin in "requestMode" and i found these paragraphs :

onload: Ads are requested immediately when the player loads. This is normally the best experience for DFP / VPAID.
onplay: The first ad request is delayed until playback is initiated. This is important for ad networks which consider ad requests to be plays, so you would not want an ad request before a play request. 

and i found videojs-ima hidden option named "requestMode" default to "onLoad"

**Comment by arnaudcasame** [comment]
Hi,

The requestMode was added because some Ad networks charge per request and not play. In the case of MOAT Network, the requestMode option depends on how MOAT counts the ad requests. We would recommend you to reach out to the MOAT Network Support team to have an answer to this question.

**Comment by dioramayuanito** [comment]
ok i will send an email yo moat
