### ISSUE TITLE
AdContainer Ui not detecting click

### ISSUE THREAD

**Issue by gourav-wynk** [googleads/videojs-ima#879]
Hi

I am using IMA-SDK Dai implementaion for android and using exo player...
I have added play button on ad container but not to able detect its click.
How can i solve this issue?

**Comment by arnaudcasame** [comment]
Hi,

This is beyond the scope of this forum hence we cannot give you support. This Github issue tracker only support issues related to the VideoJs-IMA plugin, we would recommend you to reach out to the [IMA SDK Support Team](https://groups.google.com/forum/#!forum/ima-sdk) for further assistance on your inquiry.
