### ISSUE TITLE
Document:  The necessity of `videojs.ima.scss` in ES6 Imports ?

### ISSUE THREAD

**Issue by ckybonist** [googleads/videojs-ima#880]
## Request for help
Please add some explanations about `videojs.ima.scss` in README, as I only saw `<link rel="stylesheet" href="path/to/videojs.ima.css" />` is mentioned in [Alternative Setup](https://github.com/googleads/videojs-ima#alternative-setup), while it's necessary for us to import the `css/scss` file in certain situations...

##  Motivation
   Follow by the [instructions of ES6 imports](https://github.com/googleads/videojs-ima#es6-imports), I've found a bug that `ima-ad-container` will be rendered right below the player.

![image](https://user-images.githubusercontent.com/3832925/73123369-5037cf80-3fca-11ea-8fd0-10f5b40caa71.png)

## How to reproduce the bug

1. Using ES6 imports way to get started
2. **Specify player option `aspectRatio` as "16:9"** 

## How to fix it
Add `import 'videojs-ima/dist/videojs.ima.scss';`, then ads container will cover the original video content, and the IMA player controls will be rendered (see the red box in screenshot).

<img width="554" alt="螢幕快照 2020-01-30 11 46 27" src="https://user-images.githubusercontent.com/3832925/73418389-47daee00-4356-11ea-83b9-a420a2cc4cd7.png">

Also see my [CodeSandbox](https://codesandbox.io/s/test-videojs-ima-scss-osyjn):  Please comment / uncomment the `import 'videojs-ima/dist/videojs.ima.scss';` to see the difference.

### Package versions
- video.js: 7.6.6
- videojs-contrib-ads: 6.6.5
- videojs-ima: 1.7.4

**Comment by arnaudcasame** [comment]
Hi,

I've investigated the sandbox link you shared, the Ad Display Container and the video tag must be inside of the same container, have the same size and the Ad Display Container must have an absolute position relative to the container. The vjs-ima plugin implementation in the sandbox doesn't contain any of the requirements I mentioned earlier.

**Comment by ckybonist** [comment]
Close the issue wrt. #884
