### ISSUE TITLE
Skip ads play in the background

### ISSUE THREAD

**Issue by jakubfrydrych** [googleads/videojs-ima#882]
Hi, I've encountered a problem. When, after playing an ad that is skippable, the background ad stays playing, it overlaps another ad in the background, and you hear both. Similarly, measurement events are sent.

I tried many ways until I realized that I used the completely pure demo initialization of videojs-ima that is used in the playground. To avoid possible bugs caused by other player plugins.

When I have ima3_debug.js turned on, it will display an error after skipping
[ima.outerbridge.VideoDisplaysWithPreload] Inner video display command unknown: forwardCompatibleUnload

In the attachment I send demo html with initialization + ima-vast.xml in which there are two ad slots.

[Archiv.zip](https://github.com/googleads/videojs-ima/files/4133104/Archiv.zip)

**Comment by arnaudcasame** [comment]
Hi,

Given the behavior you described, the issue is not with the videojs-ima plugin, it seems to be with the IMA SDK itself. I would recommend you to reach to their support team via their [IMA SDK forum](https://groups.google.com/forum/#!forum/ima-sdk) so they can help you investigate the issue.
