### ISSUE TITLE
Lack of any event related to hiding nonlinear ad. 

### ISSUE THREAD

**Issue by komw** [googleads/videojs-ima#883]
There is no method/event etc to detect when non-linear ad was hided. 
Any event like `window.google.ima.AdEvent.Type..COMPLETE` isn't triggered when AD was hiding (because for example setting a minSuggestedDuration option)

**Comment by arnaudcasame** [comment]
Hi,

The COMPLETE ad event doesn't fire when the ad being displayed is non-linear. You can try registering to the USER_CLOSE ad event to be able to detect when the current non-linear ad is hidden or closed. Feel free to reach out to the IMA SDK Support team via their forum if you need more details about ad events.

**Comment by komw** [comment]
USER_CLOSE doesn't fire when Ad is closed/hidded by plugin (not by user iteraction). You can specify a `minSuggestedDuration` in VAST, and Ad is hiding when reach timeout. But it is impossible to get any information that ad was hidded/closed for example in another plugins. 

From another hand any other types of ad has some events related to hide/close/end like `adend`. Closed non-liear ad doesn't fire any event.
