### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by WesleyCarnicle** [googleads/videojs-ima#885]
Hi i am Wesley Carnicle i am an owner of a wordpress news blog i am wondering how can i incorporate this into a video js player to show ads from google

**Comment by Kiro705** [comment]
Hi Wesley,

We recommend following the [Getting Started guide](https://github.com/googleads/videojs-ima#getting-started) to create a basic implementation of the plugin.

Were there specific issues you were running into with your implementation?
