### ISSUE TITLE
vastTag Recall

### ISSUE THREAD

**Issue by bajro17** [googleads/videojs-ima#886]
Hello I need help how to call vast tag if it fail first time to call it for example 5 times and check am I get response?

**Comment by Kiro705** [comment]
Hi @bajro17 ,

Do you have any sample code to reproduce this issue?

We recommend continuing with content playback if your ad request fails. Recalling a VAST tag multiple times can appear as spammy behavior to the ads server.

**Comment by lphnam** [comment]
Hi @Kiro705,
With other side of content playback, it will lead to lower Ad fill-rate, right? And if spammy, what will happen to it? 
Thank you.

**Comment by Kiro705** [comment]
Hello @lphnam ,

I am not sure about your first questions, about ad fill-rates. Spammy behavior may lead to consequences imposed from the Ad Manager side.
