### ISSUE TITLE
VideoJS-IMA AdError 501: When open video in Iphone

### ISSUE THREAD

**Issue by natilux2** [googleads/videojs-ima#887]
When I open a video clip in browser (both safari and chrome) on iPhone, it seems open in fullscreen mode and throw this error
`AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area.`
How can I fix this
Thanks

**Comment by Kiro705** [comment]
Hi @natilux2 ,

Do you have any sample code we can use to reproduce the issue? This [article on custom playback](https://ads-developers.googleblog.com/2017/06/new-custom-playback-apis-for-ima-html5.html) may also be helpful.

**Comment by natilux2** [comment]
@Kiro705  Hi
Thanks, I move to jwPlayer due no support from google Adsense team, everything works fine now.
I will close this issue
