### ISSUE TITLE
Add supporting video.js 7.7.x

### ISSUE THREAD

**Issue by bcomerford** [googleads/videojs-ima#888]
Package manager was working for videojs 7.6 but getting `undefined` for `player.ima` in 7.7. Any other reports of this?

**Comment by Kiro705** [comment]
Hi @bcomerford ,

I was not able to reproduce your issue.

I tried with v7.7.4 of videojs and the [ES6 Imports sample](https://github.com/googleads/videojs-ima#es6-imports) setup and the player played ads as expected.

Do you have any sample code to reproduce your issue?

**Comment by bcomerford** [comment]
@Kiro705 was able to upgrade on a different machine, so must have been a local issue.
