### ISSUE TITLE
google.ima.AdEvent.Type.VIEWABLE_IMPRESSION isn't trigger

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#889]
Hi all,
from two days ago, the "google.ima.AdEvent.Type.VIEWABLE_IMPRESSION" isn't triggered anymore.. 
What's the problem???
I will wait an answer..
Thanks

A.

**Comment by Kiro705** [comment]
Hi @ibraalek10 ,
Looking at the [IMA AdEvent docs](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/ima.AdEvent), it looks like you might be looking for google.ima.AdEvent.Type.IMPRESSION

Please let me know if that resolves your issue.

**Comment by christianbkoehler** [comment]
Hi, I'm having a similar issue currently. The `google.ima.AdEvent.Type. VIEWABLE_IMPRESSION` used to fire along with the `google.ima.AdEvent.Type.IMPRESSION` event but not anymore. Did the `google.ima.AdEvent.Type. VIEWABLE_IMPRESSION` event get removed recently? I can't find any release notes that mention it being removed

**Comment by Kiro705** [comment]
Hi all,
`google.ima.AdEvent.Type.IMPRESSION` is the only event in our documentation that deals with impressions. I recommend listening for that event.

Changes to non-public APIs may not be published, and so it is recommended to only use those that are publicly available.

**Comment by christianbkoehler** [comment]
@Kiro705 I see that the `google.ima.AdEvent.Type.IMPRESSION` is the only event listed in the documentation, but I can see that the `google.ima.AdEvent.Type.VIEWABLE_IMPRESSION` does exist in the ima3.js file as an AdEvent Type, but isn't listed in the documentation for whatever reason.

**Comment by Kiro705** [comment]
Hi @christianbkoehler ,

You are correct, and the reason for that is the `google.ima.AdEvent.Type.VIEWABLE_IMPRESSION` event is not meant for external use and changes to it may go unpublished.

**Comment by christianbkoehler** [comment]
Great, thank you for that information!

**Comment by ibraalek10** [comment]
Hi all,
I understand but i need this event for measuring viewability.. 
Until a few days ago, this event was triggered very well.. 
What's the matter now??? How can I solve my problem with video viewability?
I will wait your answers..
Thanks a lot,

A.

**Comment by Kiro705** [comment]
Hi @ibraalek10 ,

You will have to use `google.ima.AdEvent.Type.IMPRESSION` to measure viewability. If that is not working for you, can you provide sample code that demonstrates the problem you have. I think that would be the best way for me to help with a solution.

Thanks,
Jackson
IMA SDK DevRel

**Comment by ibraalek10** [comment]
Hi @Kiro705,
Thanks for the answer but I must tell you some things..
google.ima.AdEvent.Type.IMPRESSION is fired when the impression is called while google.ima.AdEvent.Type.VIEWABLE_IMPRESSION was fired when the impression was called and the video stay in viewport for 2 seconds.. 
This was the important difference of this two events..
I will wait your answer..
Thanks in advance,

A.

**Comment by Kiro705** [comment]
If you would like, I can file a feature request of the IMA SDK for a public event for viewable impressions. But for now this does not appear to be an issue with the videoJS-IMA plugin.

Otherwise, I would suggest having your app watch for the video to stay within the viewport as a workaround.

**Comment by ibraalek10** [comment]
Hi @Kiro705,
it would be fantastic if this event became a public event..
Please can you forward a request to the IMA SDK?
Thanks a lot,

A.

**Comment by Kiro705** [comment]
Hi @ibraalek10 ,

An update from the IMA team:
The VIEWABLE_IMPRESSION event will not be reimplemented. It was removed as an upcoming change would make it infeasible for the IMA SDK to track this. It is recommended that you measure viewability from your ads manager or your own viewability script.
