### ISSUE TITLE
Prerolls do not play when using multiple players on the page

### ISSUE THREAD

**Issue by saxena-gaurav** [googleads/videojs-ima#89]
I have 2 video.js players on a page. When I click on play button on the first player, ads do not play. Basically I referred to this example https://github.com/googleads/videojs-ima/blob/master/examples/simple/index.html  and added 2nd player. Could possibly an issue with IMA SDK?

**Comment by saxena-gaurav** [comment]
Here is a link to a page : http://solutions.brightcove.com/gsaxena/ima/

**Comment by shawnbuso** [comment]
Closing sa a duplicate of #116
