### ISSUE TITLE
Triggering ad breaks manually using AdX tags

### ISSUE THREAD

**Issue by bear0ckr** [googleads/videojs-ima#891]
Hey team!

I'm currently triggering an ad request to a Google AdX tag manually (via JS) after a set time interval. I'm doing this via player.ima.changeAdTag() function and then calling player.ima.requestAds(). I have set autoPlayAdBreaks = true in the IMA init function since the player doesn't begin without that setting. 

The video player and ads do play fine. However, I have noticed in the AdX reports that:

1) A lot of AdX buyers are not buying from this implementation.
2) All those AdX buyers start buying if I let a VMAP trigger the ad break at the same time interval instead of triggering it manually.

Can you please suggest what I'm missing here?

**Comment by arnaudcasame** [comment]
Hi,

Can you provide more details on what you mean by AdX buyers are not buying from this implementation?

**Comment by arnaudcasame** [comment]
Hi,

I’m closing this issue because it has been inactive for more than a month. Please reopen if you still encounter this issue with the[ latest stable](https://github.com/googleads/videojs-ima/releases/tag/v1.8.0) version

Thank you!
