### ISSUE TITLE
Urgent need to find root cause of ad playback error: Failed to read the 'buffered' property from 'SourceBuffer'

### ISSUE THREAD

**Issue by minasaywhat** [googleads/videojs-ima#892]
We have an urgent need to identify the root cause of this ad error that shows a blank screen in the player on mobile browsers (iOS Chrome or Safari). 
Experience: https://share.hdmtools.com/d5u0erbp

**Steps to reproduce:** 
1. Use an iOS phone or tablet with Charles Proxy or Safari dev tools enabled for mobile browser debugging (use iPhoneX emulator on Chrome desktop if you can't test on a real device). 
2. Disable all ad blocker browser extensions, if applicable
3. Open this URL and wait for the player to autoplay muted: https://www.delish.com/cooking/recipe-ideas/recipes/a58236/easy-homemade-chicken-pot-pie-recipe/?token=visible21120

**Actual Result:** 
- Ad plays just fine for 2 seconds (not a browser or device compatibility issue)
- Player shows a blank white screen for the remainder of the ad duration
- Ad progress bar continues, and ad impression and quartile events fire
- The following error is shown in the browser console:
VIDEOJS: ERROR: DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

**Expected Result:** 
- Ad playback should continue for the entire duration of the ad
- The IMA SDK should display a VAST error in the console, or an exception error to explain what is breaking or interfering with ad playback
- the quartile events of the player should not fire, and the timeline of the player shouldn't advance when in reality ad playback failed after the first 2 seconds of the ad

**Notes:**
- Header bidding is enabled, but the issue still presents when HB is disabled, as you can see here: https://www.delish.com/cooking/recipe-ideas/recipes/a58236/easy-homemade-chicken-pot-pie-recipe/?token=visible21120&utm_campaign=arb
- I confirmed that the MP4 file for the creative is compatible on all browser/devices (MP4 with H264 video codec, and ACC audio codec), as you can see here: https://s-static.innovid.com/media/encoded/12_19/297099/11_source_89547_344406.mp4
- When checking the player error logs for this "InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source." error, I can see some of them have a VAST 400 error shown in the console, but given that playback of the MP4 initially works, I'm not sure why we would get this error. 

VAST 400 error notes: 
This fatal error can be caused when a video player is unable to display the linear ad. It may occur when the MediaFile is not a valid video file of the specified format, or because the browser restricted autoplay with sound, or another unknown reason.

Any help you can provide to point us in the right direction would be greatly appreciated.

**Comment by Kiro705** [comment]
Hi @minasaywhat ,
Based on the source of the error message, it looks like it may be an error with the videoJS player and not the videoJS-IMA plugin.

However, if you could provide a sample ad tag that can reproduce the issue in the [sample player](https://googleads.github.io/videojs-ima/examples/advanced/), or sample code that reproduces the issue, that would help me get to the root of the error.

**Comment by minasaywhat** [comment]
@Kiro705 I think you might be right on that point, but I think it's going to be hard for us to continue investigating this unless our team can create a reverse PR to test this again. 

Our dev team created a fix that prevents the issue from happening, but it doesn't actually solve the root cause of the problem. Apparently we had some script running on our sites (issue was not reproducible on a page with our stand-alone player) that was causing this SourceBuffer error, which can happen when either the media file is not compatible (which we ruled out), or if the player for some reason can't download or play the next segment of the video. 

The question I have with how the player handles this is - if the media file (ad creative) plays for 1-2 seconds (compatible on browser/device), and then the media file stops playing for the remainder of the ad (white screen, with only ad controls shown), then why does the player behave as if the media file is playing through as expected, with the ad quartile events firing, and the progress bar moving forward?

**Comment by Kiro705** [comment]
Hi @minasaywhat ,

I cannot say for certain what led to the player's behavior if I am unable to reproduce said behavior. If your team is able to reproduce the issue, I think it would help us determine the root of the issue.

Please let me know if there is anything else I can do to help with the issue.
