### ISSUE TITLE
Non linear ads failed to play the content even after click (iOS / Android)

### ISSUE THREAD

**Issue by jaapmarcus** [googleads/videojs-ima#895]
When loading a non linear advertisment see example vast tag with the same issue an unhandled promise is thrown failing to start the 

> https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=[random]

See for live example:
http://mol-clan.nl/videojs-test/?vasttag=8

Please make sure to load Non Linear Ads 

Desktop, Linear ads (like preroll video's) and even failed ads are working fine. The only working solution is to mute the original source..

**Comment by jaapmarcus** [comment]
Please not currently the example tags always returns empty on Chrome...

**Comment by arnaudcasame** [comment]
Hi,

I was able to reproduce the behavior running the test page you shared on an iPhone X device. However, the issue seem to be with your implementation, I was not able to reproduce the behavior using our [VJS-IMA-AdvancedExample](https://googleads.github.io/videojs-ima/examples/advanced/) sample. We would recommend you to review your implementation and debug against our [VJS-IMA-AdvancedExample](https://googleads.github.io/videojs-ima/examples/advanced/).

**Comment by jaapmarcus** [comment]
Thank you for your response...

On the example page the video player is working according it should be but no ad is visible. 

How ever incase you increase the video size to for example 900px  width / 510px height the following errors are visible
http://mol-clan.nl/videojs-test/browser.png
http://mol-clan.nl/videojs-test/webinspector.png

Currently testing with iPad with 13.3.1

**Comment by jaapmarcus** [comment]
Found the issue on iPad 

If you disable the settings (default) Request the Desktop it works as it should be

navigator.userAgent.match('/iPad/') does not work due to the fact Apple thinks iPad is good enough that it can handle the "Desktop" site.

When I use console.log(navigator.userAgent);

it returns:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15
