### ISSUE TITLE
1009  The response does not contain any valid ads

### ISSUE THREAD

**Issue by conom13** [googleads/videojs-ima#899]
Hi there,
My video ads. administrators tell me, that from a while live preview for video advertisement stopped working. When I start debug my player I receive this messages:

[  0.116s] [boq.contributorcommonfccookieweb.fcCookieReader] No FC cookie found on document under non-legacy name. 
ima3_debug.js:42903  [  0.121s] [boq.contributorcommonfccookieweb.fcCookieReader] No legacy cookie named DATA_USE_CONSENT found on document. 
 [  0.279s] [ima.loader.AdsLoaderImpl] Requesting ads using new ads loader. 
bridge3.372.1_debug_bg.html:953  [  0.282s] [ima.loader.AdsLoaderImpl] requestAds, processing external request. 
bridge3.372.1_debug_bg.html:953  [  0.283s] [ima.loader.SequentialAdsLoader] Enqueued new request. 
bridge3.372.1_debug_bg.html:953  [  0.283s] [ima.loader.SequentialAdsLoader] Starting request from queue. 

type: "adLoadError"
errorMessage: "The response does not contain any valid ads."
errorCode: 1009

I think the problem is because of 3rd party cookies. If I blocked them from my browser live preview start serving random advertise campaign, but not the current  testing add campaign.

Can you give me a clue what can I do.
Thanks a lot!

p.s:

> https  : / / pubads . g . doubleclick . net /gampad/preview_cookie?gct=[STRING1]&op=set&redirect=[WEBSITE]&redirect_hash=[STRING2]&lineItemId=[INTEGER1]&creativeId=[INTEGER2]

live preview link for exapme

**Comment by Kiro705** [comment]
Hi @conom13 ,

Thanks for reaching out, the 1009 error suggests an issue with the ad tag. Do you know if you're able to reproduce the issue in the [sample page](https://googleads.github.io/videojs-ima/examples/advanced/) or your own sample code?

The link you provided returned a 404 error, when I tried to visit.

If you are, I think that would be the best way to.

**Comment by conom13** [comment]
https:// pubads.g. doubleclick. net/gampad/preview_cookie?gct=sTqR0Gbafc4Y2qGY8wUw2r3N-gWIAYCAgKCXzJnpiwE&op=set&redirect=https://www.vbox7.com/play:c0b24ace73&redirect_hash=AJlzBa2mfFfNqQzSirD5HSGATlEMLeSzYg&lineItemId=5322960218&creativeId=138306067477

**Comment by conom13** [comment]
And this is dfp url for ima sdk:
dfpUrlWithIma:
 https://pubads.g.doubleclick.net/gampad/ads?sz=1280x720|400x300|640x480|640x360&iu=/157018629/vbox7.com_1/vbox_preroll/21920502622&impl=s&gdfp_req=1&env=vp&output=xml_vast4&unviewed_position_start=1&url=https%3A%2F%2Fwww.vbox7.com&description_url=https%3A%2F%2Fwww.vbox7.com&correlator=1584000326&cb=1584000326tfcd=0&npa=0NaNxml_vast4&ad_rule=1&cmsid=2501857&vid=827624967795&cust_params=mdkey%3Dc0b24ace73%26break%3Dpreroll%26user%3Dedin_za_drug%26desktop%3D1

**Comment by Kiro705** [comment]
Hi @conom13 ,

This looks like an issue with you ad manager, if you would want to bring it up to your DFP contact.

I am basing this on the dfp url you sent resulting in the 1009 error, but the vast copied here (https://vastsynthesizer.appspot.com/videojs-ima-899) does work on the [videojs-ima testing page](https://googleads.github.io/videojs-ima/examples/advanced/)

Please let me know if there is anything else I can do, 
Thanks,
Jackson
IMA SDK DevRel

**Comment by WesleyCarnicl** [comment]
I'm new to google ad manager I'm trying to run video ads on my site. I have a ad unit created for the player i am using and when i do it says the vast tag is empty and i have the player with an order.
