### ISSUE TITLE
VAST 900:1021 doesn't trigger the ads-ima-adError event which makes the ad controls and events persist #714

### ISSUE THREAD

**Issue by sunilstg** [googleads/videojs-ima#900]
Hi All, 

Please help on this, I am getting error "adTimeout" and after that my "ad-load" event firing. Please advise how to get all ad error event.

**Comment by arnaudcasame** [comment]
Hi,

Were you able to reproduce the behavior using our [Advanced Videojs-IMA](https://googleads.github.io/videojs-ima/examples/advanced/) sample? Can you share the ad tag url you were using when you encountered this issue?

**Comment by sunilstg** [comment]
Hi,

With advance videojs ima it is possible so I will use it.

Thanks
