### ISSUE TITLE
cryptiles dependency is deprecated and has moved to @hapi/cryptiles

### ISSUE THREAD

**Issue by mafortier-nexapp** [googleads/videojs-ima#902]
![image](https://user-images.githubusercontent.com/64278521/80490958-19a68380-8930-11ea-9e09-ee431c523112.png)

You might want to check that.

**Comment by arnaudcasame** [comment]
Hi @mafortier-nexapp,

Thank you for reporting that to us, we'll take a closer at it and make the changes accordingly.

**Comment by Kiro705** [comment]
An update of this plugins dependancies has been made in https://github.com/googleads/videojs-ima/pull/905
