### ISSUE TITLE
Difficulty with use in Next.js 

### ISSUE THREAD

**Issue by vispaduchuri** [googleads/videojs-ima#903]
This is similar to #552, The Getting started steps to showcase the ES6 Imports, where we add certain links and scripts along with the Video-js tag in the index.html. In Next.js added these scripts in the custom _document.js.  After adding the video-js tag, Video-js is shown for all pages of the website.

Followed few examples and all end up with **player.ima is not a function** error, how can I implement this in next.js?

**Comment by arnaudcasame** [comment]
Hi,

If you're using Webpack to bundle your project, you should be able to import the plugin successfully by following the steps of our [ES6 imports guide](https://github.com/googleads/videojs-ima#es6-imports)
