### ISSUE TITLE
Ad data like getAdId issue supported?

### ISSUE THREAD

**Issue by abi3** [googleads/videojs-ima#904]
Hello, 

I m checking if i can get ads related data that is listed under google.ima.Ad class. 

Thanks,

**Comment by Kiro705** [comment]
Hello @abi3 ,

You can call the [event.getAd()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/google.ima.AdEvent#getAd) method on any IMA event to return the ad that is currently playing.

To set up IMA events you can follow the setup detailed in our [Advanced Example](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js).
