### ISSUE TITLE
Ads are working in Google Validator but not in VideoJS player

### ISSUE THREAD

**Issue by julianpfaller** [googleads/videojs-ima#906]
Hi all,
I have a VPAID tag that delivers actual ads as well as a fallback video (the fallback always appears once there is no real ad available).
Testing with the Google Validator delivers real ads every 2-3 requests. Testing with the VideoJS player with IMA SDK, I only get the fallback video, no matter how often I try.
I've tried to set the player to `INSECURE` but still just the fallback video.

I guess, since it's working fine in the Google Validator (which is just a web player), the ad settings should be fine and it should work with the VideoJS player as well. Are there any settings I'm missing out? So far, I haven't changed anything on the players configuration (except the `adTagUrl` of course), `vpaidMode` is true as well.

Thanks in advance!

**Comment by arnaudcasame** [comment]
Hi,

The ad tag URL delivering the VPAID should work the same as in the [VSI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector), the VIDEOJS-IMA plugin only processes and displays the ad served by the server, it doesn't alter in any way the ad's properties. Can you share the ad tag URL you were using when you encountered the behavior?

**Comment by julianpfaller** [comment]
Hi @arnaudcasame,
thanks for your response!
The ad tag URL I'm trying to get to work is: `https://pubads.g.doubleclick.net/gampad/ads?iu=/57201580/AATShowcase_Showcase_Android/AATShowcase_Showcase_Android_allDevices_VAST_W&description_url=http%3A%2F%2Ftoralarm.com%2Fpublic%2Fapp%2Fvideo-description.html&tfcd=0&npa=0&sz=640x480&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=`

There is a fallback (a train that runs in a circle). Every third or fourth request, I get a real ad in the VSI, but never get one with VideoJS.

Thanks in advance!

**Comment by arnaudcasame** [comment]
Hi,

I've run the ad tag you shared earlier against our [Advanced](https://googleads.github.io/videojs-ima/examples/advanced/) sample, the ad was displayed as expected by the plugin. Also, the ad's VAST XML doesn't have any fallback at all (see screenshot attached). Can you share an ad tag capable of reproducing the issue?

<img width="1581" alt="ad_successful_vast_no_fallback" src="https://user-images.githubusercontent.com/12627484/83374697-63084980-a39a-11ea-8f32-cef4fd4d2f97.png">
