### ISSUE TITLE
videojs.ima.js:1445 AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6

### ISSUE THREAD

**Issue by kalyanirawal** [googleads/videojs-ima#907]
Hi,

### Description:
We are using videojs and have integrated ima plugin for videojs.
We are creating options variable and passing it to ima which is called on player instance as follows:
var options = {
id: videoTagID
adTagUrl: 'Adtagurl'
};
player.ima(options);

### Results
Getting an error 1005 for the adtagurl

### Error output
We are getting an error on requesting the ad as below:
videojs.ima.js:1445 AdsLoader error: AdError 1005: There was a problem requesting ads from the server. Caused by: Error: 6
And 400 error code for the Adtag url.
The same adtag url is working fine on VSI but is giving error when we are using it in our player.

Thanks

**Comment by arnaudcasame** [comment]
Hi,

Can you share the ad tag you were using when you encountered the behavior? You can send it privately via `imatesting3@gmail.com` and let us know once it is done.

**Comment by kalyanirawal** [comment]
Hi,

I have shared the adtag on imatesting3@gmail.com

**Comment by arnaudcasame** [comment]
Hi,

I've run the ad tag url you shared against our [AdvancedExample](https://googleads.github.io/videojs-ima/examples/advanced/) and the ad was displayed as expected (see screenshot below). Can you share an ad tag url capable of reproducing the error you reported?
As per the IMA SDK documentation, the [AdError 1005](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/reference/js/google.ima.AdError) indicates that There was a problem requesting ads from the server.
<img width="1340" alt="Screen Shot 2020-06-09 at 8 24 26 PM" src="https://user-images.githubusercontent.com/12627484/84213928-ece99e00-aa8f-11ea-864c-959e37d9d892.png">

**Comment by kalyanirawal** [comment]
Hi,

We got it working, closing the issue, Thank you
