### ISSUE TITLE
Ad not playing on mobile if width is assigned to 100% for div tag under which videotag is appended.

### ISSUE THREAD

**Issue by kalyanirawal** [googleads/videojs-ima#909]
Hi,

We are using videojs for player and videojs-ima for ad.
Does width set to 100% cause Ad to not play on mobile?

1. We initially had common div width of 600px for laptop and mobile, in this case both ad and video clip plays properly on both laptop and mobile chrome browser.
http://cdnk.onmo.com/width600Absolute.html?clip=05697187.mp4&streaming=1&ext=m3u8&context=MADE/KIDS

2. As player 600px width is large on mobile, we changed the width to 100% for mobile phones, clip is playing but ad stopped working on chrome browser in some phones.
http://cdnk.onmo.com/width100percentage.html?clip=05697187.mp4&streaming=1&ext=m3u8&context=MADE/KIDS

Thank you

**Comment by kalyanirawal** [comment]
Hii,

Any updates on this issue?

**Comment by Kiro705** [comment]
Hello @kalyanirawal ,

Is it possible to reproduce the behavior using your ad-tag and the [videojs-ima demo player](https://googleads.github.io/videojs-ima/examples/advanced/)?

Currently, I am able to see successful ad playback for both links on chrome and firefox. To confirm, I am testing this on desktop. Is this bug only reproducible on mobile web?

Thank you,
Jackson
IMA SDK DevRel

**Comment by kalyanirawal** [comment]
Yes, it is only reproducible on mobile, on desktop it works fine. We want to set our player width according to mobile device so we gave 100% as width, in this case, in some mobile phones ad is playing  successfully but in some phones it isn't playing, so problem is the width i think. Is there any reason behind this?

Also, as width=100% didn't work for all devices i tried to set width using screen.width but still Ad didn't played in few devices while it played in some devices.

**Comment by graspme** [comment]
Hi,

I am also getting the similar issue with below error when ad size is set to player.width.
"Ad error: AdError 501: The overlay ad content could not be displayed since creative dimensions do not align with display area."

And the behavior is random in different phones.

Is there a set standard as how to set Ad size OR not to set at all and let IMA package take care of it?

Thanks,
Gaurav Khare

**Comment by Kiro705** [comment]
Hello all,

To clarify, the only change needed to reproduce this behavior is setting the width to 100% and playing the video on mobile?

Which devices is the issue reproducible on?

Is it reproducible using the Chrome inspector mimicking a mobile device?

Once we have the answers, I should be able to help debug the issue as it does seem related to the IMA-videojs plugin.

**Comment by kalyanirawal** [comment]
Hi,

The link, http://cdnk.onmo.com/width100percentage.html?clip=05697187.mp4&streaming=1&ext=m3u8&context=MADE/KIDS didnt work on Vivo v9
the two links below, 
 
1. http://cdnk.onmo.com/width600Absolute.html?clip=05697187.mp4&streaming=1&ext=m3u8&context=MADE/KIDS 

2. http://cdnk.onmo.com/widthscreen.html?clip=05697187.mp4&streaming=1&ext=m3u8&context=MADE/KIDS

worked with successful AD playback on the same phone.

Also, when video is played in landscape mode, All the three links above work fine with AD playing successfully.

Thank you

**Comment by Kiro705** [comment]
Hello @kalyanirawal ,

I do not have a Vivo v9 to test with, but was able to view ads on a Pixel 3 (please see attached screenshot)

There were no pre-roll ads, but a non-linear banner ad was shown. Is this expected? I can look into other devices I have available to test, but if the behavior is not reproducible for me, it will be difficult to determine a fix.

![Screenshot_pixel_3](https://user-images.githubusercontent.com/14110467/86945090-9a46e480-c116-11ea-9d3a-3b72a3f75480.png)

**Comment by graspme** [comment]
Hi @Kiro705 

I have a pixel 3a.

Today Ad playing in urls (width100percentage.html and width600absolute.html) but not in widthscreen.html.

But as I said earlier, the behaviour is random. Till a couple days back Ads were playing in all 3 links.

1. Different Ads are returned by Ad provider randomly.Something to do with Ad video resolutions?
2. Yes, it is reproducible using the Chrome inspector mimicking a mobile device
3. What is the relation of Ads playing everytime in landscape mode?

Thanks in advance,
Gaurav Khare

**Comment by Kiro705** [comment]
Hello Gaurav,

The best way to move forward on a fix would be to find a way to 100% of the time reproduce the issue. The specific ad chosen can vary depending on the signals sent to your ad manager, including the video player width. There may be an issue with a specific ad that is only sent at a mobile width.

Please feel free to reply with any questions, or steps to reproduce your issue.

Thank you,
Jackson
