### ISSUE TITLE
Which method to call to see if the player "isInAdsMode"

### ISSUE THREAD

**Issue by MikeSperone** [googleads/videojs-ima#910]
I'm handling an edge case in our videojs player where I need to see if we're currently playing an ad.

I got this working by doing check this successfully with this:
```
if (edgeCaseHappened) {
    if (this.player.ads.isInAdsMode() && !this.player.ads.isContentResuming()) {
        doTheThingAfterTheAd();
    } else {
        doTheThingRightNow();
    }
}
``` 

My co-worker brought up the question of whether we should be interacting with these methods and events from `videojs-contrib-ads` (`player.ads`) directly, or shouldn't there be a way to do this via `videojs-ima`?

It's not really documented either way, and I didn't _see_ anything in the src... so I was wondering if there is a `player.ima.<something>` to check for this case, or if it is recommended to directly use the methods from `videojs-contrib-ads`

Thanks!

**Comment by dioramayuanito** [comment]
hi Mike,

we can check it also from player.ima.controller.sdkImpl.adsActive === true

please cmiiw

**Comment by Kiro705** [comment]
Hello @MikeSperone ,

I would recommend using the [IMA ad events](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent) to track whether or not an ad is playing.

You could use either CONTENT_PAUSE_REQUESTED or STARTED to set a boolean to `true`, then use CONTENT_RESUME_REQUESTED or COMPLETED to set that boolean back to `false`.

The difference between the two types of events being focused on an entire ad break or individual ads.

Let me know if you have any more questions, to set up ad events with the VideoJS-IMA plugin you can look to the [advanced example](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/ads.js).
