### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#916]
Hi,  is this supposed to happen or have iI got something wrong somewhere?  I'm trying to use my own VMAP in effect, to set pre-rolls, mid-rolls etc

Access to XMLHttpRequest at 'https://domain/scripts/pmp.xml' from origin 'https://imasdk.googleapis.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by Kiro705** [comment]
Hello @spormeon ,

Would it be possible for you to share the steps to reproduce this error?

Also, are you able to reproduce this error when using our [sample ad-tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags)? If not this suggests an error with the ad-tag and not your IMA implementation.

**Comment by spormeon** [comment]
i think i have this sorted by adding a cors rule to allow https://imasdk.googleapis.com  on my s3 bucket

**Comment by Kiro705** [comment]
Issue resolved and closing.
