### ISSUE TITLE
ima only support xml or can json be used

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#917]
Hi,  I'm trying to find out if ima only supports xml for a vmap file, or can i return xml formated in json?

**Comment by Kiro705** [comment]
Hello @spormeon ,

The IMA SDK does not support VMAP or other ad-tags formated in json. For other questions related to IMA SDK support, I recommend searching in or raising questions with the [IMA support forum](https://groups.google.com/g/ima-sdk).
