### ISSUE TITLE
set cookies

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#919]
What is the default on cookie setting, I don't see any info anywhere on it, obviously in the current ad ecosystem, this is highly relied on:

only info I see is in sdk docs, but nothing in this videojs-ima:

https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.ImaSdkSettings#isCookiesEnabled

**Comment by Kiro705** [comment]
Hello @spormeon ,

The videojs-ima plugin does not directly handle cookie settings, I would recommend searching or reaching out in the [IMA forum](https://groups.google.com/g/ima-sdk) for support.

**Comment by spormeon** [comment]
surely this should be in here, its one of the fundamentals of internet advertising?

**Comment by Kiro705** [comment]
This plugin focuses on implementing the IMA SDK with the videoJS player. Because cookies are handled by the IMA SDK without needing setup from the publisher, I recommend asking there for support regarding cookies.
