### ISSUE TITLE
Skip ads for 3rd party VAST video

### ISSUE THREAD

**Issue by aydinkn** [googleads/videojs-ima#92]
Hi,

I create and show skip button, but how can I handle skip adsense for 3rd party VAST video?

**Comment by shawnbuso** [comment]
Hi,

All skip buttons should be handled by the SDK using the VAST 3 standard - you shouldn't render your own skip button in any scenario. If you have an AdSense account and you want those ads to be served as skippable, you should be able to find help in the [AdSense forum](https://productforums.google.com/forum/#!forum/adsense).

Thanks,
Shawn

**Comment by aydinkn** [comment]
I build a global video player (like jwplayer) and some times gives VAST adsense url and skip adsense parameters. I handle 2 adsense type: IMA or VAST. If player has a IMA adsense (GDFP), I not render and handle skip button because SDK handled for me.
But when I use VAST (for example: http://ad3.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2), SDK don't show and don't handle skip button.

I must handle skip adsense for VAST (not IMA), because player has some skip adsense parameters (skippable, skip offset etc.) Some developers may be need this, like me.

**Comment by aydinkn** [comment]
I mean, skip adsense parameters has come with external parameters for my global video player (like jwplayer). And I must handle that parameters if VAST XML not serving skippable. Skip control must be handled and customized on video player (for example http://support.jwplayer.com/customer/portal/articles/1433818-configuring-ad-skipping). Jwplayer not handle skip for IMA but handle with external parameters for VAST adsense. I need this.

**Comment by aydinkn** [comment]
Hi guys, I resolved my problem with:
```javascript
// For clear ad tracking timer
player.ima.onAdComplete_(null);
// Stop and clear ad assets
adsManager.stop()
```
