### ISSUE TITLE
cant get disabledAdControls to work

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#921]
i updated to 1.8.0 and am trying to turn off controls in effect with:   i'm presuming this is the right way to do it, juts add to the 
imaOptions as again, I can't see any info anywhere showing where to put etc

![prebid-config_obv_copy_js_—_Prebid_Publishers__Workspace_-2](https://user-images.githubusercontent.com/8503167/88930729-c536db00-d273-11ea-946d-fa0d1905b6de.png)

**Comment by Kiro705** [comment]
`disableAdControls` was added in version 1.8.0, can you confirm that you are on this version or higher?

Here is the commit that added the feature ([commit](https://github.com/googleads/videojs-ima/commit/3bfd6c294863bd19000d3a829e69ad2d6cec192d))

**Comment by spormeon** [comment]
yep as put above, updated to 1.8.0

**Comment by Kiro705** [comment]
Can you verify that the `ima-controls-div-showing` class is not being added to your ad controls div?

I was able to see `disableAdControls` work on my test app

**Comment by spormeon** [comment]
this?

![DevTools_-_127_0_0_1_5500_prebid_pub000017_index_outside_html](https://user-images.githubusercontent.com/8503167/88939222-2cf22380-d27e-11ea-8ab2-640acd2fde82.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

The way `disableAdControls` works can be seen [here in ad-ui.js](https://github.com/googleads/videojs-ima/blob/master/src/ad-ui.js#L493-L506). It will add the `ima-controls-div-showing` class only if `disableAdControls` is false.

For this to work it is important that there is a corresponding `ima-controls-div-showing` class in your css, like in [videojs.ima.css](https://github.com/googleads/videojs-ima/blob/master/src/css/videojs.ima.css#L77).

`showControlsForJSAds` works by hiding the controls if the ad's content type is `application/javascript`, [here in ad-ui.js](https://github.com/googleads/videojs-ima/blob/master/src/ad-ui.js#L405-L415). Note this will only happen for VPAID ads or javascript based ads.

I have verified these are working as intended, would it be possible for you to share steps to reproduce, or code snippets to help me reproduce the issue?

**Comment by spormeon** [comment]
the css item is there:

![videojs_ima1_8_0_css_—_Prebid_Publishers__Workspace_](https://user-images.githubusercontent.com/8503167/88972458-7d34aa00-d2ad-11ea-8be0-0e7741d367bf.png)

seems there is something else wrong then, as disableAdcControls is set to true, and there no div showing, but controls are still there when you float over the ad

what other code snippets do you need?

**Comment by Kiro705** [comment]
In your previous comment showing the dom, I do not see the class `ima-controls-div-showing` being added. This is expected behavior. Please see the attached image of my player with ads playing and controls not showing. This is the same state when it is moused over.

If your issue persists, please share any relevant code or steps I would need to reproduce the issue, including ad-tags and specific browsers the error is visible on.

<img width="517" alt="hidden_ad_controls" src="https://user-images.githubusercontent.com/14110467/88975943-2ae19200-d289-11ea-949c-abc18c3a8634.png">

**Comment by spormeon** [comment]
test page here: https://ads.vsvl.co.uk/pub000017/index.outside.html

**Comment by Kiro705** [comment]
Hello @spormeon ,

Looking at your test page, the file named `videojs.ima.min1.8.0.js` is actually version 1.7.5. If you search within the file, you will see `var n="1.7.5"` indicating the version number. I am not sure how this could have happened, but updating your videoJS-IMA to v1.8.0 should resolve the issue.

Please let me know if that resolves your issue.

**Comment by spormeon** [comment]
better check your zip file for 1.8.0.  got a school boy error lol

**Comment by spormeon** [comment]
you def got something wrong,  you now have 1.8.0 in the 1.8.1 download zip file

**Comment by Kiro705** [comment]
Thanks for surfacing this issue. I had been testing through the npm version and not the zip file.

latest zip files should not contain the latest version.

Can you confirm if `disableAdControls` is working for you?
