### ISSUE TITLE
VMAP timeOffset percentage

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#928]
would anyone know if its possible to have a vmap that automatically sets the mid rolls half way through a video with videojs ima and/ or ima,  e.g,  if 1 video is 1 min, it sets mid roll at 30 sec, if video is 3 mins, sets them at 1m30secs?   As far as I'm aware this is IAB VMAP spec but cant find any info anywhere?

**Comment by Kiro705** [comment]
The IMA does not currently support VMAP timeOffset percentage, so unfortunately there is not current way to do this for implementations of IMA.

**Comment by spormeon** [comment]
Ok , why is that when its a IAB standard, to which your signed up to?
