### ISSUE TITLE
seeing a url set of the page before, very weird

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#929]
Hi,  I'm seeing a weird problem, that the url on the ad tag is setting url= of the page i was on before and not the page im actually on,  is this a ima problem or an actual website problem?

![DevTools_-_www_twentyfournews_com_homepage_latest-news_png_and_Latest_News_Archives_-_Twentyfournews_com](https://user-images.githubusercontent.com/8503167/90000006-821f3380-dc87-11ea-9674-84a43e45dc93.png)

**Comment by Kiro705** [comment]
<img width="1487" alt="url_parameter_screenshot" src="https://user-images.githubusercontent.com/14110467/90060075-25853e00-dcb2-11ea-9346-66cea1f6caf1.png">

Are you able to reproduce this issue using the [videoJS-IMA plugin samples](https://googleads.github.io/videojs-ima/)? Please see the attached image. I was not able to see this in the simple example.

If you cannot reproduce there, it may be an issue with your implementation. To note, it is not recommended to manually set the `url=` parameter. This is set by the SDK.

**Comment by spormeon** [comment]
see my other issue, posted not long ago,  the url is actually being set by SDK

**Comment by spormeon** [comment]
so the SDK is using document.referrer and not window.location.href.  The HUGE problem occurs when some visits site, they must be pinging a url of where they came from and not of the site which they are on, which is utter madness, not too mention that you guys with adx obviously arn't paying for an add that looks like its come from facbook, even though the user is on domainx.com and anyone using Google ad manager is potentially paying for this privildge in ad manager CPM charges

**Comment by Kiro705** [comment]
If it is an SDK issue, I would recommend looking for support from the [IMA SDK forum](https://groups.google.com/g/ima-sdk). Based on the response there, we can determine next steps to resolve the issue.

**Comment by spormeon** [comment]
they we're reported 4 years ago! your blatantly not doing it for an "interest" reason at a guess: https://groups.google.com/g/ima-sdk/c/Uw30ImwdBlw
