### ISSUE TITLE
Request for example of VideoJS integration with IMA Flash SDK

### ISSUE THREAD

**Issue by saxena-gaurav** [googleads/videojs-ima#93]
Currently we have an example of videojs integrating with IMA HTML5 SDK. I'd like to request similar example integrating videojs with ima flash sdk.

**Comment by shawnbuso** [comment]
Hi there,

Currently we're only supporting this HTML5 integration with videojs. If you'd like to use the Flash SDK, I think your best bet would be to follow along with the [Flash "Get Started" guide](https://developers.google.com/interactive-media-ads/docs/sdks/flash/quickstart) substituting the videojs player for the Flash VideoPlayer.
