### ISSUE TITLE
getting domains reported that are no where near the site i have video on

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#930]
I believe you are using document.referer where we're expecting window.location.href or similar,  this is throwing all sorts of problems, especially with google ads.txt reports and ultimately with ADX ads and other ads, they think the domains are such as facbook.com etc, where the user has come from and not the page they are on

**Comment by Kiro705** [comment]
I have confirmed that `document.referrer` is not used within the videoJS-IMA plugin code.

Could this be related to https://github.com/googleads/videojs-ima/issues/929? If so, it may be best to close this issue and track the problem on issue #929.

**Comment by spormeon** [comment]
so its the SDK doing it?

**Comment by Kiro705** [comment]
For issues related to the IMA SDK and specifically not the videoJS-IMA plugin it is recommended to reach out in the [IMA SDK forum](https://groups.google.com/g/ima-sdk). The github issues queue here is meant for issues specific to the videoJS-IMA plugin.

**Comment by spormeon** [comment]
well i guess thats at least admission it you that's doing it, as in google
