### ISSUE TITLE
skip not working when using vmap file

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#932]
Hi  i have skip set at 5 seconds for an video in the adserver etc but its not working and setting any skip button after 5 secs, we are uisng a vmap file, that then has the tags within it,  the vast tags within seem to have the skip off set there but not being obeyed?

**Comment by Kiro705** [comment]
Hello @spormeon ,

Were you able to reproduce this behavior with IMA's sample ad tags? I tried reproducing using [this skippable tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=) and the [videoJS-IMA advanced sample](https://googleads.github.io/videojs-ima/examples/advanced/) and saw the skip button and the ad was able to be skipped as expected.

If not able to reproduce it with the sample tags, it may be an issue with the specific ad tag you are using.

Please let me know if there are any other steps to reproduce the issue.

Thank you,
Jackson
IMA SDK DevRel

**Comment by spormeon** [comment]
this ios one of the vast tags thats inside the vmap,  it obviously changes on page load but this one doesn't show any skip button.  I have disablecontrols on by the way:

https://securepubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&output=vast&unviewed_position_start=1&correlator=1597942974449&sz=640x480&url=https%3A%2F%2Fads.vsvl.co.uk%2Fpub000018%2Findex.outside1.html&iu=/1001824/Video-Corner-Units/Video-Corner-Test&description_url=https%3A%2F%2Ftwentyfournews.com&ad_type=video_text_image&pageUrl=https%3A%2F%2Fads.vsvl.co.uk%2Fpub000018%2Findex.outside1.html&cust_params=hb_uuid%3Dundefined%26hb_cache_id%3Dundefined
