### ISSUE TITLE
Replay button after ad [support]

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#935]
Is it possible to show replay button after ad? 
I tried pausing the player (`this.player.ima.getAdsManager().pause();` and pauseAds()) on events ENDED and COMPLETE but I was not able to prevent player from closing/disposing after. Is there a different aproach on how to do this properly ? 

What I want to do:
-I just want to have a replay button  after video ad is done playing 
-On button "replay" click I want to just restart the video ad without triggering new AD IMPRESSION

_I managed to pause it by pausing (`this.player.ima.getAdsManager().pause();` pauseAds()) the player on ENDED event and with use of debugger break point(setting break point and then after few seconds clicking resume script) inside COMPLETE event listener, but as soon as I remove break point and run it without it, it does not work anymore_  

If there is no specific property that ads replay button, I might just do something like this and show replay icon I guess:
```js
videoEl.addEventListener("timeupdate", function () {
    if (videoEl.currentTime > videoEl.duration - 0.5) {
        videoEl.pause();
    }
});
```
But then there is a problem that currentTime does not work on android chrome :( 

Ok I found a way to get correct currentTime on android chrome as well:
```js
player.ima.addEventListener(EventType.AD_PROGRESS, (IMAEvent) => {
        let adProgressData= IMAEvent.getAdData();
        console.log(parseInt(adProgressData.duration)-parseInt(adProgressData.currentTime));
      });
```

**Comment by damjan25** [comment]
@Kiro705 Is there a way to set currentTime throught ima ? Since setting current time on html5 video element doesn't do anything(since its always 0 or 0.04). document.querySelector("video").currentTime = 0;

**Comment by damjan25** [comment]
Why is video.currentTime not working on Android Chrome ?
For example if you open this example and ad some test ad tag into it, everything works as expected if you try it on iphone X emulator, but when you swap to pixel 2 emulator, then the currentTime is always 0 
https://googleads.github.io/videojs-ima/examples/advanced/

**Comment by Kiro705** [comment]
Hello @damjan25 ,

Unfortunately IMA does not support a method to set the current time, adEvent.current time is the time when the event was fired, and changing the value will not seek to that place within the ad.

In addition, I do not believe there is a supported way to replay viewed ads.

**Comment by damjan25** [comment]
Thank you for answer and support :)
