### ISSUE TITLE
Replay ADS Video

### ISSUE THREAD

**Issue by lzhudson** [googleads/videojs-ima#937]
Is there a way to create the video with ads only? Even after skipping the ad go to another ad and create this loop?

**Comment by Kiro705** [comment]
Hello @lzhudson ,

It sounds like you may be looking for a way to implement ad pods. Please see this [Ad Manager article on setting up ad pods](https://support.google.com/admanager/answer/6399249?hl=en).

Also, please let me know if you have any follow up questions.

Thank you,
Jackson
IMA SDK DevRel
