### ISSUE TITLE
repeating announcement video

### ISSUE THREAD

**Issue by lzhudson** [googleads/videojs-ima#938]
When I load the player, when I skip the ad and make a new request it always returns the same ad to me.

**Comment by Kiro705** [comment]
Hello @lzhudson 

I think this is likely an issue with you ad-tag setup in Ad Manager. Are you able to see loading the ad-tag in the [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) result in different ads? If the ads are the same there, I would recommend reaching out to your Ad Manager agent to help resolve the issue.

**Comment by lzhudson** [comment]
Hello @Kiro705 

I tested the tag here though, now it is returning me error 1009.
Follow the test link: https://www.mtorrespack.com.br/video-ads/

**Comment by lzhudson** [comment]
@Kiro705 Now he is repeating the same mistake. Always display the same ad even changing the tag and making the request.

**Comment by Kiro705** [comment]
Hello @lzhudson ,

Thank you for sharing the test page. I think the issue for you is with the ad tag and not the implementation. I tired using [IMA's sample skippable pre-roll](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=), then on the SKIPPED event, I called the following code to switch the ad to a [IMA's sample post-roll](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpostonly&cmsid=496&vid=short_onecue&correlator=) and that played successfully at the end of the video.

```
player.ima.changeAdTag(postRollAdTag);
player.ima.requestAds();
```

I think the current issue is the 1009 error which will have to be solved on the ad manager side.

In addition, the IMA team does not recommend requesting new ads for the same content video on the SKIPPED event. This can be seen as spammy behavior if multiple ad requests are made in quick succession.
