### ISSUE TITLE
order only videos or switch between video and banner

### ISSUE THREAD

**Issue by lzhudson** [googleads/videojs-ima#939]
How do I display a video or banner, or alternate between the two?

**Comment by Kiro705** [comment]
Hello @lzhudson ,

The decision of what type of ad to show is based on the ad tag request and can be configured in ad manager.

In terms of displaying video and banner ads, video ads can be displayed with a typical IMA setup. For banner/companion ads I would recommend following the [companion ads guide](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/companions). You can test you companion ad setup using [this sample preroll tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=) which has companions sized at 300x250 and 728x90. You can see them displayed on the [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) if you use that ad tag and scroll down on the page.

Let me know if you have any other questions regarding this.

Thank you,
Jackson
IMA SDK DevRel
