### ISSUE TITLE
marking event handler as 'passive

### ISSUE THREAD

**Issue by etomProductions** [googleads/videojs-ima#940]
Hello,

Is this a solution for this warning please?
bridge3.410.0_en.html:91 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

You can find the warning even in your example provided as demo. [Sample Page](https://googleads.github.io/videojs-ima/)

Thank you,

**Comment by Kiro705** [comment]
Hello @etomProductions ,

Can you provide steps for reproducing this error? Or which sample causes the error?

Thank you,
Jackson
IMA SDK DevRel

**Comment by etomProductions** [comment]
Hello @Kiro705,

First of all thank you so much for reply to my question and apologize for the delay as I did not got any notification from github and I will look to my email settings.

AS I mentioned above it (was) showing also in your example page as well if you open the console but for some reason not any more. Did you updated the page?

Please advise.

For me I have the error in my own host (private and dont have yet public access.) and I tried it in different hosts with the same result.

Thank you,
Kind Regards,
Tariq

**Comment by Kiro705** [comment]
Hello @etomProductions ,

Sorry for the slow reply. Without a way for me to reproduce the issue, it will be difficult to help with a solution.

Are there any specifics you can provide, as to types of devices/browsers where the error occurs. If it specific to certain ad types?

More obviously, if your code is adding any event listeners to the 'touchmove' event, I would look there to resolve the issue.
