### ISSUE TITLE
ads virtually stopped since last chrome update

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#941]
This is a bit of an unusual one, ads seem to have virtually stopped since the last chrome update few days ago, they still seem to work ok in FF, there are no errors being thrown, has anyone else been seeing this,  I'm  stumped as to what is causing it, videojs ima, videojs, not a clue

**Comment by Kiro705** [comment]
Hello @spormeon ,

There is currently an issue on Android Chrome with ad tags containing MediaFile tags `type="application/x-mpegURL"`. If the HLS resource has a manifest using cross-origin resources, which Chrome now configures MediaPlayer to refuse to play for security reasons. More information and a work-around is available here https://github.com/googleads/videojs-ima/issues/933

If it is a different, would it be possible to reproduce the issue in the [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) or the [videoJS-IMA test page](https://googleads.github.io/videojs-ima/examples/advanced/)?

**Comment by damjan25** [comment]
@Kiro705 
1. Does setting adsRenderingSettings have any downsides ? 
2. Does this effect vpaid ? 
3. Should this be set on desktop as well or only on mobile ? :thinking: 
```js
adsRenderingSettings = {
    mimeTypes: [
        'video/mp4',
        'video/webm',
    ],
}
```

**Comment by Kiro705** [comment]
Hello @damjan25 ,

By setting your mimeTypes to mp4 and webm it will limit what media types the IMA chooses from ad tags. This will also limit it for Vpaid ads. For more information you can see the [IMA documentation](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsRenderingSettings#mimeTypes).

The issue I described, related to only mobile web ad playback on Android devices.

**Comment by damjan25** [comment]
@Kiro705 thanks for explanation and solution, I tried it on IOS and Android and number of events "ADSERROR"  decreased for 85% per hour :)
