### ISSUE TITLE
How to Log Vast XML response?

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#943]
Is it possible to log vast XML response from ima ? 

For example for vast tag like this: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=

I would like to see what is inside vast XML before or after ad is loaded.

**Comment by Kiro705** [comment]
Hello @damjan25 ,

It is possible to view the VAST XML response in Chrome's network tab (see screenshot), however, IMA does not provide a method of logging this VAST XML response.

<img width="1614" alt="vast_view-screenshot" src="https://user-images.githubusercontent.com/14110467/94947721-19488080-04ac-11eb-93c6-5d74e1d5e733.png">

**Comment by damjan25** [comment]
@Kiro705 is it possible to console.log firstQuartile link from the XML if you  listen on event LOADED or maybe ADSREADY ? 🤔 
for example like this:
```
player.ima.addEventListener(EventType.LOADED, (e) => {
      console.log(e.firstQuartile)
})
```

**Comment by Kiro705** [comment]
Hello, @damjan25 ,

The most information about the ad is available using the [getAdData()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent#getAdData) method. You can call it in the `LOADED` event like this:

```
player.ima.addEventListener(google.ima.AdEvent.Type.LOADED, (e) => {
      console.log(e.getAdData());
});
```

**Comment by damjan25** [comment]
![image](https://user-images.githubusercontent.com/60606529/94998127-d66fd100-05af-11eb-8131-a438bea35309.png)
Hmm there is really not that much data in e.getAdData() obj :thinking: will there be support in there future to LOG xml from vast tags like this one ? Because it is really hard to debug in IOS real device when you get 303 error or 1009 error and you cant really check if some tracking links are missing in the XML or is the whole vast empty and its throwing the error :(

**Comment by komw** [comment]
@damjan25 did you found how to get XML content from ad tag?

**Comment by damjan25** [comment]
@komw unfortunately no. Found partial solution for some vast tags, but it did not work for all vast tags so it wasn't good enough for production and since then I havent looked into it anymore. :/
