### ISSUE TITLE
way to hide 'notify bar"?

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#944]
Is there a way to hide the notification bar on the number of ads?, this only appears for google adx ads and not prebid ads

![Prebid_and_Adx_and_Server_Video_Demo](https://user-images.githubusercontent.com/8503167/94950804-1dd85d80-04db-11eb-8499-27809a575068.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

The ad UI is not typically editable through the IMA SDK, so I do not believe this is possible through IMA methods.
