### ISSUE TITLE
How to make pause area smaller on mobile?

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#945]
On mobile phone when you click on video ad it pauses. 
1. Is it possible to make this area a bit smaller at the top and bottom ? So instead of 100% video height it would be 80%(10% margin top and bottom) of the video height would be pausable.
2. On which element is set eventListener ? :thinking:

**Comment by Kiro705** [comment]
Hello @damjan25 ,

The IMA element that gets the ad clicks is the [AdDisplayContainer](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdDisplayContainer).

The IMA SDK does not provide a way to configure the size of this element and so a method to do so does not exist in the videoJS-IMA plugin. We do not recommend altering the ad UI, as this can cause unforeseen issues depending on the types of ads being played and the player's environment.

**Comment by damjan25** [comment]
ok, thank you :D
