### ISSUE TITLE
seeing VPAID ads not load

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#948]
As in the title really,  I'm seeing some VPAID ads that don't load and throw an error,  I had a search and found that maybe i need to turn on vpaid as its not on by default , is this true?

do I need to use this?
google.ima.settings.setVpaidAllowed(true);

**Comment by Kiro705** [comment]
Hello @spormeon ,

VPAID mode being enabled is the default for the videoJS-IMA plugin, so it would only be the cause of your issue if you have manually turned it off.

You can set the VPAID setting using the plugin setting `vpaidMode` and setting it equal to the appropriate value (example: `google.ima.ImaSdkSettings.VpaidMode.ENABLED`).

To help debug, you can test your VPAID tags on the [VSI](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vastinspector) and toggle the VPAID setting in the advanced controls.

Let me know if you have any farther questions.

Jackson
IMA SDK DevRel

**Comment by damjan25** [comment]
@spormeon  did you try `google.ima.ImaSdkSettings.VpaidMode.INSECURE` ?

@Kiro705 is there any downside of running vpaidMode on INSECURE ? :thinking: 

That worked for me.

**Comment by spormeon** [comment]
i do have it there, but still seems to error with INSECURE OR ENABLED it:
var imaOptions = {
    id: 'content_video',
    adTagUrl: vmapUrl,
    adLabel: 'ADVERTISEMENT',
    autoplay: true,
    muted: true,
    debug: true,
    disableAdControls: true,
    preventLateAdStart: false,
    disableFlashAds: false,
    showControlsForJSAds: true,
    showCountdown: false,
    prerollTimeout: 18000,
    autoPlayAdBreaks: true,
    vastLoadTimeout: 18000,
    setAdWillAutoPlay: true,
    setAdWillPlayMuted: true,
    setContinuousPlayback: false,
    numRedirects: 12,
    disableCustomPlaybackForIOS10Plus: true,
    vpaidMode: google.ima.ImaSdkSettings.VpaidMode.ENABLED,   
    // ENABLED, INSECURE or DISABLED
    loadingSpinner: false,
    cookiesEnabled: true

  };

**Comment by Kiro705** [comment]
Hi all,

Please see this [guide on VPAID creatives](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/vpaid2js) to understand more about them and how IMA handles VPAID ads.

@spormeon , could you share more info on the error you are experiencing? When I tested the ad tag you provided, I saw ads play on the [videoJS-IMA test page](https://googleads.github.io/videojs-ima/examples/advanced/), but content playback did not resume following the ad. This is likely a problem with the specific VPAID ad.

As a note, I did find a bug when setting VpaidMode to DISABLED that I will work on a fix for.

**Comment by spormeon** [comment]
i cant get the error any more, as i'm not seeing the ad in last couple of days but basically it was a "blank Screen", no ad showed and the yellow progress bar went across the bottom.  Thats about all i can offer sorry
