### ISSUE TITLE
IMA plugin for only VPAID

### ISSUE THREAD

**Issue by komato3huk** [googleads/videojs-ima#953]
Good afternoon.
I ask for help in setting up the plugin to work with ads only. No content playing. Is that possible?
How to organize a plugin with multiple VPAID streams in a VAST container

**Comment by Kiro705** [comment]
Hello @komato3huk ,

Using the IMA to play ads without content is not a supported use-case. While it may be possible, I would not have any examples our guides to provide.

In terms of creating a VPAID tag or VAST tag, I would look at this google ad manager documentation on [VPAID](https://support.google.com/campaignmanager/answer/4533270?hl=en) and [VAST](https://support.google.com/admanager/table/9749596?hl=en).

**Comment by komato3huk** [comment]
Ok then I'll rephrase.
Can I add an example using VMAp to the examples?

**Comment by Kiro705** [comment]
Hello @komato3huk ,

It is my understanding that the current examples are compatible with VMAP ads.

I just tested the [Advanced demo](https://googleads.github.io/videojs-ima/examples/advanced/) with this [VMAP ad tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=) and saw ads play as expected.

For other ad tags to test you implementation with you can look the [IMA's sample tags page](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/tags).

I am open to new sample apps, but currently do not understand what use-case is currently missing.

Thank you,
Jackson
IMA SDK DevRel
