### ISSUE TITLE
ima work with GPT slots on page

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#954]
I'm trying to get this working now with other ads on the page that use GPT,  does this work with GPT as i'm seeing error, in that I can get video on own or display on own but not both together:

error is no there when its one or the other on page:
![DevTools_-_cheftalk_com_-3](https://user-images.githubusercontent.com/8503167/96266614-c0560d80-0fbe-11eb-8e96-dec44dc3d7ec.png)

**Comment by Kiro705** [comment]
Hello @spormeon ,

Are there any steps to reproduce this error? If you want to privately share the ad tag you can email it to jsui@google.com

**Comment by spormeon** [comment]
just emailed you

**Comment by Kiro705** [comment]
Hello @spormeon ,

Thank you for sharing the web page. I was able to see the error occurring there.

Would it be possible for you to share steps to reproduce the error using the [plugin's sample player](https://googleads.github.io/videojs-ima/)? or [examples](https://github.com/googleads/videojs-ima/tree/master/examples)? Without being able to see the code leading to the error, it will be hard to debug the issue.

**Comment by spormeon** [comment]
hi, you can get to all the code at the bottom of the page in source code

**Comment by Kiro705** [comment]
Hello @spormeon ,

It looks like the error is pointing to a minified file. Would it be possible to reproduce the error in one of the environments I mentioned in the above comment?

**Comment by spormeon** [comment]
it cant be replicated there as it is built within prebid as well,  cant you "pretty" the code with a chrome extension?

**Comment by Kiro705** [comment]
Hi @spormeon ,

Sorry, I misspoke. The code is minified and obfuscated, meaning I cannot determine the functionality of where the error is coming from. 

I looked at the ad tags being used on the web page, and was not able to reproduce the error in the videoJS-IMA test page.

In addition, I do not see an instance of `[object].parent` being called in the videoJS-IMA plugin code base, meaning it is likely not an issue with this plugin. The error also does not look to be coming from the IMA SDK code base, based the line error of `pubads_impl_2020101201.js:6`. For more help on integrating Google publisher tags, I would look to the [GPT docs](https://developers.google.com/doubleclick-gpt/guides/get-started) and the [GPT help articles](https://support.google.com/admanager/answer/181073) to look for a resolution to your issue.

**Comment by spormeon** [comment]
i got a feeling this may have to do with GPT lazy load feature but i'm not 100% sure, I think that as the video is on site GPT might be trying to pick it up as a "adunit' and maybe that is throwing the error, can you look into that?

**Comment by Kiro705** [comment]
Unfortunately, as this does not seem to be related to an issue with the videoJS-IMA plugin, there is little I can do to help from here. I think the best place to resolve the issue may be the [Google Ad Manager help site](https://support.google.com/admanager). However, if you think it is an issue specific to the IMA SDK you can reach their support through the [IMA technical forum](https://groups.google.com/g/ima-sdk).

The main purpose of the VideoJS-IMA plugin's issue queue is surface issues with the plugin and problems with its implementation.
