### ISSUE TITLE
disable compnaion ads

### ISSUE THREAD

**Issue by spormeon** [googleads/videojs-ima#955]
While calling a Vast Tag URL using IMA SDK for HTML5 is there a way  to disable calling the Companion Ads Node?

**Comment by Kiro705** [comment]
Hello @spormeon ,

My understanding is companion ads are not enabled in the default example of the videoJS-IMA plugin. To enable them you can follow the [advanced example here](https://github.com/googleads/videojs-ima/blob/master/examples/advanced/index.html#L24).

To disable them, you can simply omit the code regarding companions in that example, or situationally run that code dependent on certain conditions of your choice.
