### ISSUE TITLE
Help: how exactly would you play 2 ads on each quartile?

### ISSUE THREAD

**Issue by mr-winson** [googleads/videojs-ima#958]
The documentation isn't 100% clear, how exactly would you play 2 ads on each quartile?

Thanks

**Comment by Kiro705** [comment]
Hello @mr-winson,

The videoJS-IMA plugin does not have a specific method to make ad requests at a percentage of the content video. In you implementation, you will need to have a listener determine when it is the appropriate time, and then make the ad request.

Let me know if you have any questions.

Thank you,
Jackson
IMA SDK DevRel

**Comment by mr-winson** [comment]
Thanks! Yeah, I got the event listener figured out! 

Thanks.
