### ISSUE TITLE
CONTENT_RESUME_REQUESTED causes ad to be hidden

### ISSUE THREAD

**Issue by markkesty** [googleads/videojs-ima#96]
If I have a non-linear ad and someone clicks on it, it becomes a linear ad, stops the video from playing, and fills the screen. If at that point someone "closes" the ad, it goes back to being a nonlinear ad and the video is resumed through the CONTENT_RESUME_REQUESTED event which calls a method, "onContentResumeRequested_". 

The problem is that onContentResumeRequested_ also sets the adContainerDiv's display to 'none' (line 271). I imagine that this was done because the programmer assumed that once I'm done with the linear ad and I go back to nonlinear, I'm done with the ad altogether. However, in our case, this is not true. I want the nonlinear ad to continue to show and to allow the user to click on it once again and make it linear.

I fixed this by enclosing the line that hides the div in an if-statement which checks if the type of the ad is linear, in which case it doesn't hide the div:

            if (adEvent.getAd().isLinear()) {
                adContainerDiv.style.display = 'none';
            }

Please check my assumptions and fix.

**Comment by shawnbuso** [comment]
Thanks for the detailed info - if you submit this a a pull request we should be able to get it included.
