### ISSUE TITLE
ads does not run shows cors error

### ISSUE THREAD

**Issue by sahusambit09** [googleads/videojs-ima#961]
![Screenshot (32)](https://user-images.githubusercontent.com/65359407/100439394-8271fc00-30c9-11eb-88f3-8476928099ad.png)

**Comment by sahusambit09** [comment]
this problem only shows on my pc..Others just work fine..can anyone tell me how to handle this error..and this error happens on edge,firefox and chrome as well and the ads don't play

**Comment by Kiro705** [comment]
Hello @sahusambit09 ,

Would it be possible to share any details about your implementation that could help me reproduce the issue on my end?

Thank you,
Jackson
IMA SDK DevRel
