### ISSUE TITLE
Ad controls not showing up during ad breaks

### ISSUE THREAD

**Issue by joshverd** [googleads/videojs-ima#968]
This is my code for the player:
`newPlayer.ima({
  adTagUrl: "",
  disableAdControls: false,
  showControlsForJSAds: true,
});`

When an ad plays, no controls are shown. I've read the documentation and can't figure out why the controls aren't showing up during ad breaks...

**Comment by Kiro705** [comment]
Hello @joshverd ,

I was able to verify that `disableAdControls` is working as expected. The issue may be in your css setup. Would it be possible to share the styles for class `ima-controls-div`?

I also noticed your `adTagUrl` is empty, is this the case in your functioning app or only to redact the url for this question?

Thank you,
Jackson
IMA SDK DevRel

**Comment by joshverd** [comment]
That was the solution, the CSS was not loading in when I imported the NPM module. Manually adding the CSS (from here: https://googleads.github.io/videojs-ima/dist/videojs.ima.css) to my setup fixed the issue.

Thanks for your help!
