### ISSUE TITLE
How do you distinguish between main content ending and postroll ending?

### ISSUE THREAD

**Issue by brkattk** [googleads/videojs-ima#97]
I can't seem to figure out the proper event to listen to in order to tell whether a pre/mid/post-roll ad has `ended` vs. my main video content `ended`. Is there any context passed along inside the events firing to tell which ad, how many ads, or if this is the end of all the content + ads?

**Comment by shawnbuso** [comment]
It looks like we don't currently have a way of distinguishing between these events. I'll consider this a FR to get that added.

**Comment by jeremybrownau** [comment]
I've had to test on the VJS play event (this.ads.state=='content-resuming' || this.ads.state=='content-playback') testing both because of ad blockers.

**Comment by brkattk** [comment]
@jeremybrownau I'm trying to detect when all of the video content (ads and my main video) has ended, so I can kick the user to another screen. I'm not sure either of the events you mentioned would be of any help

**Comment by shawnbuso** [comment]
Hi folks,

I've looked into this a bit, and I think you can do what you're looking to do with the plugin as it is today. 

The plugin has a method called `addContentEndedListener` which takes a function as a parameter. The function you provide will be called when the **content** ends. 

You can also use `getAdsManager` to get a handle to the AdsManager, and listen for ALL_ADS_COMPLETED. That will be fired once all ads have played.

To detect when all ads and content have finished, just wait for both of those methods to be called, like so:

    var contentEnded = false;
    var adsEnded = false;
    
    function contentEndedListener() {
      contentEnded = true;
      if (contentEnded && adsEnded) {
        // Do whatever you want to do when ads and content are done.
      }
    }

    function adsEndedListener() {
      adsEnded = true;
      if (contentEnded && adsEnded) {
        // Do whatever you want to do when ads and content are done.
      }
    }

    player.ima.addContentEndedListener(contentEndedListener);
    player.on('adsready', function() {
      player.ima.getAdsManager().addEventListener(
          google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
          adsEndedListener);
    });

It's a bit ugly but I tested it and it does work. Let me know if that takes care of what you need.

**Comment by brkattk** [comment]
Thank you @shawnbuso!! This worked and was exactly what I needed.

I will say that this should probably be made easier, but this will suffice for now.
