### ISSUE TITLE
✨ Add option to pause video ad on last video frame and show replay button - Feature request

### ISSUE THREAD

**Issue by damjan25** [googleads/videojs-ima#970]
**Would it be possible to implement something like this ?** 
I see more and more  requests from publishers for something like this:
- at the end of the video pause video ad and show replay button
- on replay button click, replay the same video without triggering another AD IMPRESSION

**Where is this useful?:**
- on mobile pages where publisher has on their website fixed height ad slot. So after video is done playing you have last frame of the video and replay button and video player stays expanded/does not collapse. [CLS](https://web.dev/cls/)

**Current problem:**
- it is possible to pause video at last frame, and show replay button, but event for AD COMPLETE is not fired

I already saw few workarounds people doing this with videojs-ima, but it would be really nice if this was supported out of the box

** FOR OUTSTREAM ADS **

**Comment by Kiro705** [comment]
Hello @damjan25 ,

My understanding of the current behavior is, once the content video ends and post-rolls(if any) play, there is a replay button shown where the play button had been. If clicked, the 2nd viewing of the content video will not have ads shown.

Tested here: https://googleads.github.io/videojs-ima/examples/simple/

How would your feature request seek to change this behavior?

Thank you,
Jackson
IMA SDK Team

**Comment by damjan25** [comment]
Oh sorry I forgot to add for "**OUTSTREAM ADS**"

**Comment by Kiro705** [comment]
Hello @damjan25 ,

I do not believe Outstream Ads are actively supported for the IMA sdk. 

Is the issue still a problem if tested using one of the [IMA HTML5 samples](https://github.com/googleads/googleads-ima-html5)?

If so would it be possible to share your sample code to reproduce the issue?

**Comment by damjan25** [comment]
Ok then we will use ima just for instream and I think this issue/featureRequest can be closed :D
