### ISSUE TITLE
Ads Manager sometimes nests event properties in a seemingly random object

### ISSUE THREAD

**Issue by matt-iakhno** [googleads/videojs-ima#971]
Hello team videojs-ima,

I ran into an issue today with the events reported by adsManager.

When performing my initial integration, I took a note of the object that is returned by adsManager, and based my code on the following:

```
event {
   type: "impression",
   g: {
      adId: "12345",
      adPodInfo: { ... }
      ...
   }
   another_key: "some_value"
}
```

The way I'm listening for these events is as follows:

```
            let events = [
                google.ima.AdEvent.Type.ALL_ADS_COMPLETED,
                google.ima.AdEvent.Type.CLICK,
                google.ima.AdEvent.Type.COMPLETE,
                google.ima.AdEvent.Type.FIRST_QUARTILE,
                google.ima.AdEvent.Type.IMPRESSION,
                google.ima.AdEvent.Type.LOADED,
                google.ima.AdEvent.Type.MIDPOINT,
                google.ima.AdEvent.Type.PAUSED,
                google.ima.AdEvent.Type.RESUMED,
                google.ima.AdEvent.Type.STARTED,
                google.ima.AdEvent.Type.THIRD_QUARTILE
            ];
            for (var index = 0; index < events.length; index++) {
                this.player.ima.addEventListener(events[index], this.doSomething);
            }
```

This integration worked fine for a while, however I started receiving reports of issues. Upon investigating, I found that on different page refreshes, the event object emitted by adsManager occasionally nests the `event.g` property under another unidentifiable single-letter property. I've seen both of these so far this morning:

```
event {
   type: "impression",
   o: {
      g: {
         adId: "12345",
         adPodInfo: { ... }
         ...
      }
   }
}
```

and 

```
event {
   type: "impression",
   l: {
      g: {
         adId: "12345",
         adPodInfo: { ... }
         ...
      }
   }
}
```

This makes it impossible to react to events because I never actually know where relevant metadata will come from.

I have shipped an emergency fix up to production just to stop the bleeding, but it's ugly:

```
            let capturedEvent = {};
            if (event.g && event.g.adId) {
                capturedEvent = event.g;
            }
            if (event && event.o && event.o.g && event.o.g.adId) {
                capturedEvent = event.o.g;
            } else if (event && event.l && event.l.g && event.l.g.adId) {
                capturedEvent = event.l.g;
            }

           // now do some stuff with capturedEvent.adId
```

I need a better solution. Do you have any suggestions or advice?

Best,

Matt

**Comment by Kiro705** [comment]
Hello @matt-iakhno ,

If you are looking for the ad Id, I would recommend using [Ad.getAdId()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.Ad#getAdId) instead of parsing the ad event.

Let me know if that works for you or if you have any follow up questions.

Thank you,
Jackson
IMA SDK Team

**Comment by matt-iakhno** [comment]
Hi Jackson,

For my current integration I need to be able to access `adId`, `adPodInfo`, `title` and `duration`. Fortunately I see getters available for all of these in the documentation you linked. I will try this out and get back with a resolution in this ticket once I've had a chance, thank you.

Matt

**Comment by matt-iakhno** [comment]
Hi Jackson,

I tried this out just now, but for some reason `google.ima` is missing the `Ad` key altogether. Here's what mine looks like:

![image](https://user-images.githubusercontent.com/6405765/108404624-ef7ec480-71d4-11eb-9015-597aae03cc42.png)

Is there something additional I have to do for it to show up? I know the IMA SDK knows about the ads because I can get cue markers and extract all the ad-related data by going through `event.o.g` etc as I was doing before.

Best,
Matt

**Comment by Kiro705** [comment]
Hello @matt-iakhno ,

You will want to call [AdEvent.getAd()](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent#getAd) to access an instance of the Ad class to call these methods on.

**Comment by matt-iakhno** [comment]
Hi Jackson, that ended up working out great. Thank you for the support.
