### ISSUE TITLE
Workaround for Google Chrome that blocks ads

### ISSUE THREAD

**Issue by ibraalek10** [googleads/videojs-ima#972]
Hi all,
from September, Google Chrome blocks the video ads that exceed some limits: 
**https://thenextweb.com/apps/2020/05/15/chrome-heavy-resource-ads-block/**

There is a way from this plugin for recognize this limits and solve this problem?
Thanks in advance,

A.

**Comment by Kiro705** [comment]
Hello @ibraalek10 ,

This plugin does not currently have any methods to recognize ads that may be blocked for this reason.

I would recommend looking for an answer or reaching out via the [IMA SDK forum](https://groups.google.com/g/ima-sdk) for information on how IMA is expected to interact with this restriction.

Thank you,
Jackson
IMA SDK Team,
