### ISSUE TITLE
Live stream playback starting slowly after preroll

### ISSUE THREAD

**Issue by jankrueger** [googleads/videojs-ima#973]
Hi everyone, 

when using this library to playback a preroll on a hls live stream it feels like the actual stream content is starting really slowly after the preroll ends. 
IIRC there was an option to keep the content running "behind" the ad but i can't find it anymore. 
Is there anything we can do to reduce the gap between ad and content playback starting?

**Comment by Kiro705** [comment]
Hello @jankrueger ,

Currently this plugin is not optimized for hls live stream prefetch. I would recommend looking into an implementation that does not use the videoJS-IMA plugin. You can look to the [live stream prefetch example here](https://github.com/googleads/googleads-ima-html5/tree/master/live_stream_prefetch).

Let me know if you have any questions. I can also plan on looking into adding this to the plugin, but currently it would not be highly prioritized from the IMA team.

Thank you,
Jackson
IMA SDK Team

**Comment by dioramayuanito** [comment]
https://20.detik.com/live use videojs-ima for preroll. it live content starts in good speed because it uses hls.js engine (videojs-hlsjs-plugin from streamroot) with these options 

- chunk duration is 4sec (dont use 10sec)
- autoStartLoad : true
- startLevel : 0
