### ISSUE TITLE
Brotli support for js served

### ISSUE THREAD

**Issue by andreapernici** [googleads/videojs-ima#974]
Is it possible to enable BROTLI support for 

//imasdk.googleapis.com/js/sdkloader/ima3.js

Or is it possible for me to proxy pass it from my URL?

Example serving it as 

www.mydomain.com/js/sdkloader/ima3.js  using an nginx proxy pass so I can compress it on my side?

Thanks. Is something going to break serving it on my domain?

**Comment by andreapernici** [comment]
Tested a proxy pass, but I'm getting

`IMA SDK is either not loaded from a google domain or is not a supported version`

**Comment by Kiro705** [comment]
Hi @andreapernici ,

The IMA is built to be loaded from the Google url and error out if loaded from other urls. This is for security reasons. Unfortunately, this means you will not be allowed to host the JS from a different url.

Thank you,
Jackson
IMA SDK Team

**Comment by andreapernici** [comment]
Thanks @Kiro705 

What about adding Brotli support on your side? If possible also a pre-compressed version in order to save more kb.

**Comment by Kiro705** [comment]
Hi @andreapernici ,

The IMA SDK is built to throw the error you see if it is served from a non Google location. We do this fo security reasons. The VideoJS-IMA is open sourced, but maintained mainly by Google (I work at Google), so it will not be possible to implement Brotli support or a non-compressed version of the SDK.

**Comment by andreapernici** [comment]
Why is not possible to enable Brotli on your side? Brotli is a Google thing and it is pushing it everywhere. Why not on their properties?

**Comment by Kiro705** [comment]
Could you clarify what a Brotli supported SDK would mean in this case?

This would be a Brotli compressed version of ima3.js you could request, or the ability to Brotli compress the SDK on your end?

**Comment by andreapernici** [comment]
A brotli compressed versione of the ima3.js should be enough.

**Comment by Kiro705** [comment]
Hello @andreapernici ,

Because the compressed version would not be specific to just the videoJS-IMA plugin, I would recommend reaching out via [IMA SDK forum](https://groups.google.com/g/ima-sdk) with your request. That would be the best way to channel your request to the appropriate team.
