### ISSUE TITLE
Contrib-ads still enters postroll mode when ima is initialized without an adTagUrl

### ISSUE THREAD

**Issue by imbcmdth** [googleads/videojs-ima#975]
I was trying to setup IMA without an `adTagUrl` so that I can reuse the player for different content (some monetized in a playlist fashion) but I kept running into the situation that the `ended` event was being converted to `adended` by videojs-contrib-ads.

I think the reason is this line:
https://github.com/googleads/videojs-ima/blob/b53876568356fed47b586631e29e35da99a0721b/src/sdk-impl.js#L533-L537

If there is no AdManager instance, the library will not tell videojs-contrib-ads to skip the postroll so it enters `postroll` mode and waits until the `postRollTimeout` period (5 seconds by default) before (re)emitting the original `ended` event.

My gut tells me that we should be instructing videojs-contrib-ads to skip postrolls when `adsManager` is null or undefined but I don't know if that would have some other consequences.

**Comment by Kiro705** [comment]
Hello @imbcmdth ,

Thanks for bringing this up. I am working on pr #979 to solve this. Seems like a pretty straight forward fix. Once I publish a new version of the plugin, please test and let me know if it resolves the issue.

Jackson
IMA SDK Team

**Comment by Kiro705** [comment]
This should be solved with the latest version of the plugin, v1.10.0.
