### ISSUE TITLE
Ads error on autoplay for video with preroll

### ISSUE THREAD

**Issue by Alivejke** [googleads/videojs-ima#977]
Hi guys, we are experiencing an issue and I wanted to ask what would be your advice to better solve it. So we have an error from ima sdk in cases when we want the video to be autoplayed (we set _autoplay: any_ in video.js configuration) and we have an ad preroll. After some investigation we figured out the error is probably happening when we have this scenario:
1. We configure the player with ad preroll and _autoplay_ set to _any_
2. videojs-ima uses player state to set _adsWillAutoplay_ and _adsWillPlayMuted_
3. Ad preroll tries to play but fails with error
4. Video.js tries to detect the correct state of _autoplay_ and _muted_ (that are used by videojs-ima for _adsWillAutoplay_ and _adsWillPlayMuted_ fields) based on [internal implementation ](https://github.com/videojs/video.js/blob/main/docs/guides/options.md#autoplay)
5. Video.js autoplays video muted or not based on outcome of the detection

So it seems like the problem is in step 2 and 4, it makes more sense for them to be run in the different order, because first we want to detect correct state for _autoplay_ and _muted_ and then pass it down to videojs-ima and ima sdk as a result. Or am I digging in the wrong direction?

**Comment by Kiro705** [comment]
Hello @Alivejke ,

Thank you for reaching out about this issue. What is the desired behavior you are looking to see?

It is unclear if it is preroll not erroring or changes to the muted/autoplay status of the player.

Also, is this issue reproducible using our [sample preroll tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator=)?

Are there any other changes needed, or platform specifics needed to reproduce the issue? A preliminary test I ran showed a preroll autoplaying as expected while muted.

Thank you,
Jackson
IMA SDK Team
