### ISSUE TITLE
IMA HTML5 SDK Doesn't work on MS Edge :)

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#98]
Well, this includes the demo of the stand alone SDK and the VideoJS Demo.
If I test with tag with non-linear ad, it works again.
Even the companion ad is loaded, but no pre-rolls, mid-rolls, post-rolls :)

http://googleads.github.io/googleads-ima-html5/advanced/

**Comment by shawnbuso** [comment]
From @cycleos - "the problem appears to be applicable to IE 11 as well, but only on Windows 10.
Tests with IE11 on Windows 7 were fine."

**Comment by shawnbuso** [comment]
More from @cycleos -  I created two screencaptures to demonstrate the problem itself.

I am opening the Video JS IMA demo on github.io. I am choosing the sample ad tag. I am clicking play. No ads are displayed at all.
I am opening the IMA Stand Alone demo on github.io. I am choosing the sample ad tag. I am clicking play, the companion ad loads, but not the pre-roll.
Hope it helps.

Screencapture for VideoJS IMA:
https://www.youtube.com/watch?v=Wk8Jm0V4Y8w
Screencapture for IMA Stand Alone:
https://www.youtube.com/watch?v=5Jtc0r30FIo

This is IE11 on Windows 10. Same happens on Edge. There are no plugins, no adblockers etc. There are no errors in the console.

**Comment by shawnbuso** [comment]
Looking into this issue a bit more, it looks like the simple sample[1] works but the advanced sample[2] doesn't. So this is probably an implementation issue within the samples and the video.js plugin, and not an issue within the IMA SDK itself. We're not getting any errors in the Edge console, though. I'll continue to investigate.

**Comment by shawnbuso** [comment]
At this point it appears to be a creative/media file issue. If I take the tag from the simple sample and put it in the advanced sample it plays fine. Following up with the rest of the IMA team to determine how to fix.

**Comment by yshterev** [comment]
Hi @shawnbuso - Any progress on this? I can't get it to work on Edge or IE11 using Windows 10, following your advice to use simple sample tag and put it in the advanced sample. I am also using VideoJS 5.11 and latest version of ` videojs-contrib-ads` plugin.

**Comment by shawnbuso** [comment]
This is still an issue in the IMA SDK so we don't have an update yet unfortunately - once it's fixed in the IMA SDK it will be automatically fixed in the video.js plugin.

**Comment by yshterev** [comment]
Is it possible to somehow force flash for IE and Edge? `Single VPAID 1.0 Linear Flash (VAST Inline)` from [IMA Sample Tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags) works.

**Comment by shawnbuso** [comment]
Do you have one tag serving multiple formats, or different tags for different formats? In either case you should be able to add some logic based on the UserAgent of the current browser. If you have different tags, just change the tag passed into the plugin. If it's the same tag, you can pass in mimeTypes to adsRenderingSettings like so:

    {
      id: '...',
      adtagUrl: '...',
      adsRenderingSettings: {
        mimeTypes: ['application/x-shockwave-flash']
      }
    }

**Comment by yshterev** [comment]
I am working on a SaaS project, where users provide the different tags and our service provides embeddable player and streaming. I will probably need some kind of validation of the tags to check if flash format is supported. Thanks for the quick response :)

**Comment by shawnbuso** [comment]
This has been resolved by a patch to our ad server and should require no update on your part to see the fix - I was able to successfully play the advanced sample ad on IE11.
