### ISSUE TITLE
Non-linear in VMAP doesn't work

### ISSUE THREAD

**Issue by cycleos** [googleads/videojs-ima#99]
In brief, if you have a VMAP with non-linear ad in it, it will simply not work with IMA for VideoJS.
However, it appears to be working correctly on the Stand Alone IMA demo.

So if you have a VMAP with non-linear ads, these are not going to be displayed.

**Comment by shawnbuso** [comment]
Hi there,

We don't yet officially support overlay ads with the IMA SDK - if it's working in the standalone IMA demo it sounds like something that just happens to work even though it's not officially supported. I'll look into this issue further when IMA officially supports it. See https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility#vmap_footnote for more info.

**Comment by shawnbuso** [comment]
Closing for now - once this is supported by IMA we should support it out of the box.
