### ISSUE TITLE
Add Open Measurement APIs 

### ISSUE THREAD

**Issue by Kiro705** [googleads/videojs-ima#992]
Currently, there are not methods to follow the [IMA's Open Measurement guide](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/omsdk). These should be added.

**Comment by amusakhan2016** [comment]
Hello Kiro, 

When we can expect a fix for the issue?

Thanks,

**Comment by Kiro705** [comment]
Hello @amusakhan2016 ,

I have https://github.com/googleads/videojs-ima/pull/994 which should add the APIs for the OMSDK. I will work on publishing a new version soon with these changes.

**Comment by Kiro705** [comment]
Support for the OMSDK has been added in v1.11.0 of the plugin.

Please let me know if you have any follow up questions.

**Comment by moeednisardms** [comment]
Hi Kiro, 

Thank you for the updated version of the plugin. 

I have updated the files and enabled the settings as shown in the screenshot http://prntscr.com/12r6nww but still the access is limited in the request. 

Below is the screenshot of the errors we're getting in the console. 
http://prntscr.com/12r6vq1

Could you please advise? 

Thanks

**Comment by Kiro705** [comment]
Hello @moeednisardms ,

You should call `player.ima(imaOptions);` early on in your initiation of the page. From the snippet I cannot confirm this is being done.

In addition, your regex `'^moatads\\.com.*$'` may need to be `'^moatads\\.com/.*$'`with the addition of that forward slash.

Let me know if either of those suggestions helps debug the issue.

Thank you,
Jackson
IMA SDK Team

**Comment by moeednisardms** [comment]
Hi @Kiro705,

We have both the options in place http://prntscr.com/12zrnlk but still having limited access in the request. http://prntscr.com/12zrq1z 

Thanks

**Comment by Kiro705** [comment]
Hello @moeednisardms ,

If you implement the [omsdk guide](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/omsdk) with the [IMA simple example](https://github.com/googleads/googleads-ima-html5/tree/master/simple), do you still see limited access? If you could test this, it would help me to determine if the issue is the VideoJS-IMA plugin or IMA in general.

Let me know if this is or is not possible for you.

Thank you,
Jackson
IMA SDK Team

**Comment by moeednisardms** [comment]
Hi @Kiro705,

OK. I will try to implement it and let you know.

thanks

**Comment by moeednisardms** [comment]
HI @Kiro705,

I have implemented the OM SDK guide step by step using IMA simple example and still seeing limited access. 
It seems that the issue is with IMA.

Thanks

**Comment by moeednisardms** [comment]
Hi @Kiro705,

The issue has been fixed. It was the issue with RegEx. We checked both IMA simple example and VideoJS example as well and now we're seeing that the MOAT script has full access.

Thank you for your support.

**Comment by moeednisardms** [comment]
Hi @Kiro705, 

The below regex has fixed the issue for us. 
new RegExp('[.+\\.]*examplevendor1\\.com.*$')

Thanks

**Comment by moeednisardms** [comment]
Hi Kiro, 

I hope all is well. 

We noticed that OMID implementation has been updated. could you please let us know how to pass the OMID now?
below is the previous implementation we had 

featureFlags:{'enableOmidBeta': true},
  omidMode:{
   FULL: [ new RegExp('[.+\\.]*moatads\\.com.*$') ]
  },

Thanks
