### ISSUE TITLE
Playing Preroll => Bumper sequence of VASTs before the content playback

### ISSUE THREAD

**Issue by gl-vadym** [googleads/videojs-ima#993]
Hi Ima-Team,

**Context**: I'm trying to play two VAST files (VMAP cannot be used) in an ordered sequence: preroll (VAST adTag) => bumper (VAST adTag) => content.
**Problem**: Right after the preroll is finished I can see content playback kicking in for a brief moment. This creates a slightly annoying experience, especially if the first couple of content frames are in bright colors, and I'm looking for a way to avoid this.

Here's the current algorithm:
1. I subscribe to `"ALL_ADS_COMPLETED"` event to explicitly play the bumper ad after the preroll.
2. On the player `"play"` event I try to play the preroll ad.
3. After the preroll adpod has been played, the player fires `"ALL_ADS_COMPLETED"` and that triggers the bumper ad.

To switch adTags I use the following code:
```
player.ima.changeAdTag(adTag);
player.ima.requestAds();
```

And here are the logs I see:
```
VIDEOJS: ADS: Using playMiddleware to block content playback 
VIDEOJS: ADS: Play call to Tech was terminated. 
VIDEOJS: ADS: Received play event (BeforePreroll) 
VIDEOJS: ADS: BeforePreroll -> Preroll 
playing preroll... 
VIDEOJS: ADS: Received adsready event (Preroll) 
VIDEOJS: ADS: Triggered readyforpreroll event (Preroll) 
VIDEOJS: ADS: Starting ad break 
VIDEOJS: ADS: Ending ad break 
All ads have been played 
playing bumper... 
VIDEOJS: ADS: Preroll -> ContentPlayback 
VIDEOJS: ADS: Received adsready event (ContentPlayback) 
VIDEOJS: ADS: Triggered readyforpreroll event (ContentPlayback) 
VIDEOJS: ADS: ContentPlayback -> Midroll 
VIDEOJS: ADS: Starting ad break 
VIDEOJS: ADS: Ending ad break 
All ads have been played 
```

You can see the full code here: https://codesandbox.io/s/videojs-ima-preroll-bumper-example-dgz1g?file=/index.html 
Please pay attention to the end of the preroll ad, before the bumper you'll see a black screen (because the first seconds of content are black)

I can think of a couple of options, but I'm not sure if the library provides a way to accomplish them:
1. Make the bumper ad a part of initial/preroll adbreak;
2. Switch ad tag before "ALL_ADS_COMPLETED" is fired, preventing ads lib to end the ad break;
3. Prevent automatic `Preroll -> ContentPlayback` switch;

Please advice

**Comment by Kiro705** [comment]
Hello @gl-vadym ,

I see the most ideal solution as being using a VMAP ad tag (like our [sample pre-roll + bumper tag](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpreonlybumper&cmsid=496&vid=short_onecue&correlator=)), however you have stated this is not an option.

One other work around could be to overlay the video player with a dark color <div> during ad playback such that the overlay <div> has a higher z-index than the content player but lower than the ad-player. Unfortunately there is not an IMA supported way to seamlessly have multiple back to back ad requests, as this is expected to be done through a VMAP tag.

Please let me know if you have any follow-up questions.

Thank you,
Jackson
IMA SDK Team

**Comment by gl-vadym** [comment]
@Kiro705 thank you for the reply!
Here's the fix that I've ended up with, it's not ideal but it seems to resolve the issue that I'm seeing.

Using the custom CSS class `bumper-ad`:
```scss
// SCSS
.bumper-ad {
   & > video {
       display: none;
   }
}
```
I ensure that the player is hidden until the ad has been played:
```js
player.ima({
    adsManagerLoadedCallback: () => {
        // Add a class
        player.addClass("bumper-ad");

        // Clean up the class
        player.ima.addEventListener(window.google.ima.AdEvent.Type.ALL_ADS_COMPLETED, () => {
            player.removeClass("bumper-ad");
        });
    }
}

// Also clean up the class
player.on("adserror", () => { player.removeClass("bumper-ad") });
```
