### ISSUE TITLE
How can I pause and resume ads when I paused and play the videojs player?

### ISSUE THREAD

**Issue by arunk9034** [googleads/videojs-ima#998]
Hi Team,

I want to know how can I use google.ima.AdsManager pause and resume function with videojs player, Actually i fired a player.pause() function on click a button event but only player paused ads continuously running.

I Can't found how can i use adsManager events by google.

I also tried with ads-manager event
`player.on('ads-manager', function(response){
  var adsManager = response.adsManager;
  adsManager.pause();   
  player.ima.addEventListener(google.ima.AdsManagerLoadedEvent.Type.ADS_MANAGER_LOADED,function(){
    console.log('ads-manager');
  });
})`

But nothing works. Please help me how can i use [pasue](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsManager#pause) and [resume](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdsManager#resume) functions of [Ima SDK](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js#google.ima.AdsManager)

**Comment by Kiro705** [comment]
Hello @arunk9034 ,

I would recommend the following code snippet.

```
// Defined here for scope.
let adsManager;

player.on('ads-manager', function(response){ var adsManager = response.adsManager;})

// Function attached to your pause button.
function pause() {
  if (adIsPlaying()) {
    adsManager.pause();
  } else {
    player.pause()
  }
}
```

Let me know if you have any questions. A similar setup can be used for resuming ad playback.

You can see a different way of pausing during ad breaks in the [advanced example](https://github.com/googleads/videojs-ima/tree/master/examples/advanced) seen [here](https://googleads.github.io/videojs-ima/examples/advanced/).

**Comment by arunk9034** [comment]
Hi @Kiro705 

Thanks for your reply, but my problem has been resolved after a lot of research.

`player.ima.pauseAds();`

Worked for me!
